### ISSUE TITLE
Renaming nupic to nupic.python

### ISSUE THREAD

**Issue by david-ragazzi** [numenta/nupic#1001]
This issue matches the extraction plan (https://github.com/numenta/nupic/wiki/nupic.core-Extraction-Plan).

The plan above is very clear about `nupic.core` being just a transitional repo in the moment, in the end it will have all features located in `nupic` at moment (sensors, encoders, frameworks, etc).

I think this renaming should be done as soon as possible because the terms `nupic.core` and `nupic` already confused me and probally confused others, making I suggest incorrect and non-sense naming based on misunderstoods like seen here: https://github.com/numenta/nupic/issues/724. 

Because this misunderstood, I also suggested the name `nupic.core.net` to the bindings repository to the .Net platform. However based on the extraction plan, I should call it simply `nupic.bindings.net`.

This issue do not imply changes in the current internal structure, i.e. all namespace should continue being `nupic`. Futhermore, the most changes already were done like the default strucuture for pyhton projects and now the "pip installabe" feature which will be merged soon. Probally some minor changes should be done in `nupic.tools` or others.

**update:**
@scottpurdy suggested we renamed it to `nupic.python` in order to we follow the "project.subproject" notation.

**Comment by rhyolight** [comment]
I'm having 2nd thoughts about this. Until we have another set of language bindings, I don't think it matters.

**Comment by oxtopus** [comment]
👎 

Also, 👎  in general for prefixing w/ "nupic." as a standard.

**Comment by utensil** [comment]
👎 

The context has changed greatly since this proposal. At that time, there were few(or no) `nupic.*` projects (which are now all side projects, not language bindings), also there were few (or no) `htm.*` projects(which are mostly reimplementations in other languages, not language bindings). So this proposal was a possible choice back then but is simply outdated now.

IMHO, this issue can be safely closed. I guess @david-ragazzi would agree. 😉

**Comment by cogmission** [comment]
Extending @oxtopus' sentiment - also in general for having "dots" in the names... :-P (I really regret the non-standard Java name of HTM.Java)

**Comment by rhyolight** [comment]
If you guys want to talk about standardizing our repo names, [bring it up on the forum](https://discourse.numenta.org/c/nupic/developers).
