### ISSUE TITLE
Perm weights in hello_tp.py seem wrong

### ISSUE THREAD

**Issue by rhyolight** [numenta/nupic#1078]
From: https://issues.numenta.org/browse/NPC-145

If you uncomment the tp.printCells() call at the end of hello_tp.py you can see that all of the connection weights, even after training, are .5. 

It is expected that these weights would have been further incremented due to training.

I discussed this with Subutai who said he needed to pass on to Ron.

**Comment by rhyolight** [comment]
@subutai @scottpurdy Can one of you comment? Still relevant?

**Comment by scottpurdy** [comment]
Link to relevant code?

**Comment by rhyolight** [comment]
`hello_tp.py` was replaced by https://github.com/numenta/nupic/blob/master/examples/tp/hello_tm.py
