### ISSUE TITLE
Extensible experiment framework

### ISSUE THREAD

**Issue by rhyolight** [numenta/nupic#1080]
From: https://issues.numenta.org/browse/NPC-123

The examples directory contains a lot of experiments but they aren't organized well.  Additionally, it would be nice to be able to load and run experiments in an extensible way for benchmarking.

**Comment by rhyolight** [comment]
@scottpurdy Still relevant?

**Comment by scottpurdy** [comment]
Organization? Probably still relevant. Might be better to wait until we finish serialization so we can better organize the code as well (re: limitation of renaming things when using pickle).

I don't know about an extensible framework for examples though. Probably not worth the effort. At least right now.
