### ISSUE TITLE
Implement "python setup.py uninstall"

### ISSUE THREAD

**Issue by rhyolight** [numenta/nupic#1101]
Or at least make sure it is working as expected, no matter where the installation was written to.

**Comment by oxtopus** [comment]
:-1: setuptools doesn't have an "uninstall" option.  There's `pip uninstall`, and a myriad of ways to remove the files manually, but no native setuptools-based "uninstall".

**Comment by rcrowder** [comment]
Agree with oxtopus, pip uninstall is stable.
