### ISSUE TITLE
Use a platform-independent hash function in Coordinate Encoder

### ISSUE THREAD

**Issue by chetan51** [numenta/nupic#1205]
Investigate a faster, platform-independent hash function instead of `numpy.random`, and use it instead in Coordinate Encoder.

**Comment by oxtopus** [comment]
Feel free to re-open if anyone thinks this issue needs reconsideration, but coordinate encoder now uses the random implementation in `nupic.core`.

See https://github.com/numenta/nupic.core/blob/master/src/nupic/utils/Random.cpp and https://github.com/numenta/nupic/commit/feaec50e352e0765b07e5dcb656ad1c9deef9685
