### ISSUE TITLE
Remove stripNeverLearned from SP.compute

### ISSUE THREAD

**Issue by scottpurdy** [numenta/nupic#1262]
See also numenta/nupic.core#174

The `stripNeverLearned` parameter was added as a temporary measure to allow enabling a random SP. Remaining work:

- [ ] Update SP region to take `stripNeverLearned` parameter that defaults to `True`.
- [ ] Update examples and other clients to pass explicit values for `stripNeverLearned` and/or call `stripUnlearnedColumns` on results from `compute` method.
- [ ] Change `stripNeverLearned` defaults to `False`
- [ ] Remove `stripNeverLearned` parameter from SP.compute.

**Comment by jaredweiss** [comment]
@scottpurdy 
This issue should be split into 2 issues: 
#2278 and #2279

**Comment by scottpurdy** [comment]
@jaredweiss - can this issue be closed now?

**Comment by jaredweiss** [comment]
yep

**Comment by scottpurdy** [comment]
obsolete
