### ISSUE TITLE
Put all functionally of "CMakeLists.txt" into "setup.py"

### ISSUE THREAD

**Issue by david-ragazzi** [numenta/nupic#1573]
Once that theoretically all extensions could be build using SetupTools (
https://docs.python.org/2/extending/building.html) and that `nupic.cpp` (nupic.core) now can be build separately, we could remove CMake from NuPIC Pyhton and leave it only in NuPIC C++.

This will decrease the dependencies in addition to unify the process* into `setup.py`. 

*Again: we DO need be very careful on avoid creating several files to perform build operations instead of centralize on `setup.py`, I'm saying this due to our bad experience with the old build system.

**Comment by oxtopus** [comment]
Agreed.  No need for "compiles from local source", the _user_ either downloads it automatically as part of setup, or the _developer_ builds it separately.

**Comment by david-ragazzi** [comment]
> "published binary tarball" - the nupic.core release that is now automatically published to the amazon server.
the simplification would be setup.py would not have to be able to build nupic.core form source - either it's downloaded from the published binary, or up to the developer to compile it and point setup.py to the release directory. 

I agree with this. This would avoid a lot of install issues. We could have an option to be passed to setup.py that turn on the build from local source. If no option is passed, it simply would download the tarball. This would make the installation quicker and simpler. However, how about we create an issue for this. Otherwise, https://github.com/numenta/nupic/pull/1579 never will be merged.. :disappointed:

**Comment by breznak** [comment]
:+1: no problem with next iteration step, after this PR is merged. But the
point was to decide, and if we dont want it, cut the code.

**Comment by david-ragazzi** [comment]
> no problem with next iteration step, after this PR is merged. 

Ok, could you create an issue for that?

**Comment by rhyolight** [comment]
> Ok, could you create an issue for that?

https://github.com/numenta/nupic/issues/1716

**Comment by david-ragazzi** [comment]
@rhyolight I have seen that you removed nupic.core local build as mentioned by @breznak . Thanks for this!

So once this is merged we could CMake, Make, and GCC/CLang from dependencies section at README:

> **Dependencies:**
> - Python 2.7 (with development headers)
> - Compiler toolchain with support for C++11 such as GCC >= 4.7 (Linux-only), or llvm/clang
> - Make
> - CMake

**Comment by breznak** [comment]
> So once this is merged we could remove CMake and Make from "Dependencies" section at README:

Then we should put it in the "developer's build" page

**Comment by david-ragazzi** [comment]
>>So once this is merged we could remove CMake and Make from "Dependencies" section at README:
> Then we should put it in the "developer's build" page

@breznak I didn't understand. Once developers will build nupic.core separately, it's supposed that they will have cloned nupic.core repo and read its README.

**Comment by breznak** [comment]
>  nupic.core repo and read its README

@david-ragazzi my bad, this is true!
