### ISSUE TITLE
Use Python scripts to perform jobs that were being performed by C++ executables

### ISSUE THREAD

**Issue by david-ragazzi** [numenta/nupic#1576]
I'm working on `setup.py` in order to make it "pip-installable". The problematic point of this job is have to compile and install all current cpp executables and libraries. Some of these libraries (bindings) are inevitable to be build as extensions, however extensions like `htmtest` and `compare_version` can be replaced to pythonic versions. These 2 extensions are complicating the process as they should be installed on souce repository (`bin` folder) and not into `nupic` package folder like bindings. In the new version of `setup.py` that I mentioned only bindings are build.

When I create the PR solving https://github.com/numenta/nupic/issues/1573 , you will understand well what I'm trying explain.

* * *

- [x] [Expose version comparison logic to python somehow](https://github.com/numenta/nupic.core/issues/257)
- [x] [Remove nupic.core comparison logic from externals](https://github.com/numenta/nupic/issues/1621)

**Comment by rhyolight** [comment]
@david-ragazzi I can't close this until the subtasks are complete. What about them?

**Comment by david-ragazzi** [comment]
All subtasks were complete. Closing....

**Comment by rhyolight** [comment]
> All subtasks were complete. Closing....

Eh? https://github.com/numenta/nupic/issues/1621 is not complete!

**Comment by rhyolight** [comment]
Opening until we understand each other...

**Comment by david-ragazzi** [comment]
https://github.com/numenta/nupic/blob/master/setup.py#L568

**Comment by rhyolight** [comment]
ok thanks
