### ISSUE TITLE
LTO build problem with GCC 4.9 [Ubuntu 12.04]

### ISSUE THREAD

**Issue by dingyvlong** [numenta/nupic#1698]
When I install  NUPIC under Ubuntu 12.04 64 bit server ,I see some errors during build (I have succeed to finish the previous step ):

```
Linking CXX shared module _algorithms.so
/usr/bin/ld: /usr/local/lib/libpython2.7.a(abstract.o): relocation R_X86_64_32S against `_Py_NotImplementedStruct' can not be used when making a shared object; recompile with -fPIC
/usr/local/lib/libpython2.7.a: could not read symbols: Bad value
collect2: error: ld returned 1 exit status
make[2]: *** [_algorithms.so] Error 1
make[1]: *** [CMakeFiles/_algorithms.dir/all] Error 2
make: *** [all] Error 2
Unable to build the library!
```

How can I deal with this situation ?

**Comment by rhyolight** [comment]
A few questions:

1. what instructions are you following?
1. what command returns the error you pasted above?
1. what version of gcc or clang are you using?
1. what version of cmake are you using?

**Comment by dingyvlong** [comment]
1.I follow instructions on NuPIC wiki about "Installing NuPIC on Ubuntu ".
2.When I execute the command "python setup.py install --user ",the above error is returned.
3.My version of gcc is 4.9.
4.My version of cmake is 2.8.7.

**Comment by breznak** [comment]
@dingyvlong I don't know if we ever tried building with `gcc-4.9`, so you might be on an unexplored grounds. Could you try building with gcc-4.7/4.8 or clang? 

But first of all, during the time you posted the question (~9hrs ago) there was a merging mess going on on the nupic / nupic.core repos, so can you validate now?

**Comment by breznak** [comment]
and if the problems still persist after doing the above, please post complete output from running the `setup.py` so we can take a look what's going on

**Comment by breznak** [comment]
ok, I did some testing, gcc-49 + LTO don't play well ...fix in progress.

**Comment by breznak** [comment]
probably not LTO + gcc49 problem but gcc4.9 problem solely ..see #1699

**Comment by rhyolight** [comment]
Likely duplicates #1699.
