### ISSUE TITLE
Binaries of nupic.core are not published to S3

### ISSUE THREAD

**Issue by breznak** [numenta/nupic#1700]
or wrong URL passed.

```
Python 2.7.6
doing local build
-- Attempting to fetch nupic.core binaries from https://s3-us-west-2.amazonaws.com/artifacts.numenta.org/numenta/nupic.core/nupic_core-4379eaac04dc8964e622f7c37d3a2401a0dd0879-linux64.tar.gz and save to /home/mmm/nupic/nupic-source/extensions/core/build/release/nupic_core-4379eaac04dc8964e622f7c37d3a2401a0dd0879-linux64.tar.gz...
CMake Warning at CMakeLists.txt:232 (message):
  Error downloading nupic.core package: 22;"HTTP response code said error"
```

command: `python setup.py build` on clean master
no `.nupic_config` files exist

**Comment by breznak** [comment]
@rhyolight can you confirm https://s3-us-west-2.amazonaws.com/artifacts.numenta.org/numenta/nupic.core/nupic_core-4379eaac04dc8964e622f7c37d3a2401a0dd0879-linux64.tar.gz  
is the correct URL and is not accessible?

**Comment by rhyolight** [comment]
Hm... it's missing. The one for darwin exists:

https://s3-us-west-2.amazonaws.com/artifacts.numenta.org/numenta/nupic.core/nupic_core-4379eaac04dc8964e622f7c37d3a2401a0dd0879-darwin64.tar.gz

I'll look into it...

**Comment by breznak** [comment]
probably https://github.com/numenta/nupic.core/pull/288 didnt work out that well..

**Comment by rhyolight** [comment]
From https://travis-ci.org/numenta/nupic.core/jobs/45590166:

    Skipping deployment with the s3 provider because a custom condition was not met

**Comment by rhyolight** [comment]
I think this caused it: https://github.com/numenta/nupic.core/commit/58900b46fd849ada6ee4092fca591ef77f554795#diff-354f30a63fb0907d4ad57269548329e3

PR coming...

**Comment by rhyolight** [comment]
@breznak Actually, this won't be a PR, I'll have to push it directly to master to test it out. Coming in a few seconds...

**Comment by breznak** [comment]
should be `${TRAVIS_OS_NAME:-'linux'} = 'linux'` right? (and ditto for osx)

**Comment by rhyolight** [comment]
https://github.com/numenta/nupic.core/compare/4379eaac04dc...cad24fdb6968

Should work with `${TRAVIS_OS_NAME} = 'linux'`

**Comment by rhyolight** [comment]
@breznak What does the `:-` do, provide a default value if the variable doesn't exist?

**Comment by breznak** [comment]
@rhyolight yes, fallback if $TRAVIS_OS_NAME is unset

**Comment by rhyolight** [comment]
@breznak I see, should not be a problem since Travis promises that it's always set. But the build only deployed for OS X, not Linux. :confused: The condition looks ok to me... still investigating.

**Comment by rhyolight** [comment]
@breznak Ah, I know!

      - "if [ $CC = 'gcc' ]; then export CC='gcc-4.8'; export CXX='g++-4.8'; fi"

So `gcc` is not what I expected. ;)

**Comment by rhyolight** [comment]
Whoops, don't want to close until after deployment is proven.

**Comment by rhyolight** [comment]
Didn't work, I'm going to have to add some debug echos.

**Comment by breznak** [comment]
@rhyolight just a nit, maybe nicer [[ "${TRAVIS_OS_NAME}--${CC}" = 'linux--gcc-4.8' || "${TRAVIS_OS_NAME}--${CC}" = 'osx--clang' ]]

**Comment by breznak** [comment]
or 
`[[ "${TRAVIS_OS_NAME:-linux}--${CC}" = 'linux--gcc-4.8' || "${TRAVIS_OS_NAME}--${CC}" = 'osx--clang' ]]` to be fool proof if you say the prev. didnt work.

**Comment by rhyolight** [comment]
Ok, it's working now. https://github.com/numenta/nupic.core/commit/41fb0e0ed3db29857eca78fc70c86ece921cecd4 fixed it, but I was checkin the wrong build job for the deployment!

I'll clean up the condition and close this out. Thanks for the tips.

**Comment by breznak** [comment]
:+1:  good it works. So I can retry once new 'Update SHA' is merged?

**Comment by rhyolight** [comment]
@breznak Yes, I'll close this and watch for https://github.com/numenta/nupic/pull/1704 to complete.

**Comment by rhyolight** [comment]
Uh... I meant https://github.com/numenta/nupic/pull/1705 to complete.

**Comment by breznak** [comment]
:+1: 
btw, is it possible to set Travis to kill a running build once a new commit us pushed to the same branch? The way it queues all commits sucks.. :unamused:

**Comment by rhyolight** [comment]
I wish that were possible. I've actually found an issue for Travis-CI that defines that feature, but it is not implemented.

**Comment by rhyolight** [comment]
I keep screwing up the condition! :rage: https://github.com/numenta/nupic/pull/1706

**Comment by rhyolight** [comment]
Uh, not the clang osx build is not deploying. I'm leaving it for now and closing my computer. :rage2:

**Comment by breznak** [comment]
some connectivity err on OSX https://travis-ci.org/numenta/nupic/jobs/45629825#L67

**Comment by breznak** [comment]
@rhyolight I confirm it's working fine again, on linux.
