### ISSUE TITLE
Swarming saves best model iteratively

### ISSUE THREAD

**Issue by breznak** [numenta/nupic#1714]
with each "new best model", the model is saved to disk, as the time to write to HDD is unimportant compared to the swarming iterations time. 

So users can work with the (best so far) model even during (lengthy) swarming process. 
This also prevents an issue when already a very good performance is obtained but then some models start failing, and all time spent on swarming is wasted.

**Comment by rhyolight** [comment]
Good idea. What do you think, @scottpurdy?

**Comment by breznak** [comment]
actually, I mentioned this before, and think it's already implemented: 

```
<jobID: 1943> 3  models finished [success: 3; EOF: 3; stopped: 0; killed: 0; error: 0; orphaned: 0; unknown: 0]
<jobID: 1943> 4  models finished [success: 4; EOF: 4; stopped: 0; killed: 0; error: 0; orphaned: 0; unknown: 0]
####>> UPDATED JOB RESULTS: 
{   u'bestModel': 92852,
    u'bestValue': 0.3530317457463958,
    u'metrics': {   u"multiStepBestPredictions:multiStep:errorMetric='aae':steps=[1]:window=50:field=ecg": 60.98694014118246,
                    u"multiStepBestPredictions:multiStep:errorMetric='altMAPE':steps=[1]:window=50:field=ecg": 0.3530317457463958},
    u'saved': True} (elapsed time: 247.316 secs)
<jobID: 1943> 5  models finished [success: 5; EOF: 5; stopped: 0; killed: 0; error: 0; orphaned: 0; unknown: 0]
```

(i had the model_params in gitignore). Closing as "already implemented" :+1:

**Comment by scottpurdy** [comment]
You want swarming to save the model to disk whenever a new best model is found? And you aren't sure if it is doing that now? I think it only saves the best model currently, although there may be an option to save others. I definitely think we want this to be optional since in many cases people are really just looking for the optimal parameters and may not care for a serialized model at all (usually in cases where it doesn't take very long to rebuild the model).

But this would be a nice option to have, although I don't know how many people would find it useful.

**Comment by breznak** [comment]
@scottpurdy modified the title..no, I want the best so far parameters stored. I thought it's happening, because the swarming outputs 
`saved: True}` every time a best-model is updated, but I'm not sure if it is happening, ore where the files are.. the `model_0/{description.py, model_params.csv}` is not created. I see this after I get the `MODEL UPDATED` and saved: True, and then killing the swarming process. Or am I doing anything wrong?

**Comment by scottpurdy** [comment]
@breznak - thanks for clarification. I am guessing when it says "saved: True" it is referring to the database used for the swarming. I think it is fine to add a parameter to the swarming code that additionally stores the best model parameters to disk whenever a best model is found.

I am curious what your use case is. Do you want to be able to end a swarm early or do you want the params for all best models found throughout the process?

**Comment by breznak** [comment]
> I am curious what your use case is. 

Primarily to kill swarming early. I'm running in situations when there's a rapid improvement and then the models just plateau. So I'd like to stop the process, review the updated paramaters, maybe fix some of them and optionally restart with the updated params - do some sort of semi-supervised iterative swarming :) 

Also I'm running in problems (didn't figure yet if bug or not) where I have a more or less const speed to "finish one model"-until it sweeps through all the iterationSteps and i see "model xx finished, reached EOF.." and then I stop seeing these, python is still taking 100% CPU but no progress further (this can take like 10x more then it used to, then my patience runs out and I kill it.)

**Comment by scottpurdy** [comment]
Yeah I think the option to save best model so far to disk (in addition to the DB) is fine.
