### ISSUE TITLE
Integrate Cap'n Proto serialization with encoders

### ISSUE THREAD

**Issue by scottpurdy** [numenta/nupic#1715]
The encoders should have `read` and `write` methods that take proto references and serialize or deserialize.

* * *

- [x] ScalarEncoder - #1961
- [x] RandomDistributedScalarEncoder - #1962
- [x] DateTimeEncoder - #1963
- [x] CategoryEncoder - #1964
- [x] SDRCategoryEncoder - #1965
- [x] AdaptiveScalarEncoder - #1986
- [x] CoordinateEncoder - #1987
- [x] DeltaEncoder - #1988
  - Merged in #2007
- [x] GeospatialCoordinateEncoder - #1989
  - Merged in #2007
- [x] LogEncoder - #1990
  - Merged in #2007
- [x] MultiEncoder - #1991
  - In review at #2007
- [x] PassThroughEncoder - #1992
  - Merged in #2007
- [x] ScalarSpaceEncoder - #1993
  - Deprecated?
- [x] SparsePassThroughEncoder - #1994 
  - Merged in #2007

**Comment by rhyolight** [comment]
@scottpurdy @oxtopus Good job filling this ticket out with subtasks. I appreciate it greatly. :+1:

**Comment by oxtopus** [comment]
@scottpurdy All tasks are either completed or pending review.  Do you mind giving them a look?

**Comment by rhyolight** [comment]
:boom: Nice job Austin.
