### ISSUE TITLE
package_data is missing for linux wheels

### ISSUE THREAD

**Issue by rhyolight** [numenta/nupic#1736]
You can see this on our [regression tests](https://travis-ci.org/numenta/nupic.regression/builds/46280804#L606):

    IOError: [Errno 2] No such file or directory: '/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/nupic/swarming/jsonschema/jobParamsSchema.json'

The missing json file is declared in `package_data`, but not included in the wheel. Wheels built on OS X seem to have all the `package_data` files. 

The script that creates the wheel and uploads it to S3 is [here](https://github.com/numenta/nupic/blob/master/ci/travis/before_deploy.sh). The wheel command being used to package is `pip wheel --wheel-dir=dist/wheels .`.

**Comment by rhyolight** [comment]
After investigating on Ubuntu, I've found that wheels I'm creating are missing the following `package_data`:

```
    package_data = {
      "nupic.support.resources.images": ["*.png", "*.gif",
                                         "*.ico", "*.graffle"],
      "nupic.swarming.jsonschema": ["*.json"]
    },
```

Strangely, the rest of the `package_data` is included in the wheel.

**Comment by rhyolight** [comment]
@oxtopus Can you think of any reason this might happen on one platform and not another?

**Comment by rhyolight** [comment]
@oxtopus Never mind. I figured it out. It works if I add an empty `nupic/swarming/jsonschema/__init__.py`.

**Comment by vitaly-krugl** [comment]
@rhyolight, was it possibly missing from MANIFEST.in? We shouldn't have to add `__init__.py` files in data directories. Also see #2621

**Comment by oxtopus** [comment]
On the subject of MANIFEST.in and superfluous package_data, according to https://docs.python.org/3.4/distutils/sourcedist.html#specifying-the-files-to-distribute:

> If you do supply your own MANIFEST, you must specify everything: the default set of files described above does not apply in this case.

I interpret that to mean that if you use MANIFEST.in (which we do), then it doesn't matter what is in `package_data`.  The files need to be added in MANIFEST.in.  In which case, we can remove `package_data` from setup.py.

**Comment by rhyolight** [comment]
I find it all immensely confusing. :confused:
