### ISSUE TITLE
"Inference failed" error in Grok caused by commit ac524ac

### ISSUE THREAD

**Issue by rhyolight** [numenta/nupic#1743]
https://github.com/numenta/nupic/commit/ac524ac384766c78786d046f50abf1907b5dd497 introduced something that started causing runtime errors in Grok. 

```
ERROR - : Inference failed for row=ModelInputRow<rowID=1, data=[datetime.datetime(2013, 12, 5, 0, 0), 5.0]>
Traceback (most recent call last):
  File "/Users/amarshall/nta/nupic/nupic/frameworks/opf/clamodel.py", line 404, in run
    inferences = self._anomalyCompute()
  File "/Users/amarshall/nta/nupic/nupic/frameworks/opf/clamodel.py", line 621, in _anomalyCompute
    inputValue=self._input[self._predictedFieldName])
KeyError: None
```

**Comment by rhyolight** [comment]
My suspicions:

- https://github.com/numenta/nupic/commit/ac524ac384766c78786d046f50abf1907b5dd497#diff-5bf13635ee2cded8c4bfe689ea9a297dR367
- https://github.com/numenta/nupic/commit/ac524ac384766c78786d046f50abf1907b5dd497#diff-5bf13635ee2cded8c4bfe689ea9a297dR621

**Comment by oxtopus** [comment]
In our cases, there's no classifier region, so `_handleCLAClassifierMultiStep()` returns before it has an opportunity to set `self._predictedFieldName`.

**Comment by rhyolight** [comment]
> In our cases, there's no classifier region

We need to come up with a test for this.

**Comment by oxtopus** [comment]
Working on it.
