### ISSUE TITLE
ARCHFLAGS is required on OS X

### ISSUE THREAD

**Issue by oxtopus** [numenta/nupic#1752]
This is an anticipatory issue that doesn't (yet) affect master, but will when #1579 is merged.

When `python setup.py build` fails, the cause, and path to resolution is not immediately obvious.  For example, the failure includes a serioues of assembly-related errors, ending with:

```
In file included from nupic/bindings/algorithms_wrap.cxx:4368:
In file included from /Users/amarshall/nta/nupic/extensions/core/build/release/include/nupic/math/SparseMatrix.hpp:38:
/Users/amarshall/nta/nupic/extensions/core/build/release/include/nupic/math/ArrayAlgo.hpp:3910:45: error: register %rsp is only available in 64-bit mode
                   "movaps (%%rsp), %%xmm4\n\t"     // a time
                                            ^
<inline asm>:16:12: note: instantiated into assembly here
        addq $16, %rsp
                  ^~~~
fatal error: too many errors emitted, stopping now [-ferror-limit=]
8 warnings and 20 errors generated.
error: command '/usr/bin/clang' failed with exit status 1
```

The solution is to ensure that `ARCHFLAGS="-arch x86_64"` is set in the environment.  Either at invocation: `ARCHFLAGS="-arch x86_64" python setup.py build`, or set in the shell in advance.

As long as this is an issue, there should be some sort of warning message, or an outright forced error before the use gets too far into the process.

**Comment by rhyolight** [comment]
This is only an issue on OS X, right? So the warning should only display when `platform == 'darwin'`, correct?

**Comment by oxtopus** [comment]
Yep.

**Comment by rhyolight** [comment]
Might as well add to David's PR. See https://github.com/david-ragazzi/nupic/issues/49.
