### ISSUE TITLE
Investigate what tasks are necessary to complete swarming as a library

### ISSUE THREAD

**Issue by rhyolight** [numenta/nupic#1753]
Initial investigation builds upon the [Hypersearch Library Design Doc](https://docs.google.com/document/d/16eiYb7SWmlvcaIulhabd4GJvEwHm_48jaW9_GPBUwfY/edit?usp=sharing) that @scottpurdy originally created. But this will be harder than initially expected, so more investigation is necessary to identify subtasks for https://github.com/numenta/nupic/issues/1236.

**Comment by mihail911** [comment]
Some suggested high-level milestones to help organize our efforts:

- [ ] Separate swarming code into the core Hypersearch files and the NuPIC-specific client. Though we are particularly interested in the NuPIC-specific client, the Hypersearch API should be defined in such a way that a wide variety of clients can make use of the library in domain-specific ways.
- [ ] Define the Hypersearch API
- [ ] Migrate Hypersearch API to the new design
- [ ] Deploy Hypersearch to its own PyPI project and include in NuPIC's requirements.txt (we have already reserved the "hypersearch" name on PyPI)
- [ ] Move Hypersearch out of NuPIC into standalone repo

**Comment by scottpurdy** [comment]
@oxtopus - does that sound good to you?

@mihail911 - When we create the issue for separating the code into pure-hypersaerch an NuPIC client, we should be explicitly about what can import from where.

**Comment by oxtopus** [comment]
LGTM.  However, more emphasis needs to be made on the separation of the nupic-specific client.  There will be some client code that remains in nupic to implement nupic-specific swarming on top of the hypersearch framework.  I don't think there's an explicit callout to that.
