### ISSUE TITLE
Warning: unused variable in random_distributed_scalar.py

### ISSUE THREAD

**Issue by connollyst** [numenta/nupic#1761]
``random_distributed_scalar.num_tries`` [is set](https://github.com/numenta/nupic/blob/master/nupic/encoders/random_distributed_scalar.py#L274) but never used.

**Comment by rhyolight** [comment]
@connollyst Thanks for the report, but `numTries` is used when printing debugging information when verbosity is enabled. See: https://github.com/numenta/nupic/blob/master/nupic/encoders/random_distributed_scalar.py#L412.

**Comment by connollyst** [comment]
Ok, the documentation could be cleared up then:

> How often we need to retry when generating valid encodings

I read that as though it was a variable to be used when encoding, not just for debug output.

**Comment by rhyolight** [comment]
@chetan51 Do you have an opinion?

**Comment by connollyst** [comment]
I actually think it was intended to be used to break out of a possible infinite loop [here](https://github.com/numenta/nupic/blob/master/nupic/encoders/random_distributed_scalar.py#L272-L273).

.. I say that because I'm stuck inside that loop re-implementing this encoder in Java haha. I've definitely got a bug in my implementation at the moment, as it's running away with a valid test cast. However, I guess the question is, @chetan51, is the following loop condition _guaranteed_ to break at some point?

    while newBit in self.bucketMap[index] or \
          not self._newRepresentationOK(newRepresentation, newIndex):

If not, ``numTries`` should be used to break out and we need to move on appropriately.


Hope that helps,
Sean

**Comment by chetan51** [comment]
@connollyst Thanks for looking into this, I agree that we should use `numTries` to break out of the loop.
