### ISSUE TITLE
capnp gcc 4.7 compile error: "uninitialized member"

### ISSUE THREAD

**Issue by rhyolight** [numenta/nupic#1763]
Ubuntu 12.04

    $ gcc --version
    gcc (Ubuntu/Linaro 4.7.3-2ubuntu1~12.04) 4.7.3

When running `python setup.py install --user`:

```
/home/matt/nupic/extensions/core/build/release/include/capnp/generated-header-support.h: In constructor ‘constexpr capnp::_::RawBrandedSchema::Binding::Binding(uint8_t, uint16_t, const capnp::_::RawBrandedSchema*)’:
/home/matt/nupic/extensions/core/build/release/include/capnp/generated-header-support.h:82:27: error: uninitialized member ‘capnp::_::RawBrandedSchema::Binding::<anonymous>’ in ‘constexpr’ constructor
/home/matt/nupic/extensions/core/build/release/include/capnp/generated-header-support.h: In constructor ‘constexpr capnp::_::RawBrandedSchema::Binding::Binding(uint8_t, uint16_t, uint64_t, uint16_t)’:
/home/matt/nupic/extensions/core/build/release/include/capnp/generated-header-support.h:86:29: error: uninitialized member ‘capnp::_::RawBrandedSchema::Binding::<anonymous>’ in ‘constexpr’ constructor
/home/matt/nupic/extensions/core/build/release/include/capnp/generated-header-support.h: In constructor ‘constexpr capnp::_::RawBrandedSchema::Binding::Binding(uint8_t, uint16_t, uint16_t)’:
/home/matt/nupic/extensions/core/build/release/include/capnp/generated-header-support.h:89:55: error: uninitialized member ‘capnp::_::RawBrandedSchema::Binding::<anonymous>’ in ‘constexpr’ constructor
error: command 'gcc' failed with exit status 1
```

This used to work on Ubuntu a couple of weeks ago. I'll try again on another system when I get home in case I borked this one up somehow. 

@scottpurdy Do these error ring any bells?

**Comment by scottpurdy** [comment]
@rhyolight - `constexpr` is one of the more recently adopted C++11 features in different compilers but a chart I found said GCC 4.6 is when it was supported so that shouldn't be the issue. Other than that I don't know what the issue could be :disappointed:

**Comment by scottpurdy** [comment]
@rhyolight - Cap'n Proto does seem to be causing a decent number of issues. I wonder if unbundling it (require user to manually install it first) would help

**Comment by rhyolight** [comment]
I'd like to hear what @subutai and @chetan51 think about that idea.

**Comment by chetan51** [comment]
Sounds like a decent stop-gap solution to me.

**Comment by rhyolight** [comment]
I started a thread on nupic-commit to discuss the repercussions of this decision.

**Comment by LaminarFlow** [comment]
First time dipping into NUPIC, Github - forgive me if I'm knocking over the china.

I saw this capnp uninitialized error trying to compile yesterday under Linux.
Just noted some version dependency issues...
NUPIC stated dependency:
   Compiler toolchain with support for C++11 such as GCC >= 4.7 (Linux-only)

( I am using Debian stable-Wheezy gcc version 4.7.2 )

From capnproto.org/install.html
     Cap’n Proto  ...requires a relatively new version of a well-supported compiler. The minimum versions are:     GCC 4.8

**Comment by scottpurdy** [comment]
@LaminarFlow - thanks for the update. I think we may require GCC 4.8 as you mention. @rhyolight can you confirm?

We are hoping to have some prebuilt options available soon so most linux/OS X/Windows users can bypass all of the build reqs so stay tuned.

**Comment by rhyolight** [comment]
@LaminarFlow Yes I just updated https://github.com/numenta/nupic.core/wiki/C---Development-Workflow. You'll need gcc 4.8.

**Comment by LaminarFlow** [comment]
I would be reluctant to go beyond gcc 4.7.2 on Debian stable (Wheezy).  Down the road I may try running Debian Jessie on another machine (which I believe uses gcc 4.8), perhaps I'll swing back here then.

**Comment by rhyolight** [comment]
@LaminarFlow I've successfully installed gcc 4.8 on Wheezy on a Raspberry Pi using [these instructions](https://somewideopenspace.wordpress.com/2014/02/28/gcc-4-8-on-raspberry-pi-wheezy/). Does that help at all?

**Comment by scottpurdy** [comment]
@rhyolight - I think it is less of a will-it-work and more of a asking-for-trouble rationale. But @LaminarFlow we want to make non-developer prebuilt releases available that won't require any compiler. But we are still working out how to handle Python deps that have compiled components.

**Comment by LaminarFlow** [comment]
@scottpurdy - Yup, exactly re:asking for trouble. No problem, you guys are doing great. Thrilled to have access to this stuff. Been lurking for years and will continue ...:)

**Comment by rhyolight** [comment]
@LaminarFlow Hopefully you find it much easier to lurk on GitHub. :wink:

**Comment by rhyolight** [comment]
Closing because we require gcc 4.8.
