### ISSUE TITLE
Enable passing pycapnp builders/readers to C++ code

### ISSUE THREAD

**Issue by scottpurdy** [numenta/nupic#1794]
To integrate the Python and C++ serialization code, we need to be able to pass a builder or reader for some part of a Cap'n Proto struct from the Python code to the C++ code.

Part of #1449

**Comment by yajingfu** [comment]
hi,
I'm a newbie and I have problem when I install pycapnp. I download pycapnp-0.5.1.tar.gz and the instrument says I need to install capnproto-c++-0.5.0 first, but when I type the commad 'sudo make install', I encounter the problems as follows:
depbase=`echo src/capnp/compiler/module-loader.o | sed 's|[^/]*$|.deps/&|;s|\.o$||'`;\
	g++ -std=gnu++11 -DHAVE_CONFIG_H -I.    -I./src -I./src -DKJ_HEADER_WARNINGS -DCAPNP_HEADER_WARNINGS -DCAPNP_INCLUDE_DIR='"/usr/local/include"' -pthread -O2 -DNDEBUG -pthread -MT src/capnp/compiler/module-loader.o -MD -MP -MF $depbase.Tpo -c -o src/capnp/compiler/module-loader.o src/capnp/compiler/module-loader.c++ &&\
	mv -f $depbase.Tpo $depbase.Po
In file included from ./src/capnp/layout.h:37:0,
                 from ./src/capnp/generated-header-support.h:31,
                 from ./src/capnp/compiler/grammar.capnp.h:7,
                 from src/capnp/compiler/compiler.h:29,
                 from src/capnp/compiler/module-loader.h:29,
                 from src/capnp/compiler/module-loader.c++:22:
./src/kj/memory.h:213:28: error: expected ‘;’ at end of member declaration
./src/kj/memory.h:213:32: error: expected unqualified-id before ‘{’ token
./src/kj/memory.h:213:48: error: expected ‘;’ at end of member declaration
./src/kj/memory.h:214:36: error: expected ‘;’ at end of member declaration
./src/kj/memory.h:214:44: error: expected unqualified-id before ‘{’ token
./src/kj/memory.h:214:60: error: expected ‘;’ at end of member declaration
./src/kj/memory.h:215:29: error: expected ‘;’ at end of member declaration
./src/kj/memory.h:215:19: error: ‘kj::Own<T>&& kj::_::OwnOwn<T>::operator*()’ cannot be overloaded
./src/kj/memory.h:213:18: error: with ‘kj::Own<T>& kj::_::OwnOwn<T>::operator*()’
./src/kj/memory.h:215:34: error: expected unqualified-id before ‘{’ token
./src/kj/memory.h:215:58: error: expected ‘;’ at end of member declaration
./src/kj/memory.h:216:37: error: expected ‘;’ at end of member declaration
./src/kj/memory.h:216:25: error: ‘const kj::Own<T>&& kj::_::OwnOwn<T>::operator*() const’ cannot be overloaded
./src/kj/memory.h:214:24: error: with ‘const kj::Own<T>& kj::_::OwnOwn<T>::operator*() const’
./src/kj/memory.h:216:46: error: expected unqualified-id before ‘{’ token
./src/kj/memory.h:216:70: error: expected ‘;’ at end of member declaration
In file included from ./src/capnp/compiler/grammar.capnp.h:7:0,
                 from src/capnp/compiler/compiler.h:29,
                 from src/capnp/compiler/module-loader.h:29,
                 from src/capnp/compiler/module-loader.c++:22:
./src/capnp/generated-header-support.h: In constructor ‘constexpr capnp::_::RawBrandedSchema::Binding::Binding(uint8_t, uint16_t, const capnp::_::RawBrandedSchema*)’:
./src/capnp/generated-header-support.h:82:27: error: uninitialized member ‘capnp::_::RawBrandedSchema::Binding::<anonymous>’ in ‘constexpr’ constructor
./src/capnp/generated-header-support.h: In constructor ‘constexpr capnp::_::RawBrandedSchema::Binding::Binding(uint8_t, uint16_t, uint64_t, uint16_t)’:
./src/capnp/generated-header-support.h:86:29: error: uninitialized member ‘capnp::_::RawBrandedSchema::Binding::<anonymous>’ in ‘constexpr’ constructor
./src/capnp/generated-header-support.h: In constructor ‘constexpr capnp::_::RawBrandedSchema::Binding::Binding(uint8_t, uint16_t, uint16_t)’:
./src/capnp/generated-header-support.h:89:55: error: uninitialized member ‘capnp::_::RawBrandedSchema::Binding::<anonymous>’ in ‘constexpr’ constructor
make: *** [src/capnp/compiler/module-loader.o] Error 1

Can you tell me what shoud I do to sovle it ? Hoping for your reply. Thank you so much.

**Comment by scottpurdy** [comment]
@yajingfu - it looks like you might be using an older compiler that isn't compatible with the C++ `constexpr`.

**Comment by yajingfu** [comment]
@scottpurdy yes, you are right. The installing instruction on https://github.com/numenta/nupic/wiki/Installing-NuPIC-on-Ubuntu isntalled gcc4.7. I tried to install gcc4.8 and pycapnp has been installed seccessfully. It shows all of the required packages has been installed. but a new problem occur when I excute the command "python setup.py install --user".there are a lot of " cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++",and it shows "gcc: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-4.8/README.Bugs> for instructions.
error: command 'gcc' failed with exit status 4"

what should I do ?

**Comment by scottpurdy** [comment]
@yajingfu - please either start a mailing list thread or file a new issue to discuss this. I don't think the warnings are a problem.

**Comment by yajingfu** [comment]
OK，thank you so much
