### ISSUE TITLE
Error running unit tests: ImportError: No module named math [OS X 10.10 Binary Installation]

### ISSUE THREAD

**Issue by rhyolight** [numenta/nupic#1806]
This report is from a brand new OS X 10.10 installation. Here are the only steps I took to prepare to install NuPIC:

- installed brew
- installed xcode command line tools
- `brew install git`
- `sudo easy_install pip`

Python version: system python 2.7.6 **AND** homebrew python (same error)

## Binary Installation

    pip install nupic —user

This worked with no errors.

### Testing Binary Installation

    python -c "import nupic.bindings.math"

    ImportError: No module named math

**Comment by rhyolight** [comment]
This error did not occur when using homebrew python.

**Comment by res1233** [comment]
The code works for me on the MacPorts version of Python. Care to try it out?

**Comment by rhyolight** [comment]
Working for me since `nupic-0.2.0`.
