### ISSUE TITLE
DateEncoder could be extended to cover time too

### ISSUE THREAD

**Issue by breznak** [numenta/nupic#1823]

**Comment by rhyolight** [comment]
I thought it already covered time? Maybe I'm wrong, I haven't looked at the
code. But it detects time-of-day patterns, so I assumed it did.

---------
Matt Taylor
OS Community Flag-Bearer
Numenta

**Comment by cogmission** [comment]
I'm thinking that time can be encoded to be milliseconds since the epoch (64-bit), and in that way it could directly derive from the ScalarEncoder, and just be specialized to handle conversions from dates to longs? (i.e. The functionality already exists? Unless I'm mistaken about something?)

**Comment by breznak** [comment]
@cogmission you are right about that. So maybe DateEncoder is not needed at all? As any date can be converted to a timestamp since the beginning of the epoch. 
Anyway, closing the issue here..
