### ISSUE TITLE
anomaly_likelihood_test: Has Broken Test (Fix is in comment)

### ISSUE THREAD

**Issue by cogmission** [numenta/nupic#1831]
## The text below contains both the description of the problem, and the fix to make the test work, and the code improvement of the class being tested.
 
**.../nupic/tests/unit/nupic/algorithms/anomaly_likelihood_test.py line#226**
testEstimateAnomalyLikelihoodsMalformedRecords() - ***actually tests nothing.***

#### the lines:

data1 = _generateSampleData(mean=0.2)
data1 = data1 + [(2, 2), (2, 2, 2, 2), (), (2)]  # Malformed records
    
likelihoods, avgRecordList, estimatorParams = (
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;an.estimateAnomalyLikelihoods(data1[0:1000])
)

#### should be changed to:

data1 = _generateSampleData(mean=0.2)
data1 = data1**[0:996]** + [(2, 2), (2, 2, 2, 2), (), (2)]  # Malformed records
    
likelihoods, avgRecordList, estimatorParams = (
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;an.estimateAnomalyLikelihoods(data1[0:1000])
)

... so that when estimateAnomalyLikelihoods() is called with **data1[0:1000]** , the "malformed" records will be included.

##### A corresponding change is needed in anomaly_likelihood.py in order to have the 2nd to last record not cause an exception (i.e. the "()" in  [(2, 2), (2, 2, 2, 2), (), (2)]). 

_This is so because the test method as previously written never actually passed the above malformed records in to the method being tested; now that they are being passed in, the code which "detects" bad records is now being executed._

**The required change is on line#486 in the _anomalyScoreMovingAverage() method:**

#### Instead of:
if len(record) != 3:
&nbsp;&nbsp;&nbsp;if verbosity >= 0:
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;print "Malformed record:", record
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;continue

#### Should be:
if **not isinstance(record, list) or** len(record) != 3:
&nbsp;&nbsp;&nbsp;if verbosity >= 0:
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;print "Malformed record:", record
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;continue

**Comment by rhyolight** [comment]
@cogmission Since you've figured this out, why don't you submit a PR with the changes you suggested?

**Comment by cogmission** [comment]
Originally I didn't fix it because it meant I would have to risk my whole dev environment setup by updating and building NuPIC. But since I wrote this, I have updated twice - so I guess I could submit a fix to this... :) - ok.

**Comment by cogmission** [comment]
Oops. I hit "close and comment" instead of "comment" :P

**Comment by cogmission** [comment]
@rhyolight #1855 Now building...

**Comment by BoltzmannBrain** [comment]
A malformed record is not necessarily a non-list; the tests all feed in lists of tuples, but individual tuples are acceptable as well. @rhyolight this should be reopened (or new issue created) to allow both list and tuple types. Please see PR #1915.

**Comment by rhyolight** [comment]
I'll leave it closed, I guess, since #1915 was marked as fixing a different issue and it's been closed.

**Comment by BoltzmannBrain** [comment]
@rhyolight update: testEstimateAnomalyLikelihoodsMalformedRecords() still does not test any malformed records. When `_anomalyScoreMovingAverage()` iterates through the `records` in `anomalyScores`; see [line 480 of anomaly_likelihood.py](https://github.com/numenta/nupic/blob/master/nupic/algorithms/anomaly_likelihood.py#L480), the malformed records never enter the for loop. You can verify this by printing each `record`, and the 1000 good data entries print, but the 4 malformed data entries don't print.
PR #1916 fixes this, and should close this issue for good :)
