### ISSUE TITLE
Bug in `nupic\examples\opf\experiments\template\base\descriptionTemplate.py'

### ISSUE THREAD

**Issue by david-ragazzi** [numenta/nupic#1846]
Visual Studio (with Python Tools) found a bug when I was testing nupic under Windows. Because things like this, I really love VS, neither unit tests detect it.

The error is simply a mismatched character: instead of using a `}` to close `config = {` in https://github.com/numenta/nupic/pull/1847/files#diff-30675e63aa3defad800f8ccc304a210aL91, `)` is used.

**Comment by breznak** [comment]
Btw, with a broken file like this, does it mean the file is never used?!

**Comment by david-ragazzi** [comment]
> Btw, with a broken file like this, does it mean the file is never used?!

Or maybe python interpreter realize that was a mistake and convert automatically the caracter? I'll delete this file to check if it is crucial.

**Comment by rhyolight** [comment]
@david-ragazzi What did you get when you deleted it?
