### ISSUE TITLE
Remove dead code from nupic/research

### ISSUE THREAD

**Issue by david-ragazzi** [numenta/nupic#1857]
We need remove delete dead code from nupic.research as first step to reach 0.5.0 milestone ("clean code" release). The dead code which I found is used in anywhere (except in their tests/examples).

The resulting tree:

https://github.com/david-ragazzi/nupic/tree/remove_dead_code/nupic/research

**Comment by rhyolight** [comment]
`nupic.research` is more of an incubator and prototype for ideas. If there is dead code there, it will never get into `nupic`, so I'm not worried about this. 

As the [README](https://github.com/numenta/nupic.research#what-you-should-understand-about-this-repository) says:

> - the contents can change without warning or explanation
> - the code will change quickly as experiments are discarded and recreated
> - it might not change at all for a while
> - it could just be plain wrong or buggy for periods of time
> - code will not be production-quality and might be embarrassing
> - comments and questions about this code may be ignored
> - Numenta is under no obligation to properly document or explain this codebase or follow any understandable process
> - repository will be read-only to the public
> - if we do work with external partners, that work will probably NOT be here
> - we might decide at some point to not do our research in the open anymore and instead delete the whole repository

**Comment by breznak** [comment]
@rhyolight @david-ragazzi I think David made a typo and meant `nupic@nupic/research` directory, not `nupic.research` repo

**Comment by rhyolight** [comment]
That would make more sense.

---------
Matt Taylor
OS Community Flag-Bearer
Numenta

**Comment by david-ragazzi** [comment]
> @rhyolight @david-ragazzi I think David made a typo and meant nupic@nupic/research directory, not nupic.research repo

Yes. Thanks @breznak
