### ISSUE TITLE
Investigate Column class

### ISSUE THREAD

**Issue by breznak** [numenta/nupic#1861]
I'm afraid it would severely break the current data-structure model, but it would lead to: 
* closer mimic biological model described in Whitepaper
* functional programming model of CLA
* easy and powerful parallelization on many-core CPUs

**Comment by rhyolight** [comment]
@subutai / @scottpurdy What do you think of this idea?

**Comment by scottpurdy** [comment]
When we create algorithm implementations we start out with the concepts (cells, columns, layers) and figure out how to implement them in an efficient and modular way. So if some specific algorithm implementation is inefficient or unnecessarily confusing (like if it could be implemented with an array of Column classes without losing memory/speed efficiency) then we can discuss it. But this issue as written is way too general to be actionable.

Feel free to open an issue with a proposal for a specific algorithm but you will need to include a compelling rationale.
