### ISSUE TITLE
Move vision code to appropriate repo nupic.vision

### ISSUE THREAD

**Issue by breznak** [numenta/nupic#1863]
and remove it from nupic. 
Relevant task: https://github.com/nupic-community/nupic.vision/issues/3

Possibly depends on https://github.com/numenta/nupic/issues/1978

**Comment by rhyolight** [comment]
I'd love to remove our dependency on PIL. Going to need buy-in from @subutai.

**Comment by subutai** [comment]
I am fine with this move - would be a nice simplification. One thing that is a bit awkward is that nupic only looks in one directory for regions. If you move the regions out you have to manually copy them in before you run any scripts. It would be nice if NuPIC instead used some sort of an optional search path for locating regions.  Then this move would be a no-brainer.

**Comment by breznak** [comment]
@subutai I think it is a problem I was seeing: 

>Can I have duplicit pathnames? Like from nupic.regions.PyRegion import PyRegion from "nupic package", and from nupic.regions.ImageSensor import ImageSensor from "local" ?

would any of this help? :
 
* renaming to `nupic-vision.regions.ImageSensor` ,
* as you said, custom search path for Regions
* creating pip package that depends on Nupic and installs in `nupic/regions`

**Comment by subutai** [comment]
I don't think you would ever explicitly import a Region. It gets automatically instantiated by the Network API using the addRegion() call. I think the problem is in  `/nupic.core/src/nupic/engine/RegionImplFactory.cpp`

See line 46:
```
// Path from site-packages to packages that contain NuPIC Python regions
const char * packages[] = { "nupic.regions", "nupic.regions.extra" };
```

This specifies the directories to be searched. We could just add directories based on an optional search path.

**Comment by rhyolight** [comment]
@subutai said:
> One thing that is a bit awkward is that nupic only looks in one directory for regions. If you move the regions out you have to manually copy them in before you run any scripts. It would be nice if NuPIC instead used some sort of an optional search path for locating regions. Then this move would be a no-brainer.

https://github.com/numenta/nupic/issues/1978

**Comment by rhyolight** [comment]
Now that some of the build changes have settled, I would really like to readdress this issue. It is the only issue keeping https://github.com/numenta/nupic/issues/1862 from being closed.
