### ISSUE TITLE
Sort issues by 'recently updated' by default

### ISSUE THREAD

**Issue by breznak** [numenta/nupic#1882]
Just for convenience, could we modify the default issues filter like that?

CC @rhyolight

**Comment by rhyolight** [comment]
@breznak Which issues filter are you talking about?

**Comment by breznak** [comment]
sorry, 'sort by'

**Comment by rhyolight** [comment]
Marek, I still don't know what you are talking about. Where are issues being listed that you want sorted differently?

**Comment by breznak** [comment]
the Issues tab on the right, then Sort ...
https://github.com/numenta/nupic/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc

**Comment by rhyolight** [comment]
As far as I know, we have no control over the default sort order on Github.com issue trackers. 

You know you can see a list of recently update issues on our wallboard, right? http://status.numenta.org.
