### ISSUE TITLE
Simplify docker setup

### ISSUE THREAD

**Issue by oxtopus** [numenta/nupic#1891]
I'm not aware of anyone using the CentOS variant of the Dockerfile (https://github.com/numenta/nupic/blob/master/docker/centos/Dockerfile).  In the interest of simplifying and reducing maintenance overhead, standardize on a single Dockerfile at the root.

I'm happy to donate https://github.com/oxtopus/nupic-build-matrix to the official nupic project should we continue to maintain different platform variants in an official capacity.

**Comment by rhyolight** [comment]
Thanks Austin. Once I'm past the Great Windows Push of 2015, I'll start looking more at our pipelines again and how to use your docker work to get more builds on different linux flavors.
