### ISSUE TITLE
Use cross-platform ways to get system environment variables

### ISSUE THREAD

**Issue by david-ragazzi** [numenta/nupic#1905]
In some parts of nupic the use of `os.environ['SYSTEM_VAR']` to get system environment variables like home and temporary directories requires additional code to check which platform the code is running. This could be avoided if we use canonical ways to get such variables. After a research, I found these methods:

Get $HOME dir in *nix or $USERPROFILE in Windows (http://stackoverflow.com/questions/4028904/how-to-get-the-home-directory-in-python):

```
import os
homeDir = os.path.expanduser('~')
```

Get  $TMPDIR, $TEMP or $TMP dir (http://stackoverflow.com/questions/847850/cross-platform-way-of-getting-temp-directory-in-python):

```
import tempfile
tempDir = tempfile.gettempdir()
```

@chetan51 @rhyolight @rcrowder

**Comment by rhyolight** [comment]
:+1:
