### ISSUE TITLE
Fix serialization of AnomalyLikelihood 

### ISSUE THREAD

**Issue by breznak** [numenta/nupic#1908]
If a user creates a model and passes data into it, there is a period of time where the anomaly likelihood is always 0.5 until it gathers enough data to start it's windowed calculation. If this model is serialized and restarted, this same learning period applies again. Ideally, this resurrected model would retain the anomaly likelihood data so it could continue where it left off instead of starting with a bunch of 0.5 values upon resurrection.

**Comment by breznak** [comment]
CC @rhyolight @anubhavchaturvedi

**Comment by rhyolight** [comment]
A short-term fix would be to pickle the anomaly likelihood object and save it along with the model. When the model is resurrected, you'd need to manually unpickle it, but it should retain its history.

**Comment by rhyolight** [comment]
@subutai We talked about this recently, and there's already a ticket for it. :smile:
