### ISSUE TITLE
Build should include NAB tests

### ISSUE THREAD

**Issue by BoltzmannBrain** [numenta/nupic#1912]
Running the [Numenta detector in NAB](https://github.com/numenta/NAB/blob/master/nab/detectors/numenta/numenta_detector.py) calls:

    from nupic.algorithms import anomaly_likelihood
    from nupic.frameworks.opf.modelfactory import ModelFactory

@BoltzmannBrain tests need to be added to the NuPIC build to ensure the NAB detector will run as expected. See [NAB issue 117](https://github.com/numenta/NAB/issues/117).

**Comment by rhyolight** [comment]
If you are talking about running NAB entirely as a part of the NuPIC CI build, then :-1:. I would much prefer https://github.com/numenta/NAB/issues/117.

**Comment by BoltzmannBrain** [comment]
Not all of NAB, just a unit test for one detector on a dummy csv (one line of data).

**Comment by breznak** [comment]
> Not all of NAB, just a unit test for one detector on a dummy csv (one
line of data).

:+1:

**Comment by rhyolight** [comment]
> Not all of NAB, just a unit test for one detector on a dummy csv (one line of data).

:+1:

**Comment by rhyolight** [comment]
#1915 actually has nothing to do with this issue, so I'm re-opening. 

@BoltzmannBrain I went ahead and merged #1915 even though it wasn't linked to an appropriate issue.

**Comment by BoltzmannBrain** [comment]
Yes this should stay open, thanks Matt :)
I just mentioned this issue in #1915 because it was born out of that little bug. Will work on this one today.

**Comment by rhyolight** [comment]
Great! It's a good thing to represent NuPIC use-cases in tests.

---------
Matt Taylor
OS Community Flag-Bearer
Numenta
