### ISSUE TITLE
Problem Compiling NuPIC on Mac OS 10.10.2

### ISSUE THREAD

**Issue by prototypo** [numenta/nupic#1914]
NuPIC 0.2.0 (binary) and 0.2.1.dev0 (git checkout) will not currently install/build on a Mac. The same error results using both approaches.

> What did you do? (steps to reproduce)

Setup dependencies:

```
# First run XCode and opt to "Install Optional Components"
$ xcode-select --install # Also needed
$ sudo easy_install pip
$ sudo pip install wheel
$ sudo pip install numpy
```

Steps to install the binary:

```
$ sudo pip install nupic
```

Steps to compile:

```
$ export NUPIC=/Users/dwood/code/nupic
$ mkdir $NUPIC; cd !$
$ git clone https://github.com/numenta/nupic.git # or clone via GitHub Desktop
$ ARCHFLAGS="-arch x86_64" python setup.py install --user
```

> What happened? (actual results)

The same error occurs in both cases:

```
/System/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7/object.h:116:56: note: expanded from macro 'Py_SIZE'
#define Py_SIZE(ob)             (((PyVarObject*)(ob))->ob_size)
                                ~~~~~~~~~~~~~~~~~~~~~~^~~~~~~
_imagingft.c:237:34: error: use of undeclared identifier 'FT_GLYPH_BBOX_SUBPIXELS'
...
error: command 'cc' failed with exit status 1
```

> What should have happened? (expected results)

The binary should have installed, and the code should have compiled without error.

> Additional Information (operating system, python version, NuPIC commit SHA, etc.)

> Mac OS X 10.10.2
> Python 2.7.6 (Apple-provided system python)
> NuPIC binary release 0.2.0 and GitHub source 0.2.1.dev0.

**Comment by rhyolight** [comment]
Thanks!

**Comment by rhyolight** [comment]
@david-ragazzi @breznak Either of you ever seen this FreeType error?

**Comment by rhyolight** [comment]
@prototypo If you can re-run and dump the entire build stacktrace into pastebin, that might be helpful.

**Comment by rhyolight** [comment]
I don't see anywhere in `nupic.core` where FreeType is actually being used... There is a `external/licenses/LICENSE.freetype-2.3.4.txt` but that's all I can find. 

Also, the error reported by the OP seems to originate within python itself, not `nupic.core`. This is all confusing to me.

**Comment by rhyolight** [comment]
@prototypo I need to figure out if this is a problem with `nupic` or `nupic.core` (or a problem in your specific environment). Another thing you could do to help debug is checkout and build `nupic.core` manually to see if you get any similar errors. https://github.com/numenta/nupic.core

**Comment by rhyolight** [comment]
@prototypo One more question: Did you have a version of FreeType installed on your system before attempting to install NuPIC?

**Comment by prototypo** [comment]
Hi Matt,

Oh! Yes, I do. I have both freetype and freetype2 packages from MacPorts. I will try uninstalling them.

Regards,
Dave
--
http://about.me/david_wood

**Comment by prototypo** [comment]
Hi all,

Removing my local freetype and freetype2 development files allows me to compile NuPIC 0.21.

Good catch, Matt.

I think this could close Issue 1914, depending on how you feel about turning this into a documentation problem.

Regards,
Dave
--
http://about.me/david_wood

**Comment by rhyolight** [comment]
Thanks, @prototypo, for following up. I will close this and add this to our [build FAQ](https://github.com/numenta/nupic/wiki/Build-and-Installation-FAQ).

**Comment by prototypo** [comment]
Thanks, Matt!

Regards,
Dave
--
http://about.me/david_wood
