### ISSUE TITLE
run_nupic_tests fails on clean build

### ISSUE THREAD

**Issue by matejaputic** [numenta/nupic#1917]
I have done a clean `develop` build from the current repo (today, March 7th). I am following the instructions given in https://github.com/numenta/nupic/wiki/Installing-and-Building-NuPIC

When I run `$NUPIC/scripts/run_nupic_tests -u --coverage`, I get:
```
Traceback (most recent call last):
  File "./run_nupic_tests", line 265, in <module>
    result = main(parser, sys.argv[1:])
  File "./run_nupic_tests", line 255, in main
    exitStatus = call(["py.test"] + args + list(tests))
  File "/usr/lib/python2.7/subprocess.py", line 522, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1327, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```

Apparently it is looking for a file called py.test. I did `find . -name py.test` on the `$NUPIC` directory but nothing came up. Not sure how to generate this file.

**Comment by breznak** [comment]
not a fix, but give it a try without the `--coverage` option.

**Comment by matejaputic** [comment]
Without the `--coverage` option, I get the exact same output.

You are certainly more familiar with this than I am, but I believe the script is trying to pass a list of tests to a module called `py.test`, which doesn't exist. However, there is a `tests` directory off the main `$NUPIC` directory that has an `__init__.py` in it, which suggests that this directory is being treated as a python module. Perhaps this is the module that should be called? For example, if I run `run_nupic_tests -u`, it would make sense that the tests in `tests/unit` would be run. I'm not sure how to do this, though.

**Comment by rhyolight** [comment]
@matejaputic Thanks for the report. I'll look into this soon. 

Potential quick-fix: `pip install pytest`.

What operating system are you running on?

**Comment by matejaputic** [comment]
This is on Ubuntu 14.04.2 LTS

**Comment by oxtopus** [comment]
py.test _is_ required.  The `py.test` command probably isn't in your $PATH.

What happens when you run `pip install pytest --ignore-installed --upgrade`?

**Comment by matejaputic** [comment]
Thanks for following up on this. `pytest` was the lynchpin. Tests are running for me now, thanks!

**Comment by oxtopus** [comment]
You're most welcome!

@rhyolight I suggest we close this issue, unless you think resolution should require a workaround.

**Comment by rhyolight** [comment]
Awesome, thanks for helping @oxtopus.

**Comment by matejaputic** [comment]
May I suggest adding installation of pytest as part of the [build and install instructions](https://github.com/numenta/nupic/wiki/Installing-and-Building-NuPIC)?

**Comment by rhyolight** [comment]
py.test should be installed, it just needs to be added to the user's path. But I'll make a note of it on the wiki. Thanks!

**Comment by rhyolight** [comment]
https://github.com/numenta/nupic/wiki/Installing-and-Building-NuPIC/_compare/da55278e5dd593a83fa5167b05551dad1e91575e...b784fc1eb01f916d66cfe90c80ed37b8673a9153
