### ISSUE TITLE
Tests are being installed in an unexpected location

### ISSUE THREAD

**Issue by oxtopus** [numenta/nupic#1920]
In an Ubuntu 14.04.1 LTS environment I ran:

`pip install https://s3-us-west-2.amazonaws.com/artifacts.numenta.org/numenta/nupic/releases/nupic-0.2.1-cp27-none-linux_x86_64.whl`

NuPIC, and friends, installed just fine:

```
Successfully installed DBUtils-1.1 PyMySQL-0.6.2 PyYAML-3.10 asteval-0.9.1 astroid-1.3.5 cov-core-1.15.0 coverage-3.7.1 execnet-1.3.0 logilab-common-0.63.2 mock-1.0.1 numpy-1.9.2 nupic-0.2.1 ordereddict-1.1 pillow-2.3.0 prettytable-0.7.2 psutil-1.0.1 py-1.4.26 pycapnp-0.5.1 pylint-1.1.0 pyproj-1.9.3 pytest-2.4.2 pytest-cov-1.6 pytest-xdist-1.8 python-dateutil-2.1 six-1.9.0 tweepy-2.1 unittest2-0.5.1 validictory-0.9.1
```

Tests are installed into `/usr/local/lib/python2.7/dist-packages/tests/`:

```
# ls /usr/local/lib/python2.7/dist-packages/tests/integration/nupic/
__init__.py   config.py   external     mock.py   swarming     test_api.pyc  test_auth.pyc    test_cursors.pyc   test_resultset.pyc  test_streaming.pyc
__init__.pyc  config.pyc  integration  mock.pyc  test_api.py  test_auth.py  test_cursors.py  test_resultset.py  test_streaming.py   unit
```

```
# ls /usr/local/lib/python2.7/dist-packages/tests/integration/nupic/
__init__.py  __init__.pyc  algorithms  data  engine  opf  regions
```

Tests fail for a myriad of reasons.  Full test output at https://gist.github.com/oxtopus/0ed17d496ad19ae07dab

**Comment by rhyolight** [comment]
Thanks for filing. I've never tried to run tests from a binary installation, honestly I never expected binary installers to attempt to run tests. 

Do you think it's a good idea to include the test binaries in the package? Most software deployments I've done in the past for other projects have not included tests like this.

**Comment by oxtopus** [comment]
I wanted a quick way to verify that it's working, and was looking for a way to do it without also having to clone the repository, so tests seemed natural, and it was odd that they ended up where they did.  I think it's ok to bundle the tests with the binary, but the binary installation should include everything needed to satisfy the requirements of the tests, too.

At the very least, the binary package should be minimally useful on its own without a source checkout.  For example, you should be able to run hotgym or similar, which isn't possible with the binary package alone.

**Comment by rhyolight** [comment]
I'm not sure I agree with you. I'm going to ask what others thing on the mailing list.

**Comment by rhyolight** [comment]
So I asked the list, and the [resounding answer was yes](http://lists.numenta.org/pipermail/nupic_lists.numenta.org/2015-March/010494.html), we want to include tests and examples.

**Comment by rhyolight** [comment]
Replaced by #1977
