### ISSUE TITLE
Run OPF experiment from command line without "scripts" installed.

### ISSUE THREAD

**Issue by oxtopus** [numenta/nupic#1921]
Some python modules expose command-line utilities by allowing the user to invoke the module directly.  For example: `echo '{"foo":"bar"}' | python -m json.tool` and `python -m SimpleHTTPServer`, I'd like to be able to run an OPF experiment with only the binary installation.  Currently, the only way to invoke a single OPF experiment is to also clone the repository to gain access to `scripts/run_opf_experiment.py`, or replicate the functionality of that script separately.

**Comment by rhyolight** [comment]
:+1:
