### ISSUE TITLE
One gym anomaly example - IndexError: index out of bounds

### ISSUE THREAD

**Issue by kalletammemae** [numenta/nupic#1924]
I was trying to run for testing a one_gym_anomaly example on 64bit Lubuntu machine.

The result:

```
$ ./run.py 
Starts a NuPIC model from the model params returned by the swarm
and pushes each line of input from the gym into the model. Results
are written to an output file (default) or plotted dynamically if
the --plot option is specified.

Creating model from rec-center-hourly...
Importing model params from model_params.rec_center_hourly_model_params
Preparing to output rec-center-hourly data to rec-center-hourly_out.csv
Read 100 lines...
Read 200 lines...
Read 300 lines...
Read 400 lines...
Read 500 lines...
Read 600 lines...
Traceback (most recent call last):
  File "./run.py", line 152, in <module>
    runModel(GYM_NAME, plot=plot)
  File "./run.py", line 142, in runModel
    runIoThroughNupic(inputData, model, gymName, plot)
  File "./run.py", line 123, in runIoThroughNupic
    output.write(timestamp, consumption, prediction, anomalyScore)
  File "/home/kalle/sandbox/one_gym_anomaly_0.2.1/nupic_anomaly_output.py", line 93, in write
    value, anomalyScore, timestamp
  File "/usr/local/lib/python2.7/dist-packages/nupic/algorithms/anomaly_likelihood.py", line 142, in anomalyProbability
    skipRecords = self._claLearningPeriod)
  File "/usr/local/lib/python2.7/dist-packages/nupic/algorithms/anomaly_likelihood.py", line 311, in estimateAnomalyLikelihoods
    _filterLikelihoods(likelihoods) )
  File "/usr/local/lib/python2.7/dist-packages/nupic/algorithms/anomaly_likelihood.py", line 442, in _filterLikelihoods
    filteredLikelihoods = [likelihoods[0]]
IndexError: index out of bounds
```

Error looks to be connected with numpy. 'apt-get install python-numpy python-scipy' is telling both are the newest versions. 
There was no problems with one gym prediction example (except I had to copy rec-center-hourly.csv file to /usr/local/lib/python2.7/dist-packages/nupic/datafiles directory, swarming didn't get it from local directory)
Anomaly example run fine with older version of Nupic.

> Additional Information (operating system, python version, NuPIC commit SHA, etc.)
Python 2.7.6 (default, Mar 22 2014, 22:59:56) 
[GCC 4.8.2] on linux2
Ubuntu 14.04.2 LTS
Nupic 0.2.1, Linux wheel installation from https://github.com/numenta/nupic

**Comment by rhyolight** [comment]
Thank you for the report. I'll look into it.

**Comment by BoltzmannBrain** [comment]
This runs fine on my osx 10.9 machine; python 2.7, numpy 1.9.1, nupic 0.2.1.
@kalletammemae what version of numpy are you running?

Note: the example runs as expected when I edit line 310 in anomaly_likelihood.py to `filteredLikelihoods = _filterLikelihoods(likelihoods)`, i.e. removing the cast to a numpy array; it outputs the exact same results csv.

**Comment by kalletammemae** [comment]
Thanks for advice!
It is Ubuntu 14.04.2 LTS; Linux kernel 3.13.0-46-generic (x86_64)
Numpy 1.8.2
Nupic 0.2.1
Python 2.7.6

I removed the cast as suggested but the out of bounds issue remained:

:~/sandbox/one_gym_anomaly$ ./run.py
Starts a NuPIC model from the model params returned by the swarm
and pushes each line of input from the gym into the model. Results
are written to an output file (default) or plotted dynamically if
the --plot option is specified.

Creating model from rec-center-hourly...
Importing model params from model_params.rec_center_hourly_model_params
Preparing to output rec-center-hourly data to rec-center-hourly_out.csv
Read 100 lines...
Read 200 lines...
Read 300 lines...
Read 400 lines...
Read 500 lines...
Read 600 lines...
Traceback (most recent call last):
  File "./run.py", line 152, in <module>
    runModel(GYM_NAME, plot=plot)
  File "./run.py", line 142, in runModel
    runIoThroughNupic(inputData, model, gymName, plot)
  File "./run.py", line 123, in runIoThroughNupic
    output.write(timestamp, consumption, prediction, anomalyScore)
  File "/home/kalle/sandbox/one_gym_anomaly/nupic_anomaly_output.py", line 93, in write
    value, anomalyScore, timestamp
  File "/usr/local/lib/python2.7/dist-packages/nupic/algorithms/anomaly_likelihood.py", line 142, in anomalyProbability
    skipRecords = self._claLearningPeriod)
  File "/usr/local/lib/python2.7/dist-packages/nupic/algorithms/anomaly_likelihood.py", line 310, in estimateAnomalyLikelihoods
    filteredLikelihoods = _filterLikelihoods(likelihoods) #numpy.array(
  File "/usr/local/lib/python2.7/dist-packages/nupic/algorithms/anomaly_likelihood.py", line 442, in _filterLikelihoods
    filteredLikelihoods = [likelihoods[0]]
IndexError: index 0 is out of bounds for axis 0 with size 0

Just for case I upgraded nympy, it is version 1.9.2 now, but the IndexError didn’t disappear :(

**Comment by rhyolight** [comment]
I have no idea what is causing this error. It's very strange.

**Comment by BoltzmannBrain** [comment]
It appears your code is not generating likelihoods for the data points. To check this go to line 223 of anomaly_likelihood.py and change the `estimateLikelihoods()` printout parameter to `verbosity=2`. The printout is then:

Creating model from rec-center-hourly...
Importing model params from model_params.rec_center_hourly_model_params
Preparing to output rec-center-hourly data to rec-center-hourly_out.csv
Read 100 lines...
Read 200 lines...
Read 300 lines...
Read 400 lines...
Read 500 lines...
Read 600 lines...
In estimateAnomalyLikelihoods.
Number of anomaly scores: 600
Skip records= 300
First 20: [(datetime.datetime(2010, 7, 2, 0, 0), 21.2, 1.0), (datetime.datetime(2010, 7, 2, 1, 0), 16.4, 1.0), (datetime.datetime(2010, 7, 2, 2, 0), 4.7, 1.0), (datetime.datetime(2010, 7, 2, 3, 0), 4.7, 0.0), (datetime.datetime(2010, 7, 2, 4, 0), 4.6, 0.0), (datetime.datetime(2010, 7, 2, 5, 0), 23.5, 0.0), (datetime.datetime(2010, 7, 2, 6, 0), 47.5, 0.025000000000000001), (datetime.datetime(2010, 7, 2, 7, 0), 45.4, 0.025000000000000001), (datetime.datetime(2010, 7, 2, 8, 0), 46.1, 0.025000000000000001), (datetime.datetime(2010, 7, 2, 9, 0), 41.5, 0.0), (datetime.datetime(2010, 7, 2, 10, 0), 43.4, 0.0), (datetime.datetime(2010, 7, 2, 11, 0), 43.8, 0.0), (datetime.datetime(2010, 7, 2, 12, 0), 37.8, 0.0), (datetime.datetime(2010, 7, 2, 13, 0), 36.6, 0.0), (datetime.datetime(2010, 7, 2, 14, 0), 35.7, 0.0), (datetime.datetime(2010, 7, 2, 15, 0), 38.9, 0.0), (datetime.datetime(2010, 7, 2, 16, 0), 36.2, 0.0), (datetime.datetime(2010, 7, 2, 17, 0), 36.6, 0.0), (datetime.datetime(2010, 7, 2, 18, 0), 37.2, 0.0), (datetime.datetime(2010, 7, 2, 19, 0), 38.2, 1.0)]
Discovered params=
{'historicalLikelihoods': [0.028716559999999999, 0.066807200999999997, 0.158655254, 0.211855399, 0.72574688199999993, 0.72574688199999993, 0.69146246099999997, 0.69146246099999997, 0.61791142199999993, 0.57925970900000001], 'distribution': {'variance': 0.0032218174305555553, 'stdev': 0.05676105557999741, 'name': 'normal', 'mean': 0.061891666666666595}, 'movingAverage': {'total': 0.52499999999999925, 'windowSize': 10, 'historicalValues': [0.125, 0.050000000000000003, 0.025000000000000001, 0.050000000000000003, 0.025000000000000001, 0.025000000000000001, 0.025000000000000001, 0.025000000000000001, 0.074999999999999997, 0.10000000000000001]}}
Number of likelihoods: 600
First 20 likelihoods: [ 0.          0.001       0.001       0.001       0.001       0.001       0.001
  0.001       0.001       0.001       0.00466119  0.2118554   0.84134475
  0.84134475  0.84134475  0.84134475  0.84134475  0.84134475  0.86433394
  0.24196365]
leaving estimateAnomalyLikelihoods
Read 700 lines...


and so on for all the lines of data.

**Comment by BoltzmannBrain** [comment]
@kalletammemae have you tried running the other [hotgym examples](https://github.com/numenta/nupic/tree/master/examples/opf/clients/hotgym)?
And have you tried using anomaly_likelihood.py anywhere outside of these examples?

**Comment by kalletammemae** [comment]
Thanks for the good advice, now I got something veird indeed.
The rec-center-hourly.csv file looks very normal (size of file 84859).

BTW, the one_gym prediction example is running fine (swarming, run with plotting).


Skip records= 300
First 20: [(datetime.datetime(2010, 7, 2, 0, 0), 21.2, 1.0), (datetime.datetime(2010, 7, 2, 1, 0), 16.4, 1.0), (datetime.datetime(2010, 7, 2, 2, 0), 4.7, 1.0), (datetime.datetime(2010, 7, 2, 3, 0), 4.7, 0.0), (datetime.datetime(2010, 7, 2, 4, 0), 4.6, 0.0), (datetime.datetime(2010, 7, 2, 5, 0), 23.5, 0.0), (datetime.datetime(2010, 7, 2, 6, 0), 47.5, 0.025000000000000001), (datetime.datetime(2010, 7, 2, 7, 0), 45.4, 0.025000000000000001), (datetime.datetime(2010, 7, 2, 8, 0), 46.1, 0.025000000000000001), (datetime.datetime(2010, 7, 2, 9, 0), 41.5, 0.0), (datetime.datetime(2010, 7, 2, 10, 0), 43.4, 0.0), (datetime.datetime(2010, 7, 2, 11, 0), 43.8, 0.0), (datetime.datetime(2010, 7, 2, 12, 0), 37.8, 0.0), (datetime.datetime(2010, 7, 2, 13, 0), 36.6, 0.0), (datetime.datetime(2010, 7, 2, 14, 0), 35.7, 0.0), (datetime.datetime(2010, 7, 2, 15, 0), 38.9, 0.0), (datetime.datetime(2010, 7, 2, 16, 0), 36.2, 0.0), (datetime.datetime(2010, 7, 2, 17, 0), 36.6, 0.0), (datetime.datetime(2010, 7, 2, 18, 0), 37.2, 0.0), (datetime.datetime(2010, 7, 2, 19, 0), 38.2, 1.0)]
Malformed record: (datetime.datetime(2010, 7, 2, 0, 0), 21.2, 1.0)
Malformed record: (datetime.datetime(2010, 7, 2, 1, 0), 16.4, 1.0)
Malformed record: (datetime.datetime(2010, 7, 2, 2, 0), 4.7, 1.0)

… and so forth many lines until

Returning nullDistribution
Traceback (most recent call last):
  File "./run.py", line 152, in <module>
    runModel(GYM_NAME, plot=plot)
  File "./run.py", line 142, in runModel
    runIoThroughNupic(inputData, model, gymName, plot)
  File "./run.py", line 123, in runIoThroughNupic
    output.write(timestamp, consumption, prediction, anomalyScore)
  File "/home/kalle/sandbox/one_gym_anomaly_0.2.1/nupic_anomaly_output.py", line 93, in write
    value, anomalyScore, timestamp
  File "/usr/local/lib/python2.7/dist-packages/nupic/algorithms/anomaly_likelihood.py", line 142, in anomalyProbability
    skipRecords = self._claLearningPeriod)
  File "/usr/local/lib/python2.7/dist-packages/nupic/algorithms/anomaly_likelihood.py", line 311, in estimateAnomalyLikelihoods
    _filterLikelihoods(likelihoods) )
  File "/usr/local/lib/python2.7/dist-packages/nupic/algorithms/anomaly_likelihood.py", line 442, in _filterLikelihoods
    filteredLikelihoods = [likelihoods[0]]
IndexError: index 0 is out of bounds for axis 0 with size 0

**Comment by BoltzmannBrain** [comment]
From your printout it seems that all the records read in from rec-center-hourly.csv are malformed; notice the Malformed record: ___ lines are repeating the datetimes from the preceding list. This could be due to your changing the file location. I'd recommend reinstalling NuPIC and [starting here](https://github.com/numenta/nupic/tree/master/examples/opf/clients/hotgym/prediction/one_gym#swarming). Then if there's a swarming bug we can deal with it.

**Comment by kalletammemae** [comment]
Thanks a lot! Reinstallation was a right suggestion.

Did it (compiled new from source 0.3.0.dev0) and anomaly detection is running again. Prediction too of cause.
No more problems! :)

With best regards,
K.T.

**Comment by rhyolight** [comment]
Thanks, @BoltzmannBrain

**Comment by kalletammemae** [comment]
Hello,

Still, I will ask help under the same issue, I guess the solution is very simple but have not found it yet.

There was success with sine tutorial too.
Unfortunately geospatial example does not run any more, server.py is not coming up:

~/sandbox/nupic.geospatial-master$ python server.py
Traceback (most recent call last):
  File "server.py", line 27, in <module>
    from model.geospatial_anomaly import runGeospatialAnomaly
  File "/home/kalle/sandbox/nupic.geospatial-master/model/geospatial_anomaly.py", line 31, in <module>
    from nupic.data.datasethelpers import findDataset
ImportError: No module named datasethelpers

---
Requirements are fulfilled and even updated.
NUPIC=/home/kalle/nupic
I installed Nupic with --user key now and I removed tracks of previous versions (installed wiith sudo) of nupic in /usr/local/lib/python2.7/dist-packages directory.
Did this create some inconsistency?

With best regards,
K.T.

=======================
Thanks a lot! Reinstallation was a right suggestion.

Did it (compiled new from source 0.3.0.dev0) and anomaly detection is running again. Prediction too of cause.
No more problems! :)

With best regards,
K.T.

**Comment by rhyolight** [comment]
@kalletammemae I think your NuPIC checkout is out of date. This was a recent change to NuPIC. You'll have to pull the latest code and rebuild before this will work. Let me know how it goes.

**Comment by kalletammemae** [comment]
Hello,

Sry, no successs. Removed ~/nupic folder, downloaded and installed again.
Geospatial-masters example did show the same datasethelpers import error after  ./server.py command.

I followed guidelines on page: https://github.com/numenta/nupic/wiki/Installing-NuPIC-on-Ubuntu
(Ubuntu is running in VB).
Do I miss some environment variable?

Kalle T.

**Comment by rhyolight** [comment]
Ok, I'll test it out now...

**Comment by rhyolight** [comment]
Ah ok. I know the problem. I'll fix it. https://github.com/numenta/nupic.geospatial/issues/46

**Comment by kalletammemae** [comment]
:-) Have a nice weekend!

K.T.

**Comment by rhyolight** [comment]
@kalletammemae Ok, `nupic.geospatial` should be fixed now.

**Comment by kalletammemae** [comment]
Thanks!! Indeed, it is running fluently again. Will start experiments with own gpx data :)

K.T.

**Comment by kalletammemae** [comment]
Hello again,

Looking for few words of good advice again :-)

As promised, I was trying to test geospatial anomaly detection using my own data.
Data was collected using Android phone, Application was GSPlogger.
It is logging GPS data about once per minute.
Conversion to csv was OK.

But run.py rejected all rows except the first:
~/sandbox/nupic.geospatial-master$ ./run.py -v output/Tallinn_gpx.csv
Pre-processing output/Tallinn_gpx.csv...
Keeping row:     ['', '1424448647000', '24.7282441', '59.4121215', '', '0', '', '1']
Discarding row: ['', '1424448716000', '24.7281754', '59.4117737', '', '0.5634892450155045', '', '1']
Discarding row: ['', '1424448777000', '24.7287868', '59.410818', '', '1.8326801181201884', '', '1']
Discarding row: ['', '1424448842000', '24.72720983', '59.40979347', '', '2.227008250953827', '', '1']
…

I noticed preprocess_data.py is rejecting lines where time difference is larger than 5 sec. GPSlogger records about once per minute.
So I commented out statement: if (lastTimestamp and (timestamp - lastTimestamp).total_seconds() > 5): keep = False

After that there was more success and data.js was generated. I noticed that the system does not recognize sequences, repeating message “Starting …” after every few lines of data:
…
Starting new sequence...
DEBUG:  Result of PyRegion::executeCommand : 'None'
[2015-03-21 18:37:56] - Anomaly score: 1.0.
Starting new sequence...
DEBUG:  Result of PyRegion::executeCommand : 'None'
[2015-03-21 18:39:00] - Anomaly score: 1.0.
Starting new sequence...
DEBUG:  Result of PyRegion::executeCommand : 'None'
[2015-03-21 18:40:21] - Anomaly score: 1.0.
Starting new sequence...
DEBUG:  Result of PyRegion::executeCommand : 'None'
[2015-03-21 18:41:24] - Anomaly score: 1.0.
Anomaly scores have been written to /home/kalle/sandbox/nupic.geospatial-master/output/anomaly_scores.csv
Creating visualization at /home/kalle/sandbox/nupic.geospatial-master/static/js/data.js...

Launching server, tracks on map are observable, only thing there was no nupic  type of processing visible (learning, anomaly detection)

I’m including here picture with 8 walking tracks in Tallinn. Some noise is visible (e.g. sample near A Le Coq Arena is faulty) but also some tracks which were deliberately done differently can be recognized. And once the main track was done in opposite direction.

I guess model is not proper or not enough data to train nupic?

Regards,
Kalle T.


[cid:image001.png@01D06574.480E8FF0]

**Comment by rhyolight** [comment]
@kalletammemae This isn't a very good place to have this conversation. I'd much rather have it on our [general mailing list](http://numenta.org/lists). Can you sign up and send your question there? I think I can help you with some of this.

**Comment by kalletammemae** [comment]
OK! Tnx, K.
