### ISSUE TITLE
specifying --nupic-core-dir= with a relative path breaks the build

### ISSUE THREAD

**Issue by breznak** [numenta/nupic#1925]
The message is quite cryptic, either we should 
* throw an error that the path must be absolute
* translate relative path correctly

When:
* building nupic with custom `core` location

Steps to reproduce:
`python setup.py --nupic-core-dir=~/nupic.core/build/release build` 
fails, while `python setup.py --nupic-core-dir=/home/user/nupic.core/build/release build` is OK.

**Comment by rhyolight** [comment]
This worked for me:

    python setup.py install --nupic-core-dir=../nupic.core/build/release --user

However, this does not work:

    python setup.py install --nupic-core-dir=~/nta/nupic.core/build/release --user

[Error here](http://pastebin.com/P0yN4g1H).
