### ISSUE TITLE
Make computeRawAnomalyScore() smoother

### ISSUE THREAD

**Issue by breznak** [numenta/nupic#1935]
There are 3 branches of `if` in `Anomaly.computeRawAnomalyScore()` - the core function compution anomalies. 

* the 1st branch is smooth with regards to #predicted & #active columns. 
* the branch "score = 0.0" is OK I guess
* I have a problem with the part "score = 1.0" 
https://github.com/numenta/nupic/blob/master/nupic/algorithms/anomaly.py#L47-L50 
This creates a `big` anomaly, without taking #columns into account. 
  * 0 (zero) active cols at T & 1 (out of 10.000, say) predicted col at T-1 creates the same anomaly as 
  * 0 active cols at T & 50% (out of 10.000, say) predicted cols at T-1

**Comment by breznak** [comment]
@subutai ?

**Comment by rhyolight** [comment]
Will relabel as "bug" once the "question" has been answered. :)

**Comment by cogmission** [comment]
I wish i could add certain bugs to a special personal watch list?

**Comment by rhyolight** [comment]
I believe if you comment on an issue, you will get email notifications when
it is updated. Check your GitHub notification settings.

---------
Matt Taylor
OS Community Flag-Bearer
Numenta

**Comment by cogmission** [comment]
:+1:

On Wed, Mar 18, 2015 at 8:22 AM, Matthew Taylor <notifications@github.com>
wrote:

> I believe if you comment on an issue, you will get email notifications when
> it is updated. Check your GitHub notification settings.
>
> ---------
> Matt Taylor
> OS Community Flag-Bearer
> Numenta
>
> On Wed, Mar 18, 2015 at 9:17 AM, David Ray <notifications@github.com>
> wrote:
>
> > I wish i could add certain bugs to a special personal watch list?
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/numenta/nupic/issues/1935#issuecomment-82966232>.
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/numenta/nupic/issues/1935#issuecomment-82968196>.
>



-- 
Mit freundlichen Grüßen,
*With kind regards,*

David Ray
Java Solutions Architect
*cortical.io <http://cortical.io> GmbH*
sponsor of:  HTM.java (open source) <https://github.com/numenta/htm.java>
Mariahilferstrasse 4, 1070 Vienna, Austria
d.ray@cortical.io
http://cortical.io

**Comment by breznak** [comment]
My candidate is  https://github.com/numenta/nupic/pull/1934/files#diff-ac4ff5014c0e81ed147be47c27c7bc7aR257 
, hoping it could be `smooth`

**Comment by subutai** [comment]
When would we have zero active columns? I think this is exceedingly rare isn't it? I think there was a corner case but @scottpurdy might remember better.

**Comment by breznak** [comment]
I agree it looks like an edge-case, still, we would have to verify how rare it is (?) But still, there would be a bug nevertheless, albeit rare. 

Could we fix it using "epsilon smoothing", like it's commonly used? 

```
score = numpy.abs(nActiveColumns - numpy.in1d(...)) / (float(nActiveColumns)+EPSILON)
```

It is less readable than the current state (so comments should be extended!), but avoids all the `if branches` and distinguishes the `active=0 & prevPredicted=1   vs   active=0 & prevPredicted=50%` cases.

**Comment by scottpurdy** [comment]
@breznak - your XOR proposal would really detriment the anomaly detection due to the nature of predictions in the temporal memory. Predictions that don't come true are not a bad thing and the temporal memory is designed to make multiple predictions about what might come true.

That said, I tend to agree that the section you mention is a bit odd. I propose we remove it (and instead rely on the `else` clause that returns `0.0`). Thoughts?

**Comment by breznak** [comment]
@scottpurdy I don't think XOR method is wrong per se. It might be worse in some cases, and better in others, that's why I want to add it, along with "swaming over anomaly.compute*() methods". Consider usecase as discussed at https://github.com/numenta/nupic/issues/1300  ...?

> That said, I tend to agree that the section you mention is a bit odd. I propose we remove it (and instead rely on the else clause that returns 0.0). Thoughts?

agreed it's a strange part; not sure if plain removal is the best solution, but it's definitely in line with "Predictions that don't come true are not a bad thing" ..so :+1:

**Comment by scottpurdy** [comment]
> It might be worse in some cases, and better in others

Perhaps I shouldn't jump to conclusions :) but Numenta folks did a good amount of work to make a robust anomaly detection solution so I think it would require really convincing experimental results to be considered for a change.

@subutai - what do you think of the change in #1974? It seems safe to me, anomaly likelihood should work either way and this is a little more intuitive to me.
