### ISSUE TITLE
Swarming returns JSON error when NUPIC environment variable is unset

### ISSUE THREAD

**Issue by rhyolight** [numenta/nupic#1947]
To replicate:

1. install nupic from source following README instructions
1. `cd examples/opf/clients/hotgym/prediction/one_gym`
1. `unset NUPIC` (if set)
1. `python swarm.py`

Error:

```
∙ ./swarm.py
This script runs a swarm on the input data (rec-center-hourly.csv) and
creates a model parameters file in the `model_params` directory containing
the best model found by the swarm. Dumps a bunch of crud to stdout because
that is just what swarming does at this point. You really don't need to
pay any attention to it.

=================================================
= Swarming on rec-center-hourly data...
= Medium swarm. Sit back and relax, this could take awhile.
=================================================
Generating experiment files in directory: /Users/mtaylor/nta/nupic/examples/opf/clients/hotgym/prediction/one_gym/swarm...
Writing  313 lines...
Writing  113 lines...
done.
None
Successfully submitted new HyperSearch job, jobID=1411
Evaluated 0 models
HyperSearch finished!
Worker completion message: None

Results from all experiments:
----------------------------------------------------------------
Generating experiment files in directory: /var/folders/c1/fc9tt93s2p5b9d3wp185qxwc0000gn/T/tmp6234aw...
Writing  313 lines...
Writing  113 lines...
done.
None
json.loads(jobInfo.results) raised an exception.  Here is some info to help with debugging:
jobInfo:  _jobInfoNamedTuple(jobId=1411, client=u'GRP', clientInfo=u'', clientKey=u'', cmdLine=u'$HYPERSEARCH', params=u'{"hsVersion": "v2", "maxModels": null, "persistentJobGUID": "0d6edaa1-d262-11e4-94c6-600308a99116", "useTerminators": false, "description": {"includedFields": [{"fieldName": "timestamp", "fieldType": "datetime"}, {"maxValue": 53.0, "fieldName": "kw_energy_consumption", "fieldType": "float", "minValue": 0.0}], "streamDef": {"info": "kw_energy_consumption", "version": 1, "streams": [{"info": "Rec Center", "source": "file://rec-center-hourly.csv", "columns": ["*"]}]}, "inferenceType": "TemporalMultiStep", "inferenceArgs": {"predictionSteps": [1], "predictedField": "kw_energy_consumption"}, "iterationCount": -1, "swarmSize": "medium"}}', jobHash='\ro\x9b\xd4\xd2b\x11\xe4\xa0\xfa`\x03\x08\xa9\x91\x16', status=u'notStarted', completionReason=None, completionMsg=None, workerCompletionReason=u'success', workerCompletionMsg=None, cancel=0, startTime=None, endTime=None, results=None, engJobType=u'hypersearch', minimumWorkers=1, maximumWorkers=4, priority=0, engAllocateNewWorkers=1, engUntendedDeadWorkers=0, numFailedWorkers=0, lastFailedWorkerErrorMsg=None, engCleaningStatus=u'notdone', genBaseDescription=None, genPermutations=None, engLastUpdateTime=datetime.datetime(2015, 3, 24, 20, 12, 10), engCjmConnId=None, engWorkerState=None, engStatus=None, engModelMilestones=None)
jobInfo.results:  None
EXCEPTION:  expected string or buffer
Traceback (most recent call last):
  File "./swarm.py", line 109, in <module>
    swarm(INPUT_FILE)
  File "./swarm.py", line 101, in swarm
    modelParams = swarmForBestModelParams(SWARM_DESCRIPTION, name)
  File "./swarm.py", line 78, in swarmForBestModelParams
    verbosity=0
  File "/Users/mtaylor/nta/nupic/nupic/swarming/permutations_runner.py", line 276, in runWithConfig
    return _runAction(runOptions)
  File "/Users/mtaylor/nta/nupic/nupic/swarming/permutations_runner.py", line 217, in _runAction
    returnValue = _runHyperSearch(runOptions)
  File "/Users/mtaylor/nta/nupic/nupic/swarming/permutations_runner.py", line 160, in _runHyperSearch
    metricsKeys=search.getDiscoveredMetricsKeys())
  File "/Users/mtaylor/nta/nupic/nupic/swarming/permutations_runner.py", line 825, in generateReport
    results = json.loads(jobInfo.results)
  File "/Users/mtaylor/nta/nupic/nupic/support/object_json.py", line 163, in loads
    json.loads(s, object_hook=objectDecoderHook, **kwargs))
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 351, in loads
    return cls(encoding=encoding, **kw).decode(s)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 365, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
TypeError: expected string or buffer
```

CC @pehlert

**Comment by passiweinberger** [comment]
fixed instead by #1970

**Comment by RDaneelOlivav** [comment]
Hi, just stumbled on this problem to I think, trying to execute sine example and it doesnt find the sine.csv file because its looking for it in :
/home/<user_name>/.local/lib/python2.7/site-packages/nupic-0.3.0.dev0-py2.7-linux-x86_64.egg/nupic/datafiles/sine.csv

I tried to put it in the directory configuration of /myswarm/data/sine.csv, and the search_def.json in the /myswarm, keeps looking for it in .../nupic/datafiles/sine.csv

Any insight?

**Comment by pehlert** [comment]
@RDaneelOliav Have you tried specifying an absolute path for to the sine.csv in your search_def.json?

**Comment by RDaneelOlivav** [comment]
"source": "file:///home/<user-name>/..path_to_csv_file../sine.csv

Worked like a charm apparently but could someone tell me where can I find an explanation to how this "file://" works because it's a bit confusing for a json newbie having to write file:///abspath hahaha.

**Comment by pehlert** [comment]
The "file:///" notation is not part of the JSON specification, but instead something that is parsed by nupic itself. You can think of "file://" as a protocol identifier such as "http://" and the path behind as a regular file path. 

Paths starting with a slash are considered absolute paths while paths without a leading slash are (usually) relative to the current directory. I case of the current version of NuPIC, that is not entirely true, because relative paths are relative to $NUPIC/datafiles, which I am currently trying to change.

**Comment by RDaneelOlivav** [comment]
Great ;)

**Comment by rhyolight** [comment]
Also: https://github.com/numenta/nupic/wiki/Running-Swarms#the-data-file

**Comment by benuzal** [comment]
Hi I got the same error, on Windows x64.
How can I fix this error? 
could you help me? 

![image](https://user-images.githubusercontent.com/6921642/36371059-082ec0c4-1572-11e8-9238-93518db6b7e1.png)

**Comment by rhyolight** [comment]
@benuzal How did you install NuPIC? Is your `$NUPIC` environment variable set to the path where it is installed?

**Comment by rhyolight** [comment]
@benuzal How did you install nupic?

**Comment by benuzal** [comment]
I installed from pip install nupic

**Comment by rhyolight** [comment]
@benuzal Please post the absolute path to the working directory where you executed your script, and the complete command you used to execute the script. Thanks.

**Comment by JonnoFTW** [comment]
I get this problem as well now after doing :

```
python setup.py develop
```

Setting `$NUPIC` to `/scratch/nupic/nupic` (where I have my local copy of nupic source does nothing.

**Comment by rhyolight** [comment]
Dammit, I thought we had removed the requirement for the `NUPIC` environment variable long ago. I don't think this has anything to do with this particular issue. The error is just a bad error message.

**Comment by jpgong** [comment]
@benuzal Did you solve this problem, I have the same problem. please
