### ISSUE TITLE
Add type checks with better error messages for encoders

### ISSUE THREAD

**Issue by scottpurdy** [numenta/nupic#1950]
The encoders should check the format of the input and raise exceptions with clear descriptions of what the proper format is if the input isn't formatted correctly or doesn't use the right types. Here is an email chain from a NuPIC user that had trouble figuring out the input format for encoders:

> Thanks Scott,
> 
> The same if toy put ints but, as far as the audiostream is concerned, it uses it with float inpyts aparently, so that solution cant work. And it works if turned the input in
> to a list instaed of an numpy.array() ( it give another kind of error though, saying that the input isnt correct because of the window definition ).
> 
> I already sent it to the mailing list ;). You can see the whole output there. Tell me if you recieved it in you mailing list ;)
> 
> 2015-03-25 16:23 GMT+01:00 Scott Purdy scott@fer.io:
> The input must contain booleans. So something like this:
> 
> e = SparsePassThroughEncoder(51, 1)
> input = numpy.zeros(51, dtype="bool")
> input[0] = 1
> input[1] = 1
> encoded = e.encode(input)
> 
> And I'd recommend you send questions to the list since you will probably get much quicker responses.
> 
> Best of luck!
> 
> On Wed, Mar 25, 2015 at 5:16 AM, miguel angel rodriguez duckfrost@gmail.com wrote:
> Hi,
> 
> I started useing the NUPIC infraestructure some weeks ago and I just run into a problem that you might help:
> 
> I executed the example audiostream and it gave me the error:
> IndexError: arrays used as indices must be of integer (or boolean) type
> 
> And I pinpointed the error to the line:
> actualInt = self.e.encode(ufs)
> So I executed just the SparsePassThroughEncoder but I cant make it work
> properly either:
> 
> > > from nupic.encoders.sparse_pass_through_encoder import SparsePassThroughEncoder
> > > e = SparsePassThroughEncoder(51, 1)
> > > input = numpy.zeros(51)
> > > input[0] = 2
> > > input[1] = 12
> > > actualInt = e.encode(input)
> > > IndexError: arrays used as indices must be of integer (or boolean) type
> 
> Any thoughts? Any insight would be much appreciated, thanks
> 
> Miguel Angel Rodriguez

**Comment by rhyolight** [comment]
:+1: I've gotten more than one question that would have been resolved if this ticket were implemented.
