### ISSUE TITLE
Cover ideas/examples more on the landing page

### ISSUE THREAD

**Issue by breznak** [numenta/nupic#1952]
I was just recommending NuPIC to someone, pointing to the GH repo. I strongly feel the landing page (main README.md) should include more of the ideas, examples, pictures - not just "howto install". 

IMHO it could even be other way, the Readme contains only the "talking" - high level descriptions, ideas, advantages, ... and for install instructions you'd point elsewhere.

**Comment by rhyolight** [comment]
Sorry, I don't want the repo to have any of that. If they want more of the theory behind HTM, they can go to numenta.org to see that, or the wiki (both of which are linked at the top of the README).
