### ISSUE TITLE
I have LTO issue when I build nupic.core by myself

### ISSUE THREAD

**Issue by eebeer** [numenta/nupic#1969]
I am now using VM with Ubuntu 14.04.2 and my gcc version looks little bit a mess.

$ gcc --version
gcc (Ubuntu 4.8.2-19ubuntu1) 4.8.2

$ g++ -v
Using built-in specs.
COLLECT_GCC=g++
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/4.9/lto-wrapper
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 4.9.2-0ubuntu1~14.04' --with-bugurl=file:///usr/share/doc/gcc-4.9/README.Bugs --enable-languages=c,c++,java,go,d,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-4.9 --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --with-gxx-include-dir=/usr/include/c++/4.9 --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --enable-gnu-unique-object --disable-vtable-verify --enable-plugin --with-system-zlib --disable-browser-plugin --enable-java-awt=gtk --enable-gtk-cairo --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-4.9-amd64/jre --enable-java-home --with-jvm-root-dir=/usr/lib/jvm/java-1.5.0-gcj-4.9-amd64 --with-jvm-jar-dir=/usr/lib/jvm-exports/java-1.5.0-gcj-4.9-amd64 --with-arch-directory=amd64 --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --enable-objc-gc --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 4.9.2 (Ubuntu 4.9.2-0ubuntu1~14.04)

I changed c++ file in nupic.core, and compiled following (https://github.com/numenta/nupic.core)
'make' is okay, but I need to 'sudo make install'. Otherwise, it generated such an error

CMake Error at cmake_install.cmake:189 (FILE):
  file Internal CMake error when trying to open file:
  /home/dkim451/WORK/NUPIC/nupic.core/build/scripts/install_manifest.txt for
  writing.

After 'sudo make install', running tests is okay. (tests_cpp_region and tests_unit)

After that, I try to use my own version of nupic.core following 
git clean -xdf
export NUPIC_DEPLOYMENT_BUILD=true
python setup.py build --nupic-core-dir=/home/dkim451/WORK/NUPIC/nupic.core/build/release

(I tried this: python setup.py build --cmake_options="-DNUPIC_CORE=/your/path/nupic.core/build/release", but it downloads nupic.core binary, and cannot recognize --cmake_options)

Then I got such an error 
c++ -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -D_FORTIFY_SOURCE=2 -g -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security build/temp.linux-x86_64-2.7/extensions/py_support/NumpyVector.o build/temp.linux-x86_64-2.7/extensions/py_support/PyArray.o build/temp.linux-x86_64-2.7/extensions/py_support/PyHelpers.o build/temp.linux-x86_64-2.7/extensions/py_support/PythonStream.o build/temp.linux-x86_64-2.7/extensions/cpp_region/PyRegion.o build/temp.linux-x86_64-2.7/extensions/cpp_region/unittests/PyHelpersTest.o /home/dkim451/WORK/NUPIC/nupic.core/build/release/lib/libnupic_core.a -ldl -lpython2.7 -lkj -lcapnp -lcapnpc -lpthread -o build/lib.linux-x86_64-2.7/nupic/libcpp_region.so -m64 -fPIC -L/home/dkim451/WORK/NUPIC/nupic.core/build/release/lib -lkj -lcapnp -lcapnpc -O2
lto1: fatal error: bytecode stream generated with LTO version 2.2 instead of the expected 3.0
compilation terminated.
lto-wrapper: c++ returned 1 exit status
/usr/bin/ld: lto-wrapper failed
collect2: error: ld returned 1 exit status
error: command 'c++' failed with exit status 1

It looks like similar to 
https://github.com/numenta/nupic/issues/1740 or
https://github.com/numenta/nupic/issues/1699

Although I followed all recommendations, it does not work.

Any recommendations?

**Comment by eebeer** [comment]
I tried to downgrade both gcc and g++ to 4.7, and now it works. 

Sorry for your time.

**Comment by rhyolight** [comment]
Thanks for the report.
