### ISSUE TITLE
Maybe more explanation for build & install with custom nupic.core will be helpful.

### ISSUE THREAD

**Issue by eebeer** [numenta/nupic#1976]
In this site, https://github.com/numenta/nupic/wiki/NuPIC%27s-Dependency-on-nupic.core

there is instruction how to build nupic with custom nupic.core.
However, it will not update nupic python library in sys.path.

Therefore, I need to build & install
python setup.py build --nupic-core-dir="<path to nupic.core described above>/build/release" install --user

If you add those explanation, it will be helpful for Nupic nubie :)

**Comment by rhyolight** [comment]
Good point. I updated the wiki to this:

    python setup.py install --nupic-core-dir="<path to nupic.core described above>/build/release"

Notice it's `install` now instead of `build`, which should be what you are suggesting.
