### ISSUE TITLE
Find Regions using an optional search path instead of only looking in one directory

### ISSUE THREAD

**Issue by rhyolight** [numenta/nupic#1978]
See https://github.com/numenta/nupic/issues/1863#issuecomment-75804913 for context.
Which is being implemented in https://github.com/numenta/nupic.core/issues/359

**Comment by david-ragazzi** [comment]
@rhyolight With https://github.com/numenta/nupic.core/pull/438, would be this issue closed and so @breznak could continue his (nice) work removing vision code (https://github.com/numenta/nupic/pull/1866).

**Comment by rhyolight** [comment]
@scottpurdy @subutai @akhilaananthram  Is this issue obsolete now that https://github.com/numenta/nupic.core/pull/438 & https://github.com/numenta/nupic/pull/2165 are merged?

**Comment by akhilaananthram** [comment]
Yeah. I think its obsolete now.
