### ISSUE TITLE
Encoder unit tests not consistent with coding guidelines

### ISSUE THREAD

**Issue by oxtopus** [numenta/nupic#2000]
See comments at https://github.com/numenta/nupic/pull/1975 for some examples of unit tests that need to be cleaned up.

* * *

- [x] https://github.com/numenta/nupic/issues/2018 Category
- [x] https://github.com/numenta/nupic/issues/2019 Scalar
- [x] https://github.com/numenta/nupic/issues/2022 AdaptiveScalar
- [x] https://github.com/numenta/nupic/issues/2025 Delta
- [x] https://github.com/numenta/nupic/issues/2027 Date
- [x] https://github.com/numenta/nupic/issues/2030 Log
- [x] https://github.com/numenta/nupic/issues/2032 Multi
- [x] https://github.com/numenta/nupic/issues/2035 Pass Through
- [x] https://github.com/numenta/nupic/issues/2037 RDSE
- [x] https://github.com/numenta/nupic/issues/2039 SDR Category
- [x] https://github.com/numenta/nupic/issues/2041 Sparse Pass Through
- [x] https://github.com/numenta/nupic/issues/2043 Coordinate
- [x] https://github.com/numenta/nupic/issues/2045 Geospatial Coordinate

**Comment by oxtopus** [comment]
@rhyolight I went a little crazy with the PRs, but this should make it easier to divide and conquer for the reviews.  Each one is ready and stands alone without dependencies on the others.

**Comment by rhyolight** [comment]
No, this is perfect. Thanks for the work.
