### ISSUE TITLE
New NuPIC install: All Tests But One Are Broken

### ISSUE THREAD

**Issue by cogmission** [numenta/nupic#2008]
After running:   ARCHFLAGS="-arch x86_64" python setup.py develop --user

successfully,

https://github.com/numenta/nupic/wiki/Installing-and-Building-NuPIC#to-run-the-tests

The previous tests can only run the first test mentioned here, the others fail with:

##This Passes
```Python
# Python HTM Network API tests
$NUPIC/bin/py_region_test
```

##These Fail

```Python
# Python unit tests
$NUPIC/scripts/run_nupic_tests -u --coverage

# Python integration tests
$NUPIC/scripts/run_nupic_tests -i --coverage

# Python swarming tests (requires mysql)
$NUPIC/scripts/run_nupic_tests -w --coverage

# Run all tests!
$NUPIC/scripts/run_nupic_tests --all --coverage
```

Mindlab:nupic cogmission$ $NUPIC/scripts/run_nupic_tests -u --coverage
Traceback (most recent call last):
  File "/Users/cogmission/git/nupic/scripts/run_nupic_tests", line 265, in <module>
    result = main(parser, sys.argv[1:])
  File "/Users/cogmission/git/nupic/scripts/run_nupic_tests", line 255, in main
    exitStatus = call(["py.test"] + args + list(tests))
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 522, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 709, in __init__
    errread, errwrite)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1326, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

**Comment by rhyolight** [comment]
This is because `py.test` is not on your path. http://pytest.org/latest/getting-started.html

**Comment by cogmission** [comment]
Thanks Matt!

**Comment by cogmission** [comment]
How do I install pip and numpy? (without brew, which seems to be broken)

**Comment by rhyolight** [comment]
pip: http://pip.readthedocs.org/en/stable/installing.html#install-pip

Then "pip install numpy"

---------
Matt Taylor
OS Community Flag-Bearer
Numenta

**Comment by cogmission** [comment]
Mindlab:Downloads cogmission$ python get-pip.py
Requirement already up-to-date: pip in /Library/Python/2.7/site-packages/pip-6.0.8-py2.7.egg
Mindlab:Downloads cogmission$ pip
-bash: pip: command not found

**Comment by rhyolight** [comment]
pip has to be on your $PATH as well. Mine is:

∙ which pip
/usr/local/bin/pip

---------
Matt Taylor
OS Community Flag-Bearer
Numenta

**Comment by rhyolight** [comment]
You might also be able to run `easy_install pip`

---------
Matt Taylor
OS Community Flag-Bearer
Numenta

**Comment by cogmission** [comment]
I get this, but then there is no /usr/local/bin/pip ?
Requirement already up-to-date: pip in /Library/Python/2.7/site-packages/pip-6.0.8-py2.7.egg

**Comment by rhyolight** [comment]
Dang David, I don't know. Everybody's setup is different. Do some google
searches about pip on OS X and see if you can find a solution.

I think you should install via easy_install. Try removing
/Library/Python/2.7/site-packages/pip-6.0.8-py2.7.egg and then run "sudo
easy_install pip"

---------
Matt Taylor
OS Community Flag-Bearer
Numenta

**Comment by cogmission** [comment]
I'm sorry to bother you. It's just that this stuff should not have any variations. It should be installed via known tools - on a fresh system this definitely should not occur. It should only vary by OS (i.e. Yosemite, Mavericks) - on a fresh system there shouldn't be these problems? It should be as clear as, on Yosemite do this... On Mavericks, do this... Apple ships with a consistent setup, therefore all tools should be installed the same way? :-P

**Comment by cogmission** [comment]
Definition: Python...

A smorgasbord of chaotic variables and pieces collaborating in a symphony of desperation converging on a collusion of maximum serendipity in order to function.

**Comment by cogmission** [comment]
Yay!!! Got it. Changed some directory permissions and used "sudo" to install! All tests running!!!

Thanks Matt - and sorry for the frustration...

**Comment by cogmission** [comment]
================================= 810 passed, 14 skipped, 2 warnings in 157.41 seconds ==================================

**Comment by rhyolight** [comment]
Great!

---------
Matt Taylor
OS Community Flag-Bearer
Numenta
