### ISSUE TITLE
Does Swaming connect to internet?!

### ISSUE THREAD

**Issue by RDaneelOlivav** [numenta/nupic#2016]
Just a quick doubt. When swarming my Net usage indicator seems to spike when swarming. Is it just a glitch in UBUNTU sofware or swarming is connecting to the web in some way?

**Comment by breznak** [comment]
Swarming uses a DB (mysql) so I think the connections to the DB might be
over localhost, which will show up as net usage (but nothing leaves the
machine)

**Comment by rhyolight** [comment]
Yes, @breznak is right.
