### ISSUE TITLE
Allow users to write their own PyRegion subclasses

### ISSUE THREAD

**Issue by scottpurdy** [numenta/nupic#2057]
Currently, `nupic.core` has hard-coded Python paths for finding regions:
https://github.com/numenta/nupic.core/blob/957ebe5329defc9b78323aba66e1e0f65cbf1335/src/nupic/engine/RegionImplFactory.cpp#L47

Users should be able to write their own. This will require updating the Python Network API to take class references rather than string names of regions and possibly related changes to make this work in the PyRegion implementation and `nupic.core` code.

Part of #2093

**Comment by breznak** [comment]
this has a c++ counterpart: https://github.com/numenta/nupic.core/issues/359
