### ISSUE TITLE
Yosemite gcc/clang -stdlib=c++ issue

### ISSUE THREAD

**Issue by dreamTown** [numenta/nupic#2061]
Hi, I'm new to NuPIC and I have been trying to install it for more than a week without success. 

I'm runnig on MacOSX 10.10 Yosemite and tried using pip with my python distribtution Anaconda 2.1.0. At first it was impossible to compile capnp although my XCode is 6.3 and clang should able to handle c++11 stuff. So I brew a brand new gcc (4.9.2) and compiled it. But now when I try pip install nupic --user, I have this message regardless of the compiler I specify (native yosemite gcc, gcc 4.9.2, clang):

clang: error: invalid deployment target for -stdlib=libc++ (requires OS X 10.7 or later)
    error: command 'gcc' failed with exit status 1

I think this must be a pretty simple issue to fix but I've looked for similar questions wihtout finding any answers. 

Thanks.

EDIT: Somehow the install seems to believe I'm on MacOS 10.5 since it has created the folder:

build/lib.macosx-10.5-x86_64-2.7

**Comment by breznak** [comment]
I can't hep you much with the OSX stuff, but 
* Nupic does not compile on gcc 4.9
* I'm not sure about gcc 4.7 (because of c++11), so gcc-4.8 is your best bet

'''
clang: error: invalid deployment target for -stdlib=libc++ (requires OS X 10.7 or later)
error: command 'gcc' failed with exit status 1
'''
This is weird, why is clang failing due to gcc? Also, you can try to fiddle with the deployment target (in cmake file)

**Comment by rhyolight** [comment]
I'll try to get to this next week.

**Comment by dreamTown** [comment]
I didn't really have much time to dig moire into this, but I noticed that the requirements for pycapnp were Cython==0.21.2 but I have the 0.22 version released in February. I wonder if this could be the problem (remember I succeed compiling pycapnp with gcc 4.9 but nupic doesn't compile with it).
I raised the thing in the pycapnp forum but does someone have any idea about this ? Or someone using nupic with Cython 0.22 ?

**Comment by rhyolight** [comment]
@dreamTown Try this:

    export MACOSX_DEPLOYMENT_TARGET=10.10

And install again. See what happens.

**Comment by dreamTown** [comment]
It worked !!! Do you what is the source of the problem ? Why was the deployment target wrong ?

Thanks a lot !

**Comment by david-ragazzi** [comment]
Nice! Closing...

**Comment by rhyolight** [comment]
No clue why the deployment target was wrong. Do you do much Xcode work? If you have a project that is compiling for Mavericks, Xcode might have permanently set MACOSX_DEPLOYMENT_TARGET for you.

**Comment by dreamTown** [comment]
Actually I think the issue is more related to my Anaconda distribution (2.2.0), even if nupic did install, I was then stuck with issue #1813. I tried all the fix suggested but none of them worked (and the flag macosx-10.5 remained).
So I just started over with a homebrew version of python and pipped all the packages I needed. I guess this is the best way to do python with OS X and now I am happily settled but in case you want to dig further with anacaonda, it could be useful for future users.

**Comment by rhyolight** [comment]
I have had exactly zero success with Anaconda on OS X.

---------
Matt Taylor
OS Community Flag-Bearer
Numenta

**Comment by krosty4782** [comment]
Had the same problem; = "export MACOSX_DEPLOYMENT_TARGET=10.10" fidex it.
Thanks

**Comment by jgab3103** [comment]
This drove me completely crazy too and sure enough this fix worked! Thanks guys...

**Comment by rhyolight** [comment]
Added this to the [Build FAQ](https://github.com/numenta/nupic/wiki/Build-and-Installation-FAQ#clang-error-invalid-deployment-target).
