### ISSUE TITLE
Build from source on Linux, clang-3.5 segfault in capnp on running unit tests

### ISSUE THREAD

**Issue by breznak** [numenta/nupic#2063]
Install: 
I compile from source, on linux, clang-3.5: 
_nupic.core_ : `CC=clang-3.5  CXX=clang++-3.5 cmake ../../src -DCMAKE_INSTALL_PREFIX=../release`
nupic.core passes its tests.

_nupic_ : `export CC=clang-3.5 && export CXX=clang++-3.5 && python setup.py --nupic-core-dir=/home/mmm/devel/nupic/nupic.core/build/release/ [build,develop]`

Then run tests: 
`./scripts/run_nupic_tests -u`
and get  
```
collecting 187 items / 1 errors
============================================================================================================ ERRORS =============================================================================================================
___________________________________________________________________________________ ERROR collecting tests/unit/nupic/encoders/delta_test.py ____________________________________________________________________________________
tests/unit/nupic/encoders/delta_test.py:32: in <module>
    from nupic.encoders.delta_capnp import DeltaEncoderProto
capnp/lib/capnp.pyx:3612: in capnp.lib.capnp._Loader.load_module (capnp/lib/capnp.cpp:68827)
    ???
capnp/lib/capnp.pyx:3591: in capnp.lib.capnp.load (capnp/lib/capnp.cpp:68317)
    ???
capnp/lib/capnp.pyx:3055: in capnp.lib.capnp.SchemaParser.load (capnp/lib/capnp.cpp:62181)
    ???
E   RuntimeError: std::bad_alloc

```

**Comment by scottpurdy** [comment]
@breznak, what version of pycapnp do you have installed? `python -c "import capnp; print capnp.__version__"`

If you still have `0.5.0` or `0.5.1` then that is the problem. We recently upgrade to latest `0.5.5` in nupic to fix this issue. You can just upgrade `pycapnp`, no need to rebuild nupic or anything AFAIK.

**Comment by breznak** [comment]
yes, I'm on `0.5.1`, I have some trouble installing (pip), will report back when it succeeds, or I ran out of ideas :wink: Thanks!

**Comment by breznak** [comment]
@scottpurdy funny, I'm running in `pythonenv` and had `pycapnp-0.5.1` installed system-wide. 
`pip install pycapnp-0.5.5` within the python env succeeded, but pip list still returned 0.5.1; uninstalling the global 0.5.1, the newest 055 immediately appeared in pyenv. 

Now the tests run fine, closing! big thanks!
