### ISSUE TITLE
(Scalar) encoder + CAPNP + cProfile compination fails to load

### ISSUE THREAD

**Issue by breznak** [numenta/nupic#2067]
When I load ScalarEncoder, it works obviously, when I load it with `cProfile` module, CAPNP throws an error. 

```
  File "enc_speed.py", line 28, in <module>
    from nupic.encoders.scalar import ScalarEncoder
  File "nupic/encoders/__init__.py", line 34, in <module>
    from multi import MultiEncoder
  File "nupic/encoders/multi.py", line 40, in <module>
    from nupic.encoders.scalar_capnp import ScalarEncoderProto
  File "capnp/lib/capnp.pyx", line 3773, in capnp.lib.capnp._Loader.load_module (capnp/lib/capnp.cpp:71749)
  File "capnp/lib/capnp.pyx", line 3752, in capnp.lib.capnp.load (capnp/lib/capnp.cpp:71239)
  File "capnp/lib/capnp.pyx", line 3126, in capnp.lib.capnp.SchemaParser.load (capnp/lib/capnp.cpp:63334)
capnp.lib.capnp.KjException: /home/mmm/devel/nupic/nupic-source/nupic/encoders/scalar.capnp:0: failed: Duplicate ID @0xfa7d16f86048a6e4.
stack: 0x7f848fcd93f8 0x7f848fbfb329 0x7f848fbfae75 0x7f848fc20e6a 0x7f848fc213a2 0x7f848fc25796 0x7f848fc2588b 0x7f848fc25de9 0x7f848fc25e28 0x7f848fbfa29e 0x7f848fbfa38b 0x7f848fbaab98 0x7f848fb9ab96 0x7f848fb7c23f 0x7f848fb4f54f 0x7f848fb74bca
```

**Comment by scottpurdy** [comment]
@breznak - I can't reproduce. I tried calling the script below with python and then cProfile but it worked fine in both. This looks similar to the issue with `0.5.1` so I'd post an issue with pycapnp:
https://github.com/jparyani/pycapnp

Sample script:
```
from nupic.encoders import ScalarEncoder
```

Side note: We normally do `from nupic.encoders.scalar import ScalarEncoder` but I wanted to match your use case.

**Comment by breznak** [comment]
I forgot to post steps to reporoduce. 
@scottpurdy can you try this?
` python -m cProfile -s cumtime ./scripts/profiling/enc_profile.py ` which crashes for my install.

**Comment by scottpurdy** [comment]
@breznak - I get the same results. Traceback with KjException for duplicate ID when run with cProfile. I'd file the issue with pycapnp and make sure to include which versions you are using.

**Comment by oxtopus** [comment]
Try running with relative imports in the .canp files

**Comment by rhyolight** [comment]
Should we close this as duplicate of #2070? It contains more debugging output.

**Comment by breznak** [comment]
yep, moved to #2070
