### ISSUE TITLE
FunctionSource fails if either reset or sequence or both fields are specified

### ISSUE THREAD

**Issue by esorf** [numenta/nupic#2068]
Reset or Sequence - Fails because of uninitialized self._prevSequenceId
Both - Fails because of invalid self._resetFieldName reference

**Comment by breznak** [comment]
@esorf can you be more descriptive where/what/how that happens?

**Comment by esorf** [comment]
Here's a simple REPL session showing errors

    >>> fs = FunctionSource(dataFunction, state=None, resetFieldName="reset", sequenceIdFieldName="sequence")
    >>> fs.getNextRecordDict()
      File "/Library/Python/2.7/site-packages/nupic/data/functionsource.py", line 83, in getNextRecordDict
        reset = result[self._resetFieldName]
    AttributeError: 'FunctionSource' object has no attribute '_resetFieldName'

    >>> fs = FunctionSource(dataFunction, state=None, resetFieldName="reset", sequenceIdFieldName=None)
    >>> fs.getNextRecordDict()
      File "/Library/Python/2.7/site-packages/nupic/data/functionsource.py", line 78, in getNextRecordDict
        self._prevSequenceId += 1
    AttributeError: 'FunctionSource' object has no attribute '_prevSequenceId'

    >>> fs = FunctionSource(dataFunction, state=None, resetFieldName=None, sequenceIdFieldName="sequence")
    >>> fs.getNextRecordDict()
      File "/Library/Python/2.7/site-packages/nupic/data/functionsource.py", line 70, in getNextRecordDict
        reset = sequenceId != self._prevSequenceId
    AttributeError: 'FunctionSource' object has no attribute '_prevSequenceId'
