### ISSUE TITLE
GH labels send to our different ML

### ISSUE THREAD

**Issue by breznak** [numenta/nupic#2076]
What if we add new labels here: `Discuss, Hackers, Theory` and issues labelled with it get automatically posted to respective ML? 
That would be useful for situations when you say "Ok, let's ask this on ML" :wink: and also combines the convenience of ML with nicer interface of GH.

**Comment by breznak** [comment]
@rhyolight ?

**Comment by rhyolight** [comment]
The [GitHub webhook API](https://developer.github.com/v3/activity/events/types/) does not contain an event for labelling, but it could possibly be done in response to issue comments. Please create a ticket on https://github.com/numenta/nupic.tools/ for this if you like. But it would depend on https://github.com/numenta/nupic.tools/issues/166.
