### ISSUE TITLE
Move Connections class from TemporalMemory to a separate module

### ISSUE THREAD

**Issue by david-ragazzi** [numenta/nupic#2079]
As SpatialPooler and other classes can re-use Connections class, it's interesting that this class be called from a specific file than `temporal_memory.py`, i.e. `connections.py`.

**Comment by rhyolight** [comment]
The `status:ready` label is usually used for PRs that are ready for review.

**Comment by breznak** [comment]
:+1:

**Comment by david-ragazzi** [comment]
> The status:ready label is usually used for PRs that are ready for review. 

Thanks..Talking about... What kind of labels an issue should have, or it is not necessary?

**Comment by rhyolight** [comment]
At least one subject and one type, probably.
