### ISSUE TITLE
Miss-spelled configuration directive in pylintrc

### ISSUE THREAD

**Issue by oxtopus** [numenta/nupic#2087]
re: https://github.com/numenta/nupic/blob/master/pylintrc#L258

```
# Maximum number of branch for function / method body
max-branchs=20
```

Should be:

```
# Maximum number of branch for function / method body
max-branches=20
```

**Comment by SaganBolliger** [comment]
Looks like this has been fixed. https://github.com/numenta/nupic/blob/master/pylintrc#L262

**Comment by breznak** [comment]
yep, fixed. Thanks for notice @SaganBolliger ! Closing.
