### ISSUE TITLE
Add Cap'n Proto serialization to Python Temporal Memory

### ISSUE THREAD

**Issue by scottpurdy** [numenta/nupic#2089]
See parent issue #1449 

Depends on #2097 and #2098.

It may be better to put the schema file in nupic.core from the start even if the C++ implementation isn't there yet. That way we don't have to go and move it over later.

**Comment by chetan51** [comment]
Depends on https://github.com/numenta/nupic/issues/2097 and https://github.com/numenta/nupic/issues/2098.

**Comment by rcrowder** [comment]
Let me know if there is anything you need. I'm currently working in a Ubuntu VM to test out the SWIG and Python unit tests.
