### ISSUE TITLE
Misnamed private method in tp_segment_learning.py

### ISSUE THREAD

**Issue by rmsmith007** [numenta/nupic#2101]
**nupic/examples/tp/tp_segment_learning.py** fails when **verbosity** set to greater than **1** because method defined as **_printAllTrainingSequences** is called without the leading underscore at end of **_buildSegmentLearningTrainingSet** and **_buildSL2TrainingSet**

**Comment by rhyolight** [comment]
@chetan51 or @BoltzmannBrain Can you investigate?

**Comment by BoltzmannBrain** [comment]
@rhyolight please review
