### ISSUE TITLE
Remove learningRadius parameter in Temporal Memory

### ISSUE THREAD

**Issue by rmccall84** [numenta/nupic#2109]
The parameter in question is here:

https://github.com/numenta/nupic/blob/master/nupic/research/temporal_memory.py#L43

It is not used, neither nupic/research nor in nupic.research

It is confusing to have such an unsupported parameter given the large number of parameters. I'd be happy to remove this and add an issue to implement it. Just want to be sure that I'm not missing something.

**Comment by rmccall84** [comment]
@chetan51 @scottpurdy @subutai

**Comment by rhyolight** [comment]
@rmccall84 There is a `TODO` item at https://github.com/numenta/nupic/blob/master/nupic/research/temporal_memory.py#L538 saying: `TODO: Respect topology and learningRadius`. So maybe it is there for future development? 

@chetan51 ?

**Comment by subutai** [comment]
The parameter is only needed to support topology.  It is an item for future development so I'm fine if we file an issue and remove it.

**Comment by chetan51** [comment]
I agree with Subutai.

**Comment by rmccall84** [comment]
I've opened an issue to implement the parameter: https://github.com/numenta/nupic/issues/2110
