### ISSUE TITLE
Possible bug in c++ CLAClassifierRegion

### ISSUE THREAD

**Issue by mj-harvey** [numenta/nupic#2115]
Hi,

This is against HEAD/ ec270f3918012304263db557d969c412bb705ea5

I've constructed a simple NontemporalClassification model, with a single input. Both the input and the output classifier are of type "string".

It's trained with:

```
for r in range(1000):
	ip = str( random_integers( low=0, high=99 ) );
	res = model.run( { "input": "A" + ip, "output": "Z" + ip } )
	print "A"+ip,  res.inferences["multiStepBestPredictions"][0]
```
The output is correctly of string form ("Zxx")

However, when classification is attempted:
```
	ip = str( random_integers( low=0, high=99 ) );
	res=model.run( { "input": "A" + str(ip), "output": None } )
	print  res.inferences["multiStepBestPredictions"][0], res
```
The returned category is a float.

When I change the CLAClassifierRegion implementation from cpp to py, I recover the expected behaviour of a restring response.

If I were to hazzard a guess, I'd say the Classifier indexes the  category string and, in this case, is returning the index rather than the dereferenced value.

**Comment by rhyolight** [comment]
@oxtopus You want to take a look at this?

**Comment by oxtopus** [comment]
@scottpurdy There's a chance this may be related to https://github.com/numenta/nupic/issues/2106

I am able to confirm the difference in behavior described here toggling between cpp and py implementations, but and digging further to see if they are related.

**Comment by oxtopus** [comment]
See https://gist.github.com/oxtopus/23384ab43e063102227f for reproducible example w/ output.

**Comment by rhyolight** [comment]
Very nice, @oxtopus. Thank you for the analysis.
