### ISSUE TITLE
Remove Python shebang / executable bits

### ISSUE THREAD

**Issue by scottpurdy** [numenta/nupic#2119]
This task is to:
1. Remove "shebang" lines from files. These are the lines at the start of a file that look like `#!/usr/bin/env python`.
2. Remove the executable bit from Python scripts.

Original proposal below.

---

Currently, our Python convention is that any executable Python scripts should have the following:
1. An `if __name__ == "__main__":` block
2. First line should be `#!/usr/bin/env python`
3. File should have executable bit set

This proposal is to remove steps 2 and 3 since they are unnecessary and add extra steps. Plus the "entry_points" option in the `setup.py` script allows you to specify files or functions that should be installed as executable scripts, bypassing the need for steps 2 and 3.

**Comment by rhyolight** [comment]
:+1:

**Comment by oxtopus** [comment]
:+1: Especially as we consider Windows support

**Comment by souravsingh** [comment]
Is the issue open?

**Comment by rhyolight** [comment]
@souravsingh Yes, do you wish to work on it?

**Comment by souravsingh** [comment]
Thanks! I would like to work on the issue

**Comment by rhyolight** [comment]
@souravsingh Great! Please have a read of our [Development Process](https://github.com/numenta/nupic/wiki/Development-Process) document, and sign our [contributor's license](http://numenta.org/licenses/cl/). Let me know and I will assign you.

**Comment by souravsingh** [comment]
@rhyolight A small question: Why the contributor's license? I am seeing it for the first time in an open-source project. I am sorry for the bad question.

**Comment by souravsingh** [comment]
I am also sorry for asking such a bad question

**Comment by rhyolight** [comment]
Contributor's license agreements are very common practices among companies who host open source projects. When you sign a CLA, it says that all your code contributions are copyright  of the company hosting the open source software, not yourself. This is a common practice among us companies like Yahoo, Facebook, Google, etc. It allows ownership of the codebase to stay with one entity so major decisions about the code can be made more easily in the future.

**Comment by souravsingh** [comment]
Thanks for the answer. I have signed the Agreement and have reviewed the docs.

**Comment by rhyolight** [comment]
Thanks, @souravsingh! We'll process the document tomorrow.
