### ISSUE TITLE
Switch tests/experiments to C++ SpatialPooler

### ISSUE THREAD

**Issue by scottpurdy** [numenta/nupic#2128]
NuPIC tests are running much slower since the switch to Python SpatialPooler. In general, we should use `nupic.bindings.algorithms.SpatialPooler` everywhere unless we are specifically testing the Python version. This should speed up the build/tests a lot.

Part of this change is benchmarking the tests from SHA (@rhyolight please put SHA here from before change to new SP), SHA adf01ae4 (after switch to new Python SP), and the version after switching to the new C++ version.

**Comment by rhyolight** [comment]
Benchmark these SHAs:

| Status | SHA | Test timing |
| --------- | -------- | ---------------- |
| Before change to new SP | [10e3ea5d811f1b0fdd54a7b95b584e8fbdeaea27](https://github.com/numenta/nupic/commit/10e3ea5d811f1b0fdd54a7b95b584e8fbdeaea27) | TBA |
| After change to new SP | [04322c7c2e50c8e35a5c701362ede80af3c434ce](https://github.com/numenta/nupic/commit/04322c7c2e50c8e35a5c701362ede80af3c434ce) | TBA |
| New PR SHA with C++ version | ? | TBA |
