### ISSUE TITLE
Unknow error when installing from source on ubuntu12.04

### ISSUE THREAD

**Issue by frank-tancf** [numenta/nupic#2129]
I got 
./configure: line 2769: printf: write error: Broken pipe
./configure: line 2751: printf: write error: Broken pipe
when I did "pip install --user -r $NUPIC/external/common/requirements.txt".
I didn't find solutions anywhere.Can any one help me?

**Comment by rhyolight** [comment]
I think the wiki you are following might be out of date. 

Can you try the simple instruction:

    pip install https://s3-us-west-2.amazonaws.com/artifacts.numenta.org/numenta/nupic/releases/nupic-0.2.2-cp27-none-linux_x86_64.whl

If that doesn't work, from the checkout directory try:

    python setup.py install --user

**Comment by frank-tancf** [comment]
I got "urlopen error time out" when I did "pip install https://s3-us-west-2.amazonaws.com/artifacts.numenta.org/numenta/nupic/releases/nupic-0.2.2-cp27-none-linux_x86_64.whl"

**Comment by frank-tancf** [comment]
Unfortunatelly, neither you said worked.

**Comment by rhyolight** [comment]
@frank-tancf Do you have a working internet connection? If so, is it very slow?

**Comment by frank-tancf** [comment]
I do have a connection. And I don't think it's slow.I think maybe it's the problem of Chinese network.you know, there are some websites we cannot connect without VPN . I will try an VPN later

**Comment by breznak** [comment]
@frank-tancf I think I saw the error from time to time, not sure, but seems to me it's by "messed-up" system libs. Did you do a bigger update before that? can you try rebooting and compile again from a clean system? cheers

**Comment by frank-tancf** [comment]
@breznak I think I get the right solution from the new wiki.And I found that I missed one of needed python library.I think I am on the right way. I missed the lib named "Numpy". I got everything all right when I installed it.

**Comment by frank-tancf** [comment]
Traceback (most recent call last):
  File "setup.py", line 651, in <module>
    nupicCoreReleaseDir = prepareNupicCore(options, platform, bitness)
  File "setup.py", line 558, in prepareNupicCore
    nupicCoreLocalPackage, nupicCoreLocalDirToUnpack, nupicCoreReleaseDir
  File "setup.py", line 83, in unpackFile
    tarFileObj.extractall(destDir)
  File "/usr/lib/python2.7/tarfile.py", line 2048, in extractall
    self.extract(tarinfo, path)
  File "/usr/lib/python2.7/tarfile.py", line 2085, in extract
    self._extract_member(tarinfo, os.path.join(path, tarinfo.name))
  File "/usr/lib/python2.7/tarfile.py", line 2161, in _extract_member
    self.makefile(tarinfo, targetpath)
  File "/usr/lib/python2.7/tarfile.py", line 2201, in makefile
    copyfileobj(source, target)
  File "/usr/lib/python2.7/tarfile.py", line 266, in copyfileobj
    shutil.copyfileobj(src, dst)
  File "/usr/lib/python2.7/shutil.py", line 49, in copyfileobj
    buf = fsrc.read(length)
  File "/usr/lib/python2.7/tarfile.py", line 819, in read
    buf += self.fileobj.read(size - len(buf))
  File "/usr/lib/python2.7/tarfile.py", line 737, in read
    return self.readnormal(size)
  File "/usr/lib/python2.7/tarfile.py", line 746, in readnormal
    return self.fileobj.read(size)
  File "/usr/lib/python2.7/gzip.py", line 256, in read
    self._read(readsize)
  File "/usr/lib/python2.7/gzip.py", line 303, in _read
    self._read_eof()
  File "/usr/lib/python2.7/gzip.py", line 342, in _read_eof
    hex(self.crc)))
IOError: CRC check failed 0x15255ce7 != 0x8ed5c683L

**Comment by frank-tancf** [comment]
sorry, I got another problem when I finish downloading "nupic_core-2a06015a9579e24373380749f6cd9f8de10f7550-linux64.tar.gz" . And I don't know why.

**Comment by breznak** [comment]
> IOError: CRC check failed 0x15255ce7 != 0x8ed5c683L 

@frank-tancf just redownload the file, you can download it even manually and place it in the appropriate folder (validate the SHA, should be  `2a06015a9579e24373380749f6cd9f8de10f7550` as in the name)

**Comment by breznak** [comment]
closing as out-dated. @frank-tancf please reopen and update if needed. thanks
