### ISSUE TITLE
Create encoder for 1D depth data

### ISSUE THREAD

**Issue by chetan51** [numenta/nupic#2160]
Encodes an array of 1D depth data (an array of numbers, each representing distance to the closest object). This would be used in our sensorimotor research.

**Comment by chetan51** [comment]
Moving to nupic.research.

**Comment by breznak** [comment]
On Friday, May 29, 2015, Chetan Surpur <notifications@github.com> wrote:
> Closed #2160.
>
> —
> Reply to this email directly or view it on GitHub.<
https://ci3.googleusercontent.com/proxy/NSh77sFogcb1M57vuehr51RYLIa3cb0i-E55dDtFW7u08GFIAwaf2xxAafVVYVAK5lDQ6Pc04ieIssmdl0OsvRyixQrCTz1jMct7N_fInF0Qg9uCwiviQky_a_mytg8wzruoxq8SHA-2TP7QUU9la3oTtNFzqA=s0-d-e1-ft#https://github.com/notifications/beacon/ACENX3dqtdDcen1B53eTGn1uJz61Q6iYks5oOLbpgaJpZM4EsfcP.gif
>

Was this the Vector encoder?

-- 
Marek Otahal :o)

**Comment by chetan51** [comment]
No, it was a separate encoder for depth sensors, which we will start experimenting with in nupic.research.
