### ISSUE TITLE
KNNClassifier wishlist

### ISSUE THREAD

**Issue by rmccall84** [numenta/nupic#2198]
This Issue has been broken up into (and replaced by):

https://github.com/numenta/nupic/issues/2271

https://github.com/numenta/nupic/issues/2270

Improvements to KNNClassifier

- [ ] infer() should have options for sparse and dense inputs. Right now, for example, if distance metric is 'rawOverlap' infer must be called with a dense input even if classifier was trained on sparse input repr. If sparse input is used, the classification is non-deterministic
- [ ] Add getPatternCount() accessor method, possible others for a nice API
- [ ] Understand `partitionId` and implement, remove, or document appropriately
- [ ] Understand and then remove or document `rowID`
- [ ] Move `leaveOneOutTest` method from KNNClassifier module to appropriate test module
- [x] Improve explanations of constructor parameters
- [ ] Remove unused arguments from infer() method
- [ ] Move `leaveOneOutTest` to another module
- [ ] SVD / PCA features need better docs
- [ ] reorder parameters in constructor putting dependent parameters after their dependencies

There are several instances of KNN Classifier that one can make by specifying the following constructor arguments and, ideally, we should have adequate test coverage for the different possibilities:
- [ ] useSparseMemory (boolean)

distanceMethod (string)
- [ ] "norm"
- [ ] "rawOverlap"
- [ ] "pctOverlapOfLarger"
- [ ] "pctOverlapOfProto"

Ensure that infer() & learn() respond nicely to:
- [x] Sparse representation with unsorted indices 
- [x] Empty input list

**Comment by BoltzmannBrain** [comment]
This should be done in conjunction with #2172. And we should add to this list figuring out the use of [`partitionId`](https://github.com/numenta/nupic/blob/master/nupic/algorithms/KNNClassifier.py#L332) in the classifier.

**Comment by rmccall84** [comment]
@BoltzmannBrain thanks for connecting these two. Good unit testing of the classifier will likely resolve a lot of the issues I've raised. I'll sync w/ you before working on this.

**Comment by mihail911** [comment]
Additional Improvements:
     1) Modify KNN 'infer' so that client has option of outputting top `n` most frequent categories rather than  
          just the most frequent.

**Comment by BoltzmannBrain** [comment]
@scottpurdy this should not be closed yet, there are still many tasks in this wishlist.

**Comment by rmccall84** [comment]
@BoltzmannBrain @scottpurdy it's my fault because I put fixes in a PR scott closed. I can created sub tasks, Alex

**Comment by breznak** [comment]
@rmccall84 can you please take a look at https://github.com/numenta/nupic/issues/1844 , it's a bit older so I'm not sure about it.

**Comment by breznak** [comment]
Also 
https://github.com/numenta/nupic/issues/422 how `prediction` field is selected from current (and past) predictions. (My oldest still open issue :open_hands: )

**Comment by rmccall84** [comment]
this issue has been supplanted by https://github.com/numenta/nupic/issues/2271

https://github.com/numenta/nupic/issues/2270

**Comment by rmccall84** [comment]
@breznak I could look at it but I don't have experience with that part of the code base. if I have time later I'll look at it sry!
