### ISSUE TITLE
Travis CI build failing for my fork but works for PR

### ISSUE THREAD

**Issue by akhilaananthram** [numenta/nupic#2199]
Travis CI fails on my fork before it even attempts to compile my code.  The code compiles and passes all tests on my local machine.  Additionally, it works when I submit pull requests.

If I add "sudo: required" to .travis.yml, then Travis CI works on my fork and it still works for PR.

My fork's Travis CI console:
https://travis-ci.org/akhilaananthram/nupic/jobs/66115117

@rhyolight @scottpurdy

**Comment by rhyolight** [comment]
Sudo is required because of [this line](https://github.com/numenta/nupic/blob/master/ci/travis/before_install-linux.sh#L54) in a build script:

```
# Workaround for multiprocessing.Queue SemLock error from run_opf_bechmarks_test.
# See: https://github.com/travis-ci/travis-cookbooks/issues/155
sudo rm -rf /dev/shm && sudo ln -s /run/shm /dev/shm
```

**Comment by akhilaananthram** [comment]
Why does that only affect my fork and not master?

**Comment by rhyolight** [comment]
I don't understand why. My fork has always worked fine, even when running outside of a PR. It is certainly a permissions issue. The Travis-CI team changes things a lot. 

When your code runs in a PR, it is run as a "numenta" job. But when it runs on your own personal fork, it runs as your own job. There must be different permissions. I suggest you look through http://docs.travis-ci.com/user/build-environment-updates/ and see if you can tell that they have changed anything recently.

IMO, as long as your pull requests are running properly, this is not a NuPIC issue, it's something to do with your Travis-CI account permissions, so I'm going to close it.
