### ISSUE TITLE
Allow users to use custom regions where the class name does not match the module name.

### ISSUE THREAD

**Issue by akhilaananthram** [numenta/nupic#2211]
This means users should be able to register a region by passing a reference to its class.  Then, when they want to add the region, they simply say the class name.

**Comment by cogmission** [comment]
Ideally the inputs and outputs of a given Region should follow a convention
such that a Region could be an empty shell that doesn't do any NuPIC
specific processing but can receive a known input type on its input and can
emit a known output type on its output?

On Fri, Jun 12, 2015 at 3:18 PM, Akhila <notifications@github.com> wrote:

> This means users should be able to register a region by passing a
> reference to its class. Then, when they want to add the region, they simply
> say the class name.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/numenta/nupic/issues/2211>.
>



-- 
*With kind regards,*

David Ray
Java Solutions Architect

*Cortical.io <http://cortical.io/>*
Sponsor of:  HTM.java <https://github.com/numenta/htm.java>

d.ray@cortical.io
http://cortical.io
