### ISSUE TITLE
WARNING no libcapnp detected

### ISSUE THREAD

**Issue by camer1kj** [numenta/nupic#2223]
Trying to download pycapnp as part of the NuPIC download and receiving the following error. I do have Capnproto downloaded/updated, but it is not being detected. Also do not have sudo privileges on the computer, so may be running into a permissions issue- either way it should be detecting the capnp first. Any suggestions?

$ pip install --user pycapnp
Collecting pycapnp
Using cached pycapnp-0.5.6.tar.gz
Installing collected packages: pycapnp
Running setup.py install for pycapnp
Complete output from command /home/kj/anaconda/bin/python -c "import setuptools, tokenize;file='/tmp/pip-build-1xUnko/pycapnp/setup.py';exec(compile(getattr(tokenize, 'open', open)(file).read().replace('\r\n', '\n'), file, 'exec'))" install --record /tmp/pip-qkrn2b-record/install-record.txt --single-version-externally-managed --compile --user:
running install
running build
running build_py
creating build
creating build/lib.linux-x86_64-2.7
creating build/lib.linux-x86_64-2.7/capnp
copying capnp/gen.py -> build/lib.linux-x86_64-2.7/capnp
copying capnp/__init_.py -> build/lib.linux-x86_64-2.7/capnp
copying capnp/version.py -> build/lib.linux-x86_64-2.7/capnp
copying capnp/init.pxd -> build/lib.linux-x86_64-2.7/capnp
copying capnp/c++.capnp -> build/lib.linux-x86_64-2.7/capnp
copying capnp/schema.capnp -> build/lib.linux-x86_64-2.7/capnp
creating build/lib.linux-x86_64-2.7/capnp/helpers
copying capnp/helpers/non_circular.pxd -> build/lib.linux-x86_64-2.7/capnp/helpers
copying capnp/helpers/helpers.pxd -> build/lib.linux-x86_64-2.7/capnp/helpers
copying capnp/helpers/init.pxd -> build/lib.linux-x86_64-2.7/capnp/helpers
copying capnp/helpers/checkCompiler.h -> build/lib.linux-x86_64-2.7/capnp/helpers
copying capnp/helpers/fixMaybe.h -> build/lib.linux-x86_64-2.7/capnp/helpers
copying capnp/helpers/serialize.h -> build/lib.linux-x86_64-2.7/capnp/helpers
copying capnp/helpers/capabilityHelper.h -> build/lib.linux-x86_64-2.7/capnp/helpers
copying capnp/helpers/asyncHelper.h -> build/lib.linux-x86_64-2.7/capnp/helpers
copying capnp/helpers/rpcHelper.h -> build/lib.linux-x86_64-2.7/capnp/helpers
creating build/lib.linux-x86_64-2.7/capnp/includes
copying capnp/includes/capnp_cpp.pxd -> build/lib.linux-x86_64-2.7/capnp/includes
copying capnp/includes/types.pxd -> build/lib.linux-x86_64-2.7/capnp/includes
copying capnp/includes/schema_cpp.pxd -> build/lib.linux-x86_64-2.7/capnp/includes
copying capnp/includes/init.pxd -> build/lib.linux-x86_64-2.7/capnp/includes
creating build/lib.linux-x86_64-2.7/capnp/lib
copying capnp/lib/capnp.pxd -> build/lib.linux-x86_64-2.7/capnp/lib
copying capnp/lib/init.pxd -> build/lib.linux-x86_64-2.7/capnp/lib
copying capnp/lib/init.py -> build/lib.linux-x86_64-2.7/capnp/lib
copying capnp/lib/pickle_helper.py -> build/lib.linux-x86_64-2.7/capnp/lib
copying capnp/lib/capnp.pyx -> build/lib.linux-x86_64-2.7/capnp/lib
creating build/lib.linux-x86_64-2.7/capnp/templates
copying capnp/templates/module.pyx -> build/lib.linux-x86_64-2.7/capnp/templates
copying capnp/templates/setup.py.tmpl -> build/lib.linux-x86_64-2.7/capnp/templates
running build_ext
creating /tmp/tmpINRtOA/tmp
cc -c /tmp/timer_createGmrQ9A.c -o /tmp/tmpINRtOA/tmp/timer_createGmrQ9A.o
cc /tmp/tmpINRtOA/tmp/timer_createGmrQ9A.o -o /tmp/tmpINRtOA/a.out
/tmp/tmpINRtOA/tmp/timer_createGmrQ9A.o: In function main': timer_createGmrQ9A.c:(.text+0x15): undefined reference totimer_create'
collect2: ld returned 1 exit status
creating tmp
creating tmp/tmpINRtOA
cc -c /tmp/tmpINRtOA/vers.cpp -o tmp/tmpINRtOA/vers.o --std=c++11
cc1plus: error: unrecognized command line option "-std=c++11"
WARNING no libcapnp detected. Will download and build it from source now. If you have C++ Cap'n Proto installed, it may be out of date or is not being detected. Downloading and building libcapnp may take a while.
fetching https://capnproto.org/capnproto-c++-0.5.1.2.tar.gz into /tmp/pip-build-1xUnko/pycapnp/bundled
src/capnp/schema.c++: In member function 'bool capnp::InterfaceSchema::extends(capnp::InterfaceSchema, capnp::uint&) const':
src/capnp/schema.c++:602:12: error: converting to 'bool' from 'std::nullptr_t' requires direct-initialization [-fpermissive]
return nullptr;
^
make: *** [src/capnp/schema.lo] Error 1
make: *** Waiting for unfinished jobs....
Traceback (most recent call last):
File "", line 1, in
File "/tmp/pip-build-1xUnko/pycapnp/setup.py", line 168, in
'Topic :: Communications'],
File "/home/kjcamero/anaconda/lib/python2.7/distutils/core.py", line 151, in setup
dist.run_commands()
File "/home/kjcamero/anaconda/lib/python2.7/distutils/dist.py", line 953, in run_commands
self.run_command(cmd)
File "/home/kjcamero/anaconda/lib/python2.7/distutils/dist.py", line 972, in run_command
cmd_obj.run()
File "/home/kjcamero/anaconda/lib/python2.7/site-packages/setuptools/command/install.py", line 61, in run
return orig.install.run(self)
File "/home/kjcamero/anaconda/lib/python2.7/distutils/command/install.py", line 563, in run
self.run_command('build')
File "/home/kjcamero/anaconda/lib/python2.7/distutils/cmd.py", line 326, in run_command
self.distribution.run_command(command)
File "/home/kjcamero/anaconda/lib/python2.7/distutils/dist.py", line 972, in run_command
cmd_obj.run()
File "/home/kjcamero/anaconda/lib/python2.7/distutils/command/build.py", line 127, in run
self.run_command(cmd_name)
File "/home/kjcamero/anaconda/lib/python2.7/distutils/cmd.py", line 326, in run_command
self.distribution.run_command(command)
File "/home/kjcamero/anaconda/lib/python2.7/distutils/dist.py", line 972, in run_command
cmd_obj.run()
File "/tmp/pip-build-1xUnko/pycapnp/setup.py", line 112, in run
build_libcapnp(bundle_dir, build_dir)
File "buildutils/build.py", line 30, in build_libcapnp
raise RuntimeError('Make failed')
RuntimeError: Make failed

----------------------------------------

Command "/home/kj/anaconda/bin/python -c "import setuptools, tokenize;file='/tmp/pip-build-1xUnko/pycapnp/setup.py';exec(compile(getattr(tokenize, 'open', open)(file).read().replace('\r\n', '\n'), file, 'exec'))" install --record /tmp/pip-qkrn2b-record/install-record.txt --single-version-externally-managed --compile --user" failed with error code 1 in /tmp/pip-build-1xUnko/pycapnp

**Comment by breznak** [comment]
It does the same thing for me too, but continues afterwards. Did you kill
it with Ctrl+C or it stops there?

**Comment by camer1kj** [comment]
It just stops there.

**Comment by breznak** [comment]
Did you wait (like a couple of minutes)? it's downloading the library and
compiling it..

**Comment by camer1kj** [comment]
The program exits with the error above and does not continue further.

**Comment by camer1kj** [comment]
The problem was fixed upstream capnproto with a new commit.
