### ISSUE TITLE
Implement decrement for predicted segments corresponding to inactive cells

### ISSUE THREAD

**Issue by subutai** [numenta/nupic#2224]
This task is to implement a decay that penalizes segments that were incorrectly created and cause extra predictions. If a cell is predicted, but does not become active the corresponding segment should be decremented very slightly. In the current implementation and in the whitepaper such segments are not penalized. In some situations the old behavior can cause an increasing number of extra predictions.

The algorithm functionality has been tested and verified in nupic.research. See [orphan_temporal_memory](https://github.com/numenta/nupic.research/blob/master/sensorimotor/sensorimotor/orphan_temporal_memory.py) and [corresponding simulations](https://github.com/numenta/nupic.research/tree/master/sequence_learning).

This task is to move this functionality over to NuPIC. Specifically we need to add the decrement to TemporalMemory, FastTemporalMemory and add corresponding unit tests. Setting the decrement to zero retains the old behavior.

**Comment by cogmission** [comment]
Watch this...
