### ISSUE TITLE
Import Error

### ISSUE THREAD

**Issue by camer1kj** [numenta/nupic#2226]
It seems that NuPIC has installed successfully, however I get an error when I try to run the following sample code from your website:
from collections import deque
import time
import psutil
import matplotlib.pyplot as plt
from nupic.data.inference_shifter import InferenceShifter
from nupic.frameworks.opf.modelfactory import ModelFactory

The first 5 lines worked without an issue. 
When importing the model factory we first get this error:
ImportError: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.18' not found (required by /home/kj/.local/lib/python2.7/site-packages/nupic-0.2.4.dev0-py2.7-linux-x86_64.egg/nupic/bindings/_math.so)
Which was solved by adding the correct c compiler to our library path. (Note that we downloaded a new version of gcc since our old version was not c++11 compatible. This was installed locally since we do not have sudo privileges on the computer.)

Now with that fixed, we get this error:
ImportError: /home/kj/.local/lib/python2.7/site-packages/nupic-0.2.4.dev0-py2.7-linux-x86_64.egg/nupic/bindings/_math.so: undefined symbol: _ZN5nupic7LogItem6streamB5cxx11Ev

Any ideas?

**Comment by breznak** [comment]
closing as there seems to be newer issue from @camer1kj . Please reopen if still valid problem.
