### ISSUE TITLE
Setup error

### ISSUE THREAD

**Issue by madraf** [numenta/nupic#2235]
Hello everybody!

I'm running Crunchabang Linux 11 (a Debian based distro) with Python 2.7 and Numpy 1.9.2.
I satisfy all the requirements for the installation.

I downloaded nupic and I'm trying to run the setup. Unfortunately I've got this error:

    /usr/include/python2.7/numpy/__multiarray_api.h:1532:1: warning: 'int _import_array()' defined but not used [-Wunused-function]

![screen](https://cloud.githubusercontent.com/assets/12976940/8266853/ac994186-1744-11e5-8b9c-f6236a6a2207.png)

I'm trying to search online but I'm still struggling with this.

Could any of you help me or have any hint?

Thank you!

**Comment by Aayush-Kasurde** [comment]
It seems that "Function unused" is warning and can be ignored using `-Wno-unused-function` but if you see there are lots of errors in your screenshot of terminal.

**Comment by madraf** [comment]
Yep. You're right. My error had to do with the (old) versions of C++ or 
Clang I had in my distro's repositories.

Thanks for your help, by the way :)

**Comment by breznak** [comment]
@madraf looks like this issue is resolved for you. Please reopen if I'm mistaken.
