### ISSUE TITLE
Implement C++ capnp struct to pycapnp conversion

### ISSUE THREAD

**Issue by scottpurdy** [numenta/nupic#2242]
See parent #2241

See:
https://groups.google.com/d/msg/capnproto/1dJ97vebYdw/OFBISqJVUSgJ

This is necessary to allow the C++ PyRegion implementation to pass a struct into the Python PyRegion classes.

**Comment by scottpurdy** [comment]
@jaredweiss fyi

**Comment by scottpurdy** [comment]
replaced by numenta/nupic.core#545

**Comment by rhyolight** [comment]
@scottpurdy so should we close this issue?
