### ISSUE TITLE
Object Tracking

### ISSUE THREAD

**Issue by 6D65** [numenta/nupic#2244]
Hi,

I remember seeing in one of Jeff's old presentations, an example of objects tracking(moving people, with the boxes around them). I'm investigating the use of either Deep Learning Neural Networks or Nupic Platform for this. 

I wonder what shall I begin with? 
Are there any examples for this?

Thanks

**Comment by breznak** [comment]
@6D65 afaik nupic does not have any video examples running nowadays, for this I suggest you look at `nupic-community/nupic.vision` repo, I'm currently working on an encoder used for video frames, others mentioned something about video on ML too

**Comment by breznak** [comment]
PS: I suggest continuing the discussion either on ML, or new issue under the `nupic.vision` and closing the issue here.

**Comment by 6D65** [comment]
Cool, thank you. 

Will create a new issue under nupic.vision for now.
