### ISSUE TITLE
Refactor smudged lines (####, +=+=, ----, etc)

### ISSUE THREAD

**Issue by david-ragazzi** [numenta/nupic#2248]
Current code base has a lot of smudged lines used to separate blocks, to present obvious information, or just to decorate class and funcions, which makes some files has inconsistency format with other files:

Examples:

```
###############################################
def myFunction():
```

```
##################
#  MyClass class #
##################

class MyClass:
```

We could remove these smudged lines in order to code base follow PEP convention and by consequence the code base become cleaner.

**Comment by breznak** [comment]
+1 but with common sense, in some places I think the visual separation
helps readibility

**Comment by david-ragazzi** [comment]
> +1 but with common sense, in some places I think the visual separation helps readibility

Sure. BTW in some places I would suggest we use `#region` and `#endregion` to separate blocks. Although not a official Python feature, many editors like PyCharm are able to colapse those code blocks between these statements and make them visible or invisible to developer.
