### ISSUE TITLE
Rename cpp_region to py_algorithms

### ISSUE THREAD

**Issue by david-ragazzi** [numenta/nupic#2255]
The current prefix `cpp_` confuses us because it lead us to think it handles regions writen in c++, and not the contrary, i.e. python. To reinforce this, "cppregion" term _already_ is used in nupic.core only to separate code related to cpp regions, not python regions, i.e. more one reason to confusion. Some examples:

https://github.com/numenta/nupic.core/blob/633368e394c3de72e93e401efcd8e91ec30abf53/src/nupic/engine/RegionImplFactory.cpp#L71 and its contrapart to python regions: https://github.com/numenta/nupic.core/blob/633368e394c3de72e93e401efcd8e91ec30abf53/src/nupic/engine/RegionImplFactory.cpp#L60

https://github.com/numenta/nupic.core/blob/fd7757d57fe4ba873156963f961567a5a6f42f43/src/CMakeLists.txt#L427 and its contrapart to python regions: https://github.com/numenta/nupic.core/blob/fd7757d57fe4ba873156963f961567a5a6f42f43/src/CMakeLists.txt#L442

(I prefer use `py_algorithms.so` because is more embracing than `py_region.so`, as in the future this library could include more cortical algorithms code than only python regions code.)

**Comment by david-ragazzi** [comment]
@chetan51 @oxtopus @rhyolight @scottpurdy Please review.

**Comment by scottpurdy** [comment]
I understand the change from "cpp" to "py" but not the change from "region" to "algorithms" since this is the code for the C++ PyRegion subclass of RegionImpl and does not include any algorithms. So why "py_algorithms" instead of "py_region"?

**Comment by scottpurdy** [comment]
Also, this is related to [my recent proposal to move the C++ PyRegion into nupic.core](http://lists.numenta.org/pipermail/nupic-hackers_lists.numenta.org/2015-June/003744.html).

**Comment by david-ragazzi** [comment]
> I understand the change from "cpp" to "py" but not the change from "region" to "algorithms" since this is the code for the C++ PyRegion subclass of RegionImpl and does not include any algorithms. So why "py_algorithms" instead of "py_region"?

Ok, I changed to `py_region`.

> Also, this is related to my recent proposal to move the C++ PyRegion into nupic.core.

I think that while there're not work in progress or deadline related to proposal, we can merge first this PR and its contrapart in nupic.core before proposal be implemented.

**Comment by scottpurdy** [comment]
> I think that while there're not work in progress or deadline related to proposal, we can merge first this PR and its contrapart in nupic.core before proposal be implemented.

Agreed, just link dropping :smile:
