### ISSUE TITLE
SWIG binding for C++ TemporalMemory

### ISSUE THREAD

**Issue by rcrowder** [numenta/nupic#2257]
Linked to core PR https://github.com/numenta/nupic.core/pull/409
Initial work in https://github.com/rcrowder/nupic/tree/TM-bindings

**Comment by rcrowder** [comment]
@chetan51 @scottpurdy 
This TM-binding branch hooks into the C++ TM. The following Gist logs show how far the three integration tests make it now. Still some work to do on bringing back set containers, rather than all vector handling. 

1 Performance https://gist.github.com/rcrowder/9e3142fc78fd393430c0
2 Tutorial https://gist.github.com/rcrowder/4f7fb87da7c064c35bcf
3 Extensive https://gist.github.com/rcrowder/613c597af8527673dda7

I now have enough of the integration tests ported to C++ to be able to run them within Visual Studio (minus traces and metrics), alongside a Ubuntu VM running PyCharm (and then a choice of Py or C++ TM). Slow going, but enough to show interface differences, etc.

Next step is to do some further work on the data passing between the Py and C++.

**Comment by rcrowder** [comment]
PS: The extensive integration test had be hobbled to make it run (100s down to 10s of patterns), and certain tests removed (testH1 and up). This is likely to be vector containers blowing the Ubuntu VM memory (?), but my first point of investigation..

**Comment by chetan51** [comment]
Great, thanks for the update!
