### ISSUE TITLE
AnomalyLikelihood with default timestamp behavior

### ISSUE THREAD

**Issue by breznak** [numenta/nupic#2260]
When time stamp is not specified to `AnomalyLikelihood.anomalyProbability()` it defaults to `None` which results in using current time! `datettime.now()`. 

That was done for convenience when you can't/don't want to pass the `timestamp` manually. On the other hand, passing `None`, one would expect it is ignored - which is not. As seen in : 
https://github.com/breznak/nupic/commit/0fc0acfdc8ae977f9d6f9f995cd046ead04021eb

Possible solution: 
- make 2 "default" choices, eg 
  * `"now"` uses current time (as used now) 
  * `None` would use iterations instead of times, so 
```
l1 = AnomalyLikelihood()
l2 = AnomalyLikelihood()

l1.anomalyProbability("something", 0.45)
l2.anomalyProbability("something", 0.45)

l1 == l2 # True
```

**Comment by breznak** [comment]
@subutai ?

**Comment by rhyolight** [comment]
This makes sense to me. I do not think the current time should be used if
no timestamp is sent. Each row must have a user-provided timestamp.

---------
Matt Taylor
OS Community Flag-Bearer
Numenta
