### ISSUE TITLE
TP runs with "non fixed-sized CLA" mode

### ISSUE THREAD

**Issue by breznak** [numenta/nupic#2280]
this functionality is available, but probably not used as there are errors in setting up it for Py/C++ versions of TP and it's not being tested.

**Comment by rhyolight** [comment]
@breznak Can you clarify this issue? Are you reporting that the TP currently runs with a "non fixed-sized CLA" mode, and that is incorrect and should be changed? Or are you suggested a new feature: that the TP run with a "non fixed-size CLA" mode?

**Comment by breznak** [comment]
default is fixed-sized. Functionality for "non fixed-sized" exists, but is broken and should be fixed.

**Comment by breznak** [comment]
Duplicate of https://github.com/numenta/nupic/issues/1360 #historystrikesback

**Comment by rhyolight** [comment]
Which one is better to close?

**Comment by breznak** [comment]
duplicate of https://github.com/numenta/nupic/issues/1360 , closing here.
