### ISSUE TITLE
Build Errors on OS X 10.10.3

### ISSUE THREAD

**Issue by dbl001** [numenta/nupic#2298]
David-Laxers-MacBook-Pro:nupic davidlaxer$ sudo port select --set gcc mp-gcc48
Password:
Selecting 'mp-gcc48' for 'gcc' succeeded. 'mp-gcc48' is now active.
David-Laxers-MacBook-Pro:nupic davidlaxer$ hash gcc

David-Laxers-MacBook-Pro:nupic davidlaxer$ gcc --version
gcc (MacPorts gcc48 4.8.5_0) 4.8.5
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

David-Laxers-MacBook-Pro:nupic davidlaxer$  ARCHFLAGS="-arch x86_64" pip install nupic
You are using pip version 7.0.3, however version 7.1.0 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Requirement already satisfied (use --upgrade to upgrade): nupic in /Users/davidlaxer/nupic
Requirement already satisfied (use --upgrade to upgrade): asteval==0.9.1 in /Users/davidlaxer/anaconda/lib/python2.7/site-packages (from nupic)
Requirement already satisfied (use --upgrade to upgrade): coverage==3.7.1 in /Users/davidlaxer/anaconda/lib/python2.7/site-packages (from nupic)
Requirement already satisfied (use --upgrade to upgrade): mock==1.0.1 in /Users/davidlaxer/anaconda/lib/python2.7/site-packages (from nupic)
Requirement already satisfied (use --upgrade to upgrade): ordereddict==1.1 in /Users/davidlaxer/anaconda/lib/python2.7/site-packages (from nupic)
Requirement already satisfied (use --upgrade to upgrade): pillow==2.3.0 in /Users/davidlaxer/anaconda/lib/python2.7/site-packages (from nupic)
Collecting psutil==1.0.1 (from nupic)
  Using cached psutil-1.0.1.tar.gz
Collecting pycapnp==0.5.5 (from nupic)
  Using cached pycapnp-0.5.5.tar.gz
Collecting pytest==2.4.2 (from nupic)
  Using cached pytest-2.4.2.tar.gz
Collecting pytest-cov==1.6 (from nupic)
  Using cached pytest-cov-1.6.tar.gz
Collecting pytest-xdist==1.8 (from nupic)
  Using cached pytest-xdist-1.8.zip
Collecting python-dateutil==2.1 (from nupic)
  Using cached python-dateutil-2.1.tar.gz
Collecting PyYAML==3.10 (from nupic)
  Using cached PyYAML-3.10.tar.gz
Collecting unittest2==0.5.1 (from nupic)
  Using cached unittest2-0.5.1.tar.gz
Collecting validictory==0.9.1 (from nupic)
  Using cached validictory-0.9.1.tar.gz
Collecting PyMySQL==0.6.2 (from nupic)
  Using cached PyMySQL-0.6.2-py2.py3-none-any.whl
Collecting DBUtils==1.1 (from nupic)
  Using cached DBUtils-1.1.tar.gz
Requirement already satisfied (use --upgrade to upgrade): numpy>=1.7.1 in /Users/davidlaxer/anaconda/lib/python2.7/site-packages (from nupic)
Collecting tweepy==2.1 (from nupic)
  Using cached tweepy-2.1.tar.gz
Collecting pyproj==1.9.3 (from nupic)
  Using cached pyproj-1.9.3.tar.gz
Requirement already satisfied (use --upgrade to upgrade): prettytable==0.7.2 in /Users/davidlaxer/anaconda/lib/python2.7/site-packages/prettytable-0.7.2-py2.7.egg (from nupic)
Requirement already satisfied (use --upgrade to upgrade): py>=1.4.17 in /Users/davidlaxer/anaconda/lib/python2.7/site-packages (from pytest==2.4.2->nupic)
Collecting cov-core>=1.6 (from pytest-cov==1.6->nupic)
  Using cached cov-core-1.15.0.tar.gz
Collecting execnet>=1.0.8 (from pytest-xdist==1.8->nupic)
  Using cached execnet-1.3.0-py2.py3-none-any.whl
Requirement already satisfied (use --upgrade to upgrade): six in /Users/davidlaxer/anaconda/lib/python2.7/site-packages (from python-dateutil==2.1->nupic)
Installing collected packages: psutil, pycapnp, pytest, cov-core, pytest-cov, execnet, pytest-xdist, python-dateutil, PyYAML, unittest2, validictory, PyMySQL, DBUtils, tweepy, pyproj
  Found existing installation: psutil 2.2.1
    DEPRECATION: Uninstalling a distutils installed project (psutil) has been deprecated and will be removed in a future version. This is due to the fact that uninstalling a distutils project will only partially uninstall the project.
    Uninstalling psutil-2.2.1:
      Successfully uninstalled psutil-2.2.1
  Running setup.py install for psutil
    Complete output from command /Users/davidlaxer/anaconda/bin/python -c "import setuptools, tokenize;__file__='/private/var/folders/nj/nphdkhyj6s1dttb0pd9zb2wc0000gn/T/pip-build-JicAjT/psutil/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /var/folders/nj/nphdkhyj6s1dttb0pd9zb2wc0000gn/T/pip-UrwR1N-record/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build/lib.macosx-10.5-x86_64-2.7
    creating build/lib.macosx-10.5-x86_64-2.7/psutil
    copying psutil/__init__.py -> build/lib.macosx-10.5-x86_64-2.7/psutil
    copying psutil/_common.py -> build/lib.macosx-10.5-x86_64-2.7/psutil
    copying psutil/_compat.py -> build/lib.macosx-10.5-x86_64-2.7/psutil
    copying psutil/_error.py -> build/lib.macosx-10.5-x86_64-2.7/psutil
    copying psutil/_psbsd.py -> build/lib.macosx-10.5-x86_64-2.7/psutil
    copying psutil/_pslinux.py -> build/lib.macosx-10.5-x86_64-2.7/psutil
    copying psutil/_psmswindows.py -> build/lib.macosx-10.5-x86_64-2.7/psutil
    copying psutil/_psosx.py -> build/lib.macosx-10.5-x86_64-2.7/psutil
    copying psutil/_psposix.py -> build/lib.macosx-10.5-x86_64-2.7/psutil
    copying psutil/_pssunos.py -> build/lib.macosx-10.5-x86_64-2.7/psutil
    copying psutil/error.py -> build/lib.macosx-10.5-x86_64-2.7/psutil
    running build_ext
    building '_psutil_osx' extension
    creating build/temp.macosx-10.5-x86_64-2.7
    creating build/temp.macosx-10.5-x86_64-2.7/psutil
    creating build/temp.macosx-10.5-x86_64-2.7/psutil/arch
    creating build/temp.macosx-10.5-x86_64-2.7/psutil/arch/osx
    gcc -fno-strict-aliasing -I/Users/davidlaxer/anaconda/include -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -arch x86_64 -I/Users/davidlaxer/anaconda/include/python2.7 -c psutil/_psutil_osx.c -o build/temp.macosx-10.5-x86_64-2.7/psutil/_psutil_osx.o
    In file included from /usr/include/dispatch/dispatch.h:51:0,
                     from /System/Library/Frameworks/CoreFoundation.framework/Headers/CFStream.h:15,
                     from /System/Library/Frameworks/CoreFoundation.framework/Headers/CFPropertyList.h:13,
                     from /System/Library/Frameworks/CoreFoundation.framework/Headers/CoreFoundation.h:55,
                     from psutil/_psutil_osx.c:36:
    /usr/include/dispatch/object.h:143:15: error: expected identifier or '(' before '^' token
     typedef void (^dispatch_block_t)(void);
                   ^
    /usr/include/dispatch/object.h:362:3: error: unknown type name 'dispatch_block_t'
       dispatch_block_t notification_block);
       ^
    error: command 'gcc' failed with exit status 1
    
    ----------------------------------------
  Rolling back uninstall of psutil
Command "/Users/davidlaxer/anaconda/bin/python -c "import setuptools, tokenize;__file__='/private/var/folders/nj/nphdkhyj6s1dttb0pd9zb2wc0000gn/T/pip-build-JicAjT/psutil/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /var/folders/nj/nphdkhyj6s1dttb0pd9zb2wc0000gn/T/pip-UrwR1N-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/var/folders/nj/nphdkhyj6s1dttb0pd9zb2wc0000gn/T/pip-build-JicAjT/psutil

**Comment by dbl001** [comment]
Investigating this ...

https://github.com/hashdist/hashstack/issues/742

**Comment by dbl001** [comment]
The fix:

//Change
typedef void (^dispatch_block_t)(void);
//To
typedef void* dispatch_block_t;

http://hamelot.co.uk/programming/osx-gcc-dispatch_block_t-has-not-been-declared-invalid-typedef/

**Comment by rhyolight** [comment]
Thank you!

---------
Matt Taylor
OS Community Flag-Bearer
Numenta
