### ISSUE TITLE
iPython Notebook Server running in nupic Virtual Box

### ISSUE THREAD

**Issue by dbl001** [numenta/nupic#2301]
I ran into issues building and just installing nupic on OS X 10.10.3 but was able to install the run the
Ubuntu virtual box.  The nupic tests ran successfully in the virtual box.
I'd like to run the iPython Notebook server from within the nupic virtual box and run my iPython notebooks
from OS X 10.10.3.  

I was able to install and run the iPython notebook server in the nupic virtual box but I can't connect with it
from my browser on OS X 10.10.3.  I was able to connect to the notebook server in a different virtual box (e.g. a  Spark virtual box) so I know that it work and I'm missing some configuration steps.
The Spark virtual box has port forwarding enabled in the 'Vagrantfile'. I tried adding similar port forwarding in the nupic virtual box but it didn't solve the problem.  

Vagrantfile:
ipythonPort = 8001                 # Ipython port to forward (also set in IPython notebook config)
...
    master.vm.network :forwarded_port, host: ipythonPort, guest: ipythonPort, auto_correct: true   # IPython port (set in notebook config)

Enabling debug log messages in the iPython notebook server isn't showing my connection attempts.

**Comment by rhyolight** [comment]
So your iPython notebook is running on the VM, right? And you're trying to get to it from OS X (the host OS). Don't you need to do some kind of port-forwarding? @unixorn maybe you know?

**Comment by dbl001** [comment]
The iPython notebook server is running on the virtual machine.  I have a Spark virtual machine (32 bit) where this works (e.g. - iPython notebook server running in VM, access works through OS X 10.10.3, running notebooks in the VM / Spark works.  The Spark VM does not use Docker.
When I tried adding the port-forwarding from the Spark VM into the nupic Vagrant file (with docker code),
it still didn't work.

**Comment by rhyolight** [comment]
I don't know how to fix this, and honestly this is out of scope for a NuPIC
bug report, as it is more of a general VM / networking question.

---------
Matt Taylor
OS Community Flag-Bearer
Numenta

**Comment by dbl001** [comment]
Ok.  Thanks!
