### ISSUE TITLE
TM: predictedSegmentDecrement should be 0 by default or investigated

### ISSUE THREAD

**Issue by chetan51** [numenta/nupic#2307]
Before we set a positive value to `predictedSegmentDecrement` in temporal memory, we should verify that it doesn't reduce performance on existing models. For now, we can set it to 0, or we can investigate the implications.

**Comment by chetan51** [comment]
@ywcui1990

**Comment by subutai** [comment]
A value of 0 is backward compatible. A non-zero value is not backward compatible and we should investigate impact with hogtym and other datasets.

**Comment by ywcui1990** [comment]
I will change it to 0 for now before we investigate its impact.
