### ISSUE TITLE
Create OPF regression test

### ISSUE THREAD

**Issue by scottpurdy** [numenta/nupic#2322]
We should have a test to ensure that any changes to OPF results are intentional. This can be a simple test that runs hotgym and enforces that the error metric matches. If it fails then the expected result must be explicitly updated to match the new result.

**Comment by rhyolight** [comment]
@scottpurdy There is a similar test at https://github.com/numenta/nupic.regression/blob/master/tests/anomaly/one_gym/hotgym_anomaly_test.py can you use it?

**Comment by scottpurdy** [comment]
@rhyolight - No, that test will only catch a very narrow set of problems that cause anomaly scores to never drop to reasonable levels. We need some blocking test that prevents people from making a change that affects prediction/anomaly results at all unless they explicitly intend to. I often ask people that submit PRs to run hotgym and validate the results don't change but I don't want to have to trust them ;)

**Comment by breznak** [comment]
> ... and validate the results don't change but I don't want to have to
trust them ;)

:+1: although the other issue - with results varying from machine to
machine- will become a trouble. At least we'll resolve it faster :P

**Comment by scottpurdy** [comment]
Actually this should address the deviation from machine to machine if we assert that the prediction results are identical. That is actually how we found out that the hotgym metric results locally on OS X are not the same as on Travis right now. @tomsilver is in the process of debugging this.
