### ISSUE TITLE
Docker builds failing since July 22 2015

### ISSUE THREAD

**Issue by rhyolight** [numenta/nupic#2350]
https://registry.hub.docker.com/u/numenta/nupic/builds_history/15031/

/CC @allanino @oxtopus

**Comment by rhyolight** [comment]
This is caused by #2355.

**Comment by rcrowder** [comment]
See https://github.com/numenta/nupic/issues/2355#issuecomment-125545140

**Comment by rhyolight** [comment]
Watching https://registry.hub.docker.com/u/numenta/nupic/build_id/3974/code/bqbfs265bzzwwhzwaptca9y/ for results...

**Comment by rhyolight** [comment]
@oxtopus @allanino Can either of you tell me why [this is showing a "Build Error"](https://registry.hub.docker.com/u/numenta/nupic/build_id/3974/code/bqbfs265bzzwwhzwaptca9y/) cause I can't see any errors in the output.

**Comment by rhyolight** [comment]
Oh: 

    Error pushing to registry: Server error: 502 trying head request for numenta/nupic - sha256:b5fee3b077924662569a2196169132eb6d67aae161b79e94c7faad1bb7e33dfb

**Comment by rhyolight** [comment]
Maybe I'll try another build...

**Comment by rhyolight** [comment]
We have docker builds again! Looks like the previous error was a fluke. Restarting the job worked.
