### ISSUE TITLE
Missing numpy array object header (C++)

### ISSUE THREAD

**Issue by rhyolight** [numenta/nupic#2355]
This is causing problems for Ubuntu, but strangely not on Travis-CI. It is, however, causing docker failures as shown [here](https://registry.hub.docker.com/u/numenta/nupic/build_id/3974/code/b2kw7xyldssjs4xfnvtxbfk/). I can replicate this error on the Ubuntu box I normally build NuPIC with the exact same error when running `python setup.py install --user`.

```
gcc -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -DNUPIC2 -DNTA_OS_LINUX -DNTA_ARCH_64 -DNTA_PYTHON_SUPPORT=2.7 -DNTA_INTERNAL -DNTA_ASSERTIONS_ON -DNTA_ASM -DHAVE_CONFIG_H -DBOOST_NO_WREGEX -I/usr/local/src/nupic/external/linux64/include -I/usr/local/src/nupic/external/common/include -I/usr/local/src/nupic/extensions -I/usr/local/src/nupic -I/usr/local/src/nupic/extensions/core/build/release/include -I/usr/include/python2.7 -I/usr/include/python2.7 -c extensions/core/build/release/include/nupic/py_support/NumpyVector.cpp -o build/temp.linux-x86_64-2.7/extensions/core/build/release/include/nupic/py_support/NumpyVector.o -std=c++11 -m64 -fPIC -fvisibility=hidden -Wall -Wextra -Wreturn-type -Wunused -Wno-unused-parameter -mtune=generic -O2
[91mcc1plus: warning: command line option '-Wstrict-prototypes' is valid for C/ObjC but not for C++ [enabled by default]
[0m
[91mextensions/core/build/release/include/nupic/py_support/NumpyVector.cpp:32:31: fatal error: numpy/arrayobject.h: No such file or directory
 #include <numpy/arrayobject.h>
                               ^
compilation terminated.
```

**Comment by rhyolight** [comment]
This seems to have started happening on July 22, but I'm trying to identify the exact commit. My guess is that it was a `nupic.core` change that caused the problem.

**Comment by breznak** [comment]
hmm.. I can't (fortunately) replicate on my box (U 14.04), using `python setup.py build & develop` from locally built `nupic.core`. Could be a packaging problem?

**Comment by rcrowder** [comment]
I was broken by this after updating my NuPIC TM bindings branch last week. Recent changes to move Py CPP stuff into the core affected all this (PyArray.ccp, etc.).  It should be ok, when NuPIC has caught up with latest core SHA. 
We now seem to have a CPP Core library reliant on Python and NumPy installation? Although it did  confirm the hard-limit of 40 minutes per build on AppVeyor (NumPy install from source).

**Comment by rhyolight** [comment]
This is also failing internal pipelines, but with a different error (@jcasner):

```
ImportError: numpy.core.multiarray failed to import
ERR:  Matching Python module for TestNode not found. [/opt/numenta/jenkins/workspace/nupic-product-pipeline/build-255/nupic.core/src/nupic/engine/RegionImplFactory.cpp line 392]
Exception: Matching Python module for TestNode not found. at: /opt/numenta/jenkins/workspace/nupic-product-pipeline/build-255/nupic.core/src/nupic/engine/RegionImplFactory.cpp:392
ERROR -build - 2015-07-22 16:45:09,975 - NuPIC Tests have failed.
Traceback (most recent call last):
  File "/opt/numenta/products/infrastructure/infrastructure/utilities/nupic/build_commands.py", line 309, in runTests
    runWithOutput("bin/py_region_test", env, logger)
  File "/opt/numenta/products/infrastructure/infrastructure/utilities/cli.py", line 109, in runWithOutput
    raise CommandFailedError("Failed to execute command: %s" % command)
CommandFailedError: Failed to execute command: ['bin/py_region_test']
```

![screen shot 2015-07-28 at 10 17 57 am](https://cloud.githubusercontent.com/assets/15566/8938219/37d16d7e-3512-11e5-84ac-0d9a29a90f5b.png)

**Comment by rhyolight** [comment]
@rcorder said:

> It should be ok, when NuPIC has caught up with latest core SHA.

Everything is caught up as of yesterday, but no luck with a passing build.

**Comment by rhyolight** [comment]
My Ubuntu environment is old (needs gcc 4.8), so I'm updating to Ubuntu 14.04 right now. Once complete, I should have an environment where I can identify the breaking change.

**Comment by rhyolight** [comment]
This is happening because `numpy` needs to be explicitly installed. You can see that Travis-CI is not failing because of this change: 

https://github.com/numenta/nupic/commit/c5e1259d5c4dc4b955f71700694ec37255e90646#diff-fdac4aa350975855602432f52f20f6cdR44

So I'm updating the Docker build to install Numpy, and @jcasner is going to update the Grok builds.
