### ISSUE TITLE
Performance regression for single-order sequence

### ISSUE THREAD

**Issue by rhyolight** [numenta/nupic#2361]
NuPIC used to be 100% correct at predicting cellular automata within a 500-element window after 581 rows of data. Now it is only 98.8% correct. 

See failure at: https://travis-ci.org/numenta/nupic.regression/builds/73279926

**Comment by rhyolight** [comment]
I will try to find out which SHA this started, then I'll probably need to defer to @scottpurdy for analysis.

**Comment by scottpurdy** [comment]
I think we can update the test since there have been a couple known changes since this test was last run. Here is one case that caused changes: #1972

**Comment by rhyolight** [comment]
I've updated it.
