### ISSUE TITLE
Remove tweepy dependency

### ISSUE THREAD

**Issue by oxtopus** [numenta/nupic#2381]
tweepy doesn't appear to be used anywhere in nupic, but has entries in `DEPENDENCIES.md` and `requirements.txt`:

```
$ git grep tweepy
DEPENDENCIES.md:- tweepy ([MIT License](https://github.com/tweepy/tweepy/blob/master/LICENSE))
external/common/requirements.txt:tweepy==2.1
```

**Comment by rhyolight** [comment]
![1201133266390](https://cloud.githubusercontent.com/assets/15566/9140807/a4937c8a-3ce8-11e5-9450-33e8bebefc24.jpg)
