### ISSUE TITLE
temporal_memory.py learnOnSegments method doc incomplete

### ISSUE THREAD

**Issue by cogmission** [numenta/nupic#2387]
Trivial but should be complete for peeps trying to learn.

    @param prevMatchingSegments         (set)         Indices of segments with

[Line no. 367](https://github.com/numenta/nupic/blob/master/nupic/research/temporal_memory.py#L367) - Sentence ends there. Me thinks the author got distracted?

**Comment by go-bears** [comment]
Hello, sorry for the referencing the wrong commit. I"m a newbie learning how to contribute properly. For this bug  Is the fix you're looking for
from "Indices of segments with   " to "Indices of segments with active synapses" ?
Thank you for your time and guidance in advance.

**Comment by arhik** [comment]
This is not a valid issue anymore. The variable naming convention changed I guess. Code sections changed a lot and not a single variable named 'prevMatchingSegments' exists now following the convention as raised here. The link in the description is redirecting to 404 error page too. I strongly feel this should be closed.

**Comment by rhyolight** [comment]
Thanks @arhik.
