### ISSUE TITLE
Update all GPL codebases to AGPL

### ISSUE THREAD

**Issue by rhyolight** [numenta/nupic#2399]
cc @jcasner

Here are all the PRs that need to be merged at the same time.

* * *

- [x] [numenta.org](https://github.com/numenta/numenta.org/pull/225) ✔︎
- [x] [numenta.com](https://github.com/GrokSolutions/numenta.com/pull/248) (private) ✔︎
- [x] [numenta-apps](https://github.com/numenta/numenta-apps/pull/196) ✔︎
- [x] [nupic](https://github.com/numenta/nupic/pull/2402) ✔︎
- [x] [nupic.core](https://github.com/numenta/nupic.core/pull/535) ✔︎
- [x] [nupic.research](https://github.com/numenta/nupic.research/pull/258) ✔︎
- [x] [nupic.vision](https://github.com/numenta/nupic.vision/pull/40) ✔︎
- [x] [htm.java](https://github.com/numenta/htm.java/pull/271) ✔︎
- [x] [nupic.fluent](https://github.com/numenta/nupic.fluent/pull/136) ✔︎
- [x] [nupic.fluent.server](https://github.com/numenta/nupic.fluent.server/pull/15) ✔︎
- [x] [NAB](https://github.com/numenta/NAB/pull/170) ✔︎
- [x] [nupic.rogue](https://github.com/numenta/nupic.rogue/pull/5) ✔︎
- [x] [nupic.cloudbrain](https://github.com/numenta/nupic.cloudbrain/pull/1) ✔︎
- [x] [nupic.cerebro2](https://github.com/numenta/nupic.cerebro2/pull/74) ✔︎
- [x] [nupic.cerebro2.server](https://github.com/rhyolight/nupic.cerebro2.server/pull/1) ✔︎
- [x] [nupic.critic](https://github.com/numenta/nupic.critic/pull/6) ✔︎
- [x] [nupic.geospatial](https://github.com/numenta/nupic.geospatial/pull/48) ✔︎
- [x] [nupic.nlp-examples](https://github.com/numenta/nupic.nlp-examples/pull/11) ✔︎
- [x] [hypersearch](https://github.com/numenta/hypersearch/pull/3) ✔︎

> "✔︎" means I've double-checked them and added all copyright header changes.

**Comment by rhyolight** [comment]
@jcasner As @oxtopus [noted](https://github.com/numenta/numenta-apps/pull/196#issuecomment-130470605), I'm going to have to update all these PRs with changes to the copyright headers. I don't have time to do this before I take PTO, so I'll do it on Monday.

**Comment by jcasner** [comment]
@scottpurdy can you run your magic header update script to insert `Affero` into the header text in all these repos?  Might be the most efficient approach...

**Comment by rhyolight** [comment]
@jcasner @scottpurdy No worries, I got this. magic headers scripts are a dime a dozen. ;)

**Comment by rhyolight** [comment]
@jcasner @oxtopus @scottpurdy I believe that all the PRs above now contain the required copyright header changes, so we are set to pull the trigger.

**Comment by rhyolight** [comment]
@jcasner @scottpurdy I am going to merge all the PRs that update the licenses along with the code, saving the websites (numenta.org / .com) for last. Once the `nupic.core` build produces binaries and the autmated PR appears and runs to sync projects, I'll merge it as well. Then I will cut a release. 

There are going to be a lot of builds running today. Prepare for a long build queue.

**Comment by rhyolight** [comment]
All PRs are merged except for the websites. Now I wait for builds to run.
