### ISSUE TITLE
Master build deployment failure, missing "nupic.bindings"

### ISSUE THREAD

**Issue by rhyolight** [numenta/nupic#2413]
See: https://travis-ci.org/numenta/nupic/jobs/75138342#L6712

```
Downloading/unpacking nupic.bindings==0.1.0 (from nupic==0.2.7.dev0)
  Could not find any downloads that satisfy the requirement nupic.bindings==0.1.0 (from nupic==0.2.7.dev0)
Cleaning up...
No distributions at all found for nupic.bindings==0.1.0 (from nupic==0.2.7.dev0)
Storing complete log in /home/travis/.pip/pip.log
The command ". ./ci/travis/before_deploy.sh" failed and exited with 1 during .
```

CC @akhilaananthram @scottpurdy

**Comment by breznak** [comment]
@rhyolight maybe the tarball is not published yet? (or it's another error :/ )
I confirm these: 

* `CC=gcc-4.8 CXX=g++-4.8 python setup.py install` : 
```
setuptools version: 2.2
numpy version: 1.9.2
Attempting to fetch nupic.core binaries...
Downloading from
        https://s3-us-west-2.amazonaws.com/artifacts.numenta.org/numenta/nupic.core/nupic_core-4e477ac3599e9e79200a9c760686569d30491b63-linux64.tar.gz
to ...

Exception: Failed to download nupic.core tarball from https://s3-us-west-2.amazonaws.com/artifacts.numenta.org/numenta/nupic.core/nupic_core-4e477ac3599e9e79200a9c760686569d30491b63-linux64.tar.gz}! Ensure you have an internet connection and that the remote tarball exists.
```
--and it does not exist. (ok, this seems to be the problem with the deployment) 

* `CC=gcc-4.8 CXX=g++-4.8 python setup.py --nupic-core-dir=/home/mmm/devel/nupic/nupic.core/build/release/ build` 
runs OK

* `CC=gcc-4.8 CXX=g++-4.8 python setup.py --nupic-core-dir=/home/mmm/devel/nupic/nupic.core/build/release/ develop`

fails with your err above.

**Comment by akhilaananthram** [comment]
The tarball was published for that run.  For some reason even though the egg file for nupic.bindings  is in the tarball and the path is added to the requirements, it still says no distribution is found.

**Comment by breznak** [comment]
> The tarball was published for that run. For some reason even though the
egg file for nupic.bindings is in the tarball

Hi,
what about the local build of nupic.core? (when I don't want to use the
online binary)

**Comment by breznak** [comment]
is the tarball really published?
`wget
https://s3-us-west-2.amazonaws.com/artifacts.numenta.org/numenta/nupic.core/nupic_core-4e477ac3599e9e79200a9c760686569d30491b63-linux64.tar.gz`
fails here

**Comment by rhyolight** [comment]
There was a problem with the last `nupic.core` deployment in this build. See full logs at https://s3.amazonaws.com/archive.travis-ci.org/jobs/75138729/log.txt:

```
?25hInstalling collected packages: pip
  Found existing installation: pip 6.0.8
    Uninstalling pip-6.0.8:
[31m      Exception:
      Traceback (most recent call last):
        File "/usr/local/lib/python2.7/dist-packages/pip-6.0.8-py2.7.egg/pip/basecommand.py", line 232, in main
          status = self.run(options, args)
        File "/usr/local/lib/python2.7/dist-packages/pip-6.0.8-py2.7.egg/pip/commands/install.py", line 347, in run
          root=options.root_path,
        File "/usr/local/lib/python2.7/dist-packages/pip-6.0.8-py2.7.egg/pip/req/req_set.py", line 543, in install
          requirement.uninstall(auto_confirm=True)
        File "/usr/local/lib/python2.7/dist-packages/pip-6.0.8-py2.7.egg/pip/req/req_install.py", line 667, in uninstall
          paths_to_remove.remove(auto_confirm)
        File "/usr/local/lib/python2.7/dist-packages/pip-6.0.8-py2.7.egg/pip/req/req_uninstall.py", line 126, in remove
          renames(path, new_path)
        File "/usr/local/lib/python2.7/dist-packages/pip-6.0.8-py2.7.egg/pip/utils/__init__.py", line 316, in renames
          shutil.move(old, new)
        File "/usr/lib/python2.7/shutil.py", line 297, in move
          rmtree(src)
        File "/usr/lib/python2.7/shutil.py", line 245, in rmtree
          rmtree(fullname, ignore_errors, onerror)
        File "/usr/lib/python2.7/shutil.py", line 250, in rmtree
          onerror(os.remove, fullname, sys.exc_info())
        File "/usr/lib/python2.7/shutil.py", line 248, in rmtree
          os.remove(fullname)
      OSError: [Errno 13] Permission denied: '/usr/local/lib/python2.7/dist-packages/pip-6.0.8-py2.7.egg/EGG-INFO/PKG-INFO'
```

This needs its own ticket in nupic.core....

**Comment by akhilaananthram** [comment]
I think this is the tarball it downloads:
https://s3-us-west-2.amazonaws.com/artifacts.numenta.org/numenta/nupic.core/nupic_core-82b9a97937b17d9a2c32e9d89bca6e1fe1eea923-linux64.tar.gz

When you want to use a local build of nupic.core, you run the setup.py in nupic.core and then pass the release directory made by cmake to nupic.  Its similar to before except you run a setup in nupic.core as well.

**Comment by breznak** [comment]
> I think this is the tarball it downloads:

for some reason the `python setup.py install` tries to download
`4e477ac3599e9e79200a9c760686569d30491b63-linux64.tar.gz` and not the file
you mention (?)

**Comment by akhilaananthram** [comment]
Where is that? I didn't see it.

**Comment by tomoprime** [comment]
Guys don't forget to avoid hardcoding paths:
# setup.py about line:282
 if getPlatformInfo()[0] == "darwin":
      nupicCoreLocalDirToUnpack = "/Users/travis/build/numenta/nupic.core/bindings/py/dist"
    elif getPlatformInfo()[0] == "linux":
      nupicCoreLocalDirToUnpack = "/home/travis/build/numenta/nupic.core/bindings/py/dist"

**Comment by rhyolight** [comment]
@tomoprime Good catch there. @akhilaananthram You should be able to sub `TRAVIS_BUILD_DIR` for the first part of those paths.

**Comment by akhilaananthram** [comment]
Isn't that only be set for builds on travis? This path is the folder structure inside of the zip that is uploaded to s3 by travis.  setup.py should be able to download that even when not on travis.  We could change that path in nupic.core though so it isn't so long and platform dependent.

**Comment by rhyolight** [comment]
Aha, that makes sense, @akhilaananthram. Carry on, no change necessary.

**Comment by tomoprime** [comment]
yeah it looks like it's empty anyway...

Toms-MacBook-Pro:~ Tom$ ls nupic/extensions/core/build/release/Users/travis/build/numenta/nupic.core/bindings/py
Toms-MacBook-Pro:~ Tom$

**Comment by akhilaananthram** [comment]
yup. its a bunch of empty directories.  We can make that change to nupic.core at some point

**Comment by tomoprime** [comment]
Ok... I ran the unit tests I get an error looks related to nupic.bindings.proto...
Toms-MacBook-Pro:nupic Tom$ $NUPIC/scripts/run_nupic_tests -u --coverage
===================================================== test session starts ======================================================
platform darwin -- Python 2.7.10 -- pytest-2.4.2 -- /usr/bin/python
plugins: xdist, cov
collecting 665 items / 1 errors / 2 skipped
============================================================ ERRORS ============================================================
____________________________ ERROR collecting tests/unit/nupic/research/spatial_pooler_unit_test.py ____________________________
tests/unit/nupic/research/spatial_pooler_unit_test.py:41: in <module>
    from nupic.bindings.proto import SpatialPoolerProto_capnp
capnp/lib/capnp.pyx:3773: in capnp.lib.capnp._Loader.load_module (capnp/lib/capnp.cpp:71749)
    ???
capnp/lib/capnp.pyx:3752: in capnp.lib.capnp.load (capnp/lib/capnp.cpp:71239)
    ???
capnp/lib/capnp.pyx:3126: in capnp.lib.capnp.SchemaParser.load (capnp/lib/capnp.cpp:63334)
    ???
E   KjException: /Users/Tom/nupic/nupic/bindings/proto/RandomProto.capnp:0: failed: Duplicate ID @0x88eaee6db8e1f67c.
E   stack: 0x10af7fb97 0x10aed8500 0x10aed8717 0x10aec9ae9 0x10aec980b 0x10aece2d7 0x10aed0541 0x10aecdf11 0x10aea4067 0x10aea3dcc 0x10aeb4330 0x10aec91c7 0x10aecd8bc 0x10aecd373 0x10aecd623 0x10aea3a9e

**Comment by tomoprime** [comment]
Note a couple of days ago, Apple pushed out a Mac OS X 10.5.5 update which also upgrades Python to 2.7.10...
