### ISSUE TITLE
Resolve Swarming ExtendedLogger Dependency On NuPIC

### ISSUE THREAD

**Issue by mihail911** [numenta/nupic#2426]
Move ExtendedLogger module from outside swarming into swarming, since the rest of NuPIC has no dependency on ExtendedLogger.

**Comment by rhyolight** [comment]
@mihail911 Can you come up with a better name for this issue? Ideally, it should be something communicating the main idea of the work needing to be done. Not just a subject, but an action that needs to be taken, or a bug that needs to be fixed. Thank you.

**Comment by mihail911** [comment]
@rhyolight For sure

**Comment by rhyolight** [comment]
:+1: Thanks!
