### ISSUE TITLE
Change term `predictedColumns` to `predictedActiveColumns` in the TemporalMemory

### ISSUE THREAD

**Issue by chetan51** [numenta/nupic#2452]
If we change `predictedColumns` to `predictedActiveColumns` in the TemporalMemory implementation, everything would become fully consistent:

predictive = something that has become depolarized in the current timestep
predicted = something that became depolarized in the last timestep
(therefore) prevPredictive == predicted

**Comment by rcrowder** [comment]
@chetan51 Is it worth taking this across to the C++ now? Or wait for other changes first?

**Comment by chetan51** [comment]
@rcrowder It can be taken across now, it's a small documentation-related change anyway.

**Comment by rcrowder** [comment]
@chetan51 A minor change for anyone. I've been meaning to see if anything other than orphan decay needs syncing.
