### ISSUE TITLE
HTTP 404 when downloading nupic

### ISSUE THREAD

**Issue by DefinitlyEvil** [numenta/nupic#2461]
It returned 404 when I running: 
`pip install https://s3-us-west-2.amazonaws.com/artifacts.numenta.org/numenta/nupic/releases/nupic-0.2.10-cp27-none-linux_x86_64.whl`

**Comment by rhyolight** [comment]
Try this:

    pip install https://s3-us-west-2.amazonaws.com/artifacts.numenta.org/numenta/nupic/releases/nupic-0.2.10-py2-none-any.whl

**Comment by DefinitlyEvil** [comment]
Okay. ;)
