### ISSUE TITLE
fail to install the setup.py

### ISSUE THREAD

**Issue by wishingwei** [numenta/nupic#2470]
fail to install the setup.py   by    ''python setup.py install''

Here is the wrong message,
SystemError: Cannot compile 'Python.h'. Perhaps you need to install python-dev|python-devel.

But I do successfully install all the dependencies mentioned in the wiki,

**Comment by wishingwei** [comment]
python
Python 2.7.6 (default, Jun 22 2015, 17:58:13) 
[GCC 4.8.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.

**Comment by rhyolight** [comment]
I have some questions.

1. What flavor / version of Linux are you running?
1. How do you know that python development headers are installed properly? How did you install `python-dev`/`python-devel`?
1. What version of NuPIC are you running? (see the `VERSION` file)

**Comment by wishingwei** [comment]
1. Ubuntu 14.04 （64-bit）
2. Just run the  "sudo apt-get install python-dev" , now it tells that the  python-dev is the latest version;   
    for the Ubuntu  is  a chinese version, and I will not paste the log here.
3. Nupic version: 0.2.12.dev0

**Comment by wishingwei** [comment]
1.Ubuntu 14.04 （64-bit）
2.Just run the "sudo apt-get install python-dev" , now it tells that the python-dev is the latest version;
 for the Ubuntu is a chinese version, and I will not paste the log here.
3.Nupic version: 0.2.12.dev0

**Comment by wishingwei** [comment]
1.Ubuntu 14.04.3 LTS \n \l
 2.Just run the "sudo apt-get install python-dev" , now it tells that the python-dev is the latest version;
 for the Ubuntu is a chinese version, and I will not paste the log here.
 3.Nupic version: 0.2.12.dev0

**Comment by wishingwei** [comment]
I just made another try, and finally succeed in installation!  
Thanks for help ~@rhyolight

**Comment by rhyolight** [comment]
Great! Thanks for the bug report.

**Comment by Neuroforge** [comment]
Hi, 
I am also recieving this error.

1.Ubuntu 14.04.3 LTS \n \l
2.Just run the "sudo apt-get install python-dev" , now it tells that the python-dev is the latest version;
for the Ubuntu is a chinese version, and I will not paste the log here.
3.Nupic master branch.

Any tips on this?

**Comment by wishingwei** [comment]
@Neuroforge sorry, I just made another try and succeeded, but do not known where went wrong. Anyway, it is a long time for me to remember the details at that time. Really sorry about that.
