### ISSUE TITLE
Test H10 in TM integration test is invalid

### ISSUE THREAD

**Issue by cogmission** [numenta/nupic#2478]
There is an error in the loop on the second trial which caused the output to have the desired stats. The test fails when the loop is corrected. 

Secondly, the setting of "predictedSegmentDecrement" to 0.004 has no effect when the loop is corrected - indicating that there may need to be some algorithm enhancement in order to make the parameter have the desired effect. (Other than lowering the permanence of the Synapse resulting in eventual removal of the Synapse - which works).

**Line 532: extensive_temporal_memory_test.py**
``` Python

for _ in xrange(10):
      self.feedTM(sequenceNoisy[i])
```

**Should be:**

``` Python
for i in xrange(10):
      self.feedTM(sequenceNoisy[i])
```

Where the underscore ("_") should be an "i" so that all the sequences are actually entered.

This is the test description:

> Orphan Decay mechanism reduce predicted inactive cells (extra predictions).
    Test feeds in noisy sequences (X = 0.05) to TM with and without orphan decay.
    TM with orphan decay should has many fewer predicted inactive columns.
    Parameters the same as B11, and sequences like H9.

When the loop is "corrected" you will see by setting the "predictedSegmentDecrement" variable to "0.000" that it has no effect on the "predictedInactiveColumns" mean or sum. I had to set it to "0.999" in order for their to be noticeable reduction (by only half) - which I think may need some care and loving in order to have a more pronounced effect.

This took me **3 Days** of intense debugging before I began to suspect the problem wasn't with the code I was porting to. It is such a "subtle" change that I didn't even notice it!

**Comment by rhyolight** [comment]
@chetan51 Can you confirm? Should be a quick fix.

**Comment by cogmission** [comment]
Actually I spent three days trying to get that setting to lower the predicted inactive columns - it doesn't work! I had to set it to >0.5 to see significant changes in both the Python and Java. This is a value that ranges from 0.0 - 1.0 and where a setting of 0.004 is supposed to make a difference (according to the test and Subutai's explanation)

It doesn't work... It may result in the eventual culling of Synapses at some point but it doesn't have the desired effect of lowering predicted inactive columns.

**Comment by rhyolight** [comment]
Oh, sorry. I thought this fix was as easy as changing `_` to `i`.

**Comment by cogmission** [comment]
That actually makes the test **do** what it was intended to do - which then
also **breaks** the test and exposes the failure of that parameter to have
the desired effect :-(

On Tue, Aug 25, 2015 at 11:53 AM, Matthew Taylor <notifications@github.com>
wrote:

> Oh, sorry. I thought this fix was as easy as changing _ to i.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/numenta/nupic/issues/2478#issuecomment-134668913>.
>



-- 
*With kind regards,*

David Ray
Java Solutions Architect

*Cortical.io <http://cortical.io/>*
Sponsor of:  HTM.java <https://github.com/numenta/htm.java>

d.ray@cortical.io
http://cortical.io

**Comment by chetan51** [comment]
This was @ywcui1990's test, assigning to him.

**Comment by ywcui1990** [comment]
Sorry about the bug. I will take a look at it.

**Comment by cogmission** [comment]
@ywcui1990 No problem, everybody has over sights. I'm mostly concerned about the desired effect of this parameter (predictedSegmentDecrement) not having any linear regulatory effect on the predicted inactive columns count? This is the real problem... Because that's what the test, tests :-)
