### ISSUE TITLE
TM: Synapse Creation on every permanence adjustment

### ISSUE THREAD

**Issue by cogmission** [numenta/nupic#2479]
Not sure about what is going on with Python but I noticed something that could have tremendous memory pressure and performance impact if I'm right about what I'm seeing...?

In connections.py https://github.com/numenta/nupic/blob/master/nupic/research/connections.py#L194

``` Python
def updateSynapsePermanence(self, synapse, permanence):
    """
    Updates the permanence for a synapse.

    @param synapse    (int)   Synapse index
    @param permanence (float) New permanence
    """
    self._validatePermanence(permanence)

    data = self._synapses[synapse]
    newData = SynapseData(data.segment,   <--------------------   HERE
                          data.presynapticCell,
                          permanence)
    self._synapses[synapse] = newData

    # Update indexes
    self._synapsesForPresynapticCell[newData.presynapticCell][synapse] = newData
```

Every time the permanence is adjusted on a Synapse, a new SynapseData object is created?

(the line starting with: "newData = SynapseData(...)" )

When running a simple test in a short lived method such as extensive_temporal_memory_test.py I count something upwards of around 700 thousand Synapses! ...and 60 thousand Segments!

This line is called from "adaptSegment()" (line ~617) - EVERY TIME ADAPT SEGMENT IS CALLED!

I'm not sure how good the garbage collection is in Python (or even if it has garbage collection), but  this data should be indexed in a map and not created upon every adjustment in my opinion?

This needs to be a mutation instead of creation...?

**Comment by oxtopus** [comment]
The current state of the code is slightly different from what you have quoted:

From https://github.com/numenta/nupic/blob/master/nupic/research/connections.py#L194

```python
    # Add data
    synapse = self._nextSynapseIdx
    synapseData = SynapseData(segment, presynapticCell, permanence)
    self._synapses[synapse] = synapseData
```

The `SynapseData()` implementation is relatively simple -- just a container for some attrs and a custom `__eq__()` implementation.  The code as it currently is is readable, and I'm guessing that the overhead of creating a new instance is less than doing a lookup and mutation -- attr access and assignment comes with its own overhead.

It should be a relatively easy theory to validate with profiling if there's much concern, but I suspect it to not be much of a difference if any at all.

cc @chetan51

**Comment by oxtopus** [comment]
re:

> The SynapseData() implementation is relatively simple -- just a container for some attrs and a custom __eq__() implementation

On that note, it might be worth considering use of `namedtuple`, since we're treating it like an immutable object, and it would have the `__eq__` implementation built-in.

Less code to maintain, with the same performance characteristics.

**Comment by cogmission** [comment]
Keep in mind this is called potentially 10 thousand times per TM compute()
cycle ? :-) (Called 700 thousand times in a 100 calls with only 4 cells in
my test)

As you say we should probably profile it.

On Mon, Aug 24, 2015 at 1:29 PM, Austin Marshall <notifications@github.com>
wrote:

> The current state of the code is slightly different from what you have
> quoted:
>
> From
> https://github.com/numenta/nupic/blob/master/nupic/research/connections.py#L194
>
>     # Add data
>     synapse = self._nextSynapseIdx
>     synapseData = SynapseData(segment, presynapticCell, permanence)
>     self._synapses[synapse] = synapseData
>
> The SynapseData() implementation is relatively simple -- just a container
> for some attrs and a custom __eq__() implementation. The code as it
> currently is is readable, and I'm guessing that the overhead of creating a
> new instance is less than doing a lookup and mutation -- attr access and
> assignment comes with its own overhead.
>
> It should be a relatively easy theory to validate with profiling if
> there's much concern, but I suspect it to not be much of a difference if
> any at all.
>
> cc @chetan51 <https://github.com/chetan51>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/numenta/nupic/issues/2479#issuecomment-134328891>.
>



-- 
*With kind regards,*

David Ray
Java Solutions Architect

*Cortical.io <http://cortical.io/>*
Sponsor of:  HTM.java <https://github.com/numenta/htm.java>

d.ray@cortical.io
http://cortical.io

**Comment by cogmission** [comment]
I wish I understood Python more so I could be of some use, but this value
is only accessed by one thread so it really doesn't add anything to make it
immutable. And with 32 cells this is going to get called millions of times
per compute() cycle... Especially with a long running process... Everything
is about updating permanences and checking them in this code.... :-)

On Mon, Aug 24, 2015 at 1:32 PM, Austin Marshall <notifications@github.com>
wrote:

> re:
>
> The SynapseData() implementation is relatively simple -- just a container
> for some attrs and a custom *eq*() implementation
>
> On that note, it might be worth considering use of namedtuple, since
> we're treating it like an immutable object, and it would have the __eq__
> implementation built-in.
>
> Less code to maintain, with the same performance characteristics.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/numenta/nupic/issues/2479#issuecomment-134330003>.
>



-- 
*With kind regards,*

David Ray
Java Solutions Architect

*Cortical.io <http://cortical.io/>*
Sponsor of:  HTM.java <https://github.com/numenta/htm.java>

d.ray@cortical.io
http://cortical.io

**Comment by chetan51** [comment]
I agree with @oxtopus's analysis. We can profile it, but I'm not too concerned.

**Comment by chetan51** [comment]
Oops, accidentally closed.

**Comment by chetan51** [comment]
The next step on this issue is to profile the impact of that function. Anyone can do this.

**Comment by cogmission** [comment]
:+1: for profiling. It's so weird that this isn't a concern. If I did this in Java, it would be a red herring the size of Cincinnati ! :-) Creating a new object 100's of thousands of times per execution as opposed to merely mutating a permanence setting would be ridiculous in Java. I don't understand why allocating the variable so you can mutate is any worse (and potentially so much better performance wise)? I mean the object exists anyway until the next millisecond when it is recreated? :-P

**Comment by oxtopus** [comment]
>  I don't understand why allocating the variable so you can mutate is any worse (and potentially so much better performance wise)?

Consider this example:

```python
class MutableObject(object):
  __slots__ = ("foo", "bar",)
  def __init__(self, foo, bar):
    self.foo = foo
    self.bar = bar

  def mutate(self, foo, bar):
    self.foo = foo
    self.bar = bar
```

`obj = MutableObject("Foo", "Bar")` translates to the following python byte code:

```
  1           0 LOAD_NAME                0 (MutableObject)
              3 LOAD_CONST               0 ('Foo')
              6 LOAD_CONST               1 ('Bar')
              9 CALL_FUNCTION            2
             12 STORE_NAME               1 (obj)
             15 LOAD_CONST               2 (None)
             18 RETURN_VALUE        
None
```

Meanwhile, `obj.mutate("FOO", "BAR")`, which mutates the existing instance, translates to this:

```
  1           0 LOAD_NAME                0 (obj)
              3 LOAD_ATTR                1 (mutate)
              6 LOAD_CONST               0 ('FOO')
              9 LOAD_CONST               1 ('BAR')
             12 CALL_FUNCTION            2
             15 POP_TOP             
             16 LOAD_CONST               2 (None)
             19 RETURN_VALUE        
None
```

Alternatively, if you were to access the attrs directly and assign values externally (e.g. `obj.foo = "FOO"; obj.bar = "BAR"`):

```
  1           0 LOAD_CONST               0 ('FOO')
              3 LOAD_NAME                0 (obj)
              6 STORE_ATTR               1 (foo)
              9 LOAD_CONST               1 ('BAR')
             12 LOAD_NAME                0 (obj)
             15 STORE_ATTR               2 (bar)
             18 LOAD_CONST               2 (None)
             21 RETURN_VALUE        
None
```

Then, compare the bytecode for `MutableObject.__init__()`:

```
Austins-MacBook-Pro:Desktop amarshall$ python mutant2.py 
  6           0 LOAD_FAST                1 (foo)
              3 LOAD_FAST                0 (self)
              6 STORE_ATTR               0 (foo)

  7           9 LOAD_FAST                2 (bar)
             12 LOAD_FAST                0 (self)
             15 STORE_ATTR               1 (bar)
             18 LOAD_CONST               0 (None)
             21 RETURN_VALUE        
None
```

To `obj.mutate()`:

```
 10           0 LOAD_FAST                1 (foo)
              3 LOAD_FAST                0 (self)
              6 STORE_ATTR               0 (foo)

 11           9 LOAD_FAST                2 (bar)
             12 LOAD_FAST                0 (self)
             15 STORE_ATTR               1 (bar)
             18 LOAD_CONST               0 (None)
             21 RETURN_VALUE        
None
```

Notice, there's effectively no difference between the bytecode for the `__init__` and `mutate` functions.

The only _real_ difference, complexity-wise between the two are the extra `LOAD_ATTR` and `POP_TOP` in `obj.mutate("FOO", "BAR")`.  If anything, the mutation should be only very slightly slow, if noticeable at all.  Having to pull the item out of cache would slow things down even more.

That's the dynamic nature of Python :snake:

**Comment by cogmission** [comment]
> Notice, there's effectively no difference between the bytecode for the __init__ and mutate functions.

Austin, again thank you for going through all of this trouble explaining this to me. I'm not sure its worth it :-P

However I'm still not sure we're comparing the difference between calling a method that **does this inside** - not a comparison between a method call and an object creation?

Effectively comparing this:

```Python
def updateSynapsePermanence(self, synapse, permanence):
    """
    Updates the permanence for a synapse.

    @param synapse    (int)   Synapse index
    @param permanence (float) New permanence
    """
    self._validatePermanence(permanence)

    data = self._synapses[synapse]
    newData = SynapseData(data.segment,   <--------------------   HERE
                          data.presynapticCell,
                          permanence)
    self._synapses[synapse] = newData
```

...to this:

```Python
def updateSynapsePermanence(self, synapse, permanence):
    """
    Updates the permanence for a synapse.

    @param synapse    (int)   Synapse index
    @param permanence (float) New permanence
    """
    self._validatePermanence(permanence)

   self._synapses[synapse].permanence = permanence  <------- HERE
```

Calling those two methods can't be equivalent and the mutate in place has to be faster? This allocation of the initial variable is only done the first time the synapse for the segment is created. Every access after that is simply a mutate in place? That **HAS** to be faster than creating an object and storing it??

I'm still not convinced your painstakingly made examples are comparing the effective operation I'm talking about?

**Comment by oxtopus** [comment]
To be clear, the equivalent of:

```python
  newData = SynapseData(data.segment,   <--------------------   HERE
                          data.presynapticCell,
                          permanence)
    self._synapses[synapse] = newData
```

Would be more like:

```python
  self._synapses[synapse].segment = segment
  self._synapses[synapse].presynapticCell = presynapticCell
  self._synapses[synapse].permanence = permanence
```

Compared to creating a new instance, that's 3x additional lookup in `self._synapses` that wouldn't happen if you just created a new instance.  Otherwise, the attr lookup for `segment`, `presynapticCell`, `permanence` and assignment are equivalent to `SynapseData.__init__()`.

You don't have to take my word for it, though.  Feel free to profile it.  You might be right and it may be faster, but if it is, I doubt it will be by much.  If I'm wrong, great!

Using your example, if we can drop `segment` and `presynapticCell`, that would speed things up, too, but the difference between creating a new instance and assigning the value ought to be negligible.

**Comment by cogmission** [comment]
I believe you would only need to set the permanence? The segment and presynapticCell reference would only happen the first time it was called. Those don't ever change. A Synapse is always going to be on the same segment, and it's always going to connect to the same presynapticCell. So you only have one lookup. And why is that a "lookup"? Why wouldn't that be a direct dereferencing of an array location?

Anyway, Austin I appreciate your time - I don't want to take you away from getting us the next coolest HTM feature! :-)  I simply need to study Python to understand its data structures and internals rather than take your time up with my Java-centric understanding.

Thanks,
David

**Comment by andrewmalta13** [comment]
@cogmission Connections.py has changed and this instead of creating a new object, the permanence field is now changed. I believe this can be closed now.

**Comment by cogmission** [comment]
@andrewmalta13 👍
