### ISSUE TITLE
Make TemporalMemory more readable

### ISSUE THREAD

**Issue by chetan51** [numenta/nupic#2496]
Merge `compute` and `computeFn`, and clean up anything else that might be confusing.

**Comment by david-ragazzi** [comment]
Is this PR only focused in compute* functions and minor changes? Was OO fully discarded for Connections even proved that it makes the code more readable?

**Comment by rhyolight** [comment]
Yes, this PR is only for this one aspect of TM functions.

#1903 is still a valid issue and ready for work, if you want to try it. I'm not sure what the consensus was for the `Layer` class, but I remember that it was dropped from the proposal at some point.
