### ISSUE TITLE
Remove build dependency on darwin64, linux64 repos

### ISSUE THREAD

**Issue by rhyolight** [numenta/nupic#2504]
Completely remove all dependencies within our build systems for https://github.com/numenta/nupic-linux64 and https://github.com/numenta/nupic-darwin64

**Comment by breznak** [comment]
are those repos abandoned then, or still useful? Maybe we could keep some exotic instead - like solaris, arm*, linux32,.. which need some tweaking on the user's side. And then remove their includes/dependencies from `external/`

**Comment by rhyolight** [comment]
We are still using them in Travis-CI, but I believe they cause too much confusion amongst people trying to install. It is easier to just define the system requirements and make people figure out how to install them.

I agree that it makes sense to maintain repos like these for more exotic environments like linux32 and solaris.

**Comment by rhyolight** [comment]
I think I can update the Travis-CI builds myself...
