### ISSUE TITLE
Travis-CI not properly testing specified nupic.core version

### ISSUE THREAD

**Issue by oxtopus** [numenta/nupic#2517]
See https://travis-ci.org/numenta/nupic/builds/77699965, which was green.  The PR for which updates nupic.core commit to "e6bf5fd85d955ba9500ced8b011d1416856c2894" (see https://github.com/numenta/nupic/compare/core-update-e6bf5fd85d955ba9500ced8b011d1416856c2894).  However, the nupic installation downloads and installs an older version of nupic.core -- 57a614d73e65aa4fa2e7d249185069b519311b09 in this case.  See https://s3.amazonaws.com/archive.travis-ci.org/jobs/77699966/log.txt for full details.

**Comment by scottpurdy** [comment]
This should be addressed by #2489 by using the `--no-index` option when installing nupic.bindings. So the build will fail rather than fall back to PyPI.
