### ISSUE TITLE
Can issues of installation on OS X be fixed recently?

### ISSUE THREAD

**Issue by wuxianliang** [numenta/nupic#2520]
I have read the passed issues. I have installed nupic.core from Github and 
```shell
pip install https://s3-us-west-2.amazonaws.com/artifacts.numenta.org/numenta/nupic/30f23b47197ab8bfd6fcba27c7b4d72a2ad0ca57/nupic-0.2.12.dev0-py2-none-any.whl
```
It still report 
```python
python -c "import nupic.bindings.math"
```
```shell
ImportError: No module named math
``` 

If I change to install nupic from Gtihub, then it report
```shell
Fatal Python error: PyThreadState_Get: no current thread
Abort trap: 6
```

Can you feel my pain?

**Comment by rhyolight** [comment]
@wuxianliang Sorry, but we are experiencing some problems with the 0.2.12 build. See http://lists.numenta.org/pipermail/nupic_lists.numenta.org/2015-August/011562.html for context. 

Also, if you are using OS X, you should not be using the `https://s3-us-west-2.amazonaws.com/artifacts.numenta.org/numenta/nupic/30f23b47197ab8bfd6fcba27c7b4d72a2ad0ca57/nupic-0.2.12.dev0-py2-none-any.whl` path to install. You should simply run `pip install nupic`. But unfortunately I don't have any confidence in that binary file. So please standby and I will email the nupic-discuss mailing list as soon as we cut another release.

**Comment by wuxianliang** [comment]
@rhyolight  There is another person http://autovimana.com/ who paid on upwork.com to solve this problem. I leaned from him that "reinstall OS X" works. Yes, I have reinstalled. It works! 
It seems that we have to keep system python unchanged to install nupic.  
There are duplicate issues on installation, so I close this one.  Thank you for response.
