### ISSUE TITLE
NuPIC Docker container doesn't include MySQL

### ISSUE THREAD

**Issue by rhyolight** [numenta/nupic#2525]
We should include mysql so users can swarm. The container should have all the dependencies necessary to run all aspects of NuPIC.

**Comment by rhyolight** [comment]
cc @oxtopus @allanino

**Comment by oxtopus** [comment]
I disagree.  The official mysql images on the docker hub (https://hub.docker.com/_/mysql/) are quite nice, well documented, and easy to bring online.  Meanwhile, bundling a mysql server into nupic a nupic image violates the convention of single-responsibility per-container and would add significant overhead to support a feature that is rarely used.

I'd rather do one, or both of the following:

1. Add sufficient documentation for running a swarm with Docker (easy)
2. Publish a secondary tagged Docker build that is specific to swarming.  This would be similar in spirit to the official rabbitmq images in which you can specify "-management" suffix to the image tag that enables the management console for the given version (see https://github.com/docker-library/rabbitmq/blob/bb91e64b5664a4ab5cd681b7501a2830edbe9ddf/management/Dockerfile and https://hub.docker.com/_/rabbitmq/ for details).  In our case, we'd add a new Dockerfile that builds off of the official nupic, which adds mysql. (my complex, but elegant)

cc @unixorn

**Comment by oxtopus** [comment]
Closing in favor of #2527 and #2528
