### ISSUE TITLE
Instructions for running a swarm with Docker

### ISSUE THREAD

**Issue by oxtopus** [numenta/nupic#2527]
The stock nupic Dockerfile and official nupic image at https://hub.docker.com/r/numenta/nupic/ does not include mysql and will not run a swarm as-is.  However, the official mysql image should be suitable for running a swarm in docker containers in conjunction with the official nupic image.  Please include some documentation with an example for configuring a running container to use a separate mysql container when running a swarm.

**Comment by oxtopus** [comment]
@rhyolight I'm going to work on a proper writeup and maybe an instructional video, but the following comprises the necessary steps:

### Run MySQL container:

```
docker run \
  --name nupic-mysql \
  -e MYSQL_ROOT_PASSWORD=nupic \
  -p 3306:3306 \
  -d \
  mysql:5.6
```

### Run nupic container  

```
docker run \
  --name nupic \
  -e NTA_CONF_PROP_nupic_cluster_database_passwd=nupic \
  -e NTA_CONF_PROP_nupic_cluster_database_host=mysql \
  --link nupic-mysql:mysql \
  -ti \
  numenta/nupic
```

### Run a swarm

From inside the container, execute the following command to verify that it works:

```
${NUPIC}/scripts/run_swarm.py $NUPIC/examples/swarm/simple/search_def.json --maxWorkers=4
```

**Comment by oxtopus** [comment]
See detailed instructions at https://github.com/numenta/nupic/wiki/Running-Swarms#running-a-swarm-with-docker

**Comment by rhyolight** [comment]
:clap:

**Comment by MZamanMughal** [comment]
@rhyolight Please share this answer in Readme of Numenta/Nupic docker.
