### ISSUE TITLE
Add separate Dockerfile to support swarming

### ISSUE THREAD

**Issue by oxtopus** [numenta/nupic#2528]
This would be similar in spirit to the official rabbitmq images in which you can specify "-management" suffix to the image tag that enables the management console for the given version (see https://github.com/docker-library/rabbitmq/blob/bb91e64b5664a4ab5cd681b7501a2830edbe9ddf/management/Dockerfile and https://hub.docker.com/_/rabbitmq/ for details). In our case, we'd add a new Dockerfile that builds off of the official nupic image, which adds mysql.

**Comment by rhyolight** [comment]
cc @allanino

**Comment by allanino** [comment]
Hey @rhyolight, I agree with the creation of a new image for this and I can even give this a try. I'll have some free time by tomorrow.

**Comment by rhyolight** [comment]
That sounds great, @allanino. Much appreciated.

**Comment by allanino** [comment]
I already have a working image!

The question is: where to put the Dockerfile? 

I think the cleaner solution is to create it's own repository and use Docker Hub "Repository Links" feature to trigger its building on updates from `numenta/nupic`. Otherwise we would have to put it somewhere in `numenta/nupic`.

**Comment by allanino** [comment]
Hey @rhyolight, you might have missed my previous comment.

**Comment by rhyolight** [comment]
I think I'd rather have a `Dockerfile-complete` in this repo than have to manage another repo. Can we try that for now? We can always extract to another repo if it confuses people.

**Comment by allanino** [comment]
Sure! I'll create a PR.
