### ISSUE TITLE
Interface for learnable code

### ISSUE THREAD

**Issue by breznak** [numenta/nupic#2537]
See parent: #2536 

All classes that have a `learn` boolean should inherit from this. 

Provided calls: 

```
getLearning() # bool
setLearning(newValue)
pruneLearning() # irreversible optimization that disables learning and prunes related data structures 
getDisabled() # True after prune ^^^ has been called
```

Use-case: reduce code duplication, nicer :), programmatically decide which code is "static"=non-learnig: 
`if (not isinstance(A, Learnable)) or A.getDisabled(): doCaching()` , see https://github.com/numenta/nupic/pull/2501#issuecomment-136973745

Classes in question: some encoders (AdaptiveScalar,..), SP, TP, TM, AnomalyLikelihood, Classifier, and respective Regions. 

-------------------------
CC @scottpurdy @oxtopus : Proposal like this, guys?

**Comment by scottpurdy** [comment]
@subutai - What are your thoughts on this interface? Should it include `resetLearning()`?

**Comment by breznak** [comment]
Another question, should we use binary `getLearning() and
getDisabledLearning()`, or trinary `getLearning() # On/Off,Pruned` ?

**Comment by scottpurdy** [comment]
`getLearning()` should definitely be binary

**Comment by rhyolight** [comment]
> getLearning() should definitely be binary

YES

**Comment by subutai** [comment]
> What are your thoughts on this interface? Should it include resetLearning()?

What would this function do? Is this something to be called when a reset signal is encountered?

**Comment by scottpurdy** [comment]
@subutai - yes, but I don't know if that has a consistent meaning so perhaps should be left out.

**Comment by subutai** [comment]
OK that makes sense. I think most of our algorithms would derive meaning from reset.

About the interface proposal in general:

Should these just be incorporated into a generic algorithms base class? Are there any algorithms that do not have a learn parameter? It seems like just about all of ours do.

I wouldn't apply this to Regions right now. Regions have their own conventions. Let's just stick to basic algorithm code.

**Comment by breznak** [comment]
> Should these just be incorporated into a generic algorithms base class?
Are there any algorithms that do not have a learn parameter? It seems like
just about all of ours do.

For example some encoders (Scalar,..), Anomaly class (but not
AnomalyLikelihood),...

**Comment by breznak** [comment]
> I wouldn't apply this to Regions right now. Regions have their own conventions. Let's just stick to basic algorithm code.

:+1: 

Also, should this imply removal of the learn flag from respective methods and using setLearn() only?

**Comment by subutai** [comment]
> Also, should this imply removal of the learn flag from respective methods and using setLearn() only?

Ah that actually brings up an issue with this proposal. We don't have a stored learn flag in many of our algorithms. Instead it is just passed into compute, and can change arbitrary from call to call. This is true for SP, TP, etc.  This proposal would change that and add a learn state that is stored with each instance.

**Comment by cogmission** [comment]
Seems a stored state could limit flexibility?

On Thu, Sep 3, 2015 at 3:01 PM, Subutai Ahmad <notifications@github.com>
wrote:

> Also, should this imply removal of the learn flag from respective methods
> and using setLearn() only?
>
> Ah that actually brings up an issue with this proposal. We don't have a
> stored learn flag in many of our algorithms. Instead it is just passed into
> compute, and can change arbitrary from call to call. This is true for SP,
> TP, etc. This proposal would change that and add a learn state that is
> stored with each instance.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/numenta/nupic/issues/2537#issuecomment-137558509>.
>



-- 
*With kind regards,*

David Ray
Java Solutions Architect

*Cortical.io <http://cortical.io/>*
Sponsor of:  HTM.java <https://github.com/numenta/htm.java>

d.ray@cortical.io
http://cortical.io

**Comment by breznak** [comment]
> Ah that actually brings up an issue with this proposal. We don't have a
stored learn flag in many of our algorithms. Instead it is just passed into
compute, and can change arbitrary from call to call. This is true for SP,
TP, etc. This proposal would change that and add a learn state that is
stored with each instance.

That is true, but I don't feel storing the learn state would be wrong - if
you wanted learning on/off, you'd expect to have the same after a load from
serialized state.

The other thing is changing 'learn' with each compute() call. Question is
if we really need that functionality? And if needed, same can be achieved
with `setLearn(), compute()`.
Or we can remove the set/getLearn() from the proposal and keep it as a flag
to compute.

**Comment by cogmission** [comment]
Have we pretty much decided that all algorithms will contain state? I know I've been arguing against this because I view the algorithms like a mutator method that operates on some data and returns a result, and thus the same instance can be used (simultaneously) by different threads and different HTM structures.

**Comment by breznak** [comment]
Do you advocate for functional programming? I wouldn't mind but all (but
TM) algs include state, so we are pretty far from it.

**Comment by cogmission** [comment]
Deciding to go functional is a pretty big step. Putting big steps in front of us might serve to nullify our forward momentum - so I don't really have an opinion right now about that. 

I was mostly concerned with the direction any publicly declared interfaces would be heading in. Right now, I agree with what you said about being able to accomplish the same thing with set/get as having a boolean "isLearn" on every method. As long as we have state, then I think taking out the boolean on the methods makes the interfaces more simple and lean - which is a good direction in my opinion.

If we are headed toward separate storage of state (i.e. Architecture having these separate):
1. State
2. Column/Cell matrix
3. Algorithms

...then it would be necessary to include some access to the "isLearn" state in the method signatures (such as a Connections object that stores the state; another object or an explicit flag which is passed in).

**Comment by subutai** [comment]
> The other thing is changing 'learn' with each compute() call. Question is
> if we really need that functionality? And if needed, same can be achieved
> with `setLearn(), compute()`.

True.  I don't have a strong point of view - just wanted to mention that difference.

> Or we can remove the set/getLearn() from the proposal and keep it as a flag
> to compute.

That would be the smaller change and has less impact, but I am also ok with your proposal.

**Comment by subutai** [comment]
> Have we pretty much decided that all algorithms will contain state?

I think that is still an open discussion. Currently they do contain state and this proposal would not change that either way. So I think the "should algorithms contain state?" discussion is out of scope for this issue.

**Comment by cogmission** [comment]
Though consideration of the direction we're headed regarding state could bear upon the decision regarding method signatures? If we're pulling state out then keeping the learn Boolean in the signature makes more sense because we won't have set/get methods for it?

**Comment by scottpurdy** [comment]
Thinking about his a bit more I am inclined to leave learning as a compute parameter. If we don't need to store state then we shouldn't. If we go that route then we don't need this interface, right? Seems simpler.

**Comment by rhyolight** [comment]
Ok, who's got the ball on this issue? I think we're ready to assign it and start work?

**Comment by scottpurdy** [comment]
Is there objection to closing this in favor of the learn-as-function-parameter approach? That simplifies things like serialization and is probably less error prone.

**Comment by cogmission** [comment]
:+1:  I know I'm not a reviewer, but I agree with Scott. Moving toward extraction of state is a good thing I believe.

**Comment by rhyolight** [comment]
> Is there objection to closing this in favor of the learn-as-function-parameter approach? That simplifies things like serialization and is probably less error prone.

:+1: But we need someone to create a new issue to capture that before closing this one.

**Comment by breznak** [comment]
@scottpurdy @cogmission Ok, can we then just change the meaning of this issue to reflect your ideas?:

```
class Learnable
""" type all objects that adapt their internal state, eg use learn param."""
def compute(..., learn=False)
def disableLearning(bool)
def getLearningDisabled()
```

**Comment by cogmission** [comment]
@breznak I think the most recent conclusion is to not use this interface? That would mean that we wouldn't need this issue if we're all agreed to this (not me, but the reviewers). @scottpurdy Is this correct?

**Comment by scottpurdy** [comment]
Yes that is what I was thinking.

**Comment by breznak** [comment]
Ok, let's close it then.

**Comment by cogmission** [comment]
> Is there objection to closing this in favor of the learn-as-function-parameter approach? That simplifies things like serialization and is probably less error prone.

> :+1: But we need someone to create a new issue to capture that before closing this one. 

Did we do this, anyone?

**Comment by scottpurdy** [comment]
@cogmission - I don't know what the task would be.

**Comment by cogmission** [comment]
@scottpurdy  For the compute() interface to include an "isLearn" parameter? I'm not sure - I think @rhyolight mentioned this (above)?

**Comment by scottpurdy** [comment]
You can't enforce one parameter to a function but not the rest of the function interface.

**Comment by cogmission** [comment]
Is there a way the interfaces could all share common parameters (including "isLearn")? That would simplify things like the network architecture. Perhaps by wrapping the inputs in an InferenceInput or something that can contain the slight variances in compute() method parameters? Just an idea...
