### ISSUE TITLE
Serializable interface/abstract class

### ISSUE THREAD

**Issue by breznak** [numenta/nupic#2538]
Functionality: common logic for serialization, will hold the includes, allow easily override serialization for the whole project (eg turn it off for some fork of nupic,...)

API:

```
import capnp...

__init__(type='capnp')
def serialize():
  if self.type == 'off':
    return
  return write()
def deserialize(obj):
  if self.type == 'off':
    return
  return read()
getType() # 'oldpy', 'capnp', 'off'
def write():
  raise # implment in your code
def read():
  raise # to implement
```

Classes: all that support, or should, serialization. Example: `MyClass: super(MyClass, self).__init__(type='off')`

**Comment by scottpurdy** [comment]
This would be different for the current/old serialization and the new capnp serialization. It could actually be really nice for capnp serialization with the following:

```
getSchema() - Returns capnp type
read(proto)
write(proto)
```

And the base class could provide `readFromFile` and `writeToFile` to avoid code duplication.

The current serialization is a little more complicated. In Python it would need `__getstate__`, `__setstate__`, `serializeExtraData`, and `deserializeExtraData`. In C++ it would only need `save` and `load`. I'd prefer to hold off on doing work for old serialization as we plan to deprecate it as soon as initial capnp effort is complete.

**Comment by rhyolight** [comment]
On Wed, Sep 2, 2015 at 9:11 AM, Scott Purdy <notifications@github.com>
wrote:

> I'd prefer to hold off on doing work for old serialization as we plan to
> deprecate it as soon as initial capnp effort is complete.


Agreed.

**Comment by scottpurdy** [comment]
Proposal for the C++ interface (actually an abstract class since interfaces in C++ can't have any method definitions, only purely virtual functions):

https://github.com/scottpurdy/nupic.core/blob/capnp-interface/src/nupic/proto/Serializable.hpp

**Comment by breznak** [comment]
So putting this on hold for now (?)
