### ISSUE TITLE
Restore Connections parameter to every function in temporal memory

### ISSUE THREAD

**Issue by chetan51** [numenta/nupic#2546]
It was removed in commit fefc9916e854a1d13ede712384ee1dd93110180a to simplify the TM code, but it is needed if we want to have multiple types of dendrites, like we do in nupic.research's GeneralTemporalMemory. This keeps the code flexible and functional, so it's worth the slight readability hit.

**Comment by cogmission** [comment]
Super Magnificent Ultra Fantastic Plus One! :-)

:+1:

On Thu, Sep 3, 2015 at 2:09 PM, Chetan Surpur <notifications@github.com>
wrote:

> It was removed in commit fefc991
> <https://github.com/numenta/nupic/commit/fefc9916e854a1d13ede712384ee1dd93110180a>
> to simplify the TM code, but it is needed if we want to have multiple types
> of dendrites, like we do in nupic.research's GeneralTemporalMemory. This
> keeps the code flexible and functional, so it's worth the slight
> readability hit.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/numenta/nupic/issues/2546>.
>



-- 
*With kind regards,*

David Ray
Java Solutions Architect

*Cortical.io <http://cortical.io/>*
Sponsor of:  HTM.java <https://github.com/numenta/htm.java>

d.ray@cortical.io
http://cortical.io
