### ISSUE TITLE
Pattern and Sequence machines shift to using nupic::Random

### ISSUE THREAD

**Issue by rcrowder** [numenta/nupic#2565]
Currently the Pattern and Sequence machines in NuPIC use NumPy rand. This issue is to move the two machines across to use NuPIC Random.

**Comment by cogmission** [comment]
Back in August of last year there was an effort to keep random number generator implementations close to the Mersenne Twister which is the default for C and python - custom implementations will only serve to distance porting people interested from getting the same results why even go that direction; why do we need a custom RMG implementation?

**Comment by rhyolight** [comment]
@cogmission Yes, but it [looks like it was changed back in CoordinateEncoder](https://github.com/numenta/nupic/issues/1205#issuecomment-91409742)? 

@scottpurdy @oxtopus What is our stance on this now?

**Comment by oxtopus** [comment]
We should consistently use the same RNG implementation across the board, regardless.  I support this change.

**Comment by scottpurdy** [comment]
`nupic::Random` should be the only RNG we use right now. I'd be fine switching to something that has implementations in different languages that yield identical results but we don't have that right now. C++ stdlibs and Python `random` both have mersenne twister implementations but I don't think they get the same results given the same seed.

**Comment by rcrowder** [comment]
I'm just tracking down why I now face SparseMatrix and OPF failures with this branch. Possibly bad 0.5.1 bindings... Once tests passing locally will get a new PR ready.

**Comment by rcrowder** [comment]
@chetan51 Closed the associated PR, to re-fork and make a fresh one. Will ping you soon when this is cleaned and ready for review again.

**Comment by rcrowder** [comment]
Cleaner PR can be found here https://github.com/numenta/nupic/pull/2589
