### ISSUE TITLE
Remove nupic/research and move algorithm code to nupic/algorithms

### ISSUE THREAD

**Issue by subutai** [numenta/nupic#2569]
It is very confusing to have both nupic/research and nupic/algorithms, both of which contain algorithms. We currently import many algorithms from nupic.research instead of nupic.algorithms  It is even more confusing given that we have a nupic.research repository which is yet another thing.

This issue is to move algorithm code from nupic/research to nupic/algorithms, and to delete nupic/research altogether. As part of this we would update all tests and resolve any backward incompatibilities.

Some of the code in nupic/research, such as monitor_mixin, fdrutilities, and utils.py don't belong in nupic/algorithms and should probably move to nupic/support or some other place.

**Comment by rhyolight** [comment]
@subutai Is this an easy enough refactoring that a non-algorithms programmer could do it?

**Comment by subutai** [comment]
@rhyolight I don't think it really needs algorithm knowledge but it does require someone who is experienced with Python and very careful. This will likely cause backward incompatibilities and may be tricky to implement. So, it's definitely not for a beginner.

**Comment by breznak** [comment]
can the first step be moving all stuff to `nupic/algorithms` and later some parts can be moved elsewhere?

**Comment by subutai** [comment]
We could but I think it would be easiest to do in one step.
