### ISSUE TITLE
Error installing nupic on OSX yosemite(10.10.4)

### ISSUE THREAD

**Issue by felippemr** [numenta/nupic#2570]
Hello Guys!

I am trying to install nupic by pip( pip install nupic) but I get this error:

raise Exception("Must provide path to nupic core release. export NUPIC_CORE_RELEASE=<path>")

Exception: Must provide path to nupic core release. export NUPIC_CORE_RELEASE=<path>

Can you please help?

**Comment by felippemr** [comment]
I tried to install by vagrant and got the same error:

      raise Exception("Must provide path to nupic core release. export NUPIC_CORE_RELEASE=<path>")
    Exception: Must provide path to nupic core release. export NUPIC_CORE_RELEASE=<path>

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-18qhAN/nupic.bindings
The command '/bin/sh -c pip install --allow-all-external --allow-unverified PIL --allow-unverified  psutil -r $NUPIC/external/common/requirements.txt' returned a non-zero code: 1

**Comment by felippemr** [comment]
I tried to build the project from source and got the same error.

**Comment by rhyolight** [comment]
Sorry about the delay on this, @felippemr. This error generally occurs because there is an older (bad) version of NuPIC installed on your system. Try this:

    pip uninstall nupic -y
    pip uninstall nupic.bindings -y

Run those commands until it says `Cannot uninstall requirement nupic, not installed`. This should remove the old version of NuPIC (if there was one).

Then you can either install from binary `pip install nupic` or from source. But if you install from source, be sure you have the latest code (0.3.0 or later).

**Comment by felippemr** [comment]
@rhyolight the error persists...

When I run `:

**Comment by felippemr** [comment]
@rhyolight I did exactly what you wrote but the problem persists(I tried to install from binary).

FYI when I run ```pip freeze``` it prints:
numpy==1.9.2
urllib3==1.12
wsgiref==0.1.2

**Comment by rhyolight** [comment]
There has **got** to be some remnant of an older NuPIC installation left over on your system somewhere. The error `Exception: Must provide path to nupic core release. export NUPIC_CORE_RELEASE=` is not generated by our current codebase (post 0.3.0).

Please run the following command from anywhere so we can try to identify what version of NuPIC you are running and where it is installed:

    python -c 'import pkg_resources; nupic=pkg_resources.get_distribution("nupic"); print nupic.project_name, nupic.version, nupic.location'

**Comment by felippemr** [comment]
When I run ```python -c 'import pkg_resources; nupic=pkg_resources.get_distribution("nupic"); print nupic.project_name, nupic.version, nupic.location'```

I get:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/felippe.gestec/.virtualenvs/heimdall/lib/python2.7/site-packages/pkg_resources.py", line 346, in get_distribution
    if isinstance(dist,Requirement): dist = get_provider(dist)
  File "/Users/felippe.gestec/.virtualenvs/heimdall/lib/python2.7/site-packages/pkg_resources.py", line 225, in get_provider
    return working_set.find(moduleOrReq) or require(str(moduleOrReq))[0]
  File "/Users/felippe.gestec/.virtualenvs/heimdall/lib/python2.7/site-packages/pkg_resources.py", line 685, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/Users/felippe.gestec/.virtualenvs/heimdall/lib/python2.7/site-packages/pkg_resources.py", line 588, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: nupic

I also destroyed my virtualenv and created a new one, but the error persists.

**Comment by rhyolight** [comment]
pkg_resources.DistributionNotFound: nupic

Looks like NuPIC is no longer installed. Can you reinstall it?

**Comment by felippemr** [comment]
I tried and the full log is here:

```
(heimdall)Projects$ pip install nupic
Downloading/unpacking nupic
  Downloading nupic-0.3.0-py2-none-any.whl (5.3MB): 5.3MB downloaded
Downloading/unpacking PyMySQL==0.6.2 (from nupic)
  Downloading PyMySQL-0.6.2-py2.py3-none-any.whl (63kB): 63kB downloaded
Requirement already satisfied (use --upgrade to upgrade): numpy==1.9.2 in /Users/felippe.gestec/.virtualenvs/heimdall/lib/python2.7/site-packages (from nupic)
Downloading/unpacking pyproj==1.9.3 (from nupic)
  Downloading pyproj-1.9.3.tar.gz (2.7MB): 2.7MB downloaded
  Running setup.py (path:/Users/felippe.gestec/.virtualenvs/heimdall/build/pyproj/setup.py) egg_info for package pyproj
    Output Binary File Format: ctable2
    Output Binary File Format: ctable2
    Output Binary File Format: ctable2
    Output Binary File Format: ctable2
    Output Binary File Format: ctable2
    Output Binary File Format: ctable2
    Output Binary File Format: ctable2
    Output Binary File Format: ctable2
    Output Binary File Format: ctable2
    Output Binary File Format: ctable2
    Output Binary File Format: ctable2
    Output Binary File Format: ctable2
    Output Binary File Format: ctable2
    executing /Users/felippe.gestec/.virtualenvs/heimdall/build/pyproj/nad2bin lib/pyproj/data/alaska < datumgrid/alaska.llaexecuting /Users/felippe.gestec/.virtualenvs/heimdall/build/pyproj/nad2bin lib/pyproj/data/conus < datumgrid/conus.llaexecuting /Users/felippe.gestec/.virtualenvs/heimdall/build/pyproj/nad2bin lib/pyproj/data/FL < datumgrid/FL.llaexecuting /Users/felippe.gestec/.virtualenvs/heimdall/build/pyproj/nad2bin lib/pyproj/data/hawaii < datumgrid/hawaii.llaexecuting /Users/felippe.gestec/.virtualenvs/heimdall/build/pyproj/nad2bin lib/pyproj/data/MD < datumgrid/MD.llaexecuting /Users/felippe.gestec/.virtualenvs/heimdall/build/pyproj/nad2bin lib/pyproj/data/null < datumgrid/null.llaexecuting /Users/felippe.gestec/.virtualenvs/heimdall/build/pyproj/nad2bin lib/pyproj/data/prvi < datumgrid/prvi.llaexecuting /Users/felippe.gestec/.virtualenvs/heimdall/build/pyproj/nad2bin lib/pyproj/data/stgeorge < datumgrid/stgeorge.llaexecuting /Users/felippe.gestec/.virtualenvs/heimdall/build/pyproj/nad2bin lib/pyproj/data/stlrnc < datumgrid/stlrnc.llaexecuting /Users/felippe.gestec/.virtualenvs/heimdall/build/pyproj/nad2bin lib/pyproj/data/stpaul < datumgrid/stpaul.llaexecuting /Users/felippe.gestec/.virtualenvs/heimdall/build/pyproj/nad2bin lib/pyproj/data/TN < datumgrid/TN.llaexecuting /Users/felippe.gestec/.virtualenvs/heimdall/build/pyproj/nad2bin lib/pyproj/data/WI < datumgrid/WI.llaexecuting /Users/felippe.gestec/.virtualenvs/heimdall/build/pyproj/nad2bin lib/pyproj/data/WO < datumgrid/WO.llarunning egg_info

Downloading/unpacking validictory==0.9.1 (from nupic)
  Downloading validictory-0.9.1.tar.gz
  Running setup.py (path:/Users/felippe.gestec/.virtualenvs/heimdall/build/validictory/setup.py) egg_info for package validictory

    warning: no files found matching 'CHANGELOG.txt'
Downloading/unpacking pytest-cov==1.6 (from nupic)
  Downloading pytest-cov-1.6.tar.gz
  Running setup.py (path:/Users/felippe.gestec/.virtualenvs/heimdall/build/pytest-cov/setup.py) egg_info for package pytest-cov

Downloading/unpacking mock==1.0.1 (from nupic)
  Downloading mock-1.0.1.tar.gz (818kB): 818kB downloaded
  Running setup.py (path:/Users/felippe.gestec/.virtualenvs/heimdall/build/mock/setup.py) egg_info for package mock

    warning: no files found matching '*.png' under directory 'docs'
    warning: no files found matching '*.css' under directory 'docs'
    warning: no files found matching '*.html' under directory 'docs'
    warning: no files found matching '*.js' under directory 'docs'
Downloading/unpacking pytest-xdist==1.8 (from nupic)
  Downloading pytest-xdist-1.8.zip
  Running setup.py (path:/Users/felippe.gestec/.virtualenvs/heimdall/build/pytest-xdist/setup.py) egg_info for package pytest-xdist

    no previously-included directories found matching '.hg'
Downloading/unpacking ordereddict==1.1 (from nupic)
  Downloading ordereddict-1.1.tar.gz
  Running setup.py (path:/Users/felippe.gestec/.virtualenvs/heimdall/build/ordereddict/setup.py) egg_info for package ordereddict

Downloading/unpacking DBUtils==1.1 (from nupic)
  Downloading DBUtils-1.1.tar.gz (109kB): 109kB downloaded
  Running setup.py (path:/Users/felippe.gestec/.virtualenvs/heimdall/build/DBUtils/setup.py) egg_info for package DBUtils

    warning: no previously-included files found matching 'Release.txt'
    warning: no previously-included files found matching 'setversion.py'
    no previously-included directories found matching 'DBUtils/Docs/.svn'
Downloading/unpacking unittest2==0.5.1 (from nupic)
  Downloading unittest2-0.5.1.tar.gz (62kB): 62kB downloaded
  Running setup.py (path:/Users/felippe.gestec/.virtualenvs/heimdall/build/unittest2/setup.py) egg_info for package unittest2

Downloading/unpacking pillow==2.3.0 (from nupic)
  Downloading Pillow-2.3.0.zip (2.4MB): 2.4MB downloaded
  Running setup.py (path:/Users/felippe.gestec/.virtualenvs/heimdall/build/pillow/setup.py) egg_info for package pillow

Downloading/unpacking pytest==2.5.1 (from nupic)
  Downloading pytest-2.5.1.tar.gz (577kB): 577kB downloaded
  Running setup.py (path:/Users/felippe.gestec/.virtualenvs/heimdall/build/pytest/setup.py) egg_info for package pytest

Downloading/unpacking nupic.bindings==0.1.5 (from nupic)
  Downloading nupic.bindings-0.1.5.tar.gz (589kB): 589kB downloaded
  Running setup.py (path:/Users/felippe.gestec/.virtualenvs/heimdall/build/nupic.bindings/setup.py) egg_info for package nupic.bindings
    Python Bindings directory: /Users/felippe.gestec/.virtualenvs/heimdall/build/nupic.bindings
    NUMPY VERSION: 1.9.2
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/Users/felippe.gestec/.virtualenvs/heimdall/build/nupic.bindings/setup.py", line 534, in <module>
        raise Exception("Must provide path to nupic core release. export NUPIC_CORE_RELEASE=<path>")
    Exception: Must provide path to nupic core release. export NUPIC_CORE_RELEASE=<path>
    Complete output from command python setup.py egg_info:
    Python Bindings directory: /Users/felippe.gestec/.virtualenvs/heimdall/build/nupic.bindings

NUMPY VERSION: 1.9.2

Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "/Users/felippe.gestec/.virtualenvs/heimdall/build/nupic.bindings/setup.py", line 534, in <module>

    raise Exception("Must provide path to nupic core release. export NUPIC_CORE_RELEASE=<path>")

Exception: Must provide path to nupic core release. export NUPIC_CORE_RELEASE=<path>
 ```

**Comment by rhyolight** [comment]
I think I know what is going on here. This is happening to several people in different ways, but it always boils down to a the same `NUPIC_CORE_RELEASE` exception. 

Our last releases, 0.2.6 & 0.2.7, produced bad binary files for `nupic.bindings` on pypi. I believe that fixed this problem in the source code, but we never bumped the `nupic.bindings` version for a re-release on pypi. So people have a bad version of bindings in their pip cache, and very potentially on pypi itself. 

@oxtopus Just released a new version of [`nupic.bindings`](https://github.com/numenta/nupic.core/pull/614), which is building in CI now and should deploy to https://pypi.python.org/pypi/nupic.bindings as version 0.2 soon. Once this happens, we'll also need to version bump NuPIC to pick up that version change.

Please standby and we'll let you know when the releases are complete so you can try again. In the meantime if you want to try to install, you'll have to do it from the latest source code and figure out how to remove any lingering versions of `nupic.bindings` you might have in a local pip cache.

**Comment by rhyolight** [comment]
I believe this is the same core issue as #2543, so I am going to close as a duplicate. Let's continue our conversation there.

**Comment by felippemr** [comment]
Thank you!

**Comment by rhyolight** [comment]
@felippemr I think we fixed this yesterday by simply updating an incorrect README instruction: https://github.com/numenta/nupic/commit/63b15386f0a6f9c5ebac07388dbfa9be7b4b6c20.

The latest README for binary installation on Ubuntu should now work for you.
