### ISSUE TITLE
null-pointer exception in htm.java in version 0.6.1

### ISSUE THREAD

**Issue by metaml** [numenta/nupic#2571]
This is bug is reproducible by modifying a two coupled hard-coded values in NetworkTest.java:

* in line 220 of NetworkTest.java, change to "i.getRecordNum() == 82"
* in line 237 of NetworkTest.java, change to "assertEquals(83, lines.size());"

For consistency sake, the 2 lines were modified, if it works, the tests will just pass but the null-pointer exceptions will fire somewhere before the line 220 is reached. 

This bug prevents a modified version of htm.java-examples from running to completion against 0.6.1 of htm.java.

**Comment by cogmission** [comment]
@metaml Hi There! :-)

This should be filed agains the htm.java repo, not NuPIC - I know you didn't know... its ok, you should go [here](https://github.com/numenta/htm.java) and file it and close this one... 

Thanks for engaging though! :-)

**Comment by rhyolight** [comment]
Replaced by https://github.com/numenta/htm.java/issues/316
