### ISSUE TITLE
Can we run nupic module in pycharm or with any other python IDE. Is there any specific steps to do that?

### ISSUE THREAD

**Issue by viveklife2003** [numenta/nupic#2586]

**Comment by rhyolight** [comment]
Yes it is possible, but setting up different IDEs is the developer's responsibility. I hope you understand that we cannot provide detailed instructions on setting up every IDE.

However, [this search result](http://numenta.org/search/?q=pycharm) across all our mailing lists and issue trackers might help you. This is definitely something you could ask to the nupic-hackers mailing list. 

Also, if you do set it up, maybe you could take notes and start a wiki page about it? <https://github.com/numenta/nupic/wiki/PyCharm>
