### ISSUE TITLE
exp_generator/experimentDescriptionSchema.json incorrectly refers to StreamDef.json in wrong folder

### ISSUE THREAD

**Issue by JonnoFTW** [numenta/nupic#2592]
The file: 
https://github.com/numenta/nupic/blob/master/src/nupic/swarming/exp_generator/experimentDescriptionSchema.json#L276
incorrectly refers to a file that no longer exists (it appears this was changed after a change in file naming convention re: #971 ). It should refer to: 
https://github.com/numenta/nupic/blob/master/src/nupic/frameworks/opf/jsonschema/stream_def.json

Edit: additionally, there's a few other issues:

 * Typo at line 270, missing space to be: `Used inferenceArgs.predictedField instead`
 * At line 113, there's no description for `inferenceArgs`. Intuitively it seems to be the arguments for the type of inference you want to use, but it should probably be spelled out for completeness

**Comment by rhyolight** [comment]
Related to: https://github.com/numenta/nupic/issues/2596.

This is up for grabs for anyone.
