### ISSUE TITLE
Dockerfile out of date

### ISSUE THREAD

**Issue by oxtopus** [numenta/nupic#2604]
nupic Dockerfile doesn't build due to lack of support for binary distribution of nupic.bindings.

When I build locally in docker, I get the following failure:

```
Collecting nupic.bindings==0.2.1 (from -r /usr/local/src/nupic/external/common/requirements.txt (line 19))
  Could not find a version that satisfies the requirement nupic.bindings==0.2.1 (from -r /usr/local/src/nupic/external/common/requirements.txt (line 19)) (from versions: )
  Some insecure and unverifiable files were ignored (use --allow-unverified nupic.bindings to allow).
No matching distribution found for nupic.bindings==0.2.1 (from -r /usr/local/src/nupic/external/common/requirements.txt (line 19))
INFO[0597] The command '/bin/sh -c pip install --allow-all-external --allow-unverified PIL --allow-unverified  psutil -r $NUPIC/external/common/requirements.txt' returned a non-zero code: 1 
```

**Comment by rhyolight** [comment]
Can we just add `pip install https://s3-us-west-2.amazonaws.com/artifacts.numenta.org/numenta/nupic.core/releases/nupic.bindings/nupic.bindings-0.2.1-cp27-none-linux_x86_64.whl
` to the Dockerfile?

**Comment by oxtopus** [comment]
More or less.  Need to extract the version number out of requirements.txt in order to know which file to download.  Stand by.
