### ISSUE TITLE
Installing NuPIC will install NumPy again even though nupic.bindings also installed it

### ISSUE THREAD

**Issue by rhyolight** [numenta/nupic#2607]
See [6m 23s into this installation video](https://youtu.be/1fIpgXHXAZA?t=6m23s). When installed from binary, numpy is installed twice.

**Comment by rhyolight** [comment]
@oxtopus Any idea why this might be?

**Comment by oxtopus** [comment]
Yes!

The numpy requirement in nupic.bindings, as defined at https://github.com/numenta/nupic.core/blob/master/bindings/py/requirements.txt#L5 specifies anything >= 1.9.2.  As of 9/21/2015, the latest version on pypi is 1.9.3 (https://pypi.python.org/pypi/numpy/1.9.3), so when you install nupic.bindings, it installs 1.9.3.  Meanwhile, nupic has a strict requirement at https://github.com/numenta/nupic/blob/master/external/common/requirements.txt#L23 on 1.9.2, so it installs exactly 1.9.2 in the nupic install.

**Comment by rhyolight** [comment]
@numenta/nupic-contributors This bug was actually preventing me from compiling on Ubuntu. This is good reason to explicitly declare dependency versions.
