### ISSUE TITLE
Py and C++ classes use same init params

### ISSUE THREAD

**Issue by breznak** [numenta/nupic#2616]
EDIT: This issue is to enforce that py and C++ use the same init params. Doing otherwise is against the principle that those 2 implementations are identical. This is fixing (unfortunately not, but cornering) a real problem where SDR representations differ in SP in Py/C++ implementations. 

- [ ] blocked by: https://github.com/numenta/nupic.core/issues/628

**Comment by rhyolight** [comment]
Needs discussion from other @numenta/nupic-committers.

**Comment by rhyolight** [comment]
This would be a whole lot easier to digest if there were separate issues for the SP and the TM, each with different PRs that change default param values. I don't like them mixed together, because they are completely different algorithms and subjects.

**Comment by breznak** [comment]
> This would be a whole lot easier to digest if there were separate issues for the SP and the TM 

agreed. closing this issue then.
