### ISSUE TITLE
gcc error when set up nupic.core

### ISSUE THREAD

**Issue by frank-tancf** [numenta/nupic#2626]
Sorry guys. I got something I didn't know how to solve.

When I doing the last step of setting up nupic.core ,which is 
    python setup.py develop --nupic-core-dir=${HOME}/local --prefix=${HOME}/local

I got error message below, 

c++ -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -D_FORTIFY_SOURCE=2 -g -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security build/temp.linux-x86_64-2.7/../../src/nupic/py_support/NumpyVector.o build/temp.linux-x86_64-2.7/../../src/nupic/py_support/PyArray.o build/temp.linux-x86_64-2.7/../../src/nupic/py_support/PyHelpers.o build/temp.linux-x86_64-2.7/../../src/nupic/py_support/PythonStream.o build/temp.linux-x86_64-2.7/nupic/bindings/algorithms_wrap.o /home/thylacoleo/local/lib/libnupic_core.a -lpython2.7 -ldl -lkj -lcapnp -lcapnpc -lpthread -o build/lib.linux-x86_64-2.7/nupic/bindings/_algorithms.so -m64 -fPIC -L/home/thylacoleo/local/lib -lkj -lcapnp -lcapnpc -O2
/usr/bin/ld: /home/thylacoleo/local/lib/libkj.a(io.c++.o): relocation R_X86_64_32S against `_ZTVN2kj11InputStreamE' can not be used when making a shared object; recompile with -fPIC
/home/thylacoleo/local/lib/libkj.a: error adding symbols: wrong value
collect2: error: ld returned 1 exit status
error: command 'c++' failed with exit status 1

I thought it is familiar with #2102.But it seems like they are a bit different.
I have searched stackflow but got nothing.Can anyone help me out ?Thx

**Comment by frank-tancf** [comment]
And my Gcc version is:

Using built-in specs.
COLLECT_GCC=c++
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/4.8/lto-wrapper
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 4.8.4-2ubuntu1~14.04' --with-bugurl=file:///usr/share/doc/gcc-4.8/README.Bugs --enable-languages=c,c++,java,go,d,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-4.8 --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --with-gxx-include-dir=/usr/include/c++/4.8 --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --enable-gnu-unique-object --disable-libmudflap --enable-plugin --with-system-zlib --disable-browser-plugin --enable-java-awt=gtk --enable-gtk-cairo --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-4.8-amd64/jre --enable-java-home --with-jvm-root-dir=/usr/lib/jvm/java-1.5.0-gcj-4.8-amd64 --with-jvm-jar-dir=/usr/lib/jvm-exports/java-1.5.0-gcj-4.8-amd64 --with-arch-directory=amd64 --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --enable-objc-gc --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --with-tune=generic --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 4.8.4 (Ubuntu 4.8.4-2ubuntu1~14.04)

**Comment by rhyolight** [comment]
Duplicates https://github.com/numenta/nupic.core/issues/632.
