### ISSUE TITLE
Cells4::saveToFile can fail without generating an exception

### ISSUE THREAD

**Issue by vitaly-krugl** [numenta/nupic#2637]
Here is a real possibility of something that can result in an incomplete R2-xtra file:

```
void Cells4::saveToFile(std::string filePath) const
{
  OFStream outStream(filePath.c_str(), std::ios_base::out | std::ios_base::binary);
  outStream.precision(std::numeric_limits<double>::digits10 + 1);
  save(outStream);
}
```

When outStream goes out of scope, its destructor calls `close()`, but doesn't check for close error. `close()` doesn't raise. So, if flushing of the buffer failed in the scope of the destructor (e.g., out of disk space), then there would be no exception, and the failure would not be detected, and the file would be incomplete.

`Cells4::saveToFile()` needs to explicitly call `outStream.close()` and check its return value; if the return value indicates that there was an error (get NULL in this case), then an error needs to be propagated out of `Cells4::saveToFile()` that would cause the appropriate exception in the python side of things.

**Comment by rhyolight** [comment]
@vitaly-krugl This is a `nupic.core` bug, right?

**Comment by vitaly-krugl** [comment]
Moved to https://github.com/numenta/nupic.core/issues/643

CC @rhyolight

**Comment by rhyolight** [comment]
@vitaly-krugl Thanks.
