### ISSUE TITLE
Saving a model created within a multiprocessing.Process and saved on the main process will fail

### ISSUE THREAD

**Issue by JonnoFTW** [numenta/nupic#2640]
I'm running a numerous models, each created inside it's own process from a [`multiprocessing.Pool`](https://docs.python.org/2/library/multiprocessing.html#multiprocessing.pool.multiprocessing.Pool). Afterwards, if I want to save this model on the main process, I get the following error: 
```
File "index.py", line 254, in save_model
    model.save(out_dir)
  File "/scratch/temp/venvs/py2.7.10/lib/python2.7/site-packages/nupic/frameworks/opf/model.py", line 226, in save
    self._serializeExtraData(extraDataDir=self._getModelExtraDataDir(saveModelDir))
  File "/scratch/temp/venvs/py2.7.10/lib/python2.7/site-packages/nupic/frameworks/opf/clamodel.py", line 1302, in _serializeExtraData
    self._netInfo.net.save(outputDir)
AttributeError: 'NoneType' object has no attribute 'save'
```
Where the value of `out_dir` is `/scratch/Dropbox/PhD/htm_models_adelaide/engine/model_store/3103`

My multiprocess code is here (I've commented out the saving for now but you get the idea): https://github.com/JonnoFTW/htm-models-adelaide/blob/master/engine/index.py#L306
My model creation code is here: https://github.com/JonnoFTW/htm-models-adelaide/blob/master/engine/index.py#L74

Additionally, trying to `save` or `load` a model from within a [`multiprocessing.Process`](https://docs.python.org/2/library/multiprocessing.html#multiprocessing.Process) will fail

**Comment by rhyolight** [comment]
@scottpurdy @oxtopus @jcasner I believe this is an important bug to address, especially because @JonnoFTW is working on an HTM Challenge submission. 

Can we divert engineering resources to investigate this?

**Comment by oxtopus** [comment]
I don't think it's a bug, per se.  It's an issue w/ serialization and shared memory in python multiprocesing pools.  Consider this example:

```python
from multiprocessing import Pool
import os

class FooObject(object): pass

def foo(*args):
  fooObj = FooObject()
  print "PID {} created: {}".format(os.getpid(), id(fooObj))
  return fooObj

def main():
  pool = Pool(3)
  results = pool.map(foo, range(3))
  for result in results:
    print "PID {} Result: {}".format(os.getpid(), id(result))

if __name__ == "__main__":
  main()
```

The output for which is:

```
PID 1368 created: 4450700048
PID 1369 created: 4450700112
PID 1368 created: 4450699984
PID 1367 Result: 4450800016
PID 1367 Result: 4450800272
PID 1367 Result: 4450800336
```

The _objects_ returned by `Pool.map()` are not the same, actual instances created in the `foo()` function.  I don't know what guarantees, if any, we offer about the state of objects between processes, which would require full serialize/deserialize support (which is an on-going, and in-progress issue).

Applying it to this specific problem, the objects created in `createModel()` are not the same objects in the main process.  CLA Model state is persisted and shared between processes by saving in the process in which it was created, and loaded in another process in which it is used, similar to the way `htmengine` handles checkpoints during model swapping.

**Comment by rhyolight** [comment]
@oxtopus said:
> CLA Model state is persisted and shared between processes by saving in the process in which it was created, and loaded in another process in which it is used, similar to the way htmengine handles checkpoints during model swapping.

@JonnoFTW Is there a way you can ensure you only save models in the process that created it?

@oxtopus said:
> I don't think it's a bug, per se. It's an issue w/ serialization and shared memory in python multiprocesing pools.

So basically, this is just a property of how multiprocessing works in python. I'll remove the bug label, but I'll keep the issue open in hopes we can work with @JonnoFTW to find a workaround.

**Comment by scottpurdy** [comment]
@rhyolight - capnp effort will provide an option but no eta still due to resources

**Comment by JonnoFTW** [comment]
I'm aware of the limitations of `cPickle` wrt to multiprocessing in python.
I reorganised the code so now models are created and saved on the main process (but still run them in a child process) and now I get the exception when saving: 

```
Caching model to /scratch/Dropbox/PhD/htm_models_adelaide/engine/model_store/3102
Traceback (most recent call last):
  File "index.py", line 373, in <module>
    runAllModels(args.write_anomaly, args.incomplete)
  File "index.py", line 355, in runAllModels
    run_all(locations, write_anomaly, key)
  File "index.py", line 316, in run_all
    map(save_model, models)
  File "index.py", line 271, in save_model
    model.save(out_dir)
  File "/scratch/temp/venvs/py2.7.10/lib/python2.7/site-packages/nupic/frameworks/opf/model.py", line 226, in save
    self._serializeExtraData(extraDataDir=self._getModelExtraDataDir(saveModelDir))
  File "/scratch/temp/venvs/py2.7.10/lib/python2.7/site-packages/nupic/frameworks/opf/clamodel.py", line 1302, in _serializeExtraData
    self._netInfo.net.save(outputDir)
  File "/scratch/temp/venvs/py2.7.10/lib/python2.7/site-packages/nupic/engine/__init__.py", line 722, in save
    engine.Network.save(self, *args, **kwargs)
  File "/scratch/temp/venvs/py2.7.10/lib/python2.7/site-packages/nupic/bindings/engine_internal.py", line 1082, in save
    return _engine_internal.Network_save(self, *args, **kwargs)
TypeError: in method 'Network_save', argument 2 of type 'std::string const &'
```

**Comment by oxtopus** [comment]
Models can't be shared across process boundaries in that sense for the same reason as before.  The models will need to be created, inferences executed, and saved in the same process.

**Comment by JonnoFTW** [comment]
Even if the creating/inferring/saving all happen in a child process I get the same exception.

**Comment by oxtopus** [comment]
I'm attempting to replicate the failure mode by modifying one of the hotgym examples to use process pools at https://github.com/numenta/nupic/compare/numenta:master...oxtopus:issue-2640-pooled-models

Here's the output on my system, in which it starts in the main process (PID 2671), then creates, runs, and saves some models in PIDs 2678 and 2679, and returns back to the main process (PID 2671):

```
Currently on PID 2671
INFO:__main__:After 100 records, 1-step altMAPE=82.138762
Saving on PID 2678
INFO:__main__:After 100 records, 1-step altMAPE=82.138762
Saving on PID 2679
Model saved
Model saved
INFO:__main__:After 100 records, 1-step altMAPE=82.138762
Saving on PID 2679
INFO:__main__:After 100 records, 1-step altMAPE=82.138762
Saving on PID 2678
Model saved
Model saved
INFO:__main__:After 100 records, 1-step altMAPE=82.138762
Saving on PID 2678
Model saved
Back to PID 2671
```

All of the checkpoints are present, and there are no exceptions.

Are there any additional details you can offer that might help in replicating the problem?  Perhaps print out the object id (i.e. `id(model)`) and pid at creation, and again at save and post the output + exception?

**Comment by JonnoFTW** [comment]
Okay I figured it out, pymongo was returning unicode objects for strings, this was used as the name of the encoder. The serialisation library didn't like this and threw the error (I probably should have paid more attention). All I had to do was make the intersection names into a string and it all worked, saving/inferring from a child process.
