### ISSUE TITLE
Ubuntu 14.04 LTS build fail after commit 623 on September 26, 2015

### ISSUE THREAD

**Issue by ppuskari** [numenta/nupic#2642]
> What did you do? (steps to reproduce)
Success compile and build of the full NuPic system  core and nupic  with the 623 commit on September 26, 2015

Update to any > commit version up to present and the build will fail with a a failure to locate the capnproto install path during the cmake step after building requirements
> What happened? (actual results)
Compilation and installation success with build 623 commit
Compilation failure during cmake process using any commit level after 623 on September 26, 2015

> What should have happened? (expected results)
Successful build
> Additional Information (operating system, python version, NuPIC commit SHA, etc.)
Will need to check what has changed in the cmakelists that causes the detection of an installed capnproto to not pass with these later builds.  It appears this was perhaps fixed in a previous bug fix however before this commit then maybe dropped somehow?

**Comment by breznak** [comment]
So this is a nupic.core issue, and not nupic, right?
If so, did you double check the readme? the cmake part is `../..` now, not
`../../src` ; or that was the catch for me! :)

**Comment by ppuskari** [comment]
Yes technically this would be nupic.core  correct.

The line used was this
cmake $NUPIC_CORE/src -DCMAKE_INSTALL_PREFIX=../release

So pointing directly at the /src location

$NUPIC_CORE was properly defined and the src folder present and normal privs/ownership

If I reset to current git state it will fail, but if I go back and reset git to the 623 state it works fine.  This holds true on this build->pass build->fail setup as well as redeploying a new vm and doing build->fail (current) build->pass (623)

**Comment by breznak** [comment]
Looks like I said, you don't follow the recent readme:

cmake $NUPIC_CORE -DCMAKE_INSTALL_PREFIX=../release

This change is confusing :)

**Comment by ppuskari** [comment]
Okay looks like that is certainly the case.   It's working as designed now.     Totally missed the non Src reference.  

We can close this bug

**Comment by rhyolight** [comment]
Sorry about that, I updated the installation videos with a note in YouTube.
