### ISSUE TITLE
ImportError: No module named nupic.swarming - One Hot Gym Prediction Tutorial

### ISSUE THREAD

**Issue by poshlf** [numenta/nupic#2659]
Hello,
finally I managed to install and test correctly nupic on Mac OS X 10.11.

Following the video tutorial One Hot Gym Prediction Tutorial, when I try for the first time to execute `swarm.py` I encounter one single error `ImportError: No module named nupic.swarming`.

After reading the issue topic "Problem on running swarm.py (#1503)" I think is good to notify that I had needed to export again the `NUPIC` environment variable (even if I done this correctly during the installation process) and I had needed to install mysql through the installation of MAMP (even this, after running the command `mysql` in terminal I'm facing `mysql command not found`).

Moreover I start from scratch the tutorial from a sub-subfolder of the nupic folder that I create for the purpose.

![schermata 2015-10-09 alle 19 26 47](https://cloud.githubusercontent.com/assets/15036808/10400888/d45cd45c-6ebb-11e5-9e2c-c0409597a884.png)

**Comment by rhyolight** [comment]
You installed from binary using `pip install nupic`, right? That error makes it seem to me like your installation did not go well. Please try this:

    python -c 'import pkg_resources;n=pkg_resources.get_distribution("nupic");b=pkg_resources.get_distribution("nupic.bindings");print n.project_name, n.version;print b.project_name, b.version'

And paste what it returns.

**Comment by poshlf** [comment]
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 350, in get_distribution
    if isinstance(dist,Requirement): dist = get_provider(dist)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 229, in get_provider
    return working_set.find(moduleOrReq) or require(str(moduleOrReq))[0]
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 673, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 576, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: nupic

**Comment by rhyolight** [comment]
There must've been a problem installing. Can you go to [gitter](https://gitter.im/numenta/public?utm_source=share-link&utm_medium=link&utm_campaign=share-link) so we can debug this?

**Comment by poshlf** [comment]
Yes just a second. However, I managed to install and run the test without errors and I even successfully executed the example that you have executed in the installation video.

**Comment by rhyolight** [comment]
I have a feeling those only worked because maybe you were in the source
code and python imported the actual source instead of from binary. This
could be a simple issue with your python path and where nupic got
installed.

---------
Matt Taylor
OS Community Flag-Bearer
Numenta

**Comment by poshlf** [comment]
Pyton was pre-installed. What I have installed was python pip as sudo. As regard nupic I installed it in the user folder not in te system.

**Comment by rhyolight** [comment]
I'm not sure exactly what the problem was, but it did not seem like nupic was properly installed on @poshlf 's system. We went through the installation process again and it seemed to work this time. @poshlf is currently working on getting mysql installed properly.

**Comment by aoman89757** [comment]
@rhyolight  I got the same problem with this swarm.py file and I have tried what you said to display the nupic version, this was what I got:

fengtaiadeMacBook-Pro:nupic fengtaie$ python
Python 2.7.10 (default, Oct 23 2015, 18:17:08) 
[GCC 4.2.1 Compatible Apple LLVM 7.0.0 (clang-700.0.59.5)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import nupic
>>> quit()
fengtaiadeMacBook-Pro:nupic fengtaie$ cd 
fengtaiadeMacBook-Pro:nupic fengtaie$ cd /Users/fengtaie/Documents/numenta/nupic/examples/opf/clients/hotgym/prediction/one_gym ;
fengtaiadeMacBook-Pro:one_gym fengtaie$ ./swarm.py 
Traceback (most recent call last):
  File "./swarm.py", line 33, in <module>
    from nupic.swarming import permutations_runner
ImportError: No module named swarming
fengtaiadeMacBook-Pro:one_gym fengtaie$ python -c 'import pkg_resources;n=pkg_resources.get_distribution("nupic");b=pkg_resources.get_distribution("nupic.bindings");print n.project_name, n.version;print b.project_name, b.version'
nupic 0.3.6.dev0
nupic.bindings 0.2.2
fengtaiadeMacBook-Pro:one_gym fengtaie$

**Comment by rcrowder** [comment]
@aoman89757 All this can get quite confusing on OSX :( Particularly with Apple moving to CLang in a certain 2.7 sub-version. The nupic.bindings and nupic have a certain ordering and linking. With Pip uninstall leaving various files and directories in different places, and it's caching adds other issues. You may have more success with uninstalling nupic and nupic.bindings, then reinstalling both. Only trying to uninstall and reinstall just nupic may be a cause for this Import error. Watch out for dreaded  'Requirements already satisfied' with nupic.
