### ISSUE TITLE
Failure to update to 0.3.5 in OSX

### ISSUE THREAD

**Issue by wuxianliang** [numenta/nupic#2665]
When I update nupic to 0.3.5
```shell
pip install --upgrade nupic
```
an error occurs
```shell
Collecting nupic.bindings==0.2.2 (from nupic)
  Could not find a version that satisfies the requirement nupic.bindings==0.2.2 (from nupic) (from versions: )
No matching distribution found for nupic.bindings==0.2.2 (from nupic)
```

**Comment by rhyolight** [comment]
Try this:

    pip uninstall nupic -y
    pip uninstall nupic.bindings -y

Run those two commands a few times, then try reinstalling from scratch:

    pip install nupic --user

Are you sure that your previous installation was working properly? I suspect this may be a symptom of #2603.

**Comment by wuxianliang** [comment]
I have installed 0.3.3 correctly, but after that I installed anaconda for numba, during that installing, anaconda installed a new python. Maybe that causes problem. 
Now when I uninstall 0.3.3, it is reported that I did not install nupic, but the files are there. Wired. I will try to remove the files,

**Comment by wuxianliang** [comment]
Thank you for response. When I finish installing, I would close this issue.

**Comment by wuxianliang** [comment]
I just uninstall anaconda, then everything works fine.

**Comment by rhyolight** [comment]
Ok, thank you for the update. I haven't figured out exactly how NuPIC plays with Anaconda yet. We are using Anaconda on CentOS boxes in our internal builds and it works fine, but python on OS X is a mess all around.
