### ISSUE TITLE
Swarm directly over SDRs

### ISSUE THREAD

**Issue by RDaneelOlivav** [numenta/nupic#2675]
Does someone know if there is a way of swarming over data in SDR format? Or it has to be one of the swarming types accepted?
Is there a way of inputing to the swarm directly these SDR?

**Comment by breznak** [comment]
Can you explain better what you're trying to do?

**Comment by RDaneelOlivav** [comment]
Well, I'm trying to analise FFT data from two channels of audio, which is an array of floats basically. Because swarming doesnt allow as input lists ( I've tried it and it doesnt support it ) . I encoded that data to have it in SDR so that we have its properties and I can use it in temporal pooling and so on. But To swarm over that data, I have to convert arrays such as [0,1,0,1,0,0] into a type accepted by swarming , which basicaly leaves me with strings if I want to mantain its structure and form ( "010100" ). 
But I thin is really ineficient to convert it to string and after internally swarming will encode it again.
So thats my question: is it possible to pass the swaming an SDR encoding directly?

**Comment by breznak** [comment]
A couple of approaches you could try...

On Wed, Oct 14, 2015 at 3:10 PM, RDaneelOlivav <notifications@github.com>
wrote:

> Well, I'm trying to analise FFT data from two channels of audio, which is
> an array of floats basically. Because swarming doesnt allow as input lists
> ( I've tried it and it doesnt support it ) .
>
Can you work with the arrays of floats? Make a MultiEncoder (a group of
encoders, insude of it
AdaptiveScalar/Scalar/RandomDistributedScalar-Encoders) and work with that?


> I encoded that data to have it in SDR so that we have its properties and I
> can use it in temporal pooling and so on.
>
Are you sure you've created the SDR correctly? (Does it have all the
properties is in HTM theory?)

> But To swarm over that data,
>
Do you really need to swarm? Swarming is a parameter optimization, but
(theoretically) HTM should work well enough with the default params, so
this might not be needed.  If you need to run a HTM model instead, it is
possible to create SP/TP/TM,.. manually and feed directly to that.


> I have to convert arrays such as [0,1,0,1,0,0] into a type accepted by
> swarming , which basicaly leaves me with strings if I want to mantain its
> structure and form ( "010100" ).
> But I thin is really ineficient to convert it to string and after
> internally swarming will encode it again.
> So thats my question: is it possible to pass the swaming an SDR encoding
> directly?
>
Also, take a look at (Sparse)PassThroughEncoder(s), they should do what you
need, exactly.

Cheers,

**Comment by RDaneelOlivav** [comment]
>Can you work with the arrays of floats? Make a MultiEncoder (a group of
encoders, insude of it
AdaptiveScalar/Scalar/RandomDistributedScalar-Encoders) and work with that?

I used multiencoder for the encoding actually ;). Thats how I get all this ecnoded ;).

>Are you sure you've created the SDR correctly? (Does it have all the
properties is in HTM theory?)

I hope so, do you have a link to any property definition that is basic? I've read the basics for HTM
but if you have material from which to base upon that you reccomend, the better ;)

>Do you really need to swarm? Swarming is a parameter optimization, but
(theoretically) HTM should work well enough with the default params, so
this might not be needed.  If you need to run a HTM model instead, it is
possible to create SP/TP/TM,.. manually and feed directly to that.

Can I use the swarming predicting without swarming first to get the model?
How? And anyway I have to feed it data which cant be arrays of floats can it?
Useing the SP/TP/TM was an option, but I thought that developing my algorithm for swaming over data made it usefull for any kind of data, doesnt it? Without having to restructure with every different data input type.

>Also, take a look at (Sparse)PassThroughEncoder(s), they should do what you
need, exactly.

Audiostream, is more or les what I've been doing....Strange hahaha. But is seems only for MAC-OS? And with the outputs how could I for example recognase voices in some way? How?

**Comment by RDaneelOlivav** [comment]
And another question: Swarming with string conversions of the SDR encoding isnt a great solution isn't it?
Eg: [1,0,1,0,0] -->"10100"
Will it work?

**Comment by rhyolight** [comment]
No, I would not do that. There would be an extremely large number of category strings. Strings should be used only if there are a limited number of categories. 

@oxtopus This issue might be informative to your hypersearch work.

**Comment by RDaneelOlivav** [comment]
But if they were lets say, huge floats wouldnt it be the same? The thing here is that the size of the data is very big and in someway it has to be fed here. And anyway I'm seeing that swarming over this data wont give me high level concepts and predictions such as entonation.
And this takes me to AudioStream, how to you do it to be able to predict a certain speech patern or another? @rhyolight We could maybe move this discusion to a new one to clear up how audiostream_tp.py works in depth, if its possible.

**Comment by rhyolight** [comment]
@RDaneelOlivav I re-read this thread today, and I have some further input.

A big part of what swarming helps do is figure out the optimal way to encode input data into SDRs in the first place. The only benefit you would get from having a swarming process that accepts raw SDRs is that you would be able to help identify the best global algorithm parameters for the spatial pooler and temporal pooler. 

I think trying to swarm over SDR input is not possible as swarming works today, so I'm going to close this issue.

Floats are different, because they are a vector. You can compare them and see how close one is to another. For string categories, we don't do that. The words "car" and "cat" have entirely different meanings even though the letters used to represent them are very similar.

I am not familiar with the AudioStream example, but I have done something similar with https://github.com/nupic-community/nupic.critic. Using NuPIC and HTM for audio analysis is a hot topic right now, with lots of open questions and experimentation. So there are no real established answers. We are all still prototyping. See also: https://github.com/nupic-community/nupic.audio
