### ISSUE TITLE
Always same energy_consumption and predicted value

### ISSUE THREAD

**Issue by enricgui** [numenta/nupic#2680]
I am developing an application which is using at this stage same model_params and input data as hot_gym tutorial, but working from a database source instead of files.

The problem is that I am always getting the same value for prediction as passed as consumption energy.

I already checked out that I am providing proper datetime and float values. Model is created, saved and loaded again apparently properly since its running with no errors.

Any idea for this newbie?

Thanks in advance.

NOTE: example of output [consumption, prediction, anomalyScore]:
```
[21.2, 21.2, None]
[16.4, 16.4, None]
[4.7, 4.7, None] ----> this one is supposed to predict 16.4 in pure hot_gym tutorial
[4.7, 4.7, None]
[4.6, 4.6, None]
[23.5, 23.5, None]
[47.5, 47.5, None]
[45.4, 45.4, None]
[46.1, 46.1, None]
[41.5, 41.5, None]
```

NOTE: here is partial code
```python
        metricsManager = MetricsManager(_METRIC_SPECS, model.getFieldInfo(),
                                  model.getInferenceType())
        stringdate = "%s" % row["time"]
        timestamp = datetime.datetime.strptime(stringdate, "%Y-%m-%d %H:%M:%S")
        consumption = float(row["value"])
        result = model.run({
            "timestamp": timestamp,
            "kw_energy_consumption": consumption
        })
        result.metrics = metricsManager.update(result)
        prediction = result.inferences["multiStepBestPredictions"][1]
        anomalyScore = result.inferences["anomalyScore"]
```

**Comment by rhyolight** [comment]
It would help if your code was available for me to review. 

> The problem is that I am always getting the same value for prediction as passed as consumption energy.

This will happen generally when NuPIC doesn't have enough data to make a decent prediction. How many rows of data are you sending in?

> I already checked out that I am providing proper datetime and float values.

Can you show a sample of your data? Or better yet the code where you are feeding in new rows to the model? (I assume you are using the OPF if you are following along with hotgym.)

**Comment by enricgui** [comment]
just added output and partial code.

**Comment by enricgui** [comment]
Extended code for your consideration.

def unitprocessorrunning(row):
    id = row["id"]
    status = row["status"]
    L1 = row["L1"]
    L2 = row["L2"]
    L3 = row["L3"]
    L4 = row["L4"]
    L5 = row["L5"]
    L6 = row["L6"]
    currentime = row["currenttime"]
    livetime = row["livetime"]
    params = row["params"]
    dump = row["dump"]
    mode = row["mode"]
    model = createModel(getModelParamsFromName(params))
    shutil.copytree(os.getcwd()+"/"+dump, "/home/enric/Documents/TechnoCore/Ummon/Demo/tmpdata")
    model.load("/home/enric/Documents/TechnoCore/Ummon/Demo/tmpdata")
    model.enableInference({"predictedField": "kw_energy_consumption"})

    # Process pending input data
    connection = pymysql.connect(host = 'LOCALHOST',user='root',passwd='',db='UMMON',charset='utf8mb4',cursorclass=pymysql.cursors.DictCursor)
    cur = connection.cursor()
    query = "SELECT count(*) as num, id, time, value FROM INPUT_DATA WHERE id=%s" % id
    cur.execute(query)
    row = cur.fetchone()
    cur.close()
    connection.close()
    if row["num"]>0:
        connection = pymysql.connect(host = 'LOCALHOST',user='root',passwd='',db='UMMON',charset='utf8mb4',cursorclass=pymysql.cursors.DictCursor)
        cur = connection.cursor()
        query = "UPDATE UNITS SET currenttime=CONVERT('%s', DATETIME) WHERE id=%s" % (row["time"], row["id"])
        cur.execute(query)
        if row["time"] > livetime:
            query = "UPDATE UNITS SET mode='LIVE' WHERE id=%s" % id
            cur.execute(query)
            mode = "LIVE"
        else:
            query = "UPDATE UNITS SET mode='LEARNING' WHERE id=%s" % id
            cur.execute(query)
            mode = "LEARNING"

        # Feeding UNIT and processing results and set alert variable
        metricsManager = MetricsManager(_METRIC_SPECS, model.getFieldInfo(),
                                  model.getInferenceType())
        stringdate = "%s" % row["time"]
        timestamp = datetime.datetime.strptime(stringdate, "%Y-%m-%d %H:%M:%S")
        consumption = float(row["value"])
        result = model.run({
            "timestamp": timestamp,
            "kw_energy_consumption": consumption
        })
        result.metrics = metricsManager.update(result)
        prediction = result.inferences["multiStepBestPredictions"][1]
        anomalyScore = result.inferences["anomalyScore"]
        print "[%s, %s, %s, %s]" % (id, consumption, prediction, anomalyScore)

**Comment by rhyolight** [comment]
Please also paste your model_params?

**Comment by enricgui** [comment]
MODEL_PARAMS = \
{ 'aggregationInfo': { 'days': 0,
                       'fields': [],
                       'hours': 0,
                       'microseconds': 0,
                       'milliseconds': 0,
                       'minutes': 0,
                       'months': 0,
                       'seconds': 0,
                       'weeks': 0,
                       'years': 0},
  'model': 'CLA',
  'modelParams': { 'anomalyParams': { u'anomalyCacheRecords': None,
                                      u'autoDetectThreshold': None,
                                      u'autoDetectWaitRecords': None},
                   'clParams': { 'alpha': 0.012831921757908758,
                                 'clVerbosity': 0,
                                 'regionName': 'CLAClassifierRegion',
                                 'steps': '1'},
                   'inferenceType': 'TemporalMultiStep',
                   'sensorParams': { 'encoders': { '_classifierInput': { 'classifierOnly': True,
                                                                         'clipInput': True,
                                                                         'fieldname': 'kw_energy_consumption',
                                                                         'maxval': 53.0,
                                                                         'minval': 0.0,
                                                                         'n': 163,
                                                                         'name': '_classifierInput',
                                                                         'type': 'ScalarEncoder',
                                                                         'w': 21},
                                                   u'kw_energy_consumption': None,
                                                   u'timestamp_dayOfWeek': { 'dayOfWeek': ( 21,
                                                                                            6),
                                                                             'fieldname': 'timestamp',
                                                                             'name': 'timestamp',
                                                                             'type': 'DateEncoder'},
                                                   u'timestamp_timeOfDay': { 'fieldname': 'timestamp',
                                                                             'name': 'timestamp',
                                                                             'timeOfDay': ( 21,
                                                                                            6.913498726470548),
                                                                             'type': 'DateEncoder'},
                                                   u'timestamp_weekend': None},
                                     'sensorAutoReset': None,
                                     'verbosity': 0},
                   'spEnable': True,
                   'spParams': { 'columnCount': 2048,
                                 'globalInhibition': 1,
                                 'inputWidth': 0,
                                 'maxBoost': 2.0,
                                 'numActiveColumnsPerInhArea': 40,
                                 'potentialPct': 0.8,
                                 'seed': 1956,
                                 'spVerbosity': 0,
                                 'spatialImp': 'cpp',
                                 'synPermActiveInc': 0.05,
                                 'synPermConnected': 0.1,
                                 'synPermInactiveDec': 0.05590771028726778},
                   'tpEnable': True,
                   'tpParams': { 'activationThreshold': 14,
                                 'cellsPerColumn': 32,
                                 'columnCount': 2048,
                                 'globalDecay': 0.0,
                                 'initialPerm': 0.21,
                                 'inputWidth': 2048,
                                 'maxAge': 0,
                                 'maxSegmentsPerCell': 128,
                                 'maxSynapsesPerSegment': 32,
                                 'minThreshold': 9,
                                 'newSynapseCount': 20,
                                 'outputType': 'normal',
                                 'pamLength': 1,
                                 'permanenceDec': 0.1,
                                 'permanenceInc': 0.1,
                                 'seed': 1960,
                                 'temporalImp': 'cpp',
                                 'verbosity': 0},
                   'trainSPNetOnlyIfRequested': False},
  'predictAheadTime': None,
  'version': 1}

**Comment by rhyolight** [comment]
Something strange is going on. In your model params, you have `'inferenceType': 'TemporalMultiStep'`. But in your code, you are extracting an anomaly score: `anomalyScore = result.inferences["anomalyScore"]`. This should not be available if your model is `TemporalMultiStep`. I'm not sure what is going on here. 

Can you just push your whole codebase up onto github or just zip it up so I can test it?

**Comment by enricgui** [comment]
Hi Matt,

I replicated successfully the issue on anomaly version of hot_gym, using DB as the source which is not the problem.
Later I introduced the model load and save functions inside the data processing loop (in my application I need to do it this way since I am running different models just 1 data row for several models and loop again, so I need to save and load).

Then the issue shows up. It seems like en each iteration the model is "reset" so I get always same prediction since it appears as the first data.

I reviewed the data model directory copying and model load and save and I cannot see anything wrong. Do I have to do anything else before/after loading de model or saving it?

Here you have the code portion of the modified hot_gym version:

#
def runDBThroughNupic(inputData, model, gymName, plot):
  connection = pymysql.connect(host = 'LOCALHOST',user='root',passwd='',db='UMMON',charset='utf8mb4',cursorclass=pymysql.cursors.DictCursor)
  cur = connection.cursor()
  query = "SELECT count(*) as num, id, time, value FROM INPUT_DATA"
  cur.execute(query)
  row = cur.fetchone()
  max = row["num"]

  shifter = InferenceShifter()
  if plot:
    output = nupic_output.NuPICPlotOutput([gymName])
  else:
    output = nupic_output.NuPICFileOutput([gymName])

  metricsManager = MetricsManager(_METRIC_SPECS, model.getFieldInfo(),
                                  model.getInferenceType())

  counter = 0

  query = "SELECT time, value FROM INPUT_DATA"
  cur.execute(query)
  while counter < max:
    model2 = createModel(getModelParamsFromName(gymName))
    shutil.copytree("/home/enric/Documents/TechnoCore/Ummon/Demo/data/1_dump", "/home/enric/Documents/TechnoCore/Ummon/Demo/tmpdata")
    shutil.copystat("/home/enric/Documents/TechnoCore/Ummon/Demo/data/1_dump", "/home/enric/Documents/TechnoCore/Ummon/Demo/tmpdata")
    model2.load("/home/enric/Documents/TechnoCore/Ummon/Demo/tmpdata")

    row = cur.fetchone()
    counter += 1
    timestring = "%s" % row["time"]
    valuestring = "%s" % row["value"]
    timestamp = datetime.datetime.strptime(timestring, "%Y-%m-%d %H:%M:%S")
    consumption = float(valuestring)
    result = model2.run({
      "timestamp": timestamp,
      "kw_energy_consumption": consumption
    })
    result.metrics = metricsManager.update(result)

    if counter % 100 == 0:
      print "Read %i lines..." % counter
      print ("After %i records, 1-step altMAPE=%f" % (counter,
              result.metrics["multiStepBestPredictions:multiStep:"
                             "errorMetric='altMAPE':steps=1:window=1000:"
                             "field=kw_energy_consumption"]))

    if plot:
      result = shifter.shift(result)

    prediction = result.inferences["multiStepBestPredictions"][1]
    anomalyScore = result.inferences["anomalyScore"]
    output.write([timestamp], [consumption], [prediction])
    print "[%s, %s, %s]" % (consumption, prediction, anomalyScore)

    model2.save("/home/enric/Documents/TechnoCore/Ummon/Demo/tmpdata")
    shutil.rmtree("/home/enric/Documents/TechnoCore/Ummon/Demo/data/1_dump")
    shutil.copytree("/home/enric/Documents/TechnoCore/Ummon/Demo/tmpdata", "/home/enric/Documents/TechnoCore/Ummon/Demo/data/1_dump")
    shutil.copystat("/home/enric/Documents/TechnoCore/Ummon/Demo/tmpdata", "/home/enric/Documents/TechnoCore/Ummon/Demo/data/1_dump")
    shutil.rmtree("/home/enric/Documents/TechnoCore/Ummon/Demo/tmpdata")


  cur.close()
  connection.close()
  output.close()

**Comment by enricgui** [comment]
problem is not in directory copying calls, since I removed them and work with same saving directory and keeps on the issue situation.

It doesn't work if you load and save inside data processing loop.

**Comment by enricgui** [comment]
Solved.

Instead of using model.load() method a tried ModelFactory.LoadFromCheckpoint() and works perfectly!!!

Thanks for your time.

**Comment by rhyolight** [comment]
Great!
