### ISSUE TITLE
Allow spParams, tpParams, and clParams to be specified in swarm description JSON

### ISSUE THREAD

**Issue by rhyolight** [numenta/nupic#2701]
Without this, there is no way to specify that the new Temporal Memory algorithm should be used in swarming, so all programmatic swarms using the JSON file as a starting point will be run using the old TP algorithm. 

To be clear, I want to be [able to do this](https://gist.github.com/rhyolight/8d54a664b3e30fa7aab1#file-swarm_desc-json-L58-L60), and see that the [generated `permutations.py` file](https://gist.github.com/rhyolight/d69c416ea95f2a0f702d#file-permutations-py-L72-L77) contains any params I specify there.

**Comment by chetan51** [comment]
:+1:

**Comment by andrewmalta13** [comment]
@scottpurdy asked me to hold off on this one until discussing with @rhyolight about it further.

**Comment by rhyolight** [comment]
Let's discuss @scottpurdy. As we move away from the TP implementation, I think users should be able to swarm with the new TM algorithm. That's really all this issue is about.

**Comment by rhyolight** [comment]
I just talked to @scottpurdy about this. Conclusion is that this functionality can be achieved using the `description.py` / `permutations.py` interface instead of this JSON one. And because we plan on someday scrapping the whole swarming process in favor of one that is not tied to the OPF, this work would be redundant anyway.
