### ISSUE TITLE
CLAClassifier compute() parameter documentation needs changing.

### ISSUE THREAD

**Issue by cogmission** [numenta/nupic#2719]
The parameter documentation describes the nature of the inputs to the compute method. The current description for ```patternNZ``` should be added to, to specify that when input is from a **temporal_memory.py**, it should be the indexes of **active cells**, not just say **active indexes**. 
This author payed a somewhat high price for the lack of disambiguation.

Please see this line: https://github.com/numenta/nupic/blob/master/src/nupic/algorithms/CLAClassifier.py#L342

**Comment by rhyolight** [comment]
@chetan51 ?

**Comment by chetan51** [comment]
:+1:

**Comment by rhyolight** [comment]
I meant are you interested in implementing this change?

---------
Matt Taylor
OS Community Flag-Bearer
Numenta

**Comment by chetan51** [comment]
Ah. Sure, will do.

**Comment by chetan51** [comment]
Hmm, so the thing is that the classifier doesn't care what the nature of the inputs are. It can be from TM active cells, predicted cells, or even SP active columns. So it doesn't make sense to specify "active cells" in the CLA Classifier documentation.

@cogmission Can you think of a better place to specify this?

**Comment by cogmission** [comment]
You missed the "when" in the request. It makes  since to say, "...when the input is from the temporal memory then it is the active cells ."

**Comment by chetan51** [comment]
Even then, it doesn't have to be. It could be the correctly predicted (and currently active) cells from the TM. The classifier doesn't care, so the documentation shouldn't be in the classifier. It should be somewhere that hooks up the TM to the classifier for a typical network configuration; I'm just not sure where that is.

**Comment by cogmission** [comment]
It doesn't matter if the Classifier cares or not. The documentation is for developers. ;-) I've seen perfect documentation that mentions the "interactions" of a class with another class. It is a pragmatic reality that of the inputs a Classifier could possibly receive, one of them is a TemporalMemory - and since the site of "misuse" will be upon submission of items to the Classifier, it makes since to put it there. Even if you find "the perfect place to put it", it still won't be as good because locating it where it will be definitely read is the best place for it - and developers will consult the prototype of the method to determine how to submit inputs to it - that would be the first place they look, not in the TM, and not in some search for an integration test that combines the two - the latter would be a pain to search for...

**Comment by cogmission** [comment]
Significance of code isolation... :-P

![unknown](https://cloud.githubusercontent.com/assets/2340086/10933598/3d4d67dc-829f-11e5-83a2-cc4ce76b2324.jpeg)

**Comment by cogmission** [comment]
I think we can't get around the fact that the CLAClassifier is a "tenant" in the construction of an HTM Network - that's its main purpose. In the Java world, Class documentation often has example usage idioms documented - I think this could be considered normal/expected practice and is a pragmatic yielding to the necessity of establishing a convention for algorithm collaboration. I think we should ask @scottpurdy too, he also is a zealot for software "purity". I know the tenet of separating concerns encourages unrelated classes keeping their functionality distinct, but I think we should have a NuPIC convention which offers needed interaction information - like this.

**Comment by scottpurdy** [comment]
> I think we should ask @scottpurdy too, he also is a zealot for software "purity". I know the tenet of separating concerns encourages unrelated classes keeping their functionality distinct, but I think we should have a NuPIC convention which offers needed interaction information - like this.

Are you putting words in my mouth again? :wink: I agree that it is useful to include comments on the primary integrations. In this case the TM and TM region should be explicit about how the different outputs should be used. The CLA Classifier can also be more explicit about what it expects when used with the TM since that is the primary usage.

**Comment by cogmission** [comment]
lol! - You think we can get Chetan to "sully" his hands with impure documentation? ;-P

**Comment by chetan51** [comment]
Alright, I concede :) If there is no clearer place to put this, I'll implement this change. But I agree, we should have integration examples and tests for this.
