### ISSUE TITLE
Python quit unexpectedly.

### ISSUE THREAD

**Issue by aoman89757** [numenta/nupic#2743]
Hi everyone,

I have installed NUPIC successfully, but when trying to import nupic and quit(), I got a prompt with "Python quit unexpectedly error" and the error information in the terminal just like this:

<img width="934" alt="screen shot 2015-11-07 at 19 18 16" src="https://cloud.githubusercontent.com/assets/11574197/11014910/d7c98998-8584-11e5-83ab-eadf18380fd8.png">

>>> import nupic
Segmentation fault: 11
fengtaiadeMacBook-Pro:nupic fengtaie$ python
Python 2.7.3 (v2.7.3:70274d53c1dd, Apr  9 2012, 20:52:43) 
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import nupic
>>> quit()
Segmentation fault: 11

Anyone can figure this out ?

**Comment by rcrowder** [comment]
@aoman89757 Hi, there are a variety of known issues with different Python version on OSX. For example, see this open issue https://github.com/numenta/nupic/issues/1813 The one thing that stands out is the age of the Python you are trying to use ```2.7.3```. I don't have a Mac to test this with, but you will likely need to update to a more recent 2.7 version, and/or building NuPIC from source.

**Comment by rhyolight** [comment]
Building from source usually fixes problems like this. See our wiki for a tutorial video on it.

**Comment by aoman89757** [comment]
@rhyolight In fact, I did install it from source

**Comment by aoman89757** [comment]
@rcrowder Yeah, I relinked a more recent Python version and rebuilt it, that worked!  Thanks :)

**Comment by rcrowder** [comment]
@aoman89757 Excellent, glad to see you got it working. Apple made some big changes with 2.7 sub-versions, which can break NuPIC's link to the core C++ bindings.

**Comment by adeze** [comment]
I had to build from source, but even that had problems afterwards. I think I somehow, by magic, resolved it with setting this in ~/.bash_profile  before you install the nupic.bindings:
```
export PYTHONPATH=`python -c 'import sys;print ":".join(sys.path)'`
```

you may need to also 
```
source ~/.bash_profile
```
I also have installed python 2.7.11 via homebrew AND from the python installer. 

(I'm not if this is the solution-- as i did a bunch of things-- but things work now but this solution broke my python 3.5 distribution -- i get the same window popup now if i try 
```
python3 -v
```
so thats a seperate issue
