### ISSUE TITLE
Coordinate encoder _orderForCoordinate produces different results on Windows to Linux

### ISSUE THREAD

**Issue by rcrowder** [numenta/nupic#2763]
In nupic/tests/unit/nupic/encoders/coordinate_test.py -

In the testEncodeSaturateArea test, with side-by-side single step comparison on Ubuntu and Windows, both generate all the same seed's to send into Random. Based on the 25 coordinates when looping through them in encoder.encodeIntoArray I.e. the encoder _hashCoordinate produces the same MD5 hash codes for the 25 coordinates on Windows and Linux.

In nupic/src/nupic/encoders/coordinate.py -

The first coordinate [-2, -2] produces the same return value from _orderForCoordinate (the rng.getReal64() call). But the second and subsequent calls into _orderForCoordinate returns different values on Windows to Linux. Eventually coming to the assert fail on Windows (0.791666r == 8.0 seen here https://ci.appveyor.com/project/numenta-ci/nupic/branch/master).

I've started looking into the _state changes in the C++ RandomImpl side. But this may just be related to long vs int differences. So could be within SWIG.

The same assert fail can be recreated on Linux if the _hashCoordinate uses (2 ** 32) instead of modding with (2 ** 64). BUT that may be a confusing recreation. So beware!

**Comment by scottpurdy** [comment]
@chetan51 - Do you ahve some time that you can look into this?

**Comment by chetan51** [comment]
@scottpurdy Sure. What's the best way for me to test on a Windows machine?

**Comment by scottpurdy** [comment]
Hmm looking into this a bit more. This is a possible issue:
https://mail.python.org/pipermail/python-list/2015-March/686924.html

So we should add a unit test for `_hashCoordinate`. Additionally, it doesn't look like `Random.getUInt64` is very well tested: https://github.com/numenta/nupic.core/blob/master/src/test/unit/utils/RandomTest.cpp

So we can add some tests there for specific results given a specific seed. We should make sure that the result requires >32 bits for at least one test case.

**Comment by scottpurdy** [comment]
I am going to take a crack at these tests right now so no need to look at this for the moment @chetan51

**Comment by chetan51** [comment]
Okay sure.

**Comment by scottpurdy** [comment]
@chetan51 - I'm running into some issues running the tests that I think must be from when I upgraded to El Capitan. If you have a chance you could add them. Otherwise I'll do so when I get my environment sorted out.

**Comment by scottpurdy** [comment]
Got it sorted out... looking now.

**Comment by rcrowder** [comment]
@scottpurdy Thanks for looking further. I ran out of time last night cleaning Windows and Linux to ultimately get C++ Random to spit out debug info. Will continue here today.
On Windows and Linux the hashing works OK in the coordinate encoder (produces matching long integer seed's for Random). But as you've seen can be problematic if hashing text files (regardless of encoding, UTF-8/16 etc.). The difference with text files being the alternative ```\r\n``` and ```\n``` line endings on different OS. Python does a really good job shielding users from line ending and path separator differences internally.
Valuable to have some more Random checks, that include 32 and 64 bit version.

**Comment by scottpurdy** [comment]
Random tests seem to uncover an issue:
https://ci.appveyor.com/project/numenta-ci/nupic-core/build/0.3.0.144#L1190

In PR numenta/nupic.core#695

**Comment by rcrowder** [comment]
@scottpurdy This is fixed by the lldiv change, outlined in https://github.com/numenta/nupic.core/pull/695#issuecomment-159011687

**Comment by rcrowder** [comment]
And the testEncodeIntoArray Windows failure in the Geospatial Coordinate Encoder test

**Comment by rcrowder** [comment]
Fixed by https://github.com/numenta/nupic.core/pull/695
