### ISSUE TITLE
Some questions about the swarm_description.py file

### ISSUE THREAD

**Issue by aoman89757** [numenta/nupic#2792]
Hello,

I'm trying to imitate the one_gym prediction programme to figure out how it works. I have got one new dataset like this: 
<img width="502" alt="screen shot 2015-12-05 at 22 29 00" src="https://cloud.githubusercontent.com/assets/11574197/11608284/d2dc4016-9b9f-11e5-8181-1b44d655d41c.png">

So I modified the swarm_description.py 
<img width="942" alt="screen shot 2015-12-05 at 22 32 03" src="https://cloud.githubusercontent.com/assets/11574197/11608288/0a079e00-9ba0-11e5-9b16-fa45aa26df95.png">

Then I tried to run the swarm.py file, but I have gotten the problem like this:
<img width="875" alt="screen shot 2015-12-05 at 22 34 43" src="https://cloud.githubusercontent.com/assets/11574197/11608301/7008be32-9ba0-11e5-9e2a-0038fcfa9b60.png">

I added the "T," line in the dateset
<img width="356" alt="screen shot 2015-12-05 at 22 36 23" src="https://cloud.githubusercontent.com/assets/11574197/11608308/aa9d7eac-9ba0-11e5-90f6-fb75c8505869.png">

I got this exception:
<img width="876" alt="screen shot 2015-12-05 at 22 37 16" src="https://cloud.githubusercontent.com/assets/11574197/11608311/c6a9d140-9ba0-11e5-983b-85a74e4eb6ba.png">

Someone can figure this out?

**Comment by rcrowder** [comment]
@aoman89757 The header for a CSV requires three lines before the data rows. You can see what is required in the second and third lines here https://github.com/numenta/nupic/wiki/NuPIC-Input-Data-File-Format

**Comment by rhyolight** [comment]
Right, your first 3 lines should look like this:

```csv
Ask,Bid,Change,Last,TradePriceOnly,Volume
datetime,float,float,float,float,float
T,,,,,
```

**Comment by rcrowder** [comment]
Just got back from some errands. @rhyolight was going to ping you to say, this looks like a good candidate to add to the Wiki FAQ. With potential to raise the profile of the FAQ. Unsure if you have alist of known problems like this. OR potential to raise another issue to embellish the message output when CSV header parsing encounters a problem?

**Comment by rhyolight** [comment]
@rcrowder I'm not crazy about our FAQ on the wiki. It starts at https://github.com/numenta/nupic/wiki/FAQ and leads to https://github.com/numenta/nupic/wiki/NuPIC-Usage-FAQ where I think this should go. Something like "Why is my swarm not working?" or is that too generic?

**Comment by rcrowder** [comment]
Ah! I scanned an expanded Wiki Page index (right hand side) and found the FAQ entry, but didn't realize the headings pointed to other FAQs. My comment only refers to seeing the one wiki/FAQ page. In light of seeing the other FAQs a generic heading seems fine. Certain keywords from the error message, such as FieldMetaType, can be used to link error to possible fixes.

**Comment by aoman89757** [comment]
Aha, thanks :) @rcrowder, @rhyolight
