### ISSUE TITLE
Wiki search box

### ISSUE THREAD

**Issue by rcrowder** [numenta/nupic#2793]
Github's "This repository" search box doesn't include Wiki pages. It would be useful to add into the Wiki a dedicated page content search. For example; https://github.com/linyows/github-wiki-search

**Comment by rhyolight** [comment]
I'm already using that Chrome extension. But it cannot be added direction to the Github Wiki. It can only be installed on the client at the discretion of the browser.

**Comment by rcrowder** [comment]
Thanks, I've digged further and seen the issues :( So installation of a browser extension, or use of something like Gollum (and/or Grip) with a clone of the wiki, looks like the only answer. Unless GH add it themselves, eventually.

**Comment by rcrowder** [comment]
Or just a git clone, and git grep https://coderwall.com/p/i5heiq/searching-github-wikis

**Comment by rhyolight** [comment]
By the way, <http://numenta.org/search/> also searches the wiki.
