### ISSUE TITLE
How to set the custom configuration(username&password) of MYSQL for running swarm

### ISSUE THREAD

**Issue by aoman89757** [numenta/nupic#2794]
Hi,
I have installed successfully the nupic from the binary file on our server(not from the source code), and the swarm process need the mysql (which already installed with the custom username and password)to fire up. How can I set the custom configuration(username&password)of mysql for running swarm?

I have tried the nupic-default.xml and nupic-site.xml, but it didn't work for me :(

Thanks

**Comment by rhyolight** [comment]
@aoman89757 You saw this, right? https://github.com/numenta/nupic/wiki/MySQL-Settings

**Comment by rhyolight** [comment]
Remember you need to set a `$NUPIC` environment variable and place the config file relative to that location...

**Comment by aoman89757** [comment]
@rhyolight I did follow this tutorial, but the result is always the same:
Retrieved the following settings from NuPIC configuration:
    host   :     localhost
    port   :     3306
    user   :     root
    passwd :

**Comment by rhyolight** [comment]
What happens when you run the following command?

    cat ${NUPIC}/config/default/nupic-default.xml

**Comment by aoman89757** [comment]
I did create that file, but I got the error test result(besides, the directory of the nupic-site.xml file is different $NUPIC/src/nupic/support/nupic-default.xml ? ${NUPIC}/config/default/nupic-site.xml? ):




This script will validate that your MySQL is setup correctly for NuPIC.
MySQL is required for NuPIC swarming. The settings are defined in a 
configuration file found in $NUPIC/src/nupic/support/nupic-default.xml 
Out of the box those settings contain MySQL's default access 
credentials.

The nupic-default.xml can be duplicated to define user specific changes, 
calling the copied file $NUPIC/src/nupic/support/nupic-site.xml
Refer to the nupic-default.xml for additional instructions.

Defaults: localhost, 3306, root, no password

Retrieved the following settings from NuPIC configuration:
    host   :     localhost
    port   :     3306
    user   :     root
    passwd :     

Traceback (most recent call last):
  File "test_db.py", line 54, in <module>
    raise RuntimeError("Couldn't connect to the database."
RuntimeError: Couldn't connect to the database. Please ensure you have MySQL
 installed, running, and accessible using the NuPIC configuration settings.

**Comment by rhyolight** [comment]
Ok I think I got the path wrong. Wherever the `nupic-default.xml` file is, you should put your own `nupic-site.xml` file in the same directory. Copy the exact format of `nupic-default.xml` and replace the MySQL authentication values. 

Are you certain that MySQL is actually running?
