### ISSUE TITLE
testGetRegion unit test relies on pycapnp

### ISSUE THREAD

**Issue by rcrowder** [numenta/nupic#2812]
PR https://github.com/numenta/nupic/pull/2781 introduced a new network unit test that relies on pycapnp, so fails on OS platforms that don't have that package.

**Comment by rcrowder** [comment]
Fixed within https://github.com/numenta/nupic.core/pull/741 The nupic.core TestNode.py file had the capnp import guarded instead of changing NuPIC Python code cc @chetan51

**Comment by chetan51** [comment]
Thanks @rcrowder
