### ISSUE TITLE
KNN classifier overlap scores

### ISSUE THREAD

**Issue by SaganBolliger** [numenta/nupic#2817]
From https://jira.numenta.com/browse/RES-142:

The KNNClassifier output data is the inferred category probabilities. The HTMNetwork model uses this for querying by first assigning each data sample its own category, and then the category probabilities are relative distances to each data sample. This is hacky, and it would be much more useful (in Imbu and otherwise) to get the actual distance (overlap) values from the KNNClassifier region.
This will also be necessary for matching HTM subsequences in IMBU-28.
See the imbu runner for an example of querying the HTMNetwork model.

**Comment by BoltzmannBrain** [comment]
@SaganBolliger out of jira context this issue makes no sense. The nupic issue here is "get the actual distance (overlap) values from the KNNClassifier as a standard output of the region."

**Comment by SaganBolliger** [comment]
No longer needed.
