### ISSUE TITLE
AppVeyor doesn't require twine upload. It only relies on a win_amd64 nupic.bindings wheel from PyPi.

### ISSUE THREAD

**Issue by rcrowder** [numenta/nupic#2877]
The 'any' wheel produced by Travis git tagged release builds can be used on Windows. As long as nupic.core AppVeyor git tagged release successfully builds and uploads to PyPi the appropriate nupic.bindings Windows wheel (a `...win_amd64.whl` file).

In `appveyor.yml` the `on_success` handler can be remove. The `python setup.py bdist_wheel` can also be changed to a `python setup.py install`.

**Comment by rhyolight** [comment]
Aha, good catch :+1:
