### ISSUE TITLE
NuPIC Readme and Wiki needs to describe Windows PyPi installation.

### ISSUE THREAD

**Issue by rcrowder** [numenta/nupic#2878]
With a working Windows nupic.bindings file on PyPi (0.2.7 - https://pypi.python.org/pypi/nupic.bindings), all documentation relating to Windows installs and building needs updating to take that into account.

**Comment by rcrowder** [comment]
@rhyolight No obvious changes are required to the main README.md Just a tidy up of any Windows related Wiki info. And of course dealing with the `Import Error` issues with nupic.bindings, that now exists across all supported platforms.

**Comment by rhyolight** [comment]
@rcrowder Close this issue and #1786?

**Comment by rcrowder** [comment]
@rhyolight Yes and yes.
