### ISSUE TITLE
Windows build failure

### ISSUE THREAD

**Issue by rhyolight** [numenta/nupic#2912]
Latest `nupic.core` builds are currently failing in NuPIC. 

See https://ci.appveyor.com/project/numenta-ci/nupic/build/0.1.0.749

**Comment by rcrowder** [comment]
@rhyolight Fix has been merged in https://github.com/numenta/nupic/pull/2905

**Comment by rhyolight** [comment]
@rcrowder brilliant, thanks

**Comment by rcrowder** [comment]
A potential fix was added recently in https://github.com/jswhit/pyproj/commit/68ee8dc7ba8aa61ab01c5147350aaf1e1d9bf3be
