### ISSUE TITLE
Nupic.bindings==0.2.8.dev0 Unavailable

### ISSUE THREAD

**Issue by abrahamrhoffman** [numenta/nupic#2932]
Ubuntu 14.04.3 (as root)
- git clone https://github.com/numenta/nupic.core.git
- git clone https://github.com/numenta/nupic.git
- (make evironment variable)
- cd $NUPIC
- pwd -> /root/nupic
- python setup.py install

Error:
Reading https://pypi.python.org/simple/nupic.bindings/
No local packages or download links found for nupic.bindings==0.2.8.dev0
error: Could not find suitable distribution for Requirement.parse('nupic.bindings==0.2.8.dev0')

Issue:
** https://pypi.python.org/simple/nupic.bindings/ does not contain the 0.2.8.dev0 .egg [or] .whl **

**Comment by passiweinberger** [comment]
Same Issue on OSX el Capitan

**Comment by rhyolight** [comment]
I would expect this to fail in exactly this manner. If you attempt to build nupic from local source code, it is also expected that you will build nupic.core from local source code as well. I just wrote a mailing list post about this you might find useful. I suggest you try to [install from binary first](https://www.youtube.com/watch?v=1fIpgXHXAZA&list=PL3yXMgtrZmDoVW97tHIncED4H-ALcp9oJ&index=3). If that doesn't work, [try to compile](https://www.youtube.com/watch?v=BrnPQJKpcWo&list=PL3yXMgtrZmDoVW97tHIncED4H-ALcp9oJ&index=4). 

If you have any more problems, I encourage you to join our [mailing list](http://lists.numenta.org/mailman/listinfo/nupic_lists.numenta.org) and ask questions there.

**Comment by abrahamrhoffman** [comment]
Thanks. I followed instructions as provided and it worked as expected on Ubuntu 14.04.3.

### This is the install procedures for installing and setting up Nupic on Ubuntu 14.04.3 w/Python 2.7 ###

# Let's start by cleaning up apt #

apt-get clean
apt-get -y update
apt-get -y autoremove

# Now let's install Python Development Dependencies #

apt-get -y install python2.7-dev
apt-get -y install python-dev
apt-get -y autoremove

# Install the latest PIP #

apt-get -y install pip

# Install Python Wheel #

pip install wheel

# Install NumPy #

pip install numpy

# Install Nupic wheel # 

pip install https://s3-us-west-2.amazonaws.com/artifacts.numenta.org/numenta/nupic.core/releases/nupic.bindings/nupic.bindings-0.2.7-cp27-none-linux_x86_64.whl

# Finally Install Nupic #

pip install nupic

**Comment by rhyolight** [comment]
Outstanding! Thanks for your patience.
