### ISSUE TITLE
AttributeError: 'TPShim' object has no attribute 'topDownCompute'

### ISSUE THREAD

**Issue by rhyolight** [numenta/nupic#2935]
I got this error by switching from `'temporalImp': 'cpp'` to `'temporalImp': 'tm_py'` in the model params of a model. The code worked before the change, but after the change I got this:

```
Traceback (most recent call last):
  File "./run.py", line 226, in <module>
    runModel(model, data, field, plot, options.log)
  File "./run.py", line 195, in runModel
    "value": value
  File "/Users/mtaylor/Library/Python/2.7/lib/python/site-packages/nupic/frameworks/opf/clamodel.py", line 386, in run
    self._tpCompute()
  File "/Users/mtaylor/Library/Python/2.7/lib/python/site-packages/nupic/frameworks/opf/clamodel.py", line 503, in _tpCompute
    tp.compute()
  File "/Users/mtaylor/nta/nupic/src/nupic/engine/__init__.py", line 446, in compute
    return self._region.compute()
  File "/Users/mtaylor/nta/nupic.core/bindings/py/nupic/bindings/engine_internal.py", line 1384, in compute
    return _engine_internal.Region_compute(self)
  File "/Users/mtaylor/nta/nupic/src/nupic/regions/TPRegion.py", line 480, in compute
    self._compute(inputs, outputs)
  File "/Users/mtaylor/nta/nupic/src/nupic/regions/TPRegion.py", line 534, in _compute
    outputs['topDownOut'][:] = self._tfdr.topDownCompute().copy()
AttributeError: 'TPShim' object has no attribute 'topDownCompute'
```

I am running tip of master of both core and nupic, compiled locally on my machine:

    nupic 0.3.7.dev0 (SHA 58c96d0f39b074e5c306c6863ae57345e47f2908)
    nupic.bindings 0.2.8.dev0 (SHA 621a1b7fb3d0ff4ff3d2358a782095350945c266)

This error is very easy to replicate in the `river-runner` demo app.

```
git clone git@github.com:nupic-community/river-runner.git
cd river-runner
```

Test that it works before switching temporal implementation:

    python run.py [--plot]

If not plotting, results are written to a CSV file.

Now edit [`model_params/anomaly_params.py`](https://github.com/nupic-community/river-runner/blob/master/model_params/anomaly_params.py#L86) and switch from `'temporalImp': 'cpp'` to `'temporalImp': 'tm_py'`.

Now when running, you should get the error pasted above.

**Comment by rhyolight** [comment]
@chetan51 Can you take an initial look at this and tell me if you see anything obvious? (cc @scottpurdy)

**Comment by rhyolight** [comment]
Strangely, this does not happen when I make the same change in the simple hotgym sample...

```diff
diff --git a/examples/opf/clients/hotgym/simple/model_params.py b/examples/opf/clients/hotgym/simple/model_params.py
index ec53684..46c4a1f 100644
--- a/examples/opf/clients/hotgym/simple/model_params.py
+++ b/examples/opf/clients/hotgym/simple/model_params.py
@@ -156,7 +156,7 @@ MODEL_PARAMS = {

             # Temporal Pooler implementation selector (see _getTPClass in
             # CLARegion.py).
-            'temporalImp': 'cpp',
+            'temporalImp': 'tm_py',

             # New Synapse formation count
             # NOTE: If None, use spNumActivePerInhArea
```

**Comment by chetan51** [comment]
@rhyolight I've seen this error before, it happens when `topDownMode` is true in `TPRegion` because `topDownCompute` isn't implemented in `TPShim`. I'll look into it further tomorrow.
