### ISSUE TITLE
py.test tests/unit crashes Python on El Capitan

### ISSUE THREAD

**Issue by YRG999** [numenta/nupic#2936]
Using OS X El Capitan
Version 10.11.3 Beta (15D13b)

I ran py.test tests/unit in the nupic directory and got the following:
============================= test session starts ==============================
platform darwin -- Python 2.7.11, pytest-2.8.5, py-1.4.31, pluggy-0.3.1
rootdir: /Users/toyves/GitHub/nupic, inifile: 
plugins: cov-1.6, xdist-1.8
collecting 6 itemsAbort trap: 6

After this, Python crashes. I could include a crash report if you like.

As for installing, I followed Matthew Taylor's Compiling NuPIC on OS X Yosemite (https://www.youtube.com/watch?v=sxb_Zrls7Zs) to install nupic.core before I knew you could easily install with pip. I had trouble installing capnp. The nupic.core install command (cmake $NUPIC_CORE -DCMAKE_INSTALL_PREFIX=../release -DPY_EXTENSIONS_DIR=$NUPIC_CORE/bindings/py/nupic/bindings) kept complaining "ImportError: No module named capnp".

I think I have a problem with Python as I had Enthought Canopy installed and it was using the Canopy version of Python, so I ended up uninstalling it, then installing Python using homebrew. Then I deleted directories based on the warnings from brew doctor until I got the message that my machine was ready to brew. Now, however, I'm getting messages that the /usr/local directory is not writeable.

I'd appreciate any help anyone can give me.

Thanks.

**Comment by rhyolight** [comment]
I'm sorry about your troubles @YRG999. But it's really hard to debug issues with custom installed python version on people's systems. I would not know where to start. We recommend OS X users always use the system python version, so if you can get back to that state it would be a starting point. There is some basic info [here](https://docs.python.org/2/using/mac.html). The way I remove homebrew python and use system python is by running this:

```
brew uninstall python
sudo easy_install pip
```

**Comment by YRG999** [comment]
Thanks for the tips. I'll work on fixing python on my system and try again.

**Comment by rhyolight** [comment]
Thanks and good luck. Please [email the list](http://lists.numenta.org/mailman/listinfo/nupic_lists.numenta.org) with questions.
