### ISSUE TITLE
Consider docs/ with relevant papers

### ISSUE THREAD

**Issue by breznak** [numenta/nupic#2943]
Even though the content is available and online, it's common that projects include some "background" literature - here the list is quite easy: the "HTM Whitepaper" and "NAB Anomaly Benchmark".

**Comment by breznak** [comment]
what d you think @rhyolight ?

**Comment by rhyolight** [comment]
Are you proposing adding this to the README?

**Comment by breznak** [comment]
Readme sounds like a good idea too. I was proposing a folder `docs/` with the PDFs in the repo.

**Comment by rhyolight** [comment]
We are about to post all of our papers with descriptions in one spot on numenta.com, that is where I would like to link. I'd rather not add PDFs to the git repo, that inflates the size of the checkout forever. But once our "papers" webpage is completed, I think it should be linked in the REAME. Here is a [sneak peek](http://numenta.com/papers/).

**Comment by breznak** [comment]
sounds good :+1:
