### ISSUE TITLE
Bump version to reflect api changes

### ISSUE THREAD

**Issue by oxtopus** [numenta/nupic#2958]
I recently ran into problems working on imbu in which some new code depended on some new APIs in KNNClassifier.py (see https://github.com/numenta/numenta-apps/pull/563), and also noticed that some APIs have been removed (see https://github.com/numenta/nupic/commit/837b5fbaef6585982fe3a735c765e8e5661234a8).

Since these are api-breaking changes, we should bump the version.

cc @rhyolight

**Comment by rhyolight** [comment]
Will do today.

**Comment by rhyolight** [comment]
Hey @numenta/nupic-reviewers! Be sure to let me know if any API-breaking changes are getting merged into master so I can bump the version immediately afterwards. 

@oxtopus I will make this a MINOR version bump, not a BUGFIX.

**Comment by rhyolight** [comment]
NuPIC 0.4.5
