### ISSUE TITLE
TM: Add accessor methods and update API to use lists of indices

### ISSUE THREAD

**Issue by chetan51** [numenta/nupic#2959]
For `temporal_memory.py`:

- Add accessor methods for `activeCells`, `predictiveCells`, `activeSegments`, `winnerCells`, `matchingSegments`, `matchingCells`. These should return a list of indices. Update all callers to use these methods instead of accessing the properties directly.
- Change `compute` method to take a list of indices (instead of a set), and update all callers.

**Comment by SaganBolliger** [comment]
It looks like the callers that will need to be updated are
- temporal_memory_monitor_mixin.py
- TP_shim.py
- hello_tm.py
- temporal_memory_test.py (this will likely require the most work)
