### ISSUE TITLE
AppVeyor should respect NUPIC_CORE_COMMITISH

### ISSUE THREAD

**Issue by subutai** [numenta/nupic#2965]
AppVeyor should use NUPIC_CORE_COMMITISH and switch to the appropriate SHA of nupic.core before running tests. Currently it does not seem to do that, which causes spurious test failures when nupic.core is ahead of nupic.

Please see #2952 for associated discussion.

**Comment by rhyolight** [comment]
@rcrowder Honestly, I have no clue how to do this, but I would like to try to fix it. Can you perhaps point me in the right direction? Hopefully I can try some trial and error through a remote branch.

**Comment by rcrowder** [comment]
@rhyolight I'm out of the country on business until Sunday night (GMT). Can help Mon/Tues.

**Comment by rcrowder** [comment]
@rhyolight In my mind this seems fairly straight forward to accomplish. Requiring only small changes to the two AppVeyor yaml files.
NuPIC currently relies on a nupic.bindings wheel file from PyPi to pip install and run against. The idea is to duplicate this bindings wheel, with a commit sha'd filename and upload to AWS on iterative builds of nupic.core Subsequently the nupic AppVeyor yaml can work out whether to pip install from PyPi (tagged releases), or from AWS (iterative builds).
I'll create a nupic.core issue to outline changes there, with this issue the one to sync to.

**Comment by rhyolight** [comment]
I'm in the process of setting up the nupic.core build on Atlassian Bamboo
at https://ci.numenta.com/browse/NUP-NUP. Maybe this should wait until
after? Any work we do on AppVeyor will be wasted soon.

---------
Matt Taylor
OS Community Flag-Bearer
Numenta

**Comment by rcrowder** [comment]
It can wait. I wasn't sure when you'd be turning off AV and Travis for Bamboo. The occurrence of issues caused by this is fairly infrequent, and obvious when they occur.

**Comment by rhyolight** [comment]
Ok. That being said, I still don't know exactly how long this is going to
take me. Among my other responsibilities, probably a couple weeks?

---------
Matt Taylor
OS Community Flag-Bearer
Numenta
