### ISSUE TITLE
install nupic failure, missing "nupic.bindings" [Ubuntu 15]

### ISSUE THREAD

**Issue by kleineLi** [numenta/nupic#2973]
Hi!
tell me, please, what is the problem? And how to fix it?
![121324](https://cloud.githubusercontent.com/assets/10851840/12535359/1611a488-c2a2-11e5-96e6-ceb5d2758220.png)

**Comment by rhyolight** [comment]
Hello @kleineLi, can you tell me are you running 32 bit linux?

**Comment by kleineLi** [comment]
No, i have 64 bit linux

**Comment by rhyolight** [comment]
Can you tell me exactly what version of Ubuntu you are using?

**Comment by kleineLi** [comment]
of course, sorry. Ubuntu 15.10

**Comment by kleineLi** [comment]
I tried to do that on Ubuntu 15.04, but nothing did not work, the same mistakes.

**Comment by rhyolight** [comment]
@kleineLi Ok, I have not done any testing with Ubuntu 15, so I'll need to get a new VM set up. I'll assign myself but I won't get to it until next week.

**Comment by kleineLi** [comment]
Ok, i'm waiting

**Comment by kleineLi** [comment]
and if ignore this warning, then appear following inconsistencies
![run_nupic_tests](https://cloud.githubusercontent.com/assets/10851840/12721140/453f9328-c90f-11e5-8fab-a922f841196b.png)

![my_run_nupic_tests](https://cloud.githubusercontent.com/assets/10851840/12721141/453fc208-c90f-11e5-8a65-23ca840dfaf4.png)

**Comment by rhyolight** [comment]
@kleineLi Setting up a VM today. But I don't understand what you are saying with those last two images. Can you elaborate?

**Comment by rhyolight** [comment]
I am having problems installing Ubuntu 15.10 on VirtualBox. I might need to try 15.04...

**Comment by kleineLi** [comment]
that I do not have a test file "run_nupic_test" as you

**Comment by rhyolight** [comment]
You have to actually `git clone` the repo, as described [here](https://youtu.be/1fIpgXHXAZA?t=8m27s). The test running is a part of the source code distribution, not the binary installation.

**Comment by rhyolight** [comment]
Did you just run `pip install nupic`? or did you follow the [README](https://github.com/numenta/nupic) and run `pip install https://s3-us-west-2.amazonaws.com/artifacts.numenta.org/numenta/nupic.core/releases/nupic.bindings/nupic.bindings-0.3.1-cp27-none-linux_x86_64.whl
pip install nupic`?

When installing nupic.bindings as described above, you might need python development headers (`sudo apt-get python-dev`).

**Comment by rhyolight** [comment]
FYI, I got nupic installed and ran tests on Ubuntu 15.10 by running the following:

- `sudo apt-get install python-dev` (python development headers)
- `curl https://raw.github.com/pypa/pip/master/contrib/get-pip.py | sudo python` (most updated version of pip)
- `pip install https://s3-us-west-2.amazonaws.com/artifacts.numenta.org/numenta/nupic.core/releases/nupic.bindings/nupic.bindings-0.3.1-cp27-none-linux_x86_64.whl --user` (nupic.core bindings)
- `pip install nupic --user` (nupic)
- `sudo apt-get install git` (to clone the repo and get tests)
- `git clone https://github.com/numenta/nupic.git` (to download nupic source for unit tests)
- `export PATH=~/.local/bin:$PATH` (adds `py.test` to the path so I can run tests)
- `cd nupic; export NUPIC=\`pwd\`` (sets local `NUPIC` env var for tests)
- `python scripts/run_nupic_tests.py -u` (run unit tests)

All passed for me.

**Comment by rhyolight** [comment]
@kleineLi Did my comments help you? I'm going to close this issue if I do not get a response.

**Comment by kleineLi** [comment]
yes, thanks.

03.02.2016, 23:08, "Matthew Taylor" <notifications@github.com>:
