### ISSUE TITLE
Docker build failure (pip?)

### ISSUE THREAD

**Issue by rhyolight** [numenta/nupic#2987]
Hey @allanino @oxtopus! Do either of you know what's causing this failure? Been happening awhile, I just haven't gotten around to it:

https://hub.docker.com/r/numenta/nupic/builds/bigrfv4moshr9zvqyohw784/

```
The command '/bin/sh -c wget https://raw.github.com/pypa/pip/master/contrib/get-pip.py -O - | python' returned a non-zero code: 1
```

**Comment by oxtopus** [comment]
Not sure what's wrong, and it looks like it's been a problem for more than a week now.  On the other hand, there hasn't been a problem in bamboo, which builds the docker image and runs test in a container: https://ci.numenta.com/download/NUP-NDB-JOB1/build_logs/NUP-NDB-JOB1-77.log

**Comment by oxtopus** [comment]
Looks like the log reported in the docker hub is not complete.  Here's what I get, which does indicate that we need to change the Dockerfile:

```
27-Jan-2016 16:08:54	Saving to: 'STDOUT'
27-Jan-2016 16:08:54	
27-Jan-2016 16:08:54	     0K                                                       100% 46.3M=0s
27-Jan-2016 16:08:54	
27-Jan-2016 16:08:54	2016-01-27 16:08:54 (46.3 MB/s) - written to stdout [260/260]
27-Jan-2016 16:08:54	
27-Jan-2016 16:08:54	You're using an outdated location for the get-pip.py script, please use the one available from https://bootstrap.pypa.io/get-pip.py
27-Jan-2016 16:08:55	The command '/bin/sh -c wget https://raw.github.com/pypa/pip/master/contrib/get-pip.py -O - | python' returned a non-zero code: 1
27-Jan-2016 16:08:55	
```
