### ISSUE TITLE
TM performance tests are unreliable

### ISSUE THREAD

**Issue by SaganBolliger** [numenta/nupic#2991]
The temporal memory [performance test](https://github.com/numenta/nupic/blob/master/tests/integration/nupic/algorithms/temporal_memory_performance_test.py) passes unreliably in CI and locally. Sometimes the test fails to show that the C++ TM is faster than python. See for instance [this build failure](https://ci.appveyor.com/project/numenta-ci/nupic/build/0.1.0.1008). This should be further investigated. However, it is possible that these failures are not symptomatic of worse performance of the C++ implementation and rather are due to random fluctuations of the server load affecting the real time it takes to run each of the TM implementations. If this is the case, one possible solution is to train each model for only one time step in each iteration of the outer loop over time steps, rather than the current test that fully trains each model before proceeding to the next model. This proposal in pseudocode: 
```python
for record in records:
  for model in models:
    times[model] += real time of model.compute(record)
```
This would reduce the tendency for fluctuations in server load to bias the results of the test.

This issue was found while testing #2979

@chetan51 @scottpurdy

**Comment by breznak** [comment]
What you propose could be extended to implementing what I proposed as "time metric" #1711 
- each model would return `computationTime` per each step in `ModelResults`. I think this is what @scottpurdy agreed upon. This value could then be used for your computation...

**Comment by scottpurdy** [comment]
@breznak - This is about benchmarking the TM where your proposals were around parameter tuning. For the purpose of this issue we wouldn't want to change parameters at all but instead compare running time for apples-to-apples models.

**Comment by chetan51** [comment]
@SaganBolliger :+1:

**Comment by breznak** [comment]
> but instead compare running time for apples-to-apples models.

and for that functionality, you could use if the model returned you a computation time for each iteration, no?

**Comment by SaganBolliger** [comment]
After implementing the suggestion here in #2979, that PR passes AV CI. As expected, the changes reduce the variance in the difference between the implementations considerably. However, on Windows the difference between the speed of the Py and C++ TM implementations is very small. On most builds I've seen the them be within 0.15% of each other, and at times Python is still marginally faster (so we can expect the CI to still randomly fail). Also, this confirms that there is still an issue with the Windows implementation in that the Linux/OSX builds show the C++ implementation running ~70% faster than Python.
