### ISSUE TITLE
Bump version to reflect API-breaking change

### ISSUE THREAD

**Issue by oxtopus** [numenta/nupic#3011]
#2998 is another API-breaking change that slipped through without a version bump.  In this case, it removed a module which affected at least https://github.com/numenta/nupic.research/blob/0e4b0b853483dade0b5e0ce50d53df0320ce5e27/htmresearch/algorithms/temporal_memory_factory.py#L25 and possibly others.

**Comment by rhyolight** [comment]
Will do by EOD.
