### ISSUE TITLE
I should be able to persist the anomaly likelihood state with my model

### ISSUE THREAD

**Issue by rhyolight** [numenta/nupic#3021]
When serializing a model, the state that the anomaly likelihood code uses is lost because it is a post-process. Users should be able to have an option to persist this state so when they resurrect their models they don't have to wait for 500 data points before getting anomaly likelihood values again.

/cc @subutai

**Comment by subutai** [comment]
To be a little more precise: the anomaly likelihood is currently a post process and not part of the model. The current recommended approach is to save the AL state separately from the model (e.g. by pickling the class).  That way you do NOT need to pass in 500 data points again.  The HTM Engine for example, saves the AL state separately from the model and resurrects that state each time it loads a model.

It would be more convenient if the CLAModel implementation included the Anomaly Likelihood class for anomaly models and then they could both be saved with one save statement, and reloaded with one load statement.

**Comment by breznak** [comment]
similar https://github.com/numenta/nupic/issues/2266

**Comment by rhyolight** [comment]
I think I'll close in favor of #2266 (I forgot it existed!)
