### ISSUE TITLE
Unable to lauch Nupic Studio

### ISSUE THREAD

**Issue by phani611** [numenta/nupic#3022]
I was able to install Nupic studio on Windows 7 SP1 but unable to lauch the same. Has anyone tried/faced this issue ? Is this not supported on windows ?

I tried to reinstall to see if it works. It did not help.. Refer to the success message

Please advise

[Studio Launch issue.docx](https://github.com/numenta/nupic/files/145401/Studio.Launch.issue.docx)

**Comment by breznak** [comment]
I think the issue should be opened on the NuStudio project's tracker

**Comment by rhyolight** [comment]
Yes, @phani611 please open an issue in nupic.studio's issue tracker here: https://github.com/nupic-community/nupic.studio/issues
