### ISSUE TITLE
coreos-vagrant docker build error  

### ISSUE THREAD

**Issue by BnkColon** [numenta/nupic#3026]
run $ docker build -t nupic:`git rev-parse HEAD` .

But get an error in 

[ 68%] Built target _math
make: **\* [all] Error 2
Traceback (most recent call last):
  File "setup.py", line 58, in <module>

  File "/usr/local/src/nupic.core/bindings/py/setup.py", line 201, in <module>
    getExtensionFiles(platform)
  File "/usr/local/src/nupic.core/bindings/py/setup.py", line 166, in getExtensionFiles
    generateExtensions()
  File "/usr/local/src/nupic.core/bindings/py/setup.py", line 185, in generateExtensions
    subprocess.check_call(["make", "-j3"])
  File "/usr/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['make', '-j3']' returned non-zero exit status 2
The command '/bin/sh -c pip install         --cache-dir /usr/local/src/nupic.core/pip-cache         --build /usr/local/src/nupic.core/pip-build         --no-clean         pycapnp==0.5.5         -r bindings/py/requirements.txt &&     python setup.py install' returned a non-zero code: 1

**Comment by rhyolight** [comment]
@oxtopus Can you review this issue please?

**Comment by oxtopus** [comment]
Looks like same failure as in https://hub.docker.com/r/numenta/nupic/builds/bvwatcsdwfbzijajcj3t3qa/

**Comment by rhyolight** [comment]
The [Docker builds](https://hub.docker.com/r/numenta/nupic/builds/) have been intermittently failing for a long time, so I haven't been paying much attention to these errors. Looks like this one might be a legit error, though.

**Comment by oxtopus** [comment]
Straight-up docker build against master using [Docker Machine](https://docs.docker.com/machine/) works for me.  Now trying the coreos/vagrant configuration.

We also do builds in a docker environment without the Dockerfile, and it's been very stable (see https://ci.numenta.com/browse/NUP-PY)

**Comment by oxtopus** [comment]
The coreos/vagrant configuration built for me, too.  I'm at a loss and would like to see if any others can replicate the failure, and under which, specific, circumstances.
