### ISSUE TITLE
Lots of packages with python2 code

### ISSUE THREAD

**Issue by oneindelijk** [numenta/nupic#3027]
While installing nupic (pip3 install), the installer fails and shows for all these files
`SyntaxError: Missing parentheses in call to 'print'
These are all in the /usr/local/lib/python3.5/dist-packages/nupic/ tree
`

**Comment by rhyolight** [comment]
@oneindelijk We do not support python 3, sorry.

**Comment by hyzhak** [comment]
@rhyolight do you actually have plan to migrate to python 3?

**Comment by rhyolight** [comment]
@hyzhak We have no plans to do so, but it is not off the table. You might bring up this discussion on our forums at https://discourse.numenta.org/c/nupic
