### ISSUE TITLE
db_test checking mysql connection suggested enhancement

### ISSUE THREAD

**Issue by ahaverty** [numenta/nupic#3038]
Hi Nupic,
This is probably more of an enhancement suggestion than an issue.
I was having issues running swarms using my custom defined mysql credentials. The swarm was outputting database errors, however the recommended db_test.py was telling me I was successfully connecting.

I later realised that it was due to my custom mysql user being restricted to my project's database schema. A, now obvious, problem that I overlooked!

Perhaps the db_test.py could include tests to check that it has permissions to create the tables necessary for swarming or perhaps mention it in the documentation?
Thank you

**Comment by rhyolight** [comment]
@ahaverty Very good idea, thanks for posting.

**Comment by rcrowder** [comment]
Sorry to jump in, but another thing that test_db.py could have added is for it to print out whether it uses nupic_site.xml or nupic_default.xml, plus the location where the xml is picked up from. Something that can be used to diagnose install issues (pip or source built), alongside Alan's excellent suggestion in this issue.

**Comment by rhyolight** [comment]
@rcrowder 👍
