### ISSUE TITLE
Make the SDR classifier the default option for CLA classifier Region

### ISSUE THREAD

**Issue by ywcui1990** [numenta/nupic#3059]
After the SDR classifier gets integrated to NuPIC, and gets proved to have better performance on example data, we should make the SDR classifier the default classifier for CLA classifier region, and possibly deprecate CLAClassifier.

**Comment by cogmission** [comment]
Watching this...

**Comment by subutai** [comment]
@cogmission I was about to send you an email on this, but you are too fast!

**Comment by cogmission** [comment]
@subutai Welcome to "cogmission-land" where Clint Eastwood comes to learn how to be fast on the draw!

Fade to black: Faintly you hear the whistles of the characteristic western theme music in the background...

**Comment by subutai** [comment]
@cogmission And I know where you learned your tricks - from 007!

**Comment by cogmission** [comment]
@subutai shhhh...  that information is classified! :-P

**Comment by scottpurdy** [comment]
There is a separate SDRClassifierRegion now so I don't think we need to change the CLAClassifierRegion but instead switch to the SDRClassifier version. Any objections to closing this issue?

**Comment by subutai** [comment]
@scottpurdy Sounds good to me.

**Comment by scottpurdy** [comment]
Closing. We can reopen if something changes.
