### ISSUE TITLE
From nupic.core [#917] Replace Phases w/columnSegmentWalk

### ISSUE THREAD

**Issue by cogmission** [numenta/nupic#3116]
(see: [nupic.core 917](https://github.com/numenta/nupic.core/pull/917))

This is a **HIGH PRIORITY** issue which needs follow up here, and also in HTM.java (see: [#421](https://github.com/numenta/htm.java/issues/421))

The TM algorithm implementation from nupic.core preserves the algorithm but radically changes the methodology to provide performance increases but will affect testing... Therefore, the carried-over changes must be vetted rigorously and tests should reflect the same determinant results because they are used as porting tools also...

**Comment by rhyolight** [comment]
@cogmission I save the `priority:1` label for production issues like broken binaries.

**Comment by cogmission** [comment]
👍 @rhyolight Just want to make sure it doesn't get efficiently filed, then forgotten :-P

**Comment by rhyolight** [comment]
Heads-up @scottpurdy and @mrcslws, I'm going to create an internal JIRA for this issue so we can try to help David with a reference implementation in Python for HTM.Java.

**Comment by cogmission** [comment]
![images-1](https://cloud.githubusercontent.com/assets/2340086/14999429/dc684420-114e-11e6-8d7b-d7b2bd43ad0f.jpeg)
