### ISSUE TITLE
Always set default value for maxBoost to 1.0

### ISSUE THREAD

**Issue by rhyolight** [numenta/nupic#3144]
As discussed by @subutai on [HTM Forum](https://discourse.numenta.org/t/why-maxboost-is-always-2-0/560/7?u=rhyolight):

> maxBoost is described in the Spatial Pooler pseudocode [1]. As Alex Lavin mentions at the end of his post, boosting is, by definition, only useful for really long and complex data sources where you need to optimally allocate the SP columns. For most simple streaming tasks it can be set to 1.0.

> To my knowledge, swarming does not explore different values of boosting, just uses a default value of 2.0. I think that default should be set to 1.0. There is an existing NuPIC ticket [2] to improve the various swarm parameters, and this should be one of them. There are other parameters that could be improved in swarming.

> [1] http://numenta.com/assets/pdf/biological-and-machine-intelligence/0.4/BaMI-Spatial-Pooler.pdf
> [2] https://github.com/numenta/nupic/issues/2829

**Comment by breznak** [comment]
@rhyolight got it in #3143 :wink: maybe it needs a warning comment if we agree on that

**Comment by rhyolight** [comment]
> maybe it needs a warning comment if we agree on that

What do you mean a warning comment?

**Comment by breznak** [comment]
That boosting should be set only for special datasets, and not for common
time-series (that's what I understood from @subutai 's reply) where it may
cause more harm than good
