### ISSUE TITLE
Add examples illustrating overlap properties of Spatial Pooling

### ISSUE THREAD

**Issue by subutai** [numenta/nupic#3149]
This task is to add an example to examples/sp that illustrates various overlap properties of Spatial Pooling. In particular we want easy to understand script(s) to replicate Figures 5, 7, and 9 in this paper:

http://arxiv.org/abs/1505.02142

The script should produce image files (using matplotlib), one for each graph. It should be clearly commented and documented so that a new user can understand what is going on.

Should also update the README in that directory accordingly.

**Comment by rhyolight** [comment]
This would be great to have for the spatial pooling HTM School episode(s).
