### ISSUE TITLE
ImportError: No module named swarm_description in OneHotGymPredictionTutorial

### ISSUE THREAD

**Issue by be4pro** [numenta/nupic#3169]
Hi,
While I was running `swarm.py` of the OHGP Tutorial on Windows, the shell shows that
> Traceback (most recent call last):
  File "D:\Python\Scripts\nupic-0.5.4\nupic-0.5.4\examples\opf\clients\hotgym\prediction\one_gym\swarm.py", line 34, in <module>
    from swarm_description import SWARM_DESCRIPTION
ImportError: No module named swarm_description

I uninstalled nupic and nupic.binding and reinstalled nupic via `pip install nupic` and `python setup.py install` as #2659 suggested. Yet it didn't work.
The way `pip install nupic` encountered the ImportError description above, the other way `python setup.py install` showed up even more Error messages.

Help! Please.

**Comment by rhyolight** [comment]
Looks like you are on Windows. Have you seen this? https://github.com/numenta/nupic/wiki/Running-NuPIC-on-Windows

**Comment by rhyolight** [comment]
cc @rcrowder

**Comment by be4pro** [comment]
I did what the [webpage](https://github.com/numenta/nupic/wiki/Running-NuPIC-on-Windows) instructed and the running result still showed up the same Error.

P.S.
1.nupic and nupic.binding is on `pip list` 
2.`python -c "from nupic.bindings.math import Random; print Random().getUInt64();"` shows up a random number

**Comment by rcrowder** [comment]
@rhyolight Yes that's the correct and up to date Windows instructions for pip installing nupic. With a fresh Python install and pip install of the latest nupic, I'm watching OHG swarming working right now. Once complete I'll try a pip uninstall followed by a source setup.py install, to see if I can recreate this import error.

**Comment by rcrowder** [comment]
@be4pro I haven't been able to recreate the Import Error you are seeing. Using a mix of nupic (source) and nupic.bindings (pip install), I can create an Import Error for nupic.swaming (nupic 0.5.2.dev0 with nupic.bindings 0.4.4). But that is expected when mixing source and pip packages.

What versions of nupic and nupic.bindings show up for you using `pip list` ?

**Comment by be4pro** [comment]
@rcrowder nupic is 0.5.4 and nupic.bindings is 0.4.4

**Comment by be4pro** [comment]
Problem Solved after I ran swarm.py by cmd, instead of pyzo. I think it could be simply a PATH-setting problem.
Installing nupic by following the guide on [https://github.com/numenta/nupic/wiki/Running-NuPIC-on-Windows](https://github.com/numenta/nupic/wiki/Running-NuPIC-on-Windows) is fine,btw.
Thank you for the help.

**Comment by rcrowder** [comment]
Glad to hear you've got it working. Thank you for letting us know how you fixed this.
