### ISSUE TITLE
SDR classifier yields much higher errors in OPF experiments

### ISSUE THREAD

**Issue by natoromano** [numenta/nupic#3173]
In the integration test at `nupic.integration.opf.opf_experiments_results_test.OPFExperimentResultsTest`, switching from CLA classifier to SDR classifier yields substantially higher errors, breaking the tests for which an error range is specified.

**Comment by ywcui1990** [comment]
@natoromano Have you tried tuning the learning rate parameter in SDR classifier? The alpha parameter may need to be set very differently for the SDR classifier than the CLA classifier. Also, what error metric is being used for these test? I can take a look at this when I get back.

**Comment by natoromano** [comment]
@ywcui1990 yes, tuning the learning rate worked, but the issue is still open as the PR with the corresponding changes, #3168, is not merged yet.

**Comment by ywcui1990** [comment]
OK. Glad to hear that tuning the learning rate worked. Let me know if you need any help from me regarding the SDR classifier.

**Comment by natoromano** [comment]
Fixed by #3182
