### ISSUE TITLE
Can NUPIC be used or installed in cygwin?

### ISSUE THREAD

**Issue by be4pro** [numenta/nupic#3181]
Hi,
I'm a windows user and have nupic installed successfully.
Recently, I failed to maneuver nupic installed on windows through cygwin.
I thought it could be a PATH-related issue. So I tried to install nupic in cygwin but it failed.
Is there a simpler way to work nupic in cygwin?
I knew there's a guide to help [https://github.com/numenta/nupic/wiki/Running-Nupic-in-a-Virtual-Machine](https://github.com/numenta/nupic/wiki/Running-Nupic-in-a-Virtual-Machine).
Yet, is that the best way by now to install and use nupic?
Thanks.

**Comment by rhyolight** [comment]
@be4pro I'm not aware of anyone who's tried running in cygwin, but you might [ask this question on our forums](https://discourse.numenta.org/c/nupic).

**Comment by be4pro** [comment]
@rhyolight OK. Thank you.
