### ISSUE TITLE
Move extensive_tm_test_base to nupic.test

### ISSUE THREAD

**Issue by natoromano** [numenta/nupic#3186]
Move extensive_tm_test_base.py to src.nupic.test instead of tests/, so that it can be imported and subclassed elsewhere (e.g. in nupic.research to test other TM implementation).

Make corresponding changes in test imports.

Waiting for your confirmation to go ahead and do this @scottpurdy, @mrcslws or @subutai.

**Comment by rhyolight** [comment]
I was not aware that there was a `src/nupic/test` directory. Seems like a bad idea overall to have test code alongside production code, because our distribution process bundles it all up and compiles it together. So now we've got test code distributing with prod code, which is generally a bad idea. 

Personally, I would rather have duplicated abstract test code between nupic and nupic.research rather than exposing it as a production interface.

**Comment by subutai** [comment]
@rhyolight Looking at the code, I believe `src/nupic/test` is for support code for tests, i.e. code that could be useful to tests to import. I think the code in this directory should get moved to `nupic/support/unittesthelpers` which also has the same purpose, and a more descriptive name. I agree with you that it's really confusing to have a `src/nupic/test` directory.

I don't have a strong opinion about @natoromano's proposal to move extensive_tm_test_base.py into a generally importable location. I can see the pro's and con's.

**Comment by rhyolight** [comment]
Let's at least put them all in the same place, and the "unittesthelpers"
directory is much more explanatory.

---------
Matt Taylor
OS Community Flag-Bearer
Numenta

**Comment by mrcslws** [comment]
RE:

> Personally, I would rather have duplicated abstract test code between nupic and nupic.research rather than exposing it as a production interface.

I agree. For `extensive_tm_test_base`, I prefer duplicating the code in nupic.research. Like @subutai says, there are pros and cons, but I like the flexibility of having a test suite devoted to the ExtensiveTemporalMemory.

Did we just volunteer @natoromano to rename `src/nupic/test` to `src/nupic/unittesthelpers`? :)

**Comment by subutai** [comment]
> Did we just volunteer @natoromano to rename src/nupic/test to src/nupic/unittesthelpers? :)

The latter directory already exists. I guess we volunteered him to move the code from `src/nupic/test` to `src/nupic/unittesthelpers` 😄

**Comment by mrcslws** [comment]
Ha. My mistake. Like you said, it's `/src/nupic/support/unittesthelpers`.

**Comment by natoromano** [comment]
It made more sense to directly subclass AbstractTemporalMemory test, as too many methods had to be reimplemented, so for now it makes sense to leave extensive_tm_test_base where it is.
