### ISSUE TITLE
Invalid Syntax when I use "python setup.py install" 

### ISSUE THREAD

**Issue by xiaochouxiaohai** [numenta/nupic#3190]
I was trying to install pydelicious, and I down load it from https://pypi.python.org/pypi/pydelicious/, (not sure where I should put this file to), and then run the code "python setup.py install" in Spyder,

It just said "SyntaxError: invalid syntax"

**Comment by rhyolight** [comment]
@xiaochouxiaohai As far as I can tell, this issue had nothing to do with NuPIC. Neither "pydelicious" nor "Spyder" are NuPIC dependencies. Perhaps you created this issue in the wrong repository?
