### ISSUE TITLE
Could not find a version that satisfies the requirement nupic.bindings==0.4.4

### ISSUE THREAD

**Issue by guamian** [numenta/nupic#3191]
Hi, when I was following the installation tutorial on youtube: https://www.youtube.com/watch?v=rN-57iBvcT4 I got this error message:

Could not find a version that satisfies the requirement nupic.bindings==0.4.4 (from nupic) (from versions: )
No matching distribution found for nupic.bindings==0.4.4 (from nupic)

Operating system: Ubuntu 16.04
Python version: Python 2.7.11+
Pip version: pip 8.1.1

What should I do to solve this problem?

**Comment by rhyolight** [comment]
@guamian Are you sure you ran this command as described [at 4:50 in the video](https://www.youtube.com/watch?v=rN-57iBvcT4&t=4m50s)?

    pip install https://s3-us-west-2.amazonaws.com/artifacts.numenta.org/numenta/nupic.core/releases/nupic.bindings/nupic.bindings-0.4.4-cp27-none-linux_x86_64.whl

This is the command that should install `nupic.bindings` version 0.4.4. What is the console output when you run this command?

**Comment by guamian** [comment]
It worked. Thx. This error occurs because I was not upgrade my pip to the latest version.
