### ISSUE TITLE
Plotting problem for hot gym tutorial

### ISSUE THREAD

**Issue by be4pro** [numenta/nupic#3194]
Hi,
My problem is that while I was running `run.py --plot`, the plot didn't show actively.
it only shows the final result after `run.py` ends up reading 4,300 lines, instead of showing actively as the tutorial video presented.
I'm using numpy (1.9.2), matplotlib (1.5.1) on windows.

**Comment by rcrowder** [comment]
@be4pro Could you try changing the line from `plt.draw()` to `plt.pause(0.001)`
https://github.com/numenta/nupic/blob/master/examples/opf/clients/hotgym/prediction/one_gym/nupic_output.py#L186

**Comment by be4pro** [comment]
@rcrowder It works! Thanks for your help, Richard. :)

**Comment by rcrowder** [comment]
You're welcome. This is a common problem with using matplotlib in interactive mode. The call to pause() allows mpl to handle events (such as window updates), and includes a call to draw().

**Comment by be4pro** [comment]
I see. Thank you. I'll try to learn more.
