### ISSUE TITLE
AttributeError: 'TPShim' object has no attribute 'saveToFile'

### ISSUE THREAD

**Issue by cheribral** [numenta/nupic#3203]
I've been working on a UDF for kapacitor (https://docs.influxdata.com/kapacitor/v0.13/examples/socket_udf/) by stealing the some of the guts out of the influx.htm example, but have hit a snag when it comes to saving the state of models.  Since kapacitor handles the running process and triggering snapshots, I've been trying to distill what I need from model_checkpoint_mgr from htmengine.

When I run model.save(path), I am getting`AttributeError: 'TPShim' object has no attribute 'saveToFile'`.  I'm reporting this as a possible bug, but realize I could just be doing it wrong too.  If so, let me know.

The code I'm using to test the basics idea is this, which works all the way until the model.save:

```python
  points = influx_points("cpu", "usage_iowait")
  model = createModel()
  anomalyLikelihood = anomaly_likelihood.AnomalyLikelihood()
  shifter = InferenceShifter()
  for point in points:
    timeString = point[0]
    if "." in timeString:
      timeString = timeString.split(".").pop(0)
    else:
      timeString = timeString.split("Z").pop(0)
    timestamp = datetime.strptime(timeString, DATE_FORMAT)

    value = point[1]
    result = model.run({
      "timestamp": timestamp,
      "value": value
    })
    result = shifter.shift(result)
    inferences = result.inferences
    anomalyScore = inferences["anomalyScore"]

    likelihood = anomalyLikelihood.anomalyProbability(
          value, anomalyScore, timestamp)

    print {
      "timestamp": timestamp.isoformat(),
      "inferences": result.inferences,
      "anomalyLikelihood": likelihood
    }
  model.save("/tmp/test")
```

Edit:  Stacktrace in case it helps
```
  File "./influx-anomaly.py", line 67, in runit
    model.save("/tmp/test")
  File "/home/chris/.local/lib/python2.7/site-packages/nupic/frameworks/opf/model.py", line 300, in save
    self._serializeExtraData(extraDataDir=self._getModelExtraDataDir(saveModelDir))
  File "/home/chris/.local/lib/python2.7/site-packages/nupic/frameworks/opf/clamodel.py", line 1362, in _serializeExtraData
    self._netInfo.net.save(outputDir)
  File "/home/chris/.local/lib/python2.7/site-packages/nupic/engine/__init__.py", line 749, in save
    engine.Network.save(self, *args, **kwargs)
  File "/home/chris/.local/lib/python2.7/site-packages/nupic/bindings/engine_internal.py", line 1083, in save
    return _engine_internal.Network_save(self, *args, **kwargs)
  File "/home/chris/.local/lib/python2.7/site-packages/nupic/regions/TPRegion.py", line 790, in serializeExtraData
    self._tfdr.saveToFile(filePath)
AttributeError: 'TPShim' object has no attribute 'saveToFile'
```

**Comment by rhyolight** [comment]
@scottpurdy I have seen a similar error before in #2935: `AttributeError: 'TPShim' object has no attribute 'topDownCompute'`. But I'm not sure why this would be happening here.

**Comment by BoltzmannBrain** [comment]
@cheribral what implementation of temporal memory are you using? I.e., what is `'temporalImp'` set to in your model params?

**Comment by cheribral** [comment]
@BoltzmannBrain It is using tm_py

**Comment by BoltzmannBrain** [comment]
My understanding is that saving/loading is not implemented for TPShim, although it should be. Using `py` instead of `tm_py` should resolve your issue.

**Comment by BoltzmannBrain** [comment]
@cheribral please let us know if this resolved your issue

**Comment by cheribral** [comment]
Apologies, I had written a reply and never actually hit save.  Yes this did the trick.  Choosing py made it save, but process many times slower.  I chose cpp which let it save while being fast enough to work through the stream I was feeding it.   Thank you for the suggestion.

**Comment by BoltzmannBrain** [comment]
👍
