### ISSUE TITLE
The SDRClassifier doesn't serialize its "maxSteps"

### ISSUE THREAD

**Issue by mrcslws** [numenta/nupic#3222]
The proto declares a `maxSteps` https://github.com/numenta/nupic.core/blob/064f8b1ef003d5ee07405cd5ac41583f83ab1d35/src/nupic/proto/SdrClassifier.capnp#L11

But the Python class never writes to it: https://github.com/numenta/nupic/blob/76e5b07b35764826b34221104e9c43704138b9e3/src/nupic/algorithms/sdr_classifier.py#L406

One acceptable fix would be to remove `maxSteps` from the proto. It's redundant: it's just the maximum element with the `steps`, which is also serialized.

**Comment by natoromano** [comment]
@rhyolight this can be closed (fixed by #3223 but the multiple issue reference did not work).
