### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by mellertson** [numenta/nupic#3224]
I'm getting a segmentation fault when attempting to run ['python sine_experiments.py'](https://github.com/rhyolight/nupic.examples/tree/master/sine-prediction). I used gdb to debug the issue, here's the output from gdb. I'm not sure where to go, or if perhaps I have something configured wrong. But, I hope providing the backtrace helps.

Additionally, I installed both nupic.core then nupic.  The unit tests for both ran without error. I'm using the following versions on Ubuntu 16.04:
python 2.7.12
numpy 1.9.2
pycapnp 0.5.8 (Python bindings)
cmake 3.5.1
capnproto 0.5.3 (C++ libs)
gcc 5.3.1
make 4.1

I installed everything as per the instructions, but executed cmake using the following:
cmake $NUPIC_CORE -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX=../debug -DPY_EXTENSIONS_DIR=$NUPIC_CORE/bindings/py/nupic/bindings

I also used a slightly different syntax when installing Python modules using pip.  I used a syntax like the following:
sudo -H pip install <module>

**Backtrack from GDB**
/nupic.examples/sine-prediction$ gdb -ex r --args python sine_experiment.py
GNU gdb (Ubuntu 7.11-0ubuntu1) 7.11
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later http://gnu.org/licenses/gpl.html
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law. Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
http://www.gnu.org/software/gdb/bugs/.
Find the GDB manual and other documentation resources online at:
http://www.gnu.org/software/gdb/documentation/.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from python...Reading symbols from /usr/lib/debug/.build-id/da/dc6dc447374ae242ac392c67c898e3d5f49972.debug...done.
done.
Starting program: /usr/bin/python sine_experiment.py
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7ffff1d40700 (LWP 20688)]
[New Thread 0x7fffef53f700 (LWP 20689)]
[New Thread 0x7fffecd3e700 (LWP 20690)]

Thread 1 "python" received signal SIGSEGV, Segmentation fault.
__memset_sse2 () at ../sysdeps/x86_64/multiarch/../memset.S:78
78 ../sysdeps/x86_64/multiarch/../memset.S: No such file or directory.
(gdb)

**Comment by mellertson** [comment]
FYI, I found a potential solution on the [Nuementa forums,](https://discourse.numenta.org/t/segmentation-fault-while-running-basic-swarm/877/11) I'm trying that now.  I'll update this issue with a status.

**Comment by mellertson** [comment]
The post on the [Nuementa forums](https://discourse.numenta.org/t/when-swarming-got-error-1698-28000-access-denied-for-user-root-localhost-mysql/893) solved my issue.  Thanks for the solution @vitaly-krugl :smile:

**Comment by rhyolight** [comment]
@mellertson Great! Thanks for serving yourself. I had not gotten to this until this morning. :)
