### ISSUE TITLE
Ensure no remaining differences between python and c++ temporal memory implementations

### ISSUE THREAD

**Issue by andrewmalta13** [numenta/nupic#3239]
- requires a large refactoring of src/nupic/research/connections.py and minimal changes to src/nupic/temporal_memory.py

- would fix #3199

**Comment by andrewmalta13** [comment]
I have been working on a PR to shore up the remaining differences between the two temporal memory implementations, while along the way fixing the serialization issue #3199 created by the change to columnSegmentWalk.  In the process I have run into some performance issues that, although I have not explored all options, might mean that this change will make the temporal memory implementation slower than the current implementation in nupic. On the other hand, I have verified that these implementations (after a slight change to nupic.core) perform exactly the same when fed in hotgym (This is not the case with the current implementation).

My question is do we value the parity of the two implementations over the speed of the python implementation?

@scottpurdy  @mrcslws

**Comment by mrcslws** [comment]
I think we want the ability to have parity, but we don't necessarily need it all the time if it would mean hurting performance. i.e. a `whoNeedsParityJustGoFaster` parameter might be acceptable.

I'm curious to know more details. I'm hoping this trade-off isn't fundamentally necessary.

**Comment by scottpurdy** [comment]
Generally we are ok with slight performance hits in the Python implementations to keep parity. We don't accept perf hits in C++.
