### ISSUE TITLE
Incorrect Documentation of Connections method

### ISSUE THREAD

**Issue by cogmission** [numenta/nupic#3240]
The documentation for the enclosed method, states that it, "...returns the column that a segment's presynaptic cell belongs to." What it does is **return the column of the ```Cell``` that _owns_ the segment.** If I'm not mistaken, ```Segments``` don't have presynaptic cells; ```Synapses``` do. I believe there may be many Cells that synapse to a segment, and each of those synapses have "presynaptic" cells (source cells).

The documentation [for the method should](https://github.com/numenta/nupic/blob/master/src/nupic/research/connections.py#L83) probably read:
 **Returns the column of the ```Cell``` which _owns_ the segment.**

```Python
 def columnForSegment(self, segment, cellsPerColumn):
    """ Returns the column that a segment's presynapticCell belongs to

    @param segment        (int) Segment index
    @param cellsPerColumn (int) Number of cells in a column in the tm

    @return (int)
    """
    return self._segments[segment] / cellsPerColumn
```

As a side note, this really messed me up trying figure out how to derive a presynaptic cell from a segment, until I realized it's not possible. :-P

**Comment by andrewmalta13** [comment]
@cogmission thanks for the heads up. Will be fixed soon.
