### ISSUE TITLE
group_by_test.py has contains misnamed class

### ISSUE THREAD

**Issue by cogmission** [numenta/nupic#3270]
Just a small oversight (someone probably forgot to come back to rename it)...

[nupic/tests/unit/nupic/support/group_by_test.py](https://github.com/numenta/nupic/blob/master/tests/unit/nupic/support/group_by_test.py#L27) has a main test class named ```ConnectionsTest``` which should be named GroupByTest. The inner class has no association with the ```Connections``` class, and specifically tests the new ```group_by2``` functionality.

**Comment by rhyolight** [comment]
Thanks, David.
