### ISSUE TITLE
I'm looking for the implementation of WCCI paper

### ISSUE THREAD

**Issue by chickenbestlover** [numenta/nupic#3286]
hello nupic, 

I've read your WCCI IJCNN 2016 paper : A comparative study of HTM and other neural network models for online sequence learning with streaming data. 

It's really interesting that HTM overwhelmed LSTM which is the state of the art algorithm learning streaming data.

And I read from the paper that full source code for the implementation is available on Github at https://github.com/numenta/nupic, which is here.

However, I cannot find the exact location of the code. 

It would be very grateful if anyone let me know where the code is. 

thank you

**Comment by rhyolight** [comment]
@chickenbestlover You're in the right place. This is the implementation. Code starts here: https://github.com/numenta/nupic/tree/master/src/nupic

I recommend you read our wiki: https://github.com/numenta/nupic/wiki

**Comment by chickenbestlover** [comment]
Thank you for your kind answer.
But..  i dont think this is the implementation of wcci 2016 paper; the
auther of the paper compared the performance of htm with that of lstm and
elm. But here, only nupic source code exists. Even the dataset is absent.

2016. 8. 23. 오전 12:03에 "Matthew Taylor" <notifications@github.com>님이 작성:

**Comment by rhyolight** [comment]
Ah ok, you are looking for https://github.com/numenta/NAB

---------
Matt Taylor
OS Community Flag-Bearer
Numenta

**Comment by ywcui1990** [comment]
The implementation for the HTM sequence memory paper is here: https://github.com/numenta/nupic.research/tree/master/projects/sequence_prediction

This is where we compare HTM with other machine learning algorithms on sequence prediction tasks.

**Comment by chickenbestlover** [comment]
Thank you , but this is not what i've been lookinf for.
I sent an email to Yuwei(the author) and he told me the exact location.
It's here :

https://github.com/numenta/nupic.research/tree/master/projects/sequence_prediction

Anyway, thank you for your kindness.

Sincerely yours,

Jinman Park

2016. 8. 23. 오전 12:40에 "Matthew Taylor" <notifications@github.com>님이 작성:
