### ISSUE TITLE
Winner columns chosen with no overlap with input (local inhibition)

### ISSUE THREAD

**Issue by rhyolight** [numenta/nupic#3287]
> See discussion of this problem at https://discourse.numenta.org/t/sp-columns-activating-without-input-when-using-topology/1267

Given the condition for selecting winner columns during the local inhibition step here:

https://github.com/numenta/nupic/blob/f1dd3ca676891f7370cf5404b3bbe432ac503f75/src/nupic/research/spatial_pooler.py#L1471

I believe there is a bug that allows columns to be activated that have no overlap with the input vector. When the condition is updated to ensure the column overlaps with the input vector, the proper behavior is observed.

Before:

[![](http://img.youtube.com/vi/w1t4quc1oNs/0.jpg)](https://www.youtube.com/watch?v=w1t4quc1oNs)

After:

[![](http://img.youtube.com/vi/BiMZvSbGZKs/0.jpg)](https://www.youtube.com/watch?v=BiMZvSbGZKs)

**Comment by rhyolight** [comment]
Working on a failing unit test...

**Comment by mrcslws** [comment]
This is equivalent to using a `stimulusThreshold` of 1. So with this change, there's no difference between having a stimulus threshold of 0 or of 1.

An alternate fix would be to just change the default value for `stimulusThreshold`. Then we'll just be doing the `>` check in one place, not two.

(I don't have a strong opinion)

**Comment by rhyolight** [comment]
> An alternate fix would be to just change the default value for stimulusThreshold. Then we'll just be doing the > check in one place, not two.

I would prefer this, but I just reverted my change and set `stimulusThreshold` to 1.0, and got the same behavior (after 39 time steps exactly):

<img width="916" alt="screen shot 2016-08-22 at 2 02 53 pm" src="https://cloud.githubusercontent.com/assets/15566/17871635/475ff394-6871-11e6-9e51-191d62f3d6fc.png">

<img width="914" alt="screen shot 2016-08-22 at 2 03 04 pm" src="https://cloud.githubusercontent.com/assets/15566/17871641/50bf00a6-6871-11e6-9180-ff0619d66898.png">

**Comment by rhyolight** [comment]
Aside from `stimulusThreshold`, the other SP params I'm using are:

```python
{'columnDimensions': [32, 32],
 'dutyCyclePeriod': 1000,
 'globalInhibition': False,
 'inputDimensions': [32, 32],
 'localAreaDensity': 0.1,
 'maxBoost': 1,
 'minPctActiveDutyCycle': 0.001,
 'minPctOverlapDutyCycle': 0.001,
 'numActiveColumnsPerInhArea': 1,
 'potentialPct': 0.85,
 'potentialRadius': 8,
 'synPermActiveInc': 0.05,
 'synPermConnected': 0.1,
 'synPermInactiveDec': 0.008,
 'wrapAround': False}
```

**Comment by mrcslws** [comment]
Oh, interesting. Yeah, it's definitely a bug that this still happens with `stimulusThreshold` of 1.

Ok, I support this change.

**Comment by scottpurdy** [comment]
@subutai - Do you want to look at this before the change is made?

**Comment by vova616** [comment]
What about _inhibitColumnsGlobal?
If all the column overlaps are zero does it also makes the same mistake?

**Comment by rhyolight** [comment]
@scottpurdy In answer to your more [general question here](https://github.com/numenta/nupic.core/pull/1054#issuecomment-241572042), I ran an experiment using an input vector with an inconsistent sparsity (starting with no active bits, building up to a lot, and cycling through).

Using these SP params:

```python
{'columnDimensions': [32, 32],
 'dutyCyclePeriod': 1000,
 'globalInhibition': False,
 'inputDimensions': [32, 32],
 'localAreaDensity': 0.1,
 'maxBoost': 1,
 'minPctActiveDutyCycle': 0.001,
 'minPctOverlapDutyCycle': 0.001,
 'numActiveColumnsPerInhArea': 1,
 'potentialPct': 0.85,
 'potentialRadius': 8,
 'stimulusThreshold': 1,
 'synPermActiveInc': 0.05,
 'synPermConnected': 0.1,
 'synPermInactiveDec': 0.008,
 'wrapAround': False}
```

[![](http://img.youtube.com/vi/7zsyIiuAMMM/0.jpg)](https://www.youtube.com/watch?v=7zsyIiuAMMM)


Here is the result, please watch. There is definitely more distance between the mininum # of active columns and maximum # of active columns when the input vector is cycling between few on bits and many on bits.

I noticed there is also this variation before my change, but it is not as extreme because so many columns are being activated without having overlap to the input vector when the input vector is very sparse.

**Comment by subutai** [comment]
@rhyolight I haven't looked into this in detail, but shouldn't the change be:
```
if overlaps[i] >= self._stimulusThreshold and numBigger < numActive:
```
??

**Comment by rhyolight** [comment]
@subutai I don't think we need to do that, because when the overlaps were calculated, the `stimulusThreshold` was used:

https://github.com/rhyolight/nupic/blob/162ff7e7bab66925d84990215670f50eeffdfb9b/src/nupic/research/spatial_pooler.py#L1379

Overlaps beneath the stimulus threshold should have already been zeroed out.

**Comment by subutai** [comment]
ok, thanks. I'm ok with this change.

**Comment by rhyolight** [comment]
@ vova616 said:
> If all the column overlaps are zero does it also makes the same mistake?

In the case of global inhibition, the only time all a column's neighbors have no overlap is when there are no bits on in the input vector. That is a very rare case, and also I believe the `numActiveColumnsPerInhArea` defines that a minimum number of bits will be on anyway within the one inhibition area. So I don't think this is an issue.

**Comment by vova616** [comment]
Yes but is it fine to choose columns with zero overlaps as winners in global inhibition?
For example its possible that numActive will be bigger than the number of columns with a non zero overlap score, if numActive is 50 , and only 40 columns got a non zero overlap score, 10 random columns with an overlap score of 0 will be chosen as active/winner to satisfy the settings.

https://github.com/rhyolight/nupic/blob/162ff7e7bab66925d84990215670f50eeffdfb9b/src/nupic/research/spatial_pooler.py#L1435

**Comment by rhyolight** [comment]
@vova616 Yes but the density is calculated using `numActiveColumnsPerInhArea`:

https://github.com/rhyolight/nupic/blob/162ff7e7bab66925d84990215670f50eeffdfb9b/src/nupic/research/spatial_pooler.py#L1410

The OPF will choose a `numActiveColumnsPerInhArea` that creates 2% sparsity in output from the SP. Honestly I don't have time to dig deeply into this, especially because we've been exercising global inhibition for years now, but topology is something we've just started looking at again. 

Feel free to find another issue if you can find evidence of something not working.

**Comment by vova616** [comment]
@rhyolight Thanks, I will look into it :).

**Comment by mrcslws** [comment]
@vova616 is right, this causes inconsistent SP behavior. After this change:

- With global inhibition: Columns with 0 overlap can get activated
- With local inhibition: Columns with 0 overlap can't get activated

Here's some quick code you can paste into a notebook:

~~~python
import numpy as np

from nupic.research.spatial_pooler import SpatialPooler

sp = SpatialPooler(inputDimensions=(200),
                   columnDimensions=(1024),
                   potentialRadius=200,
                   potentialPct=0.1,
                   globalInhibition=True,
                   localAreaDensity=-1.0,
                   numActiveColumnsPerInhArea=10.0,
                   stimulusThreshold=0,
                   synPermInactiveDec=0.008,
                   synPermActiveInc=0.05,
                   synPermConnected=0.10,
                   minPctOverlapDutyCycle=0.001,
                   minPctActiveDutyCycle=0.001,
                   dutyCyclePeriod=1000,
                   maxBoost=10.0,
                   seed=-1,
                   spVerbosity=0,
                   wrapAround=True)

encoding = np.zeros(200, dtype=np.float32)
spOutput = np.zeros(1024, dtype=np.float32)

sp.compute(encoding, learn=True, activeArray=spOutput)
print spOutput.nonzero()[0]
print sp.getOverlaps().nonzero()[0]
~~~

With globalInhibition=True, the output is

~~~
[1014 1015 1016 1017 1018 1019 1020 1021 1022 1023]
[]
~~~

With globalInhibition=False, and with your change, the output will be empty.

I think your change is good, but we should make it in both code paths.

Unless we want this behavior. Someone could make a case for that. One option is to control this via stimulusThreshold, and people opt in to this behavior by choosing stimulusThreshold=0. (That would require a different bugfix)

**Comment by rhyolight** [comment]
Thanks @mrcslws and @vova616. Can we track the global inhibition issue separately? **This** issue is complicated enough for me. @vova616 would you like to [create a new issue](https://github.com/numenta/nupic/issues/new) about this for global inhibition?

**Comment by mrcslws** [comment]
Here's what I have in mind.

https://github.com/mrcslws/nupic/commit/86547f93be70095dfc202e2828b8197ec704a690

I think something like this addresses the core issue that the stimulus threshold is not working correctly. It takes a slightly different approach from the current fix. I'm not sure there's a reason to do a temporary fix that we're going to change again... what do you think of this approach?

**Comment by rhyolight** [comment]
@mrcslws That makes sense to me. If you can turn this into a PR, I'll test it with my topological data sets. But then you'll be on the hook to do the C++ version as well. ;)

**Comment by rhyolight** [comment]
@mrcslws Update: I tested your fix and it works great with my topo data sets.
