### ISSUE TITLE
Connections: computeActivity() - segment variable not updated due to scope issue?

### ISSUE THREAD

**Issue by cogmission** [numenta/nupic#3290]
Please forgive me if my lack of Python knowledge is at fault here, but to me, upon inspection of this code, [the ```segment``` variable's value here](https://github.com/numenta/nupic/blob/master/src/nupic/research/connections.py#L517) takes on the value it was last set to be in the last iteration of the [above for loop here?](https://github.com/numenta/nupic/blob/master/src/nupic/research/connections.py#L497) 

If this is so, the ```segment``` is never consistent with the segment being marked as active in the current ```if``` clause? How does the current segment get it's lastIteration recorded if the segment variable is never reassigned to the current segment being iterated over?

Please advise?

@rhyolight  I believe this is a bug?

**Comment by cogmission** [comment]
Closing this as it will be obsoleted by #3307 anyway. @rhyolight  Did anyone see this?

**Comment by rhyolight** [comment]
Somehow I missed this!
