### ISSUE TITLE
Move audiostream example out of nupic

### ISSUE THREAD

**Issue by rhyolight** [numenta/nupic#3295]
> from https://discourse.numenta.org/t/proposal-move-audiostream-example-out-of-nupic-codebase/1251

https://github.com/numenta/nupic/tree/master/examples/audiostream is a community-contributed example codebase, but because it is inside the NuPIC repository, it implies that maintainers of the repo will keep it running and up-to-date, yet this is not the case. I don't think we have tried to run this code in years. It might not even work anymore.

Anyway, since we aren't maintaining this code, I think we should move it out of NuPIC. I propose we move this code into https://github.com/htm-community/nupic-example-code, where I think more community examples of NuPIC usage should go.

- [x] push code into https://github.com/htm-community/nupic-example-code
- [ ] delete code from nupic

**Comment by rhyolight** [comment]
Thanks @arhik for taking care of the first step! https://github.com/htm-community/nupic-example-code/pull/1

**Comment by arhik** [comment]
I could fix the audiostream example code last month not bothered to push it because matplotlib was commented out through out (Matplotlib hangs on my linux 16.04 on this example for some reason). The bug is in pyaudio library calls. Tweaking the sampling frequency and bins helped solve it.

**Comment by rhyolight** [comment]
@arhik Sounds good to me!

**Comment by iorobertob** [comment]
What is needed here? I worked based on this example and I think I improved it a bit, used a nonblocking callback and got it run similar to the nupic.critic with opf. Maybe this could be of some use!

**Comment by rhyolight** [comment]
Hi @iorobertob. This move was partially in an effort to lighten the NuPIC codebase. I plan on moving more examples out of the codebase in the future if I can get approval. The new home will be https://github.com/htm-community/nupic-example-code.

**Comment by iorobertob** [comment]
I see that! cool!

**Comment by rhyolight** [comment]
@iorobertob That being said, [there were complaints that this example was no longer working for users](https://discourse.numenta.org/t/proposal-move-audiostream-example-out-of-nupic-codebase/1251), so if you know how to fix it, I would gladly accept PRs for https://github.com/htm-community/nupic-example-code/tree/master/audiostream.

**Comment by iorobertob** [comment]
@rhyolight sure! will happily prepare something there!
