### ISSUE TITLE
The TM benchmark doesn't cover many scenarios

### ISSUE THREAD

**Issue by mrcslws** [numenta/nupic#3300]
Currently the TM benchmark just does 2000 steps of hotgym [1]. 

It should cover more scenarios. It should test various sequences, some that are very predictable and others that are not very predictable. And it should test the TM with various parameters, especially with various cellsPerColumn.

[1] And it's a little goofy: It gets the column SDR using a `RandomDistributedScalarEncoder` that only has `n=400`, so 1648 of the 2048 columns are never active.

**Comment by rhyolight** [comment]
@mrcslws never mind about the code reference, I see your PR now. 

But still, if this doesn't run with regression tests, I think that is where it should run.

**Comment by mrcslws** [comment]
@rhyolight with default parameters, this script takes a couple minutes, and it just runs the tests on the C++ TM. It will take the lifetime of the universe to run on the Python TM (it's better to not run all the tests when using Python). It doesn't test anything, except that the TM doesn't throw an exception. So I think putting this in our regression tests would just slow down our CI and make servers' CPUs really hot without accomplishing much else.
