### ISSUE TITLE
SpatialPooler: Performance nit:  remove extra loop 

### ISSUE THREAD

**Issue by cogmission** [numenta/nupic#3308]
[I believe this line should be moved to be in the above ```for``` loop](https://github.com/numenta/nupic/blob/master/src/nupic/research/spatial_pooler.py#L1194) so that the ```perm``` list is not iterated over twice. So at the bottom of the for loop, the current index of ```perm``` being processed should be checked to see if it is below ```synPermTrimThreshold``` as the list is being built, rather than run a filter over it after it has been built - necessitating a new iteration.

I'm not a Python expert, but something like:
```Python
perm = numpy.zeros(self._numInputs, dtype=realDType)
    for i in xrange(self._numInputs):
      if (potential[i] < 1):
        continue

      if (self._random.getReal64() <= connectedPct):
        perm[i] = self._initPermConnected()
      else:
        perm[i] = self._initPermNonConnected()

      perm[i] = 0 if perm[i] < self._synPermTrimThreshold else perm[i]

```

**Comment by rhyolight** [comment]
Makes sense to me... @numenta/nupic-reviewers ?

**Comment by cogmission** [comment]
@mrcslws Ping - what do ya' think?

**Comment by scottpurdy** [comment]
I don't think the link is valid. Please click the "Y" key to get a permalink when linking to code on GH.

**Comment by cogmission** [comment]
@scottpurdy I just checked it, it's fine?

**Comment by rhyolight** [comment]
@cogmission It links to line 1194 in the **latest** version of the file, which is not the same place it was when you linked to it. Click the link and look at the highlighted line. It is a comment.

Scott is saying that you should find the line in the file you want to link to and press "Y", which will update the page to a URL to a permalink to that line in that file _in that SHA_.

**Comment by scottpurdy** [comment]
Link aside, I think it's probably more efficient as it is but it is hard to say unless someone tries it. Putting the check in the loop will do the condition check-set in Python for every index. Doing it after like it currently is will do the check set in C++ for every index. So yes extra loop but it's a C++ loop. Feel free to do it in Java whatever way makes the most sense.

**Comment by cogmission** [comment]
Not sure what you mean by C++ loop. We're looking at Python code, no? If this were calling through a SWIG interface there wouldn't be Python code here at all, would there? There would just be a reference to an interface? Sorry, I'm not sure what you mean?

I would assume that using:

```Python
perm[perm < self._synPermTrimThreshold] = 0
```
There is a "check set" anyway? You can't escape the check. But now it's also done in an extra loop? But yeah, it's theoretical until tested I agree...

**Comment by oxtopus** [comment]
@scottpurdy is refering to the fact that numpy includes lots of optimizations implemented in C/C++, including the style of indexing described at http://docs.scipy.org/doc/numpy-1.10.0/reference/arrays.indexing.html#boolean-array-indexing

In other words, there's some magic happening behind the scenes when you assign values using that numpy-specific indexing scheme that takes advantage of native C/C++ better than if you were to perform the operations within the loop in the python runtime.

**Comment by cogmission** [comment]
@oxtopus Ah thanks! That was really confusing... :-P

**Comment by rhyolight** [comment]
If @scottpurdy and @oxtopus are not concerned about this, I'm not either.

**Comment by rhyolight** [comment]
@cogmission But thanks for lookin' out, bro. 😄
