### ISSUE TITLE
TM: Change three main functions into traditional methods

### ISSUE THREAD

**Issue by mrcslws** [numenta/nupic#3309]
In the TemporalMemory's [top-level column loop](https://github.com/numenta/nupic/blob/18ef587aba3654440dd8db20e87e2d96894e8b4c/src/nupic/research/temporal_memory.py#L167), we dispatch columns to one of three functions:

- activatePredictedColumn
- burstColumn
- punishPredictedColumn

These three functions exist for readability. We could paste their contents directly into the top-level loop, and that's originally how my code was written, but it made sense to "name" these procedures and move them out of the main loop.

These are actually static methods, which is essentially the same thing as a function.

There are two things here that I don't like:

- They take enormous argument lists. Almost every `self.*` attribute gets passed in. This adds potential for bugs, since you have to carefully get the parameters in the right order. And it makes the code harder to read. It's easier to understand code that you can fit on your screen all at once, and these long argument lists make it where you can't see the whole top-level column loop at once.
- It's a missed opportunity for extensibility. Even if we switch to overridable `classmethod`s, if the methods don't receive the `self` that severely limits the ability to add functionality. For example, the [FaultyTemporalMemory](https://github.com/numenta/nupic.research/blob/1d144224ad7ae5565c202e20952010e3eb9a5168/htmresearch/algorithms/faulty_temporal_memory.py) needs to access `self.deadCells`.

I'd like to convert these to traditional methods which receive a `self`, and stop passing in `self.*` parameters.

**Comment by oxtopus** [comment]
Yes, please!  The explicit dependency on `TemporalMemory.*` within those functions is something that has got in the way in my current efforts.  Proper instance methods would be nice, and passing `self.`_anything_ to a static method in the same class ought to be seen as an antipattern and opportunity for refactoring.

There might even be a slight, if perceptible performance improvement to inlining the functions, but it's not a big deal to me.

**Comment by cogmission** [comment]
@mrcslws Is there an end in sight? :-P

**Comment by rhyolight** [comment]
@cogmission said:
> @mrcslws Is there an end in sight? :-P

Software is never done!

**Comment by mrcslws** [comment]
I discussed with @scottpurdy. Here's a summary.

Our code should be organized as:

- Methods that contain almost no logic. They modify the `self`.
- Functions that don't receive a `self`. They receive all of their data explicitly. They can mutate data structures that are explicitly passed in, and/or they can return values.

Following these rules, our code is best as-is. If we chose to make these into non-static methods, we'd need to create new static methods that choose active cells, choose learning segments, etc., so it'd be the same code as today, just more spread around. The long argument lists will still exist, we'll just have more methods.

So I think that's a :-1:.

**Comment by rhyolight** [comment]
@mrcslws close the issue?

**Comment by oxtopus** [comment]
What about class methods as a compromise?

We have code some of the functions that explicitly call other functions on `TemporalMemory`.  By converting them to class methods, we can at least better support extensibility. 

For example:

```python
@classmethod
def burstColumn(cls, connections, random, column, matchingSegments,
                prevActiveCells, prevWinnerCells, cellsPerColumn,
                maxNewSynapseCount, initialPermanence, permanenceIncrement,
                permanenceDecrement, learn):

  ...

  if matchingSegments is not None:
    bestMatching = max(matchingSegments, key=lambda seg: seg.overlap)
    winnerCell = bestMatching.segment.cell

    if learn:
      cls.adaptSegment(connections, bestMatching.segment,
                       prevActiveCells, permanenceIncrement,
                       permanenceDecrement)

  ...
```

**Comment by mrcslws** [comment]
@oxtopus sure, that'd be a good change. Thanks for filing another issue https://github.com/numenta/nupic/issues/3316, I'll go ahead and close this one.

**Comment by oxtopus** [comment]
Proper PR at https://github.com/numenta/nupic/pull/3317 is ready for review
