### ISSUE TITLE
Do we have any timestamp that takes Nano seconds

### ISSUE THREAD

**Issue by komaldedhia** [numenta/nupic#3320]
Hi,
I want to use anomaly detection and my data contains time in nano seconds.  
Is there any way to represent datetime in nanoseconds?

Thanks and regards,
Komal.

**Comment by rhyolight** [comment]
Hi @komaldedhia! I answered your question on [our forum](https://discourse.numenta.org/t/why-cant-i-encode-time-in-very-small-increments-with-dateencoder/1356). That is the best place to get help.
