### ISSUE TITLE
Nupic wants loose dev requirements and concrete deployment requirements

### ISSUE THREAD

**Issue by rhyolight** [numenta/nupic#3326]
https://github.com/numenta/nupic.core/issues/1069 documents a new issue that interferes with nupic developers' need to use their own choice of nupic.bindings build. 

We're going to prototype an approach that places loose requirements in nupic's setup.py and concrete requirements in its requirements.txt. 

References 
* https://bitbucket.org/pypa/wheel/issues/172/wheel-doesnt-support-environment-markers 
* https://packaging.python.org/requirements/ 
* https://caremad.io/2013/07/setup-vs-requirement/ 
* https://www.python.org/dev/peps/pep-0440/

**Comment by oxtopus** [comment]
I think it would be a mistake to have dependencies defined in two places, which is why we are parsing requirements.txt in the first place.  If we were to maintain two standards for dependencies (loose in dev, strict in deployment), please try keep the dependencies specified in exactly one place.

**Comment by rhyolight** [comment]
Safe to close at this point, I think. We may readdress this later.
