### ISSUE TITLE
Bug in recursive AnomalyLikelihood calculation of left tail probabilities

### ISSUE THREAD

**Issue by BoltzmannBrain** [numenta/nupic#3336]
The [`normalProbability` method](https://github.com/numenta/nupic/blob/master/src/nupic/algorithms/anomaly_likelihood.py#L732) covers both tails of the Gaussian distribution by flipping values less than the mean. However, the current logic does this flip twice:

```
xp = 2 * distributionParams["mean"] - x
return 1.0 - normalProbability(xp, distributionParams)
```

should be

```
xp = 2 * distributionParams["mean"] - x
return normalProbability(xp, distributionParams)
```

I've implemented this and tested it on NAB, but oddly don't see different overall NAB scores.

**Comment by rhyolight** [comment]
> I've implemented this and tested it on NAB, but oddly don't see different overall NAB scores.

Seem troubling, doesn't it?

**Comment by scottpurdy** [comment]
Seems like the correct change to me. @subutai - do you see any problem with the proposed change?

**Comment by BoltzmannBrain** [comment]
Indeed @rhyolight. I've verified that the flip calculation indeed runs during NAB testing, but the exact same detections (and anomaly scores) result.
