### ISSUE TITLE
TM initialization parameters should be accessible via getter methods

### ISSUE THREAD

**Issue by rhyolight** [numenta/nupic#3342]
Just like the SP, the TM should expose the initialization parameters sent to its constructor through getter methods. This allows users to programmatically inspect the TM object to see how it was created. This is a list of initialization parameters that are not exposed.

### `maxSegmentsPerCell`
This param is used to create an instance of the `Connections` class, which exposes `maxSegmentsPerCell` as a public property. So it is possible to get this value from the TM with `tm.connections.maxSegmentsPerCell`, but a getter would make the TM API more direct.

> **Proposal**: add `tm.getMaxSegmentsPerCell()` function.

### `maxSynapsesPerSegment`
This param is used to create an instance of the `Connections` class, which exposes `maxSynapsesPerSegment` as a public property. So it is possible to get this value from the TM with `tm.connections.maxSynapsesPerSegment`, but a getter would make the TM API more direct.

> **Proposal**: add `tm.getMaxSynapsesPerSegment()` function.

**Comment by rhyolight** [comment]
@numenta/nupic-committers Any disagreements with this?

**Comment by oxtopus** [comment]
I disagree with the conclusion that they should be accessible via getters, but think it should have a `__repr__()` that is representative of its creation per intent described in https://docs.python.org/2/library/functions.html#func-repr

**Comment by subutai** [comment]
👍 I think we should be able to cleanly access everything from the outside.

**Comment by mrcslws** [comment]
👍 . Getters are good because it gives us a common interface with the C++ TM.

FYI there used to be a lot more inaccessible params. I added getters recently, and Andrew added them to the TM: https://github.com/numenta/nupic.research/commit/4a074cbe689ff995ce01d6ba1703679bee9fad78

**Comment by scottpurdy** [comment]
👍 

@oxtopus - I think having a good `repr` is a separate issue since I wouldn't want someone to have to parse the `repr` to extract some specific value they want programmatic access to.

**Comment by breznak** [comment]
Basically :+1: , I'd like to suggest a modification to the proposal: 
- make the classes accept params in `{json: 'format'}`, then we can have `get/setParams()` (w/o need of exact knowledge which params are there) - this will be useful for the parameter optimization algorithms.

**Comment by rhyolight** [comment]
@breznak That's a larger conversation, if you want to officially propose this, please create a new ticket so we don't pollute this simple discussion. Thanks! :)

**Comment by oxtopus** [comment]
I seem to recall prior discussion (invoking @cogmission here) suggesting a consistent "parameter set" object.  That seems like a good idea given the use case presented in this issue.
