### ISSUE TITLE
SpatialPooler.stripUnlearnedColumns()  Obsolete?

### ISSUE THREAD

**Issue by cogmission** [numenta/nupic#3345]
[The ```stripUnlearnedColumns()``` method](https://github.com/numenta/nupic/blob/master/src/nupic/research/spatial_pooler.py#L793) used to be called from the ```compute()``` method in the past, but is no longer referenced anywhere in the SpatialPooler class or by any other non-test code. [There are tests for it however](https://github.com/numenta/nupic/blob/master/tests/unit/nupic/research/spatial_pooler_unit_test.py#L330), but I'm wondering if the method should be removed since it appears to be unused?

**Comment by rhyolight** [comment]
Please comment @numenta/nupic-reviewers.

**Comment by scottpurdy** [comment]
@mrcslws can you look into this?

**Comment by mrcslws** [comment]
It might be safe to remove it, but I'm not sure. Somebody might find it useful, but we don't use it anywhere.

We turned off this method by default here: https://github.com/numenta/nupic/pull/1189/files

Then we moved the call to the SPRegion here: https://github.com/numenta/nupic/commit/9b456bd9b66b9110aafdae63f9b012f88a64de12

Then we removed it from the SPRegion here:
https://github.com/numenta/nupic/pull/2286

So little by little we've been abandoning it.

Somebody using a frozen Spatial Pooler (i.e. with learning disabled) might want to only activate columns that represent a learned spatial pattern, and ignore columns that are still just randomly initialized. This method gives them a way to do it. It's a way to filter the SP output.

**Comment by scottpurdy** [comment]
IIRC, it is a pretty useful thing if you know what you're doing. But it can be very confusing if you aren't expecting it so we made a conscious effort to make it optional. As NuPIC is an API, the fact that it isn't directly used isn't a problem. I say leave it. But perhaps we should add an example for how to use it.

**Comment by cogmission** [comment]
👍🏾
