### ISSUE TITLE
CLAModel requires "predictedField" when in "Anomaly" mode

### ISSUE THREAD

**Issue by cogmission** [numenta/nupic#3357]
The CLAModel throws an exception which forces the user to specify a "predicted field" even though there is no classifier specification.

[It exits from here if there is no classifier](https://github.com/numenta/nupic/blob/master/src/nupic/frameworks/opf/clamodel.py#L691) but it shouldn't be [in this method](https://github.com/numenta/nupic/blob/master/src/nupic/frameworks/opf/clamodel.py#L662) if that is the case to begin with? [This method should not be called](https://github.com/numenta/nupic/blob/master/src/nupic/frameworks/opf/clamodel.py#L662) when the configuration condition (which specifies no CLAClassifier or any other classifier) is true?

[The following error is thrown:](https://github.com/numenta/nupic/blob/master/src/nupic/frameworks/opf/clamodel.py#L684)
```console
Traceback (most recent call last):
  File "/Users/cogmission/git/lscheinkman/NAB/run.py", line 203, in <module>
    main(args)
  File "/Users/cogmission/git/lscheinkman/NAB/run.py", line 69, in main
    runner.detect(detectorConstructors)
  File "/Users/cogmission/git/lscheinkman/NAB/nab/runner.py", line 133, in detect
    self.pool.map(detectDataSet, args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/pool.py", line 251, in map
    return self.map_async(func, iterable, chunksize).get()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/pool.py", line 567, in get
    raise self._value
ValueError: No predicted field was enabled! Did you call enableInference()?
```

CLAModel wants this method ```(self.model.enableInference({"predictedField": "value"})``` to be called...

**Comment by rhyolight** [comment]
I think this makes sense. If the user only wants `TemporalAnomaly`, there is no reason to specify `predictedField`. 

The side effect of this is that predictions will no longer be available within anomaly model results. This may be acceptable, but there are many cases where you might want them in addition to anomaly scores and likelihoods. 

So for this to make me happy, the `predictedField` should be optional. If there is one specified, the model results should include predictions. If not, only anomalies.

**Comment by rhyolight** [comment]
I want to open this for further discussion amongst @numenta/nupic-committers.

**Comment by scottpurdy** [comment]
The CLAModel is an Online Prediction Framework (OPF) client. The OPF requires predictions for a specific field. If you want to do anomaly detection or predict multiple fields then you probably don't want the OPF. Just create a network with what you want.

**Comment by cogmission** [comment]
Hey Scott,
There's just a little bit of cognitive dissonance around the purposes, usage and standards for these things then.

The NAB NumentaDetector and NumentaTMDetector both instantiate CLAModels. If what you're saying is what should be the rule, then they shouldn't use CLAModels at all because its not appropriate in the context of NAB (@rhyolight says they _may_ be required to provide predictions; but not within a NAB context).

The problem is that the InferenceType ```InferenceType.TemporalAnomaly``` is used and the ```clEnable``` parameter is false within the ModelParams used to construct the CLAModel by the Numenta detectors. When this mode is specified there should be no reason to have to specify a "predictedField" for fear of an exception being thrown.

Otherwise like you say, CLAModels should not be used within NAB?

**Comment by scottpurdy** [comment]
> CLAModels should not be used within NAB?

Probably not, IMHO.

**Comment by rhyolight** [comment]
https://github.com/numenta/NAB/issues/275

**Comment by cogmission** [comment]
Also, _maybe_ there should be some work done to clarify that the mode ```InferenceType.TemporalAnomaly``` is _always_ used in _addition_ to predictions as well? Since the OPF _always_ does predictions, when Anomaly detection is also configured, it should be understood that it is always in addition to predictions and not _instead of_ predictions. (not mutually exclusive). 

Also, CLAModel may need some care and lovin' to update it with current usage because it [still refers to "reconstruction"](https://github.com/numenta/nupic/blob/2e1301e551a1e4367eaf1644c05781841aa5b3ba/src/nupic/frameworks/opf/clamodel.py#L396) and should probably have a PR dedicated to syncing it with current usage patterns?

**Comment by rhyolight** [comment]
Yes, I think this may just be a documentation issue. Perhaps https://github.com/numenta/NAB/issues/275 can be closed, still thinking about it. I have found the OPF useful to create anomaly models from swarm results, because you don't have to tune much at all.

**Comment by cogmission** [comment]
>  I have found the OPF useful to create anomaly models from swarm results, because you don't have to tune much at all.

No doubt. The way I understood it, anomaly models are perfectly fine - its just that it is understood that they are in addition to predictions and that it is not prediction or anomaly detection; but prediction or prediction _and_ anomaly detection?

**Comment by rhyolight** [comment]
Closing in favor of #3367.
