### ISSUE TITLE
Bamboo CI build-linux.sh requires local artifacts

### ISSUE THREAD

**Issue by oxtopus** [numenta/nupic#3376]
Early in the process of getting bamboo to build nupic, we operated under the assumption that a specific "artifact download" task would convey artifacts between jobs, resulting in this line: https://github.com/numenta/nupic/blob/master/ci/bamboo/build-linux.sh#L50, which installs the nupic.bindings from local working directory.

We've since decided to use pypi to host artifacts, so the line referenced above fails in its current form in the bamboo build plan.

**Comment by oxtopus** [comment]
In the interest in getting a green build, I have added the following to the bamboo build plan before it attempts to run the failing code:

```
apt-get update  
apt-get install -y curl 
mkdir -p wheelhouse
pushd wheelhouse
curl -O https://s3-us-west-2.amazonaws.com/artifacts.numenta.org/numenta/nupic.core/releases/nupic.bindings/nupic.bindings-0.4.9-cp27-none-linux_x86_64.whl
popd
```

Once this issue is resolved, we can remove this snippet.

**Comment by vitaly-krugl** [comment]
CC @scottpurdy @oxtopus 

Please note that per DEVOPS-184, this work has already been performed via https://github.com/numenta/nupic/pull/3355. This PR presently includes OSX and Win64 test logic that would need to be removed. Per Scott's instructions concerning DEVOPS-184, we extracted ubuntu configuration logic into separate scripts whose contents might subsequently be used in a Dockerfile to speed up the build and test. The corresponding Bamboo build is configured here: https://ci.numenta.com/browse/BS-NUPIC-TL.
