### ISSUE TITLE
docker 

### ISSUE THREAD

**Issue by masajirv** [numenta/nupic#3377]
I'm trying installing and running NuPIC with docker for windows.

At first, I installed Docker Toolbox for windows, because my windows edition is Window 7 Professional.
But I had some error in tests and examples.   
Is NuPIC coverd with Docker Toolbox?   Should I upgrade windows edition to 10 and install Docker not Docker Toolbox?

**Comment by rhyolight** [comment]
I don't know anything about Docker vs Docker Toolbox, sorry. I'm marking this as a duplicate of #3373.

You can ask for technical help on our forum at https://discourse.numenta.org/c/nupic

**Comment by masajirv** [comment]
Thank you for your advise! I'll try it!
