### ISSUE TITLE
TemporalMemory: Binary conducted w/o previous sort.

### ISSUE THREAD

**Issue by cogmission** [numenta/nupic#3379]
In ```growSynapses()``` the winner cells (wrapped in candidates list) is never sorted in any previous call site prior to conducting the [binary search here](https://github.com/numenta/nupic/blob/master/src/nupic/research/temporal_memory.py#L677).

Please excuse if this list is built up with cells in sequence, but I don't believe it is?

**Comment by rhyolight** [comment]
@numenta/nupic-committers Please comment?

**Comment by mrcslws** [comment]
The `activeCells` and `winnerCells` are always sorted since they're built up from walking the columns in order. The candidates list stays sorted as items are removed.

**Comment by mrcslws** [comment]
FYI, in C++ we assert this. https://github.com/numenta/nupic.core/blob/b2075e72ac5fe7da2fa17e1026f39aad2529627a/src/nupic/algorithms/TemporalMemory.cpp#L295

Python is usually run with asserts enabled, so it would be bad to have this assert in our Python code.

It's nice having asserts that don't run in Release builds. It makes code more readable.
