### ISSUE TITLE
Nupic uses a very old version of Numpy

### ISSUE THREAD

**Issue by JonnoFTW** [numenta/nupic#3396]
The version of numpy required in [requirements.txt](https://github.com/numenta/nupic/blob/master/requirements.txt) is 1.9.2. Nupic runs fine with the latest version of numpy (1.11.2). I haven't tried compiling nupic with the latest version though. I suggest you update the requirements to include the latest version so that when running a project that uses nupic  and numpy, we can make use of the latest performance improvements and APIs.

**Comment by rhyolight** [comment]
@numenta/nupic-committers Any objections? Are we leaving anyone behind by updating numpy?

**Comment by scottpurdy** [comment]
Probably fine to upgrade, just need to make sure it passes CI on all platforms. Also, it is more of a nupic.core issue since we have to compile against the headers. If it works there then it should be fine here.

**Comment by rhyolight** [comment]
@scottpurdy do we really need this in NuPIC's [`requirements.txt`](https://github.com/numenta/nupic/blob/master/requirements.txt#L21)?

    numpy==1.9.2

See also: https://github.com/numenta/nupic.core/issues/1140

**Comment by breznak** [comment]
@rhyolight I think we had errs for someone with older/newer releases..so let's see how the newest version fares.

**Comment by scottpurdy** [comment]
@rhyolight I don't understand your question. Yes, we need numpy with a specific version in `requirements.txt`. And we should update it in nupic when we update the version dependency on nupic.core to keep the versions of numpy in sync.

**Comment by rhyolight** [comment]
@scottpurdy Since NuPIC depends on nupic.core, which depends on numpy, I was just wondering if we could remove NuPIC's dependency on numpy. But maybe that's bad python practice, since it really does need numpy and there is nothing declaring that besides requirements.txt.

**Comment by oxtopus** [comment]
nupic has explicit dependencies on numpy independent of nupic.bindings.  numpy needs its own entry in requirements.txt like everything else AND it needs to be the same version as what is in nupic.bindings or else there will be a conflict.

**Comment by rhyolight** [comment]
Now that https://github.com/numenta/nupic.core/issues/1140 is fixed, nupic.core is using numpy 1.11.2. In order to fix this, we'll need to release a version of nupic.core and test it with nupic.
