### ISSUE TITLE
hello_tm.py fails because minThreshold value is higher than activationThreshold

### ISSUE THREAD

**Issue by Containerhouse** [numenta/nupic#3404]
Line 68: I propose to lower `minThreshold` from `10` to `8` so its value is not higher than the `activationThreshold` (set at `8`). 

https://github.com/numenta/nupic/blob/master/examples/tp/hello_tm.py#L68

**Comment by rhyolight** [comment]
@scottpurdy Make sense to you?

**Comment by scottpurdy** [comment]
@mrcslws changed the algorithm such that `minThreshold` cannot be higher than `activationThreshold`. That may not be the correct behavior though so we may want to change it back. Let me double check with @subutai and follow up after.

**Comment by subutai** [comment]
@scottpurdy Yes, `minThreshold` should never be higher than `activationThreshold`. They can be equal though.
