### ISSUE TITLE
remove weird "r" character before comment in SP

### ISSUE THREAD

**Issue by rhyolight** [numenta/nupic#3405]
Check this out:

https://github.com/numenta/nupic/blob/6924a904644bbb8cdba6ca7a62050cf8456614f8/src/nupic/research/spatial_pooler.py#L1303

How does that even work?

**Comment by SimLeek** [comment]
That r turns the comment into a raw string, keeping things like newlines. It shouldn't be necessary in a comment though.

**Comment by rhyolight** [comment]
Oh! Thanks for the python tip!
