### ISSUE TITLE
Unnecessary semicolons in multiple files.

### ISSUE THREAD

**Issue by SimLeek** [numenta/nupic#3408]
Pycharm highlighted a few unnecessary semicolons [here](https://github.com/numenta/nupic/blob/master/tests/unit/nupic/research/connections_test.py), and now I can't unsee them:

    # Let some time pass.
    connections.startNewIteration();
    connections.startNewIteration();
    connections.startNewIteration();

    # Create a segment with 3 synapse.
    segment2 = connections.createSegment(42)
    connections.createSynapse(segment2, 1, .5)
    connections.createSynapse(segment2, 2, .5)
    connections.createSynapse(segment2, 3, .5)
    connections.startNewIteration();

    # Give the first segment some activity.
    connections.recordSegmentActivity(segment1)

    # Create a new segment with 1 synapse.
    segment3 = connections.createSegment(42);
    connections.createSynapse(segment3, 1, .5)

Semicolons in python are used to write multiple function calls on the same line. Here, there's only one function per line, and python already separates functions by newlines, so the semicolons are redundant.

It technically doesn't affect anything at all... but... it irritates me slightly...

Using ctrl+shift+r in Pycharm and putting in the regex replacement ";\n" -> "\n" fixes the entire project in one go, removing what looks like 20 of those semicolons in different files. Just make sure to set file mask(s) to *.py so the *.capnp files are left alone and set context to ignore comments and string literals (though, I wonder about some of the semicolons at the ends of lines in the comments and strings too).

**Comment by mrcslws** [comment]
Ha, oops. I think this means I copy-pasted code from [the C++ version of this test](https://github.com/numenta/nupic.core/blob/037413df412e8df6056f8bfcfbe3a4fcc9a0cd93/src/test/unit/algorithms/ConnectionsTest.cpp#L128) and was in too much of a coding trance to notice the semicolons.

**Comment by SimLeek** [comment]
Ah, that makes sense.

Oh, in the future, if you need to copy-paste some C++ code into Python, you could use a few regex translations to speed things up!

C++ -> Python examples:

#Comments: ` (.*)//([^\n]*)` to `$1#$2`
->arrows: `->` to `.` (A normal replace would work too.)
functions: `([^\n]*);\n` to `$1`
Multi-line comments: `\/\*+((?:\n|.)*)\*\/` to `"""$1"""`
and then `\* *` to nothing.
