### ISSUE TITLE
running   ./scripts/run_nupic_tests.py  error!

### ISSUE THREAD

**Issue by yyccR** [numenta/nupic#3433]
the error is that:
![image](https://cloud.githubusercontent.com/assets/14156500/21448581/5c8b052e-c91f-11e6-991d-b6a5d3121beb.png)
the string "未找到命令" means that can not find the command.
can you tell me what happen?
and i have do this: 
export NUPIC=`pwd`

**Comment by yyccR** [comment]
i am  a fooler, i forgot to write the python command.

**Comment by rhyolight** [comment]
No worries! 😅
