### ISSUE TITLE
Ubuntu 14.04 : Pip Wheel Unsupported?

### ISSUE THREAD

**Issue by abrahamrhoffman** [numenta/nupic#3438]
pip install nupic
...
No distributions at all found for nupic.bindings==0.4.13 (from nupic)

pip install https://pypi.python.org/packages/37/88/7b729c3f1ec03b6c2905ae61e3762d64a275be52fc560611a3d22993e4bc/nupic.bindings-0.4.13-cp27-cp27mu-manylinux1_x86_64.whl
...
nupic.bindings-0.4.13-cp27-cp27mu-manylinux1_x86_64.whl is not a supported wheel on this platform

Perhaps the wheel was not certified for Linux?

**Comment by rhyolight** [comment]
That is strange, we are using manylinux to create the wheel. @vitaly-krugl do you know why this might happen?

**Comment by abrahamrhoffman** [comment]
Additionally:
git clone https://github.com/numenta/nupic.git
cd nupic
python setup.py install
...
Searching for nupic.bindings==0.4.16
Reading https://pypi.python.org/simple/nupic.bindings/
No local packages or working download links found for nupic.bindings==0.4.16
error: Could not find suitable distribution for Requirement.parse('nupic.bindings==0.4.16')

lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.5 LTS
Release:	14.04
Codename:	trusty

**Comment by abrahamrhoffman** [comment]
According to https://github.com/pypa/manylinux , there is wheel compatibility with pip v8.1+ . I had an older version of pip.

Fix: pip install pip --upgrade

Thanks Matt!
