### ISSUE TITLE
Potential API violation(s) in engine/__init__.py

### ISSUE THREAD

**Issue by oxtopus** [numenta/nupic#3446]
Consider the following snippet from the `CollectionWrapper` implementation in `engine/__init__.py`:

```python
  def keys(self):
    keys = set()
    for i in range(self.collection.getCount()):
      keys.add(self.collection.getByIndex(i)[0])
    return keys

  def values(self):
    values = set()

    for i in range(self.collection.getCount()):
      p = self.collection.getByIndex(i)
      values.add(self.valueWrapper(p[0], p[1]))
    return values

  def items(self):
    items = set()
    for i in range(self.collection.getCount()):
      p = self.collection.getByIndex(i)
      items.add((p[0], self.valueWrapper(p[0], p[1])))
    return items
```

Now, consider this snippet from the [Python documentation re: dict objects](https://docs.python.org/2/library/stdtypes.html#dict.items)...

> If items(), keys(), values(), iteritems(), iterkeys(), and itervalues() are called with no intervening modifications to the dictionary, the lists will directly correspond. This allows the creation of (value, key) pairs using zip(): pairs = zip(d.values(), d.keys()). The same relationship holds for the iterkeys() and itervalues() methods: pairs = zip(d.itervalues(), d.iterkeys()) provides the same value for pairs. Another way to create the same list is pairs = [(v, k) for (k, v) in d.iteritems()].

In Python, sets are unordered and because of their use in `CollectionWrapper.keys()` and `CollectionWrapper.values()`, and `CollectionWrapper.items()`, there's no guarantee of consistent ordering between the two, potentially resulting in a violation of the assumptions that `zip(d.keys(), d.values()) == d.items()` as is consistent with `dict` and `dict`-like objects in Python.

`CollectionWrapper.keys()` and `CollectionWrapper.values()` should iterate in the same order, producing lists (not sets).  `CollectionWrapper.items()` could then be simplified to something like:

```python
def items(self):
  return zip(self.keys(), self.values())
```

**Comment by rhyolight** [comment]
Very well-explained Austin, thanks.
