### ISSUE TITLE
Binary nupic 0.5.7 fails on Ubuntu 16.04 Xenial - capnp

### ISSUE THREAD

**Issue by breznak** [numenta/nupic#3457]
Installing nupic on an updated machine to ubuntu 16.04 Xenial (it used to run here in the past, even same OS version). 

Follow the guidelines, `pip install nupic` : 

```
(env) mmm@mmm-U2442:/mnt/store/devel/HTM/nupic-source$ pip list |grep nu
DEPRECATION: The default format will switch to columns in the future. You can use --format=(legacy|columns) (or define a format=(legacy|columns) in your pip.conf under the [list] section) to disable this warning.
numpy (1.11.2)
nupic (0.5.7, /mnt/store/devel/HTM/env/lib/python2.7/site-packages)
nupic.bindings (0.5.1)
```

Steps to reproduce: 
`py.test tests/unit`

Outputs many of (capnp related errors):
```
tests/unit/nupic/research/tp_test.py:36: in <module>
    from nupic.research import fdrutilities
../env/local/lib/python2.7/site-packages/nupic/research/fdrutilities.py:31: in <module>
    from nupic.bindings.math import (SM32, SparseBinaryMatrix)
../env/local/lib/python2.7/site-packages/nupic/bindings/math.py:72: in <module>
    _math = swig_import_helper()
../env/local/lib/python2.7/site-packages/nupic/bindings/math.py:68: in swig_import_helper
    _mod = imp.load_module('_math', fp, pathname, description)
E   ImportError: /mnt/store/devel/HTM/env/local/lib/python2.7/site-packages/nupic/bindings/_math.so: undefined symbol: _ZNK5capnp6Schema15requireUsableAsEPKNS_1_9RawSchemaE
========================================================================= 214 passed, 6 skipped, 56 error in 16.29 seconds ===================
```

This is a binary install. 
I get similar error with source build; with or w/o `libcapnp-dev` (0.5.3) installed on the system. 

Any ideas? Can I build w/o capnp serialization to be able to run? 
Thank you

**Comment by rhyolight** [comment]
Somehow, the wrong version of nupic.bindings is installed (0.5.1, which is tip of master).

Nupic 0.5.7 depends on nupic.bindings 0.4.13. See https://github.com/numenta/nupic/blob/0.5.7/requirements.txt#L20

Now, how did that new version get installed from `pip`?

**Comment by breznak** [comment]
Thanks Matt! Uninstalled (there were 2 versions of nupic "over each other", so that might have caused the 0.5.1 problem). 
Yes, `pip install nupic`, now bindings are at correct version, the error stays the same :(

**Comment by rhyolight** [comment]
Hmm, we build these binaries with manylinux. @vitaly-krugl have you see this error before?

    E   ImportError: /mnt/store/devel/HTM/env/local/lib/python2.7/site-packages/nupic/bindings/_math.so: undefined symbol: _ZNK5capnp6Schema15requireUsableAsEPKNS_1_9RawSchemaE

**Comment by pavelromashkin** [comment]
@rhyolight there are issues with running nupic install - it wants the latest nupic.bindings 0.5.1 which don't work with ubuntu. If you try to install nupic.bindings-0.5.1-cp27-cp27mu-manylinux1_x86_64.whl locally, it won't work.

**Comment by rhyolight** [comment]
@pavelromashkin Thanks for the tip. I wonder if any other manylinux Python/C++ modules are having similar problems on Ubuntu 16.

**Comment by breznak** [comment]
> there are issues with running nupic install - it wants the latest nupic.bindings 0.5.1 which don't work with ubuntu. 

Thank you for confirmation. Btw, I managed to manually install the 0.4.13 version as Matt pointed out, but the err is still the same. 

Any ideas to workaround temporarily? (disable capnp during build somehow?)

**Comment by vitaly-krugl** [comment]
@rhyolight, I haven't seen this issue before. Just noticed your question.

By the way, I think we should close this issue, since there is now https://github.com/numenta/nupic.core/issues/1230 open directly in nupic.core.
