### ISSUE TITLE
RandomDistributedScalarEncoder and SparsePassThroughEncoder are missing from nupic.encoders __init__.py

### ISSUE THREAD

**Issue by JonnoFTW** [numenta/nupic#3480]
All the encoders are in the [__init__.py](https://github.com/numenta/nupic/blob/master/src/nupic/encoders/__init__.py#L22-L35) for nupic.encoders except for
`RandomDistributedScalarEncoder` and `SparsePassThroughEncoder` are missing from nupic.encoders __init__.py

This makes it awkward when you want to import them since you need to do:
```
from nupic.encoders import random_distributed_scalar, ScalarEncoder
rdse = random_distributed_scalar.RandomDistributedScalarEncoder()
scalar_encoder = ScalarEncoder()
```

Ideally you should only need to:

```
from nupic.encoders import RandomDistributedScalarEncoder
rdse = RandomDistributedScalarEncoder()
```

**Comment by rhyolight** [comment]
Makes sense to me. @scottpurdy @mrcslws @oxtopus any objections?

**Comment by oxtopus** [comment]
👍

**Comment by scottpurdy** [comment]
Fine with me

**Comment by rhyolight** [comment]
@JonnoFTW Are you offering to help?

**Comment by JonnoFTW** [comment]
@rhyolight I'll make a pull request soon
