### ISSUE TITLE
Error when installing on Windows 10

### ISSUE THREAD

**Issue by tokyobro** [numenta/nupic#3493]
Hi, completely new to Github, Nupic and Python. My environment Dependencies should be OK. I did check through the issues hope I haven't missed anything. 
Any help is appreciated. 

PS C:\Users\..\Documents\Python2017> pip install nupic
Requirement already satisfied: nupic in c:\users\..\documents\python2017\nupic\src
Collecting asteval==0.9.1 (from nupic)
  Using cached asteval-0.9.1.tar.gz
Collecting coverage==3.7.1 (from nupic)
  Using cached coverage-3.7.1-cp27-none-win32.whl
Collecting mock==1.0.1 (from nupic)
  Using cached mock-1.0.1.zip
Collecting ordereddict==1.1 (from nupic)
  Using cached ordereddict-1.1.tar.gz
Collecting psutil==1.0.1 (from nupic)
  Using cached psutil-1.0.1.tar.gz
Collecting pytest==2.5.1 (from nupic)
  Using cached pytest-2.5.1.tar.gz
Collecting pytest-cov==1.6 (from nupic)
  Using cached pytest-cov-1.6.tar.gz
Collecting pytest-xdist==1.8 (from nupic)
  Using cached pytest-xdist-1.8.zip
Collecting python-dateutil==2.1 (from nupic)
  Using cached python-dateutil-2.1.tar.gz
Collecting PyYAML==3.10 (from nupic)
  Using cached PyYAML-3.10.tar.gz
Collecting unittest2==0.5.1 (from nupic)
  Using cached unittest2-0.5.1.zip
Collecting validictory==0.9.1 (from nupic)
  Using cached validictory-0.9.1.tar.gz
Collecting PyMySQL==0.6.2 (from nupic)
  Using cached PyMySQL-0.6.2-py2.py3-none-any.whl
Collecting DBUtils==1.1 (from nupic)
  Using cached DBUtils-1.1.tar.gz
Collecting pyproj==1.9.3 (from nupic)
  Using cached pyproj-1.9.3.tar.gz
    Complete output from command python setup.py egg_info:
    nad2bin.c
    nad2bin.c(106) : warning C4996: 'scanf': This function or variable may be unsafe. Consider using scanf_s instead. To
 disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.
            C:\Users\..\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0\VC\Include\stdio.h(306) : s
ee declaration of 'scanf'
    nad2bin.c(121) : warning C4996: 'scanf': This function or variable may be unsafe. Consider using scanf_s instead. To
 disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.
            C:\Users\..\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0\VC\Include\stdio.h(306) : s
ee declaration of 'scanf'
    nad2bin.c(129) : warning C4244: '=' : conversion from 'double' to 'float', possible loss of data
    nad2bin.c(130) : warning C4244: '=' : conversion from 'double' to 'float', possible loss of data
    nad2bin.c(133) : warning C4996: 'scanf': This function or variable may be unsafe. Consider using scanf_s instead. To
 disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.
            C:\Users\..\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0\VC\Include\stdio.h(306) : s
ee declaration of 'scanf'
    nad2bin.c(137) : warning C4244: '=' : conversion from 'double' to 'float', possible loss of data
    nad2bin.c(138) : warning C4244: '=' : conversion from 'double' to 'float', possible loss of data
    nad2bin.c(153) : warning C4996: 'fopen': This function or variable may be unsafe. Consider using fopen_s instead. To
 disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.
            C:\Users\..\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0\VC\Include\stdio.h(237) : s
ee declaration of 'fopen'
    nad2bin.c(174) : warning C4996: 'fopen': This function or variable may be unsafe. Consider using fopen_s instead. To
 disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.
            C:\Users\..\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0\VC\Include\stdio.h(237) : s
ee declaration of 'fopen'
    nad2bin.c(220) : warning C4996: 'fopen': This function or variable may be unsafe. Consider using fopen_s instead. To
 disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.
            C:\Users\..\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0\VC\Include\stdio.h(237) : s
ee declaration of 'fopen'
    nad2bin.c(352) : warning C4244: '=' : conversion from 'double' to 'float', possible loss of data
    nad2bin.c(353) : warning C4244: '=' : conversion from 'double' to 'float', possible loss of data
    pj_malloc.c
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "c:\users\..\appdata\local\temp\pip-build-ri___r\pyproj\setup.py", line 16, in <module>
        cc.link_executable(objects, execname)
      File "c:\python27\lib\distutils\ccompiler.py", line 700, in link_executable
        debug, extra_preargs, extra_postargs, None, target_lang)
      File "c:\python27\lib\distutils\msvc9compiler.py", line 669, in link
        raise LinkError(msg)
    distutils.errors.LinkError: command 'C:\\Users\\..\\AppData\\Local\\Programs\\Common\\Microsoft\\Visual C++ for P
ython\\9.0\\WinSDK\\Bin\\mt.exe' failed with exit status 255

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in c:\users\..\appdata\local\temp\pip-build-ri___r\pyproj

**Comment by TimKanake** [comment]
@tokyobro did you find a fix for this error? I am receiving the same exit status code while trying to install spacy.
