### ISSUE TITLE
Multidimensional spatial pooler

### ISSUE THREAD

**Issue by MedSolve** [numenta/nupic#3560]
Hi,

When i initiate my spatial pooler with the following, the input vector needs to be an array of 1x1024
`inputDimensions=(32,32)`

I find this highly strange since i am initiating a multidimension spatial pooler. Is this how the behavior is ment to be? I am using the python implementation and i will add environmental if this is actually a bug and not just a misunderstanding

**Comment by rhyolight** [comment]
Yes, this is how it is meant to be. This is in an effort to keep the data passed between nodes in an HTM network as simple as possible (a 1d list of bits). What these bits represent and how they are transformed are decided by how you configure your dimensions.
