### ISSUE TITLE
HTMPredictionModel predictedField init param never used

### ISSUE THREAD

**Issue by rhyolight** [numenta/nupic#3586]
The [`predictedField`](https://github.com/numenta/nupic/blob/master/src/nupic/frameworks/opf/htm_prediction_model.py#L120) init param, although [documented](https://github.com/numenta/nupic/blob/master/src/nupic/frameworks/opf/htm_prediction_model.py#L138), is never used.

Funny because I always thought this was really important @scottpurdy?

**Comment by scottpurdy** [comment]
You do have to specify the predicted field but apparently can't do it through the constructor as you point out. You have to call [enableInference](https://github.com/numenta/nupic/blob/c89603223b5c34f17b5d788cab5295038efab8d4/src/nupic/frameworks/opf/model.py#L155-L162) as [shown here](https://github.com/numenta/nupic/blob/c89603223b5c34f17b5d788cab5295038efab8d4/examples/opf/clients/hotgym/simple/hotgym.py#L68).
