### ISSUE TITLE
HTMPredictionModel sets/gets anomaly params incorrectly

### ISSUE THREAD

**Issue by rhyolight** [numenta/nupic#3587]
HTMPredictionModel calls [`setParameter`](https://github.com/numenta/nupic/blob/c89603223b5c34f17b5d788cab5295038efab8d4/src/nupic/frameworks/opf/htm_prediction_model.py#L317) and [`getParameter`](https://github.com/numenta/nupic/blob/c89603223b5c34f17b5d788cab5295038efab8d4/src/nupic/frameworks/opf/htm_prediction_model.py#L325) on its anomaly classifier improperly (does not include the `index` argument). The interface for ``PyRegion`` is:

    PyRegion.setParameter(self, name, index, value)
    PyRegion.getParameter(self, name, index)

In the code I liked above, these are called without the ``index`` argument in both cases.

I don't see where the HTMPredictionModel `setParameter`/`getParameter` functions are called in our codebase, so I don't think they are being tested.

**Comment by rhyolight** [comment]
Please review this @scottpurdy. Found will documenting.

**Comment by scottpurdy** [comment]
@rhyolight - what's the action item for me here?

**Comment by mrcslws** [comment]
I'm not sure there's a problem here. When you call `setParameter`, you're not calling the PyRegion `setParameter` directly. You're calling into this wrapper: https://github.com/numenta/nupic/blob/4bd9e6de3b2c94c28bda5e309745375f47c644c6/src/nupic/engine/__init__.py#L527

That wrapper calls into the appropriate C++ method, based on type, which then calls the PyRegion's `setParameter` method.

The wrapper doesn't take an index.

When someone calls `getParameter` or `setParameter` with an index, they must have called `getSelf()` and are circumventing this wrapper.

**Comment by mrcslws** [comment]
I haven't looked closely, but it seems strange that we hide that functionality in `__init__.py` rather than putting it in the bindings in nupic.core.

**Comment by rhyolight** [comment]
This just confused me because I could not tell what `setParameter` was being called upon.
