### ISSUE TITLE
nupic.framworks.opf.opf_utils.PredictionElement is never used

### ISSUE THREAD

**Issue by rhyolight** [numenta/nupic#3603]
As [described here](https://github.com/numenta/nupic/blob/17969b843e944c3a67fbb4cd7e049a6af585c91b/src/nupic/frameworks/opf/opf_utils.py#L271-L290):

```python
# PredictionElement- represents a predicted record and its asssociated
#                     bit-string encoding for a network's sensor region and/or
#                     the classification of that input as produced by
#                     a classifier.
#
# predictionRow:  A sequence of field values where each element is the predicted
#                 value in the format specified by getDecodedFieldMetaInfo().
#                 This is the output of topDownCompute() for each encoder
#
# predictionEncodings: A sequence of numpy arrays, where each element is the
#                      binary representation of the corresponding predicted field
#                      in "predictionRow".
#
# classification: The classification category of this input.
#

PredictionElement = namedtuple("PredictionElement",
                                ("predictionRow",
                                 "predictionEncodings",
                                 "classification"))
```

This named tuple is seemingly never used in our codebase. The only place I found even a vague reference was in [`tests/integration/nupic/opf/expgenerator_test.py`](https://github.com/numenta/nupic/blob/17969b843e944c3a67fbb4cd7e049a6af585c91b/tests/integration/nupic/opf/expgenerator_test.py#L406-L461), but the `test_PredictionElement` test does not use the named tuple, nor does any other code.

**Comment by rhyolight** [comment]
@scottpurdy comments?

**Comment by rhyolight** [comment]
Docs for PredictionElement also reference obsolete function `getDecodedFieldMetaInfo`.

**Comment by scottpurdy** [comment]
Probably fine to just remove it
