### ISSUE TITLE
Consider if Khoronos' NNEF NeuralNetwork Exchange Format is applicable for HTM

### ISSUE THREAD

**Issue by breznak** [numenta/nupic#3630]
..and plan to use it eventually. 

This would be great for interoperability and easier evaluation of HTM. 

http://www.eetimes.com/author.asp?section_id=36&doc_id=1331731

**Comment by breznak** [comment]
@rhyolight this may better fit the discourse forums..

**Comment by rhyolight** [comment]
Yes, please discuss there.
