### ISSUE TITLE
Failed building wheel for pycapnp

### ISSUE THREAD

**Issue by ankur-manikandan** [numenta/nupic#3643]
Hi, I seem to be having an issue while installing NuPic. I have tried installing it on two different systems, but I keep getting the same error. 

I use the following command to install NuPic: *pip install nupic*

The error I get is the same as:
https://gist.github.com/rhyolight/1dcf21845ce641363d795de94b4296c7

It seems like @rhyolight has come across this error before. 

Any help would be appreciated. 

Thanks,
Ankur

**Comment by rhyolight** [comment]
Are you using conda?

**Comment by ankur-manikandan** [comment]
Yes, I did download the anaconda package to install python and other libraries. I used Anaconda2 4.3.1

**Comment by rhyolight** [comment]
Thank you for confirming.

**Comment by ankur-manikandan** [comment]
Thanks for the help @rhyolight ! Appreciate it. I will look at the issue #3167 that you provided.

**Comment by iampatgrady** [comment]
Is there a plan to ever support environment?  Is there a way to install in spite of having Anaconda?
