### ISSUE TITLE
Resolution on unsigned >= 0 checks

### ISSUE THREAD

**Issue by breznak** [numenta/nupic#370]
enabled in `-Wextra`, for GCC: 
comparison of unsigned expression >= 0 is always true [-Wtype-limits]

or on Clang: tautological compare warning. 

We have `NTA_CHECK( 0 <= var && var <= MAX) << "var is out of range! "` serving as a gate. However the var is set to dattype `unsigned  int` hence the warning. My question is: remove the `var >= 0` condition and assume (IFF) someone decides to change var's type to signed to take care of the checking? Or we want to keep this, and place surpress #pragma to each relevant occurence? Or we just keep ignoring and mute Wtype-limits?

**Comment by rhyolight** [comment]
> So I will just enable Wextra and call this closed.

Is there a PR for this?

**Comment by breznak** [comment]
@rhyolight  closing as the checks have been fixed somewhen inbetween. and Wextra added in https://github.com/numenta/nupic.core/pull/273
