### ISSUE TITLE
./scripts/run_nupic_tests.py -u error on macOS Sierra

### ISSUE THREAD

**Issue by Baquetron** [numenta/nupic#3701]
Hi to everybody!
I´m a newbie here and just got stuck in the youtube tutorial on line ./scripts/run_nupic_tests.py -u
The thread seems to be similar to #3433 but I have not still figured it out.

<img width="794" alt="captura de pantalla 2017-06-12 a las 21 37 44" src="https://user-images.githubusercontent.com/26557195/27052535-3ebdb632-4fba-11e7-88c3-c4e3ba8b8a47.png">

Thanks for your help!

**Comment by rhyolight** [comment]
As stated in #3433, run `python ./scripts/run_nupic_tests.py -u`. ;)

**Comment by Baquetron** [comment]
Ups, that was easy

However I still get one error when running it
<img width="725" alt="captura de pantalla 2017-06-13 a las 0 44 46" src="https://user-images.githubusercontent.com/26557195/27058549-416f5d32-4fd2-11e7-9c93-700a81bf5cfd.png">

Seems to be something with capnp...
Thanks for your quick answer and for your tutorials, really like your method! Keep on

**Comment by rhyolight** [comment]
> Thanks for your quick answer and for your tutorials, really like your method! Keep on

😄 Thanks!

You may be running into backwards compatibility issues. I recently made a bunch of breaking changes, [here is how to fix it](https://discourse.numenta.org/t/warning-0-7-0-breaking-changes/2200/4?u=rhyolight). If that doesn't help, let me know. 

Otherwise, you might try manually installing [capnp](https://capnproto.org/install.html).

**Comment by Baquetron** [comment]
Finally done!

Just have to add `git checkout tags/0.8.0` and then run `python ./scripts/run_nupic_tests.py -u` saw on https://discourse.numenta.org/t/warning-0-7-0-breaking-changes/2200/4

Thanks again for your help!
