### ISSUE TITLE
unable to install nupic on ubuntu 16.04 LTS

### ISSUE THREAD

**Issue by pxc3113** [numenta/nupic#3729]
I'm using ubuntu 16.04 LTS and I have troubles installing nupic. The output after typing in "pip install nupic" is as follows:

zhiwei@zhiwei-Lenovo-Rescuer-15ISK:~$ pip install nupic
Collecting nupic
  Downloading nupic-0.8.0-py2-none-any.whl (4.8MB)
    100% |████████████████████████████████| 4.8MB 11kB/s 
Requirement already satisfied: pytest-cov==2.5.0 in /usr/local/lib/python2.7/dist-packages (from nupic)
Requirement already satisfied: unittest2==0.5.1 in /usr/local/lib/python2.7/dist-packages (from nupic)
Requirement already satisfied: DBUtils==1.1 in /usr/local/lib/python2.7/dist-packages (from nupic)
Requirement already satisfied: pytest-xdist==1.16.0 in /usr/local/lib/python2.7/dist-packages (from nupic)
Requirement already satisfied: mock==1.0.1 in /usr/local/lib/python2.7/dist-packages (from nupic)
Requirement already satisfied: asteval==0.9.1 in /usr/local/lib/python2.7/dist-packages (from nupic)
Requirement already satisfied: numpy==1.12.1 in /usr/local/lib/python2.7/dist-packages (from nupic)
Requirement already satisfied: validictory==0.9.1 in /usr/local/lib/python2.7/dist-packages (from nupic)
Requirement already satisfied: pyproj==1.9.3 in /usr/local/lib/python2.7/dist-packages (from nupic)
Requirement already satisfied: pytest==3.0.7 in /usr/local/lib/python2.7/dist-packages (from nupic)
Collecting pycapnp==0.5.12; platform_system == "Linux" or platform_system == "Darwin" (from nupic)
  Downloading pycapnp-0.5.12.tar.gz (454kB)
    100% |████████████████████████████████| 460kB 7.7kB/s 
Requirement already satisfied: coverage==3.7.1 in /usr/local/lib/python2.7/dist-packages (from nupic)
Collecting prettytable==0.7.2 (from nupic)
  Downloading prettytable-0.7.2.zip
Collecting psutil==1.0.1 (from nupic)
  Downloading psutil-1.0.1.tar.gz (156kB)
    100% |████████████████████████████████| 163kB 44kB/s 
Collecting python-dateutil==2.1 (from nupic)
  Downloading python-dateutil-2.1.tar.gz (152kB)
    100% |████████████████████████████████| 153kB 8.3kB/s 
Collecting ordereddict==1.1 (from nupic)
  Downloading ordereddict-1.1.tar.gz
Collecting nupic.bindings==0.7.0 (from nupic)
  Downloading nupic.bindings-0.7.0-cp27-cp27mu-manylinux1_x86_64.whl (3.9MB)
    100% |████████████████████████████████| 4.0MB 4.3kB/s 
Collecting PyMySQL==0.6.2 (from nupic)
  Downloading PyMySQL-0.6.2-py2.py3-none-any.whl (63kB)
    100% |████████████████████████████████| 71kB 3.4kB/s 
Collecting PyYAML==3.10 (from nupic)
  Downloading PyYAML-3.10.tar.gz (241kB)
    100% |████████████████████████████████| 245kB 4.9kB/s 
Requirement already satisfied: execnet>=1.1 in /usr/local/lib/python2.7/dist-packages (from pytest-xdist==1.16.0->nupic)
Requirement already satisfied: py>=1.4.22 in /usr/local/lib/python2.7/dist-packages (from pytest-xdist==1.16.0->nupic)
Requirement already satisfied: setuptools in /usr/lib/python2.7/dist-packages (from pytest==3.0.7->nupic)
Requirement already satisfied: six in /usr/local/lib/python2.7/dist-packages (from python-dateutil==2.1->nupic)
Requirement already satisfied: apipkg>=1.4 in /usr/local/lib/python2.7/dist-packages (from execnet>=1.1->pytest-xdist==1.16.0->nupic)
Building wheels for collected packages: pycapnp, prettytable, psutil, python-dateutil, ordereddict, PyYAML
  Running setup.py bdist_wheel for pycapnp ... error
  Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-STbTn5/pycapnp/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/tmprxBLSxpip-wheel- --python-tag cp27:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-2.7
  creating build/lib.linux-x86_64-2.7/capnp
  copying capnp/version.py -> build/lib.linux-x86_64-2.7/capnp
  copying capnp/__init__.py -> build/lib.linux-x86_64-2.7/capnp
  copying capnp/_gen.py -> build/lib.linux-x86_64-2.7/capnp
  copying capnp/__init__.pxd -> build/lib.linux-x86_64-2.7/capnp
  copying capnp/schema.capnp -> build/lib.linux-x86_64-2.7/capnp
  copying capnp/c++.capnp -> build/lib.linux-x86_64-2.7/capnp
  creating build/lib.linux-x86_64-2.7/capnp/helpers
  copying capnp/helpers/helpers.pxd -> build/lib.linux-x86_64-2.7/capnp/helpers
  copying capnp/helpers/non_circular.pxd -> build/lib.linux-x86_64-2.7/capnp/helpers
  copying capnp/helpers/__init__.pxd -> build/lib.linux-x86_64-2.7/capnp/helpers
  copying capnp/helpers/checkCompiler.h -> build/lib.linux-x86_64-2.7/capnp/helpers
  copying capnp/helpers/serialize.h -> build/lib.linux-x86_64-2.7/capnp/helpers
  copying capnp/helpers/capabilityHelper.h -> build/lib.linux-x86_64-2.7/capnp/helpers
  copying capnp/helpers/asyncHelper.h -> build/lib.linux-x86_64-2.7/capnp/helpers
  copying capnp/helpers/fixMaybe.h -> build/lib.linux-x86_64-2.7/capnp/helpers
  copying capnp/helpers/rpcHelper.h -> build/lib.linux-x86_64-2.7/capnp/helpers
  creating build/lib.linux-x86_64-2.7/capnp/includes
  copying capnp/includes/types.pxd -> build/lib.linux-x86_64-2.7/capnp/includes
  copying capnp/includes/schema_cpp.pxd -> build/lib.linux-x86_64-2.7/capnp/includes
  copying capnp/includes/capnp_cpp.pxd -> build/lib.linux-x86_64-2.7/capnp/includes
  copying capnp/includes/__init__.pxd -> build/lib.linux-x86_64-2.7/capnp/includes
  creating build/lib.linux-x86_64-2.7/capnp/lib
  copying capnp/lib/capnp.pxd -> build/lib.linux-x86_64-2.7/capnp/lib
  copying capnp/lib/__init__.pxd -> build/lib.linux-x86_64-2.7/capnp/lib
  copying capnp/lib/pickle_helper.py -> build/lib.linux-x86_64-2.7/capnp/lib
  copying capnp/lib/__init__.py -> build/lib.linux-x86_64-2.7/capnp/lib
  copying capnp/lib/capnp.pyx -> build/lib.linux-x86_64-2.7/capnp/lib
  creating build/lib.linux-x86_64-2.7/capnp/templates
  copying capnp/templates/setup.py.tmpl -> build/lib.linux-x86_64-2.7/capnp/templates
  copying capnp/templates/module.pyx -> build/lib.linux-x86_64-2.7/capnp/templates
  running build_ext
  creating /tmp/tmpaRQVW8/tmp
  cc -c /tmp/timer_createEoqclt.c -o /tmp/tmpaRQVW8/tmp/timer_createEoqclt.o
  /tmp/timer_createEoqclt.c:1:1: warning: return type defaults to ‘int’ [-Wimplicit-int]
   main (int argc, char **argv) {
   ^
  /tmp/timer_createEoqclt.c: In function ‘main’:
  /tmp/timer_createEoqclt.c:2:5: warning: implicit declaration of function ‘timer_create’ [-Wimplicit-function-declaration]
       timer_create();
       ^
  cc /tmp/tmpaRQVW8/tmp/timer_createEoqclt.o -o /tmp/tmpaRQVW8/a.out
  /tmp/tmpaRQVW8/tmp/timer_createEoqclt.o: In function `main':
  timer_createEoqclt.c:(.text+0x15): undefined reference to `timer_create'
  collect2: error: ld returned 1 exit status
  creating tmp
  creating tmp/tmpaRQVW8
  x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -c /tmp/tmpaRQVW8/vers.cpp -o tmp/tmpaRQVW8/vers.o --std=c++11
  cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
  /tmp/tmpaRQVW8/vers.cpp:4:26: fatal error: capnp/common.h: No such file or directory
  compilation terminated.
  *WARNING* no libcapnp detected or rebuild forced. Will download and build it from source now. If you have C++ Cap'n Proto installed, it may be out of date or is not being detected. Downloading and building libcapnp may take a while.
  fetching https://capnproto.org/capnproto-c++-0.5.3.1.tar.gz into /tmp/pip-build-STbTn5/pycapnp/bundled
  error: <urlopen error [Errno 110] Connection timed out>
  
  ----------------------------------------
  Failed building wheel for pycapnp
  Running setup.py clean for pycapnp
  Running setup.py bdist_wheel for prettytable ... done
  Stored in directory: /home/zhiwei/.cache/pip/wheels/b6/90/7b/1c22b89217d0eba6d5f406e562365ebee804f0d4595b2bdbcd
  Running setup.py bdist_wheel for psutil ... done
  Stored in directory: /home/zhiwei/.cache/pip/wheels/e6/08/44/7b1d25a298f1279063c2a0df3b4650ec2aae6b5d894ac64054
  Running setup.py bdist_wheel for python-dateutil ... done
  Stored in directory: /home/zhiwei/.cache/pip/wheels/8f/4c/08/00bc25800e712738588857793d79bbff317622d615aa53b481
  Running setup.py bdist_wheel for ordereddict ... done
  Stored in directory: /home/zhiwei/.cache/pip/wheels/cf/2c/b5/a1bfd8848f7861c1588f1a2dfe88c11cf3ab5073ab7af08bc9
  Running setup.py bdist_wheel for PyYAML ... done
  Stored in directory: /home/zhiwei/.cache/pip/wheels/cc/2a/d6/5a7108e2281e4c783740d79c40eac3ebc2d4157b1c7e4f17ef
Successfully built prettytable psutil python-dateutil ordereddict PyYAML
Failed to build pycapnp
Installing collected packages: pycapnp, prettytable, psutil, python-dateutil, ordereddict, nupic.bindings, PyMySQL, PyYAML, nupic
  Running setup.py install for pycapnp ... error
    Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-STbTn5/pycapnp/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-4mXp7n-record/install-record.txt --single-version-externally-managed --compile:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-STbTn5/pycapnp/setup.py", line 92, in <module>
        from Cython.Distutils import build_ext as build_ext_c
    ImportError: No module named Cython.Distutils
    
    ----------------------------------------
Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-STbTn5/pycapnp/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-4mXp7n-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-STbTn5/pycapnp/
zhiwei@zhiwei-Lenovo-Rescuer-15ISK:~$

**Comment by rhyolight** [comment]
It looks like you may have a problem with your g++ version. Make sure you have a compiler that can handle C++11?

**Comment by pxc3113** [comment]
Thanks for your attention. I'm a beginner in programming. Can you provide more detail on that? How can I install a compiler that can handle C++11?

**Comment by rhyolight** [comment]
ok closing this one.
