### ISSUE TITLE
change nyc taxi data file name

### ISSUE THREAD

**Issue by rhyolight** [numenta/nupic#3747]
`./src/nupic/datafiles/extra/nycTaxi/nyc_taxi.csv` should be `./src/nupic/datafiles/extra/nycTaxi/nycTaxi.csv`

**Comment by jlee124** [comment]
I'm a newcomer to open source and am looking for beginner issues to fix. Happy to fix this!

**Comment by agdenadel** [comment]
It looks like the PR for this issue has stalled. @rhyolight is it fine if I submit a PR to change it?

**Comment by rhyolight** [comment]
@agdenadel Sure! But you need to sign our contributor license at http://numenta.org/licenses/cl/

**Comment by agdenadel** [comment]
@rhyolight I did sign it and received the confirmation email. Is there anything on your end to see that I've submitted it?

**Comment by agdenadel** [comment]
@rhyolight you can close this issue.
