### ISSUE TITLE
Duplicate ID errors running nupic-bindings-check and unit tests

### ISSUE THREAD

**Issue by Ivorforce** [numenta/nupic#3759]
I'm getting these errors running the two commands:

[nupic-bindings-check](https://pastebin.com/xYWY95HA)

[tests/unit](https://pastebin.com/k6mza7Ue)

e.g. `E   KjException: /usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/nupic/encoders/sdr_category.capnp:0: failed: Duplicate ID @0x8017c9c04559354c.`

These are not my pastes - @pianomanfrazier uploaded them. I'm getting the exact same errors though. Perhaps you can chime in on this? I could not find an issue related to them.

I'm running latest master (f7618a911adfa50b7bd53e62fbccbc890680aa7f). pip freeze:

pycapnp==0.6.1
nupic==1.0.2.dev0
nupic.bindings==1.0.0

**Comment by rhyolight** [comment]
Thanks for reporting. I've seen [more than one](https://discourse.numenta.org/t/who-is-having-capnp-problems/2684) error against nupic 1.0+ recently about capnp issues. I'm trying to investigate.

**Comment by pianomanfrazier** [comment]
I wan't able to resolve this error. I compiled capnp from source and still had issues.

**Comment by rhyolight** [comment]
Ok, I apologize if you guys have reported this before on similar issues. These capnp dependency are hard to track down. Can you both please provide your:

- Operating system with as much detail as possible
- bits (32 or 64)
- installation method (source code or pip?) If source code, where did you get it?
- [nupic version](https://discourse.numenta.org/t/how-to-check-what-version-of-nupic-is-installed/1045)

**Comment by Ivorforce** [comment]
* macOS 10.12.6 (16G29)
* 64 bits
* I tried both, also (assuming it did work, I'm not 100% familiar with pip) from source running back quite far in the commit tree

**Comment by Ivorforce** [comment]
After running setup.py for --user as described in https://github.com/numenta/nupic/issues/2732#issuecomment-322728214 I was able to reinstall pycapnp and still run nupic. I'm guessing (/hoping) this fixed the problem entirely.

**Comment by rhyolight** [comment]
Let me know if you run into any more problems.

**Comment by Richardn2002** [comment]
I once encountered the Duplicate ID problem and solved it by the solution above(install nupic with --user) ,but recently i encountered it again and the solution didn't work.
After 2 days I find that deleting the 'capnp' folder from site-packages works. Write a note here for others to see :)
