### ISSUE TITLE
nupic install pycapnp trouble

### ISSUE THREAD

**Issue by Alex31416** [numenta/nupic#3760]
I ran into some difficulties when installing nupic on linux mint (64-bit). [The logs](https://github.com/numenta/nupic/files/1221100/nupic_log.txt) always mentioned failing to build pycapnp, so I tried installing that package separately and succeeded, [using these steps](http://jparyani.github.io/pycapnp/install.html) except with "curl -O https://capnproto.org/capnproto-c++-0.6.1.tar.gz" (0.5.0 is pretty old). But the nupic build wouldn't use the existing pycapnp until I changed setup.py ":platform_system=='Linux' or platform_system=='Darwin'":
        ["pycapnp==0.5.12"]
to the version I installed: ["pycapnp==0.6.1"]
After that, I was able to install nupic ("Successfully installed numpy-1.12.1 nupic-1.0.2.dev0 nupic.bindings-1.0.0"). So maybe that counts as a solution; up to you guys.

The tests run okay I think:
platform linux2 -- Python 2.7.12, pytest-3.0.7, py-1.4.34, pluggy-0.4.0
rootdir: /home/alex/Downloads/nupic-master, inifile:
plugins: xdist-1.16.0, cov-2.5.0
collected 734 items 

tests/unit/nupic/serializable_test.py ..
tests/unit/nupic/utils_test.py ......
tests/unit/nupic/algorithms/anomaly_likelihood_jeff_test.py ...ss..
tests/unit/nupic/algorithms/anomaly_likelihood_test.py .....................
tests/unit/nupic/algorithms/anomaly_test.py ..............
tests/unit/nupic/algorithms/backtracking_tm_constant_test.py ...
tests/unit/nupic/algorithms/backtracking_tm_cpp2_test.py .
tests/unit/nupic/algorithms/backtracking_tm_cpp_test.py .......
tests/unit/nupic/algorithms/backtracking_tm_test.py .......
tests/unit/nupic/algorithms/connections_test.py .........
tests/unit/nupic/algorithms/inhibition_object_test.py s
tests/unit/nupic/algorithms/knn_classifier_test.py .........s...
tests/unit/nupic/algorithms/sdr_classifier_test.py ...........................
tests/unit/nupic/algorithms/sp_learn_inference_test.py s
tests/unit/nupic/algorithms/sp_overlap_test.py .s.s
tests/unit/nupic/algorithms/spatial_pooler_boost_test.py ..
tests/unit/nupic/algorithms/spatial_pooler_compatability_test.py ...ss....
tests/unit/nupic/algorithms/spatial_pooler_compute_test.py ..
tests/unit/nupic/algorithms/spatial_pooler_cpp_api_test.py ............................
tests/unit/nupic/algorithms/spatial_pooler_cpp_unit_test.py ....
tests/unit/nupic/algorithms/spatial_pooler_py_api_test.py ............................
tests/unit/nupic/algorithms/spatial_pooler_unit_test.py s...................................
tests/unit/nupic/algorithms/temporal_memory_test.py ...............................s.....s.
tests/unit/nupic/algorithms/monitor_mixin/metric_test.py ..
tests/unit/nupic/algorithms/monitor_mixin/trace_test.py ..
tests/unit/nupic/data/aggregator_test.py .
tests/unit/nupic/data/dictutils_test.py ......
tests/unit/nupic/data/fieldmeta_test.py .....
tests/unit/nupic/data/file_record_stream_test.py ......
tests/unit/nupic/data/filters_test.py s
tests/unit/nupic/data/functionsource_test.py ......
tests/unit/nupic/data/inference_shifter_test.py ........
tests/unit/nupic/data/record_stream_test.py .......
tests/unit/nupic/data/utils_test.py .......
tests/unit/nupic/data/generators/anomalyzer_test.py ...........
tests/unit/nupic/data/generators/pattern_machine_test.py .........
tests/unit/nupic/data/generators/sequence_machine_test.py .....
tests/unit/nupic/docs/examples_test.py .xx.xxxxxx
tests/unit/nupic/encoders/adaptivescalar_test.py .......
tests/unit/nupic/encoders/category_test.py ..
tests/unit/nupic/encoders/coordinate_test.py .................
tests/unit/nupic/encoders/date_test.py ........
tests/unit/nupic/encoders/delta_test.py .....
tests/unit/nupic/encoders/geospatial_coordinate_test.py ...........
tests/unit/nupic/encoders/logenc_test.py ......
tests/unit/nupic/encoders/multi_test.py ..
tests/unit/nupic/encoders/pass_through_encoder_test.py ....
tests/unit/nupic/encoders/random_distributed_scalar_test.py ...............
tests/unit/nupic/encoders/scalar_test.py .............
tests/unit/nupic/encoders/scalarspace_test.py .
tests/unit/nupic/encoders/sdrcategory_test.py ...
tests/unit/nupic/encoders/sparse_pass_through_encoder_test.py .....
tests/unit/nupic/engine/network_test.py ...........
tests/unit/nupic/engine/syntactic_sugar_test.py .....
tests/unit/nupic/engine/unified_py_parameter_test.py ..
tests/unit/nupic/frameworks/opf/htmpredictionmodel_classifier_helper_test.py ......................
tests/unit/nupic/frameworks/opf/htmpredictionmodel_test.py ......
tests/unit/nupic/frameworks/opf/opf_metrics_test.py ...............................
tests/unit/nupic/frameworks/opf/previous_value_model_test.py .......
tests/unit/nupic/frameworks/opf/safe_interpreter_test.py ........
tests/unit/nupic/frameworks/opf/two_gram_model_test.py ......
tests/unit/nupic/frameworks/opf/common_models/cluster_params_test.py .
tests/unit/nupic/math/lgamma_test.py .
tests/unit/nupic/math/topology_test.py ....................
tests/unit/nupic/regions/anomaly_likelihood_region_test.py ...
tests/unit/nupic/regions/anomaly_region_test.py .
tests/unit/nupic/regions/knn_anomaly_classifier_region_test.py .....................
tests/unit/nupic/regions/knn_classifier_region_test.py .
tests/unit/nupic/regions/record_sensor_region_test.py ...
tests/unit/nupic/regions/regions_spec_test.py s...s......
tests/unit/nupic/regions/sdr_classifier_region_test.py ..
tests/unit/nupic/regions/tm_region_test.py ....
tests/unit/nupic/support/configuration_test.py ............s....................
tests/unit/nupic/support/custom_configuration_test.py ...................s.........................
tests/unit/nupic/support/decorators_test.py ............
tests/unit/nupic/support/group_by_test.py ......
tests/unit/nupic/support/object_json_test.py ...............
tests/unit/nupic/support/consoleprinter_test/consoleprinter_test.py .

============================ pytest-warning summary ============================
WC1 /home/alex/Downloads/nupic-master/tests/unit/nupic/engine/network_test.py cannot collect test class 'TestNode' because it has a __init__ constructor
WC1 /home/alex/Downloads/nupic-master/tests/unit/nupic/frameworks/opf/htmpredictionmodel_classifier_helper_test.py cannot collect test class 'TestOptionParser' because it has a __init__ constructor
WC1 /home/alex/Downloads/nupic-master/tests/unit/nupic/regions/knn_anomaly_classifier_region_test.py cannot collect test class 'TestOptionParser' because it has a __init__ constructor
WC1 /home/alex/Downloads/nupic-master/tests/unit/nupic/support/decorators_test.py cannot collect test class 'TestParentException' because it has a __init__ constructor
WC1 /home/alex/Downloads/nupic-master/tests/unit/nupic/support/decorators_test.py cannot collect test class 'TestChildException' because it has a __init__ constructor
==== 709 passed, 17 skipped, 8 xfailed, 5 pytest-warnings in 383.42 seconds ====

**Comment by rhyolight** [comment]
We do have some dependency problems with pycapnp. If you are not going to use [capnp for serialization](http://nupic.docs.numenta.org/1.0.1/guides/serialization.html) you should be ok to ignore these errors.
