### ISSUE TITLE
Can't pickle <class 'nupic.algorithms.backtracking_tm._SegmentUpdate'>

### ISSUE THREAD

**Issue by javitorl** [numenta/nupic#3763]
Hi, I got this error when saving a model

cPickle.PicklingError: Can't pickle <class 'nupic.algorithms.backtracking_tm._SegmentUpdate'>: attribute lookup nupic.algorithms.backtracking_tm._SegmentUpdate failed

It is easy to fix, just changing the last line en backtracking_tm.py

from 
SegmentUpdate = BacktrackingTM._SegmentUpdate
to
_SegmentUpdate = BacktrackingTM._SegmentUpdate

right?

**Comment by rhyolight** [comment]
@scottpurdy or @lscheinkman Please confirm is this a quick fix?

**Comment by lscheinkman** [comment]
@rhyolight I think it will fix. This class was renamed in a previous PR, the '_' was added later

**Comment by rhyolight** [comment]
Seems like something we'll need to do a bugfix for.
