### ISSUE TITLE
Date encoder setting for time of day?

### ISSUE THREAD

**Issue by benbastaki** [numenta/nupic#3778]
Hi, could you please tell me if the setting below is correct to encode Date input to Morning, Noon,Afternoon, Evening and night.
If it is not correct could you suggest a correct setting. I need this for anomaly detection for vital sign readings. 

'encoder_n': 6,
'timeOfDay': (21, 4)

**Comment by rhyolight** [comment]
This is not really a code issue, but a usage question. @benbastaki I'll be writing up a response to this with some better instructions on how to use the DateEncoder, but can we move this conversation to the [NuPIC Forum](https://discourse.numenta.org/c/nupic)?

**Comment by benbastaki** [comment]
Sorry was not sure where I can ask my question. yes please we can move it to the NuPIC Forum.

**Comment by rhyolight** [comment]
Great, can you create an account there and ask a question in the NuPIC forum? I have the answer I'll post it here and there when you're done. Thanks!

* * *

Here are the [DateEncoder docs](http://nupic.docs.numenta.org/1.0.3/api/algorithms/encoders.html#date-encoder):

![screen shot 2017-12-07 at 8 05 33 am](https://user-images.githubusercontent.com/15566/33724854-6bac328a-db25-11e7-94db-b0ac3e16b8e2.png)

So you only need to provide an integer for `timeOfDay` in the constructor, which means how long, in hours, the time window will be. The default is a 4-hour window, which gives you time periods like morning, afternoon, evening, early night, late night, etc.

**Comment by benbastaki** [comment]
Thanks for your answer, I also looked into the link which I have reviewed in the past.
To make it clear to myself so I should have  timeOfDay: (4)? this is the part I am confused!

**Comment by rhyolight** [comment]
Thanks for creating the forum post here, where we are continuing this discussion: https://discourse.numenta.org/t/dateencoder-and-example-of-timeofday-usage/3149/2
