### ISSUE TITLE
Error importing fieldmeta

### ISSUE THREAD

**Issue by fcabrera23** [numenta/nupic#3779]
When running Htmengine,i get error because of importation

from nupic.data import fieldmeta
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name fieldmeta

**Comment by rhyolight** [comment]
This is because the HTM Engine codebase has not been updated to use NuPIC 1.0. It still depends on 0.5.6. You must install NuPIC 0.5.6 to use HTM Engine.
