### ISSUE TITLE
Hi,Jeff Hawkins;

### ISSUE THREAD

**Issue by jiaxiaogang** [numenta/nupic#3785]
Hi,Jeff,我非常欣赏HTM及其作法和坚持;我想说的是:你为什么不去看看鲁利亚的三个联合区的理论;还有你可以参考CLIPS的方式,只是将其改为OOPIPS;试想这样的数据神经元之间的关联需要上万;并且能够解决知识表示的问题;另外还有一点提醒你;中国有本书叫<<道德经>>里面有"道生一,一生二,二生三,三生万物",还有"天得一以清,地得一以宁";希望我的信能够帮助到你;也希望你可以回信与我建立联系;thanks;

**Comment by rhyolight** [comment]
Jeff doesn't read this, and also he does not speak Chinese.

**Comment by jiaxiaogang** [comment]
I have contacted Jeff Hawkins via email, thank you;

**Comment by jiaxiaogang** [comment]
> Jeff doesn't read this, and also he does not speak Chinese.

The reason I'm showing you Luria's Three Functional Units Theory is because the cortex is a very important mystery, but research on the cortex would be hindered if other important components were missing.

Here is a brief summary of the theory:Luria's Three Functional Units Theory, proposed by neuropsychologist Alexander Luria, describes the brain as three interacting units for complex functions: Unit 1 (Arousal/Energy) from the brainstem for wakefulness; Unit 2 (Reception/Processing) in parietal, temporal, and occipital lobes for sensory input; and Unit 3 (Planning/Control) in the frontal lobe for directing behavior, goal-setting, and self-regulation. This model explains how brain damage affects specific functions and forms the basis for later models like the PASS theory (Planning, Attention, Simultaneous, Successive processing). 

In addition, I have some of my own work called the HE system. I divide the cortex from micro to macro into six parts: single sparse code (the smallest indivisible unit of information), group sparse code, single feature (local feature), group feature (feature with stronger holistic characteristics), concept (including three types of sensory input: general concept, behavioral concept, and value concept), and temporal sequence (including two types: scene temporal sequence and solution temporal sequence).

In addition to the macro-micro relationships mentioned above, it also has abstract and concrete relationships: it doesn't restrict the level of abstraction, but during reading, it only reads adjacent abstract levels for judgment or use, and nested relationships: referring to the relationship between the temporal sequence of the scenario and the temporal sequence of the solution.

There are many statistical values, such as strength, matching degree, stability, efficiency, perceived value, etc., used for statistics and to help with competition in subsequent identification or decision-making.

The above is only the network part; there is also the mind control part, which we can discuss another time.

Finally: I have done a lot of coding practice work. It learns knowledge completely from scratch and performs value judgments and decisions, including: input, perception, recognition, feedback, analogical inductive learning, prediction, perceived value, intentionality, planning, solving, transfer (referring to transferring the solution to a new scenario along the abstract concrete relationships), reflection, behavioralization, and output. Based on this, I have made several DEMOs for verification: image recognition, foraging, collision avoidance, and a tool DEMO (a bird throws nuts on the road to get them, letting a car crush the nut shells).

**Comment by jiaxiaogang** [comment]
No need to reply to me. I don't understand English. The English I sent was just translated using Google Translate.
