### ISSUE TITLE
Generated Code documentation info on cla model parameter configuration

### ISSUE THREAD

**Issue by akamlani** [numenta/nupic#379]
There are a lot of possible parameter values for a corresponding field label of the model parameters configuration.  It is unclear what these are other than looking at examples and grepping through the code base.

* MODEL_PARAMS in model_params.py, or config in description.py depending if using the custom OPF Client or OpfRunExperiment.
* Best if this would be generated by the code itself and placed in the top level directory, e.g. pydoc or doxygen since new possible parameter values are bound to change.
* Example fields of modelParams: 'inferenceType', 'encoders'->'type'
* Example fields of numeric based values.  What is the range (min, max) and acceptable values, and default values.  For example if you changed the 'minThreshold' or 'activationThreshold' in 'tpParams'.  

This would be a helpful guide for moving beyond the APIs and concentrating more on the configuration and metadata used by the APIs.

**Comment by rhyolight** [comment]
This issue has been closed because it is obsolete. 

![Obsolete Walkman](http://wtop.com/wp-content/uploads/2014/07/352730.jpg)

Replaced by #3207
