### ISSUE TITLE
Maintenance mode & further development

### ISSUE THREAD

**Issue by breznak** [numenta/nupic#3793]
Seeing the project has stabilized to v1.0 is great! 
It seems moved to the MAINTENANCE mode https://github.com/numenta/nupic/issues/2228#issuecomment-330929482 , 
so what does it mean for further active development? Feature-wise and implementation-wise. Is the focus moved to the nupic.core for that? 
All the best in 2018!

**Comment by rhyolight** [comment]
Thanks for the well-wishes Marek! For future development, it looks like a [community fork](https://discourse.numenta.org/t/nupic-core-c-bindings/3137) is emerging. They are working on Python 3 and C# bindings there.
