### ISSUE TITLE
run_swarm.py gives logging warning

### ISSUE THREAD

**Issue by JonnoFTW** [numenta/nupic#3803]
When running [/scripts/run_swarm.py](https://github.com/numenta/nupic/blob/master/scripts/run_swarm.py) and an error occurs, nothing is logged to stdout.

If you add these lines immediately below the imports, you will get sensible error reporting:
```
import logging
logging.basicConfig()
```
Doing this helped me fix the error where no password was set for mysql.

**Comment by rhyolight** [comment]
Seems like an easy fix. Do you want to create the PR?
