### ISSUE TITLE
Newbie - sine_experiment.py on Windows x64 error

### ISSUE THREAD

**Issue by benuzal** [numenta/nupic#3806]
Hi when I try to run sample code, I get the error, while executing swarm_over_data().
That is the error 'No handlers could be found for logger "nupic.database.client_jobs_dao" '
How can I fix this? 

![image](https://user-images.githubusercontent.com/6921642/36304620-5b4715ac-1321-11e8-81b4-1f55b82fa76e.png)

Thanks,

**Comment by benuzal** [comment]
This is solved after, install mysql server and edit "C:\Python\Python27\Lib\site-packages\nupic\support\nupic-default.xml" file for mysql root password. 
you need to enter your root password and install mysql server

**Comment by Gavin93-cn** [comment]
Hi, when you edited "nupic-default.xml" file, did the passwd re-read from default file?
