### ISSUE TITLE
ssl cert problem while installing nupic

### ISSUE THREAD

**Issue by colingoldberg** [numenta/nupic#3829]
Trying to install nupic on a mac that has python 2.7...

$ pip install nupic got the following error:
Collecting nupic
  Could not fetch URL https://pypi.python.org/simple/nupic/: There was a problem confirming the ssl certificate: [SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:590) - skipping
  Could not find a version that satisfies the requirement nupic (from versions: )
No matching distribution found for nupic

I then tried the following:
$ cd /usr/local/share
$git clone https://github.com/numenta/nupic.git
- succeeded
$ cd nupic
$ pip install .

- and I get:
$ pip install .
Processing /usr/local/share/numenta/nupic
Collecting asteval==0.9.1 (from nupic==1.0.5.dev0)
  Could not fetch URL https://pypi.python.org/simple/asteval/: There was a problem confirming the ssl certificate: [SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:590) - skipping
  Could not find a version that satisfies the requirement asteval==0.9.1 (from nupic==1.0.5.dev0) (from versions: )
No matching distribution found for asteval==0.9.1 (from nupic==1.0.5.dev0)

Running on mac os x 10.9.5
Python 2.7.12
pip 9.0.1 from /System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages (python 2.7)

Any help is appreciated.

Colin Goldberg

**Comment by rhyolight** [comment]
I have never seen this type of problem reported during installation. Can you try installing again with `pip install nupic`?

**Comment by colingoldberg** [comment]
I got the same error message.

    $ pip install nupic
    Collecting nupic
    Could not fetch URL https://pypi.python.org/simple/nupic/: There was a problem confirming the ssl certificate: [SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:590) - skipping
    Could not find a version that satisfies the requirement nupic (from versions: )
    No matching distribution found for nupic

Is there a workaround I can use? As I mentioned above, I downloaded the repository and tried pip install . (inside the directory), but got a similar ssl cert message for 'asteval'.

Colin Goldberg

**Comment by colingoldberg** [comment]
I tried a suggested upgrade of pip as per https://stackoverflow.com/questions/49768770/not-able-to-install-python-packages-ssl-tlsv1-alert-protocol-version
ie.
    curl https://bootstrap.pypa.io/get-pip.py | python

    $ pip --version
    pip 10.0.0 from /System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pip (python 2.7)

But it fails, with the following output:
`
$ sudo -H pip install nupic
Collecting nupic
  Downloading nupic-1.0.4-py2-none-any.whl (4.8MB)
    100% |████████████████████████████████| 4.8MB 169kB/s 
Collecting PyYAML==3.10 (from nupic)
  Downloading PyYAML-3.10.tar.gz (241kB)
    100% |████████████████████████████████| 245kB 113kB/s 
Collecting coverage==3.7.1 (from nupic)
  Downloading coverage-3.7.1.tar.gz (284kB)
    100% |████████████████████████████████| 286kB 979kB/s 
Collecting psutil==1.0.1 (from nupic)
  Downloading psutil-1.0.1.tar.gz (156kB)
    100% |████████████████████████████████| 163kB 269kB/s 
Collecting DBUtils==1.1 (from nupic)
  Downloading DBUtils-1.1.tar.gz (109kB)
    100% |████████████████████████████████| 112kB 109kB/s 
Collecting python-dateutil==2.1 (from nupic)
  Downloading python-dateutil-2.1.tar.gz (152kB)
    100% |████████████████████████████████| 153kB 209kB/s 
Collecting validictory==0.9.1 (from nupic)
  Downloading validictory-0.9.1.tar.gz
Requirement already satisfied: numpy==1.12.1 in /System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages (from nupic) (1.12.1)
Collecting pytest-xdist==1.16.0 (from nupic)
  Downloading pytest-xdist-1.16.0.tar.gz (88kB)
    100% |████████████████████████████████| 92kB 18kB/s 
    Complete output from command python setup.py egg_info:
    Download error on https://pypi.python.org/simple/setuptools_scm/: [SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:590) -- Some packages may not be found!
    Download error on https://pypi.python.org/simple/setuptools-scm/: [SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:590) -- Some packages may not be found!
    Couldn't find index page for 'setuptools_scm' (maybe misspelled?)
    Download error on https://pypi.python.org/simple/: [SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:590) -- Some packages may not be found!
    No local packages or working download links found for setuptools_scm
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/tmp/pip-install-zLPWff/pytest-xdist/setup.py", line 37, in <module>
        'Programming Language :: Python :: 3',
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/core.py", line 111, in setup
        _setup_distribution = dist = klass(attrs)
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/setuptools/dist.py", line 318, in __init__
        self.fetch_build_eggs(attrs['setup_requires'])
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/setuptools/dist.py", line 375, in fetch_build_eggs
        replace_conflicting=True,
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pkg_resources/__init__.py", line 851, in resolve
        dist = best[req.key] = env.best_match(req, ws, installer)
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1123, in best_match
        return self.obtain(req, installer)
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1135, in obtain
        return installer(requirement)
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/setuptools/dist.py", line 443, in fetch_build_egg
        return cmd.easy_install(req)
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 667, in easy_install
        raise DistutilsError(msg)
    distutils.errors.DistutilsError: Could not find suitable distribution for Requirement.parse('setuptools_scm')
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/tmp/pip-install-zLPWff/pytest-xdist/
`

Is anyone working on a python 3 update to nupic? Is it worth my while to attempt this? (even as I don't have a lot of python experience).

Colin Goldberg

**Comment by colingoldberg** [comment]
I tried - and succeeded - installing nupic on a DigitalOcean instance. So I guess I will use this instead of breaking my head on my macbook pro (that has python 2.7).

I do wonder, however, about (my) attempting to update nupic for python 3.6 - would it be too much?

Colin Goldberg

**Comment by rhyolight** [comment]
Colin, thanks for your attempts. I'm not sure why this is happening for you on your Mac. I've never gotten a report of this error before. There are folks on [HTM Forum working on a form of NuPIC with python 3 support](https://discourse.numenta.org/t/proposal-to-introduce-pybind-for-move-toward-python-3-compatibility/3110/97).

**Comment by shahardror** [comment]
Hi, I am getting the exact same error messages when trying to install nupic in a python 2.7 virtualenv, on Windows. Can you please help and try to explain what these messages mean in order to overcome them? thank you!

**Comment by jpgong** [comment]
> Hi, I am getting the exact same error messages when trying to install nupic in a python 2.7 virtualenv, on Windows. Can you please help and try to explain what these messages mean in order to overcome them? thank you!

@shahardror 
Maybe the pip version is too low, the following method solved my problem
pip install setuptools-scm
pip install --upgrade pip
pip install setuptools -U

For detailed description please see
https://stackoverflow.com/questions/67603407/distutilserror-could-not-find-suitable-distribution-for-requirement-parsesetu
