### ISSUE TITLE
trouble installing Nupic in Yosemite Mac

### ISSUE THREAD

**Issue by pvilloslada** [numenta/nupic#3834]
Hi. I tried to install Nupic in my Mac running Yosemite iOS and using Python 2.7 and have tried to download several libraries but always received this error message
"python setup.py egg_info" failed with error code 1 in /private/tmp/pip-install-NAJoQw/nupic.bindings/
Let me know if you have been able to solve before

**Comment by rhyolight** [comment]
What command exactly did you use to install?

**Comment by pvilloslada** [comment]
Hi Matthew

thank you for your help!

I tried "pip install nupic" then run intro troubles because of nupic.bindings. After a quick search I found out nupic.bindings should be installed previously, however when doing "pip install nupic.binding" I found this error.

best regards

Pablo

**Comment by rhyolight** [comment]
So I can see your original error, please run the following and paste the output here:

```
pip uninstall nupic -y
pip install nupic
``

I'd like to see the error you get.

**Comment by pvilloslada** [comment]
Hi

Thank you so much for your help. This is the error I got when trying to instal nupic

Could not find a version that satisfies the requirement nupic.bindings==1.0.4 (from nupic) (from versions: 0.1.3, 0.1.5, 0.2, 0.2.1, 0.2.2, 0.2.3, 0.2.4, 0.2.5, 0.2.7, 0.3.0, 0.3.1, 0.4.0, 0.4.1, 0.4.2, 0.4.3, 0.4.4, 0.4.5, 0.4.6, 0.4.7, 0.4.8, 0.4.9, 0.4.10.dev0, 0.4.10, 0.4.12, 0.4.13, 0.4.14, 0.4.15, 0.4.16, 0.5.0, 0.5.1, 0.5.3, 0.6.0, 0.6.1, 1.0.1)
No matching distribution found for nupic.bindings==1.0.4 (from nupic)

Let me know if you have seen it before

best regards

Pablo

**Comment by rhyolight** [comment]
I sorry, but we don't have a binary installation file for Yosemite in pypi. I can direct you in compiling from source code if you are interested in trying.

**Comment by pvilloslada** [comment]
Thank you for your replay!

I am going to upgrade the OS of my Mac to Sierra and check if it works fine. I/ll keep you posted

best regards

Pablo

On 09 May, 2018, at 05:38 PM, Matthew Taylor <notifications@github.com> wrote:

I sorry, but we don't have a binary installation file for Yosemite in pypi. I can direct you in compiling from source code if you are interested in trying.

**Comment by pvilloslada** [comment]
Hi

I have updgraded the mac OS to High Sierra 10.13.4 (17E199). Second, I have swtiched python2 from Anaconda to HomeBrew. Third, I have upgradedd cc. Now, I have received a new error 

Failed building wheel for pycapnp
  Running setup.py clean for pycapnp
Failed to build pycapnp
Installing collected packages: pycapnp, nupic.bindings, DBUtils, nupic
  Running setup.py install for pycapnp ... error
    Complete output from command /usr/local/opt/python@2/bin/python2.7 -u -c "import setuptools, tokenize;__file__='/private/var/folders/3w/3t0vz6yx5_1g___7kh9m0mkm0000gn/T/pip-install-0oXZHk/pycapnp/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /private/var/folders/3w/3t0vz6yx5_1g___7kh9m0mkm0000gn/T/pip-record-H1Ya0D/install-record.txt --single-version-externally-managed --compile --user --prefix=:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/3w/3t0vz6yx5_1g___7kh9m0mkm0000gn/T/pip-install-0oXZHk/pycapnp/setup.py", line 92, in <module>
        from Cython.Distutils import build_ext as build_ext_c
    ImportError: No module named Cython.Distutils
    
    ----------------------------------------
Command "/usr/local/opt/python@2/bin/python2.7 -u -c "import setuptools, tokenize;__file__='/private/var/folders/3w/3t0vz6yx5_1g___7kh9m0mkm0000gn/T/pip-install-0oXZHk/pycapnp/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /private/var/folders/3w/3t0vz6yx5_1g___7kh9m0mkm0000gn/T/pip-record-H1Ya0D/install-record.txt --single-version-externally-managed --compile --user --prefix=" failed with error code 1 in /private/var/folders/3w/3t0vz6yx5_1g___7kh9m0mkm0000gn/T/pip-install-0oXZHk/pycapnp/

I have this version of pip 

pip 10.0.1 from /usr/local/lib/python2.7/site-packages/pip (python 2.7)

do you have any suggestion?

best regards

Pablo

**Comment by rhyolight** [comment]
What command are you running to get that error?

**Comment by rhyolight** [comment]
Now that you have a fresh OS, let's try to clean it up and make sure we are starting from scratch. Please run these lines a few times (until it says they are not installed)

```
pip uninstall nupic -y
pip uninstall nupic-bindings -y
```

Now that everything is uninstalled, try running this again:

```
pip install --user nupic
```

Please save your output from these commands if there are errors and paste them here.

**Comment by pvilloslada** [comment]
Dear Matthew

I have followed your indications. Unfortunately I got the same message

Macintosh-114:~ pablo$ pip uninstall nupic -y
Skipping nupic as it is not installed.
Macintosh-114:~ pablo$ pip uninstall nupic-bindings -y
Skipping nupic-bindings as it is not installed.
Macintosh-114:~ pablo$ pip install --user nupic
Collecting nupic

…..


Failed building wheel for pycapnp
  Running setup.py clean for pycapnp
Failed to build pycapnp
Installing collected packages: pycapnp, nupic.bindings, DBUtils, nupic
  Running setup.py install for pycapnp ... error
    Complete output from command /usr/local/opt/python@2/bin/python2.7 -u -c "import setuptools, tokenize;__file__='/private/var/folders/3w/3t0vz6yx5_1g___7kh9m0mkm0000gn/T/pip-install-Ro6djP/pycapnp/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /private/var/folders/3w/3t0vz6yx5_1g___7kh9m0mkm0000gn/T/pip-record-Qe0saw/install-record.txt --single-version-externally-managed --compile --user --prefix=:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/3w/3t0vz6yx5_1g___7kh9m0mkm0000gn/T/pip-install-Ro6djP/pycapnp/setup.py", line 92, in <module>
        from Cython.Distutils import build_ext as build_ext_c
    ImportError: No module named Cython.Distutils
    
    ----------------------------------------
Command "/usr/local/opt/python@2/bin/python2.7 -u -c "import setuptools, tokenize;__file__='/private/var/folders/3w/3t0vz6yx5_1g___7kh9m0mkm0000gn/T/pip-install-Ro6djP/pycapnp/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /private/var/folders/3w/3t0vz6yx5_1g___7kh9m0mkm0000gn/T/pip-record-Qe0saw/install-record.txt --single-version-externally-managed --compile --user --prefix=" failed with error code 1 in /private/var/folders/3w/3t0vz6yx5_1g___7kh9m0mkm0000gn/T/pip-install-Ro6djP/pycapnp/


could be this related with the version of pythons installed in my Macbook?

best regards

Pablo

**Comment by rhyolight** [comment]
Sorry you are having trouble. I don't know what the problem is. Perhaps you just need to install cython? The only other thing I know to suggest is that you try to [compile nupic.core locally](https://github.com/numenta/nupic.core#building-from-source).

**Comment by pvilloslada** [comment]
Thank you again! I think this may be related with the several version of python I have installed along time…

I am going to try your suggestions

regards

Pablo Villoslada

**Comment by rhyolight** [comment]
Oh yeah... python version problems are the worst on a mac. I've been through it. At one point I ended up starting from scratch. I've had success with homebrew python and system python together, but not always. I can't get anaconda to work. Good luck.

**Comment by pvilloslada** [comment]
yes, this is what I am going to do it, starting again from scratch and try homebrew python

Pablo

**Comment by pvilloslada** [comment]
Dear Matthew

I have followed all options you suggested plus some others from the web… now I get this error which seems related with the code

    error: command 'clang' failed with exit status 1

I have also tried to install locally but the same error appeared. Let me know if you have any suggestion

If you or some of your collaborators at Numenta have some time in the following weeks, I can stop any afternoon at your offices in Redwood city in my way back home

best regards

Pablo Villoslada

**Comment by rhyolight** [comment]
@pvilloslada Sure, please email me at matt@numenta.org.
