### ISSUE TITLE
py.test tests/unit failure (1 out of 738)

### ISSUE THREAD

**Issue by colingoldberg** [numenta/nupic#3836]
Just in case this helps, I am posting the "Failures" output from py.test tests/unit

platform linux2 -- Python 2.7.12, pytest-3.0.7, py-1.5.3, pluggy-0.4.0
rootdir: /usr/local/share/numenta/nupic, inifile:
plugins: xdist-1.16.0, cov-2.5.0
collected 738 items 
...
================================================================= FAILURES ==================================================================
___________________________________________________ SDRClassifierTest.testSoftMaxOverflow ___________________________________________________

self = <tests.unit.nupic.algorithms.sdr_classifier_test.SDRClassifierTest testMethod=testSoftMaxOverflow>

    def testSoftMaxOverflow(self):
      """
        Test if the softmax normalization overflows
        """
      c = SDRClassifier([1], 1.0, 0.1, 0)
      weight = numpy.array([[sys.float_info.max_exp + 1]])
      res = c.inferSingleStep([0], weight)
>     self.assertFalse(numpy.isnan(res), "SoftMax overflow")
E     AssertionError: array([ True], dtype=bool) is not False : SoftMax overflow

tests/unit/nupic/algorithms/sdr_classifier_test.py:799: AssertionError
----------------------------------------------------------- Captured stderr call ------------------------------------------------------------
/usr/local/lib/python2.7/dist-packages/nupic/algorithms/sdr_classifier.py:377: RuntimeWarning: overflow encountered in exp
  expOutputActivation = numpy.exp(outputActivation)
/usr/local/lib/python2.7/dist-packages/nupic/algorithms/sdr_classifier.py:378: RuntimeWarning: invalid value encountered in divide
  predictDist = expOutputActivation / numpy.sum(expOutputActivation)
========================================================== pytest-warning summary ===========================================================
WC1 /usr/local/share/numenta/nupic/tests/unit/nupic/engine/network_test.py cannot collect test class 'TestNode' because it has a __init__ constructor
WC1 /usr/local/share/numenta/nupic/tests/unit/nupic/frameworks/opf/htmpredictionmodel_classifier_helper_test.py cannot collect test class 'TestOptionParser' because it has a __init__ constructor
WC1 /usr/local/share/numenta/nupic/tests/unit/nupic/regions/knn_anomaly_classifier_region_test.py cannot collect test class 'TestOptionParser' because it has a __init__ constructor
WC1 /usr/local/share/numenta/nupic/tests/unit/nupic/support/decorators_test.py cannot collect test class 'TestParentException' because it has a __init__ constructor
WC1 /usr/local/share/numenta/nupic/tests/unit/nupic/support/decorators_test.py cannot collect test class 'TestChildException' because it has a __init__ constructor
============================= 1 failed, 712 passed, 17 skipped, 8 xfailed, 5 pytest-warnings in 326.69 seconds ==============================

Run on DigitalOcean Ubuntu 16.04
Python 2.7.12

**Comment by rhyolight** [comment]
Please run unit tests with this command:

    python ./scripts/run_nupic_tests.py -u

Is the output the same? Also be sure to pull tip of master because we have made changes recently.

**Comment by ilialexander** [comment]
Hi LunaAmour,

I was having the same issue. I solved it by uninstalling nupic and using the --user option for installation.

Let me know if this is of any help.

**Comment by DeepakVellampalli** [comment]
Hello guys!
Even I faced the same error while running "py.test tests/unit". As per your suggestion @ilialexander I reinstalled Nupic using "--user" option. After that "python ./scripts/run_nupic_tests.py -u" neither gave an error nor gave any type of output. Should I assume that everything got fixed?
However, "py.test tests/unit" still gives the same error. 

P.S :  This solution of using "--user" installs the package globally and deprives the benefit of using virtual environment.

**Comment by rvsandeep** [comment]
`tests/unit/nupic/docs/examples_test.py::ExamplesTest::testFiveStepConfidencesOpfVsNetwork <- ../../.local/lib/python2.7/site-packages/unittest2/case.py xfail
tests/unit/nupic/docs/examples_test.py::ExamplesTest::testFiveStepPredictionsOpfVsNetwork <- ../../.local/lib/python2.7/site-packages/unittest2/case.py xfail
tests/unit/nupic/docs/examples_test.py::ExamplesTest::testNumberOfOneStepPredictions PASSED
tests/unit/nupic/docs/examples_test.py::ExamplesTest::testOneStepConfidencesAlgoVsNetwork <- ../../.local/lib/python2.7/site-packages/unittest2/case.py xfail
tests/unit/nupic/docs/examples_test.py::ExamplesTest::testOneStepConfidencesOpfVsAlgo <- ../../.local/lib/python2.7/site-packages/unittest2/case.py xfail
tests/unit/nupic/docs/examples_test.py::ExamplesTest::testOneStepConfidencesOpfVsNetwork <- ../../.local/lib/python2.7/site-packages/unittest2/case.py xfail
`
I'm facing the same issue, My first attempt was directly using `pip install nupic`, i tried with `--user` option and also building from the local repository later.

**Comment by Thanh-Binh** [comment]
@rhyolight I have the same issues with my Ubuntu, which can ONLY solved by using --user.
I have no idea why it works sometimes by using --user, sometimes nur by using sudo?

**Comment by rvsandeep** [comment]
@rhyolight No i'm not using virtualenv. I tried the same steps on my mac as well and it's  failing for the above tests as well.   
` 713 passed, 17 skipped, 8 xfailed, 5 pytest-warnings in 210.08 seconds`

**Comment by DeepakVellampalli** [comment]
@rhyolight I tried using `virtualenv ` but it didn't work, so ended up installing  by "--user" way.

**Comment by rhyolight** [comment]
You may have the wrong nupic.bindings version. Can you run `pip list | grep nupic` to find out?  If you have anything less than 1.0.6 you should [uninstall completely](https://discourse.numenta.org/t/uninstalling-nupic/2175) then run `pip install nupic` again. (thanks @lscheinkman for pointing this out)

**Comment by DeepakVellampalli** [comment]
@rhyolight You are right, I am having nupic.bindings 1.0.4. I think re-installation will work. 
Thank you so much!
