### ISSUE TITLE
(numenta-apps) Unicorn

### ISSUE THREAD

**Issue by zksnrwam** [numenta/nupic#3839]
Hi, I'm having problems installing and starting unicorn (numenta-apps). How can I use it with the cmd?

**Comment by rhyolight** [comment]
What are you trying to do? Do you want to simply install HTM Studio to try HTM on your data? Or are you trying to build out an HTM application?

**Comment by zksnrwam** [comment]
I installed HTM Studio correctly for Windows (with .exe file setup). I tried to use my data and it works correctly. But I would like to build an HTM application. First, can I use HTM Studio from CMD? is it possible?
I would like to use https://github.com/numenta/numenta-apps/tree/master/unicorn for my HTM application. I installed unicorn-backend with the pip command but I do not know how to use it. Are there some docs that explain the whole process?

Thanks.

**Comment by rhyolight** [comment]
Development on Windows will be hard. We ship binaries for OS X and most Linux, but there have always been complications with the windows binaries. 

If you want to build an HTM application, I suggest using NuPIC, which is our most stable HTM. See http://nupic.docs.numenta.org/1.0.3/index.html

But again, YMMV on Windows. I know some contributors who use windows and work on NuPIC, so it certainly works, but I am not much help with Windows problems.

**Comment by zksnrwam** [comment]
is it possible for linux? as?

**Comment by rhyolight** [comment]
Linux Yes. I don't know what "as?" means.
