### ISSUE TITLE
File descriptor leaking issue

### ISSUE THREAD

**Issue by emmaai** [numenta/nupic#3846]
When `swarm.OFPModelRunner.run()` finishes the loop and does `self._finalize()`, it doesn't release the file descriptor that it acquires at the beginning of loop, which caused file descriptor leaking issue.  It will be reported as `Not enough memory` error on Linux if running with large enough set of data and many enough processes. The processes will be killed consequently.

It is fixed by adding 
`  if self._inputSource:
        self._inputSource.close()
`
in `self._finalize`.

**Comment by rhyolight** [comment]
@emmaai good catch, thanks.
