### ISSUE TITLE
one_gym anomaly

### ISSUE THREAD

**Issue by terentiuss** [numenta/nupic#3850]
Hi,
is it possible to have 2 or more csv input, and to match if the anomaly results in the first file are also in the second one, at the same day and time?
how can do it?

this is the link I'm referring to: https://github.com/numenta/nupic/tree/master/examples/opf/clients/hotgym/anomaly/one_gym

Thanks

**Comment by rhyolight** [comment]
Sure you can do this, it just takes a little python. But it is out of scope of the sample application. If you want to discuss your approach, please join [HTM Forum](https://discourse.numenta.org/c/nupic).
