### ISSUE TITLE
Question about structure in NUPIC with new theory implemented

### ISSUE THREAD

**Issue by RDaneelOlivav** [numenta/nupic#3853]
Hi,
After the update on the HTM theory of in the "A Framework for Intelligence and Cortical Function Based on Grid Cells in the Neocortex", my question is:

Is there something in NUPIC infrastructure that has already implemented this? Can someone guide me in this topic?

Thanks a lot, so eager to dive into it and build something fun with it ;).

**Comment by rhyolight** [comment]
see https://github.com/numenta/htmpapers/tree/master/biorxiv/location_in_the_neocortex_a_theory_of_sensorimotor_object_recognition_using_cortical_grid_cells

**Comment by rhyolight** [comment]
Also https://discourse.numenta.org/
