### ISSUE TITLE
The anomalyScore is the final anomalyScore that has been processed by normal distrubution?

### ISSUE THREAD

**Issue by summerchenjuan** [numenta/nupic#3866]
In the paper, there are two anomalyScore. one is St, the raw score,  other is Lt, the finaly score, which is processed by Anomalylikelihood.  After result=model.run(), we can get a modelResult, so what is the result.inferences['anomalyScore']? Is St or Lt?

**Comment by rhyolight** [comment]
It is St. Please post questions like this about the NuPIC API on the [forum](https://discourse.numenta.org/c/nupic), this issue tracker is for bug reports. Thanks!
