### ISSUE TITLE
No module named research,spatial_pooler

### ISSUE THREAD

**Issue by Toon6115** [numenta/nupic#3868]
I follow the NuPIC+Walkthrough file, until they need to call  SpatialPooler. It can not find it. Encoder/Decoder work fine. Here is an error message.

mportErrorTraceback (most recent call last)
<ipython-input-71-19e12ed1fd8b> in <module>()
----> 1 from nupic.research.spatial_pooler import SpatialPooler

ImportError: No module named research.spatial_pooler

**Comment by rhyolight** [comment]
Please see https://discourse.numenta.org/t/warning-0-7-0-breaking-changes/2200

Please ask further questions on HTM Forum, thanks.
