### ISSUE TITLE
Help with getting started

### ISSUE THREAD

**Issue by ajaykmr2292** [numenta/nupic#3871]
I want to build a prediction system based on the sequence of patterns I am getting. I would like to use `nupic` for that (Basically, I would like to build HTM for my own application). Can you please tell me how to get started? (There is too much of code and repos to understand and get started).

**Comment by rhyolight** [comment]
Hi @ajaykmr2292! Thanks for posting your issue. Please see our [Quick Start](http://nupic.docs.numenta.org/stable/index.html) guide and ask questions on [HTM Forum](https://discourse.numenta.org/categories).

**Comment by ajaykmr2292** [comment]
hey..thanks for the info. Btw, I see there are 3 methods to create models. Can I know whats the difference between `opf`, `Network` and `Algorithms API`? Also, I learnt about swarming. Can I know the reason for swarming in the first place (is it like parameter initialization for deep learning models?). Or is it the place where the actual learning takes place?

Thanks.

**Comment by ajaykmr2292** [comment]
And also can I know what is the meaning of `installing nupic in develop mode`?

**Comment by rhyolight** [comment]
Please join our forum and ask questions like this there. https://discourse.numenta.org/categories
