### ISSUE TITLE
Best way to learn NUPIC including New Grid Cells structure

### ISSUE THREAD

**Issue by RDaneelOlivav** [numenta/nupic#3874]
Hi,
I wanted to know what is the best way to learn all there is about NUPIC including the new Grid cells structure and python3 use.
Is there any step by step tutorial?

Thanks a lot in advance.

**Comment by rhyolight** [comment]
We don't have anything but the supporting code for Numenta papers to implement the grid cell location-based stuff. See https://github.com/numenta/htmpapers but there is no tutorial. It is research code.

**Comment by RDaneelOlivav** [comment]
Thanks ;). I'll look into it again more deeply then.
