### ISSUE TITLE
Upstream accepting implementation improvements that pass all tests and do not change API?

### ISSUE THREAD

**Issue by breznak** [numenta/nupic#3876]
In community nupic.cpp repo we're bringing over some needed python code, 
and find errors, improvements to the implementation. 

https://github.com/htm-community/nupic.cpp/pull/457#discussion_r282125036 

Will you accept the changes upstream here, or we should stick with nupic.py as a live successor of this repo? I still see a lot of people using and reporting against this repo.

**Comment by rhyolight** [comment]
> should stick with nupic.py as a live successor of this repo?

I suggest this. We are not planning on keeping this repository updated.
