### ISSUE TITLE
Does nupic work on Pypy?

### ISSUE THREAD

**Issue by dstromberg** [numenta/nupic#3877]
Hi.

Has anyone tried to use Numenta's version of nupic on a Pypy that is compatible with Python 2.7?

I gather Pypy intends to keep 2.7 compatibility into the indefinite future, since it is written in a dialect of 2.7 called RPython.

Thanks!

**Comment by rhyolight** [comment]
Yes, in python 2.7, `pip install nupic` works.

**Comment by dstromberg** [comment]
I tried:
sudo /usr/local/pypy-7.0.0/bin/pip2 install nupic

But got:
Collecting nupic.bindings==1.0.6 (from nupic)
  ERROR: Could not find a version that satisfies the requirement nupic.bindings==1.0.6 (from nupic) (from versions: 1.0.1)
ERROR: No matching distribution found for nupic.bindings==1.0.6 (from nupic)

Am I doing something wrong?

You realize that Pypy != CPython, right?  They both implement essentially the same language (Python 2.7 in this case), but their internals are very different.
