### ISSUE TITLE
8 xfails on Ubuntu Server 19.04

### ISSUE THREAD

**Issue by barnettjv** [numenta/nupic#3881]
After installing nupic.core and nupic. I get 8 xfails when I execute "run_nupic_tests.py -u". I've include below screenshots. Are these "expected"?
![Screenshot at 2019-09-23 01-17-42](https://user-images.githubusercontent.com/52405331/65411143-f8c9ee80-dda0-11e9-86cd-7fd61977f744.png)
![Screenshot at 2019-09-23 01-18-10](https://user-images.githubusercontent.com/52405331/65411154-01222980-dda1-11e9-99e9-2d82508f3d59.png)
![Screenshot at 2019-09-23 01-18-21](https://user-images.githubusercontent.com/52405331/65411164-067f7400-dda1-11e9-9e0e-a14c18098174.png)

**Comment by rhyolight** [comment]
Yes, `xfail` means "expected failure"
