### ISSUE TITLE
swarming in docker not working!

### ISSUE THREAD

**Issue by johncleveland** [numenta/nupic#3884]
Docker version 19.03.2, build 6a30dfc on
18.04.1-Ubuntu

The error in the shell after following instructions here: https://nupic.docs.numenta.org/1.0.0/guides/swarming/running.html

root@6e9c90fece4b:/home/docker# ${NUPIC}/scripts/run_swarm.py ${NUPIC}/examples/swarm/simple/search_def.json --maxWorkers=4
/usr/local/src/nupic/scripts/run_swarm.py: line 23: $' @file run_swarm.py\nThis script is the command-line interface for running swarms in nupic.': command not found
/usr/local/src/nupic/scripts/run_swarm.py: line 25: import: command not found
/usr/local/src/nupic/scripts/run_swarm.py: line 26: import: command not found
/usr/local/src/nupic/scripts/run_swarm.py: line 27: import: command not found
/usr/local/src/nupic/scripts/run_swarm.py: line 28: import: command not found
/usr/local/src/nupic/scripts/run_swarm.py: line 31: syntax error near unexpected token `from'
/usr/local/src/nupic/scripts/run_swarm.py: line 31: `from nupic.swarming import permutations_runner'

**Comment by rhyolight** [comment]
How are you invoking the docker image? The Dockerfile for NuPIC specifies Ubuntu 14, not 18, so I have a suspicion maybe you built your own image? I suggest you use the images we have on docker hub at https://hub.docker.com/r/numenta/nupic.

The error suggests the python scripts is not being interpreted properly as python. Maybe trying running `python $NUPIC/scripts/run_swarm.py`?

**Comment by johncleveland** [comment]
Sorry I responded on the forum:

I am following the exact instructions here:

https://nupic.docs.numenta.org/1.0.0/guides/swarming/running.html

the instruction:

docker run \
  --name nupic \
  -e NTA_CONF_PROP_nupic_cluster_database_passwd=nupic \
  -e NTA_CONF_PROP_nupic_cluster_database_host=mysql \
  --link nupic-mysql:mysql \
  -ti \
  numenta/nupic

the mysql command is:

docker run \
  --name nupic-mysql \
  -e MYSQL_ROOT_PASSWORD=nupic \
  -p 3306:3306 \
  -d \
  mysql:5.6

When in the shell I run 

${NUPIC}/scripts/run_swarm.py  ${NUPIC}/examples/swarm/simple/search_def.json --maxWorkers=4

I will just run ${NUPIC}/scripts/run_swarm.py and see what happens. Have to go now. 
Thanks for responding so promptly !!

**Comment by johncleveland** [comment]
problem Solved!  I copied and pasted from the above cite and there is no python command.
Thanks for your prompt response!
