### ISSUE TITLE
REST & TCP/UPD encoder

### ISSUE THREAD

**Issue by breznak** [numenta/nupic#431]
Allow libraries that can send messages over TCP/UDP/REST to interface with nupic via this encoder. 
The encoder would be instantiated by 2 URL addresses (for send/receive, en/de-code) and mode (active/passive) either the `encode()` is called, or a packet is received on the listening URI. 

Q1: do you think this is useful and would like it in nupic upstream? @rhyolight 
Q2: should TCP/UDP and REST be included together? (currently I have usecase for TCP, but REST would be very similar and can be useful eg for the cortical.io encoder) @scottpurdy @oxtopus 
Q3: this would require a new python lib as a dependency, should the idea of `encoders/extra` be revisited? *) 

*) I still think `encoders/` should be "pure mathematical" encoders that encode numbers using different encodings (Adaptive, Scalar, RDSE). "Specific" encoders (like this one, geo-*, maybe Date) should be in `encoders/extra` 

EDIT (old): ---------------------------------------------------
Would it be good idea to have REST encoder? 

It would be initialized with a url and list [parameters], for encoding it'd take 
list of [pramameter's values] in order of parameters above. 

The decode bould be tricky, so this will be an abstract class and decode must be handeled by specific use-cases. Max we could provide parser from xml/json to dict for ease. 

This could be applied to @rhyolight  's NLP CEPT code. And as a next step, a WordEncoder using CEPT is created. 

See https://github.com/numenta/nupic/issues/430 for where would this belong

**Comment by scottpurdy** [comment]
I don't think encoders should be dealing with this. I suppose if a user of NuPIC had a common use case then they could encapsulate it in a region from the network api and then link it to their encoder. But in the vast majority of cases it would be simplest to let the user get the data however they want and then just pass the value in.

**Comment by rhyolight** [comment]
I agree with Scott. Specific communication protocols are outside the scope of data encoders. Encoders should focus on data and data formats, not protocols. I don't really even understand how it would work unless it was an abstract base class and users would implement extracting the data from the protocol themselves. In that case, they'd have to do most of the work themselves anyway.

**Comment by cogmission** [comment]
I have a suggestion. How about a "Sensor" class to unify protocol input methods and encoder input formats? Something I'm considering for HTM.java.

**Comment by breznak** [comment]
> I don't really even understand how it would work

I thought it'd go like this: I have a program producing inputs to Nupic and
sending them over TCP, so I'd make an encoder listen on given address and
handle incoming data.

> How about a "Sensor" class ...

I like David's idea, is `Sensor` something I want to extend then? As we
have File,Image,.. sensors. Do we want TCP/Networking sensor?

**Comment by oxtopus** [comment]
It's relatively trivial to start a socket listener and shuffle data into an active model via `model.run()` with the API as-is.  The same can be said for HTTP/REST, although that quickly starts to expand in scope once you start taking into consideration high-availability, scalability, and efficient use of resources.  For that reason, I think it's best to keep it out of the framework.

That said, even Python ships with https://docs.python.org/2/library/simplehttpserver.html and the nifty `python -m SimpleHTTPServer` technique to quickly and simply start a static web server.  I think it would be handy to have a similarly simple way to quickly make a model available over a tcp connection out-of-the-box, even if it's not meant for production work loads.

**Comment by rhyolight** [comment]
> That said, even Python ships with https://docs.python.org/2/library/simplehttpserver.html and the nifty python -m SimpleHTTPServer technique to quickly and simply start a static web server. I think it would be handy to have a similarly simple way to quickly make a model available over a tcp connection out-of-the-box, even if it's not meant for production work loads.

Good idea. Would make a great hackathon project.

**Comment by rhyolight** [comment]
So, I'm going to close this... if someone wants to work on either @cogmission's or @oxtopus's idea, please create a separate ticket.

**Comment by cogmission** [comment]
We have "Sensors" that are distinguished by their connection protocols as well as resource format ( Fike Sensor, Image Sensor respectively) - therefore there is already a precedent for FTPSensor, HTTPSensor etc - I think the Sensorvtype should be more specific then TCPSensor or UDPSensor because there are too many different ways to connect at that level. 

This is for "pulling" data - I still like @oxtopus' idea for "pushing data **to** a network layer - I don't think the two are mutually exclusive.

**Comment by breznak** [comment]
@rhyolight This won't help you reducing ticket counts :wink: I'm going to need this, so #1979 

@cogmission you're right,
* `Sensor` is "fetch only", but allows you to mix resources available online & locally. 
* `Region` would let you read&write model's inputs/outputs over the network
