### ISSUE TITLE
String aka WordEncoder(using CEPT)

### ISSUE THREAD

**Issue by breznak** [numenta/nupic#432]
For NLP tasks, encode words. As a category is not enough, because we want "want" and "wants" to be similar. 

One solutioon would be a vector of letters, problem is different size of resultiong bitstring (words have diff lengths). 

Alternatively we could query CEPT, see  https://github.com/numenta/nupic/issues/431 for implement. details.

**Comment by rhyolight** [comment]
There is one in nupic.research now: https://github.com/numenta/nupic.research/blob/master/htmresearch/encoders/cio_encoder.py
