### ISSUE TITLE
Allow construction of hierarchy from OPF's description.py 

### ISSUE THREAD

**Issue by breznak** [numenta/nupic#440]
This should allow defining more SP/TP/Encoder/... segments in the `description.py`, add some source/target field to each of them and we should be able to construct hiearchical models easily!! 

@fergalbyrne : "
It's easy enough: map Subutai's code into a dict by naming the components:

{
  "region": {
    "name": "ImageLayer1",
    "type": "SensorRegion",
    yadayada..
  "link": {
    "input": "ImageLayer1",
    "output": "CLA1",
    "type": "defaultLink"
....

This could be digested by a dict-to-API converter which would programmatically run Subutai's Network-building code.
"

see http://lists.numenta.org/pipermail/nupic_lists.numenta.org/2013-November/002240.html

**Comment by scottpurdy** [comment]
I'm going to close this as I don't know that there is a use case for it currently. If someone wanted this I would recommend they do it outside the OPF at the moment. If someone creates a successful setup that makes sense to include in OPF then we can create a new model type with the hierarchy.
