### ISSUE TITLE
Populate wikepedia pages on HTM and NuPIC

### ISSUE THREAD

**Issue by rhyolight** [numenta/nupic#450]
As suggested on our [mailing list](http://lists.numenta.org/pipermail/nupic_lists.numenta.org/2013-November/002278.html).

**Comment by rhyolight** [comment]
https://en.wikipedia.org/wiki/Hierarchical_temporal_memory
https://en.wikipedia.org/wiki/Hierarchical_temporal_memory#NuPIC_platform_and_development_tools

**Comment by cogmission** [comment]
@rhyolight Not to cause confusion but those articles are very inaccurate and out of date.

**Comment by rhyolight** [comment]
@cogmission That may be, but I don't think a Github Issue is the right place to track this.

**Comment by cogmission** [comment]
@rhyolight I agree. That occurred to me too.
