### ISSUE TITLE
Add support for Random Distributed Encoder in ExpGenerator

### ISSUE THREAD

**Issue by subutai** [numenta/nupic#573]
Add support for Random Distributed Encoder in ExpGenerator. This will allow the encoder to be used in swarms.

**Comment by breznak** [comment]
@rhyolight can be closed? I'm using RDSE in swarming

**Comment by rhyolight** [comment]
@breznak How are you using it in swarms?

**Comment by breznak** [comment]
` 'encoders': {
        u'ecg': PermuteEncoder(fieldName='ecg', w=21,encoderClass="RandomDistributedScalarEncoder", resolution=PermuteFloat(0.1, 0.5), ),
      },
`

but I don't swarm over RDSE as a type of encoder to use, if that's what you meant?

**Comment by rhyolight** [comment]
@subutai Can you clarify please?

**Comment by subutai** [comment]
Hmm, that's what I meant. If you can already do that then the issue can be closed! I will close it.
