### ISSUE TITLE
Clean up _getDataDirs

### ISSUE THREAD

**Issue by subutai** [numenta/nupic#665]
In `py/nupic/data/datasethelpers.py` the function `_getDataDirs` relies on some obsolete assumptions, such as `NTA_ROOTDIR` environment and NuPIC being installed under `$HOME/nta`. Maybe it should just look at the path and value of `NTA` variable. Review and clean these up.

**Comment by rhyolight** [comment]
This issue has been closed because it is obsolete. 

There is no longer a `datasethelpers.py` script, and `NTA_ROOTDIR` is no longer used anywhere in the codebase.
