### ISSUE TITLE
No vagran/nupic-current.box on amazon

### ISSUE THREAD

**Issue by charlesll** [numenta/nupic#740]
Hello,

I tried to install Nupic to test it and I'm stuck at the Vagrant up command, that gives me an error 404 not found. The link in the wiki:

https://s3-us-west-2.amazonaws.com/public.numenta.org/vagrant/nupic-current.box

seems not good and leads to nothing actually. I tried in my web navigator to see if it was going somewhere and I obtained that:

<Error>
<Code>NoSuchKey</Code>
<Message>The specified key does not exist.</Message>
<Key>vagrant/nupic-current.box</Key>
<RequestId>D898F4AA0170112D</RequestId>
<HostId>
4B+7Q26ZRzYwpNuXGEFFfY4sAKLP9nDDdYUoBy5XoD1sZ3Rt2S4hOAluPsfmDuPX
</HostId>
</Error>

Playing with the URLs I've found a vagrant/nupic-current_dontuse.box key that actually works. 

Have I missed something here? What link should we use?

Thanks in advance.

**Comment by bkremnev** [comment]
It's 2015 and vagrant method still not working. Whats up with that? Was this project abandoned?

**Comment by rhyolight** [comment]
Sorry, but we diverted support from vagrant to docker. https://github.com/numenta/nupic/wiki/Install-NuPIC-using-Docker

**Comment by bkremnev** [comment]
Thanks for quick replay. I was able to install NuPIC using docker but I suggest you to remove information  about vagrant method so people like me won't waste time on it.

**Comment by rhyolight** [comment]
Good point, thanks.

---------
Matt Taylor
OS Community Flag-Bearer
Numenta

**Comment by rhyolight** [comment]
https://github.com/numenta/nupic/wiki/Running-Nupic-in-a-Virtual-Machine/_compare/4e0ba7f7b261bdfa808d9a89a352386bc5bf5487...494170d5c7068fb223fcf9a6c998af09eca1ea3d

**Comment by riccardoravaro** [comment]
remove the vagrant method please, I wasted my time! =)

**Comment by rhyolight** [comment]
> remove the vagrant method please, I wasted my time! =)

@riccardoravaro I'm sorry! But where in our docs are we still mentioning Vagrant? It has been awhile since we used it. Thanks.
