### ISSUE TITLE
Refactor boosting/inhibition to stand-alone objects

### ISSUE THREAD

**Issue by breznak** [numenta/nupic#824]
edit:
we discussed this with @chetan51 back then, I will try to investigate this issue again - if it is possible to extract Boosting/Inhibition functionality from SP/TP to stand-alone classes. 
pros:
* simpler SP/TP/(TM?) code
* code shared among implementations
* code shared among different classes SP/TP,...

cons:
* there are (easy) optimizations for some cases -- with right data-structure, we can optimize (using eg GPU lib) for all cases

----------------------
I think we should (again) create a class `Boosting` (or BoostingStrategy ?) that would take care of the logic of: 
when should it start boosting? 
which columns? 
and how "strongly" to boost? 

Then we could easily have implementations: GreedyBoosting (now), SmoothBoosting, PartialBoosting (1 at a time)...

**Comment by rhyolight** [comment]
Discussing [on this HTM Forum thread](https://discourse.numenta.org/t/should-boosting-and-or-inhibition-code-be-pulled-out-into-objects/1000/2).

**Comment by rhyolight** [comment]
This idea was rejected. [See the forum thread for discussion. ](https://discourse.numenta.org/t/should-boosting-and-or-inhibition-code-be-pulled-out-into-objects/1000)
