### ISSUE TITLE
Detailed profiling of model checkpointing

### ISSUE THREAD

**Issue by scottpurdy** [numenta/nupic#845]
The size and speed of checkpointing are very important for some uses of NuPIC. This task is to do detailed profiling of checkpointing. It should include where the time is spent and the size that each part of the model contributes.

Make sure to do this on both "young" and more saturated models to get an idea of the difference.

**Comment by rhyolight** [comment]
@scottpurdy do you still want to keep this issue around for capnp serialization?

**Comment by scottpurdy** [comment]
This issue can be closed. It will be addressed with the new serialization anyway when we get around to wrapping that up.
