### ISSUE TITLE
Verify if `tp_test.assertTPsEqual` works with the C++ TP

### ISSUE THREAD

**Issue by chetan51** [numenta/nupic#853]
In `tp_test.assertTPsEqual`, there is this comment:

    This is temporarily disabled since it does not work with the C++
    implementation of the TP.

Check if the comment is no longer valid, since the method is being called, and whether it works with the C++ TP.

**Comment by rhyolight** [comment]
@numenta/nupic-committers I'm going to close this because it's on the TP. Let me know if you think it should be open.
