### ISSUE TITLE
SP adaptSynapses: Experiment with discouraging shared inputs

### ISSUE THREAD

**Issue by chetan51** [numenta/nupic#894]
As per #892, might be worth experimenting with the following approach:

"Permanence values for shared inputs, which are input bits that are turned on and connected to more than one active column, are decreased in order to discourage multiple columns from learning the same input pattern."

**Comment by rhyolight** [comment]
@subutai I think this should be done in the research repo. I'm not sure it should be reported here.

**Comment by subutai** [comment]
Moved to research repo: https://github.com/numenta/nupic.research/issues/576
