### ISSUE TITLE
TP: Misleading comment in inferPhase2?

### ISSUE THREAD

**Issue by chetan51** [numenta/nupic#902]
In the TP's `inferPhase2` function, there's this comment:

    The computes the predicted state, then
    checks to insure that the predicted state is not over-saturated, i.e.
    look too close like a burst. This indicates that there were so many
    separate paths learned from the current input columns to the predicted
    input columns that bursting on the current input columns is most likely
    generated mix and match errors on cells in the predicted columns. If
    we detect this situation, we instead turn on only the start cells in the
    current active columns and re-generate the predicted state from those.

As far as I can see, there's no such logic going on in the function.

**Comment by rhyolight** [comment]
@subutai ping

**Comment by subutai** [comment]
Obsolete - vote to close
